#!/usr/bin/env python3
"""Generate kurn attention kernels for ggml-cpu's FLASH_ATTN_EXT (kurn-attn.cpp).

Every kernel is the kurn.attention template (data/attn_kernel.c) for one configuration, with
its public symbols renamed so that many configurations link into libggml-cpu:

  variant  target        what it is for
  f32      avx512        default: f32 decode row engine (n_q x G <= 8) and f32 tile engine otherwise
  amx      amx_bf16      the same with the AMX-BF16 tile engine (opt-in, GGML_KURN_AMX=1)
  bf16     avx512_bf16   the same with the AVX512-BF16 tile engine (GGML_KURN_FA_ENGINE=bf16)
  exact    avx512        f32 tile engine for every n_q (dec_rows 0) and one KV split: a row's result
                         does not depend on the batch it is computed in, the KV length or the
                         thread count (batch-invariant attention, GGML_KURN_FA_MODE=exact)

for KV formats f16, bf16 and q8_0 (K and V of the same type) and head dims 64, 128, 256 and
576/512 (MLA, V a view of K). Each file is compiled only when the ggml-cpu build has the ISA
the target needs (guard macros below), so a non-native build drops what it cannot run.

    python gen_ggml_attn.py DIR [--config JSON] [--only-dims 128,256]

writes DIR/kattn_<variant>_<kv>_d<dk>[_<dv>].c, DIR/kurn_attn.h and DIR/kattn_dispatch.h.
--config is JSON {variant: {codegen keys}} (tile_q, tile_kv, split, dec_rows, kcenter).
"""

import argparse
import json
import os

from kurn import attention as A
from kurn.toolchain import data_path

_AVX512 = "defined(__AVX512F__) && defined(__AVX512BW__) && defined(__AVX512DQ__) && defined(__AVX512VL__) && defined(__F16C__)"
VARIANTS = {
    # name: (target, extra codegen keys, guard, engine id, exact)
    "bf16": ("avx512_bf16", {}, f"{_AVX512} && defined(__AVX512BF16__)", 1, 0),
    "amx": ("amx_bf16", {}, f"{_AVX512} && defined(__AVX512BF16__) && defined(__AMX_TILE__) && defined(__AMX_BF16__) && defined(__linux__)", 2, 0),
    "f32": ("avx512", {}, _AVX512, 0, 0),
    "exact": ("avx512", {"dec_rows": 0, "split": 1}, _AVX512, 0, 1),
}
KV = ("f16", "bf16", "q8_0")
DIMS = ((64, 64), (128, 128), (256, 256), (576, 512))
SYMBOLS = ("kattn_workspace", "kattn_config", "kattn_pack_bytes", "kattn_packed", "kattn_pack", "kattn")
GEN = "// Generated by kurn/integration/llama.cpp/gen_ggml_attn.py. Do not edit."


def name(variant, kv, dk, dv):
    return f"kattn_{variant}_{kv}_d{dk}" + ("" if dv == dk else f"_{dv}")


def config(variant, kv, dk, dv, overrides=None):
    target, extra, _, _, _ = VARIANTS[variant]
    spec = {"op": "attn", "target": target, "kv": kv, "dk": dk, "dv": dv, **extra, **(overrides or {})}
    if variant == "exact":
        spec.update(dec_rows=0, split=1)  # what makes it exact; not overridable
    return A.resolve(spec)


def source(variant, kv, dk, dv, overrides=None):
    """The generated kernel with its public symbols renamed to <name>_<symbol> (kattn -> <name>)."""
    c = config(variant, kv, dk, dv, overrides)
    n = name(variant, kv, dk, dv)
    ren = [f"#define {s} {n}{s[len('kattn'):]}" for s in SYMBOLS]
    src = A.generate(c)
    quiet = "#pragma GCC diagnostic ignored \"-Wcast-qual\""  # ggml-cpu builds with -Wcast-qual; the template does not
    return c, n, "\n".join([VARIANTS[variant][2].join(("#if ", "")), quiet, *ren, src, "#endif", ""])


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("dir")
    ap.add_argument("--config", help="JSON file or inline JSON {variant: {codegen keys}}")
    ap.add_argument("--only-dims", help="comma-separated K head dims to generate (default: all)")
    a = ap.parse_args(argv)
    cfg = (json.loads(a.config) if a.config.lstrip().startswith("{") else json.load(open(a.config))) if a.config else {}
    dims = [d for d in DIMS if not a.only_dims or str(d[0]) in a.only_dims.split(",")]
    os.makedirs(a.dir, exist_ok=True)
    for f in os.listdir(a.dir):
        if f.startswith("kattn_") and f.endswith(".c"):
            os.remove(os.path.join(a.dir, f))
    with open(data_path("kurn_attn.h")) as fh:
        open(os.path.join(a.dir, "kurn_attn.h"), "w").write(fh.read())
    decls, rows = [], []
    for variant, (target, _, guard, engine, exact) in VARIANTS.items():
        for kv in KV:
            for dk, dv in dims:
                c, n, src = source(variant, kv, dk, dv, cfg.get(variant))
                open(os.path.join(a.dir, n + ".c"), "w").write(src)
                desc = " ".join(f"{k}={c[k]}" for k in A.CODEGEN_KEYS)
                decls += [
                    f"#if {guard}",
                    f"size_t {n}_workspace(const kattn_args *, int); void {n}(const kattn_args *, void *, int, int);",
                    f"size_t {n}_pack_bytes(const kattn_args *, int64_t); "
                    f"void {n}_pack(const kattn_args *, void *, int64_t, int64_t, int64_t, int, int); "
                    f"void {n}_packed(const kattn_args *, const void *, int64_t, void *, int, int);",
                    "#endif",
                ]
                rows += [
                    f"#if {guard}",
                    f'    {{ "{n}", "{desc}", {engine}, {exact}, {dk}, {dv}, {A.KV_FORMATS[kv]}, {c["tile_q"]}, {c["dec_rows"]}, '
                    f"{n}_workspace, {n}, {n}_pack_bytes, {n}_pack, {n}_packed }},",
                    "#endif",
                ]
    hdr = [
        GEN,
        "#pragma once",
        '#include "kurn_attn.h"',
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        *decls,
        "typedef struct {",
        "    const char *name, *config;",
        "    int engine;       // 0 f32, 1 AVX512-BF16, 2 AMX-BF16 (tile engine)",
        "    int exact;        // batch-invariant configuration (f32, no decode engine, one KV split)",
        "    int dk, dv, kv;   // head dims, KATTN_KV_* format of K and V",
        "    int tile_q;       // query tokens per tile",
        "    int dec_rows;     // decode row engine when n_q * G <= dec_rows",
        "    size_t (*workspace)(const kattn_args *, int);",
        "    void (*run)(const kattn_args *, void *, int, int);",
        "    size_t (*pack_bytes)(const kattn_args *, int64_t);",
        "    void (*pack)(const kattn_args *, void *, int64_t, int64_t, int64_t, int, int);",
        "    void (*packed)(const kattn_args *, const void *, int64_t, void *, int, int);",
        "} kurn_fa_kernel;",
        "static const kurn_fa_kernel kurn_fa_kernels[] = {",
        *rows,
        '    { NULL, NULL, 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL },',
        "};",
        "#ifdef __cplusplus",
        "}",
        "#endif",
    ]
    open(os.path.join(a.dir, "kattn_dispatch.h"), "w").write("\n".join(hdr) + "\n")
    print(f"kurn attention: {len(rows) // 3} kernels ({', '.join(VARIANTS)} x {', '.join(KV)} x "
          f"{', '.join(f'{dk}' if dk == dv else f'{dk}/{dv}' for dk, dv in dims)})")


if __name__ == "__main__":
    main()
