"""Lowering rules: (op, weight format, target) + schedule -> C source with intrinsics.

Each lowering function takes (target, resolved config) and returns C that
implements the kernel's entry points in `kurn.h`; kernels.py maps
(op, weights) to its lowering. Register tiles are unrolled here (in Python) so
the C compiler sees straight-line code with constant indices.
"""

import re


def prelude(target):
    arch = "#include <arm_neon.h>" if target == "neon" else "#include <immintrin.h>"
    if target == "neon":
        f16 = "static inline float f16f(uint16_t h) { __fp16 v; memcpy(&v, &h, 2); return (float)v; }"
    elif target == "scalar":
        f16 = """static inline float f16f(uint16_t h) {
    uint32_t s = (uint32_t)(h & 0x8000) << 16, e = (h >> 10) & 0x1f, m = h & 0x3ff, b;
    if (e == 0) { if (!m) b = s; else { e = 113; while (!(m & 0x400)) { m <<= 1; e--; } b = s | (e << 23) | ((m & 0x3ff) << 13); } }
    else if (e == 31) b = s | 0x7f800000 | (m << 13);
    else b = s | ((e + 112) << 23) | (m << 13);
    float f; memcpy(&f, &b, 4); return f;
}"""
    else:
        f16 = "static inline float f16f(uint16_t h) { return _cvtsh_ss(h); }"
    return f"""// Generated by kurn. Do not edit; edit the .kurn spec instead.
#include "kurn.h"
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
{arch if target != "scalar" else ""}
{f16}
"""


def _rows_loop(R, body_fn, reduce_fn, decl_fn, prefetch_fn=None, inner="p", n_inner="np"):
    """Emit `for r in steps of R` + a single-row tail. body_fn(i) -> per-row code inside inner loop."""

    def block(n):
        lines = [f"        const block_T *w{i} = w + (r + {i}) * nb;" for i in range(n)]
        lines += [decl_fn(i) for i in range(n)]
        lines.append(f"        for (int64_t {inner} = 0; {inner} < {n_inner}; {inner}++) {{")
        lines.append("            INNER_PRE")
        if prefetch_fn:
            lines += [prefetch_fn(i) for i in range(n)]
        lines += [body_fn(i) for i in range(n)]
        lines.append("        }")
        lines += [reduce_fn(i) for i in range(n)]
        return "\n".join(lines)

    return f"""    int64_t r = r0;
    for (; r + {R} <= r1; r += {R}) {{
{block(R)}
    }}
    for (; r < r1; r++) {{
{block(1)}
    }}"""


# --------------------------------------------------------------------------- q8_0 GEMV
def q8_0_gemv_vnni16(s):
    """Layout vnni16: 16 weight rows interleaved per block so one 64-byte load feeds
    vpdpbusd for 16 rows (lane = row) against a broadcast 4-byte activation slice.
    Weights are stored pre-biased (+128, u8); the bias term depends only on the
    activation, so it is folded into the accumulator seed. Same bytes as Q8_0."""
    G, P = s["rows"], s["prefetch"]
    aligned = s.get("align") == 64
    ld512, ld256 = ("_mm512_load_si512", "_mm256_load_si256") if aligned else ("_mm512_loadu_si512", "_mm256_loadu_si256")
    seed = "\n".join(f"                __m512i e{g} = nc, o{g} = _mm512_setzero_si512();" for g in range(G))
    kk_lines = []
    for kk in range(8):
        acc = "e" if kk % 2 == 0 else "o"
        kk_lines.append(f"                {{ const __m512i xk = _mm512_set1_epi32(xw[b * 8 + {kk}]);")
        for g in range(G):
            kk_lines.append(f"                  {acc}{g} = _mm512_dpbusd_epi32({acc}{g}, {ld512}(blk{g}->q + {64 * kk}), xk);")
        kk_lines.append("                }")
    pf = (
        "\n".join(
            f"                _mm_prefetch((const char *)(blk{g} + {P}), _MM_HINT_T0); _mm_prefetch((const char *)(blk{g} + {P}) + 256, _MM_HINT_T0);"
            for g in range(G)
        )
        if P
        else ""
    )
    fin = "\n".join(
        f"                a{g} = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_add_epi32(e{g}, o{g})), _mm512_mul_ps(_mm512_cvtph_ps({ld256}((const __m256i *)blk{g}->d)), dx), a{g});"
        for g in range(G)
    )
    decl = " ".join(f"__m512 a{g} = _mm512_setzero_ps();" for g in range(G))
    blks = "\n".join(f"                const vblk *blk{g} = pk->blk + (g + {g}) * nb + b;" for g in range(G))
    store = "\n".join(f"            store16(y, (g + {g}) * 16, r0, r1, a{g});" for g in range(G))
    return (
        prelude("avx512_vnni")
        + f"""
typedef struct {{ uint8_t q[8 * 64]; uint16_t d[16];{" uint8_t pad[32];" if aligned else ""} }} vblk; // {576 if aligned else 544} B per 16 rows x 32 values ({"padded to 64 B" if aligned else "exactly the bytes of 16 native Q8_0 blocks"})
typedef struct {{ int64_t nb, ngroups; vblk *blk; }} packed_t;

void *kq8_gemv_prepare(const void *W, int64_t K, int64_t N) {{
    const block_q8_0 *w = (const block_q8_0 *)W;
    packed_t *pk = malloc(sizeof *pk);
    pk->nb = K / QK8_0; pk->ngroups = (N + 15) / 16;
    pk->blk = aligned_alloc(64, sizeof(vblk) * pk->nb * pk->ngroups);
    memset(pk->blk, 0, sizeof(vblk) * pk->nb * pk->ngroups);
    for (int64_t g = 0; g < pk->ngroups; g++)
        for (int64_t b = 0; b < pk->nb; b++) {{
            vblk *o = pk->blk + g * pk->nb + b;
            for (int r = 0; r < 16; r++) {{
                if (g * 16 + r >= N) {{ for (int kk = 0; kk < 8; kk++) for (int j = 0; j < 4; j++) o->q[kk * 64 + r * 4 + j] = 0x80; continue; }}
                const block_q8_0 *src = w + (g * 16 + r) * pk->nb + b;
                o->d[r] = src->d;
                for (int kk = 0; kk < 8; kk++)
                    for (int j = 0; j < 4; j++) o->q[kk * 64 + r * 4 + j] = (uint8_t)(src->qs[kk * 4 + j] ^ 0x80);
            }}
        }}
    return pk;
}}

static inline void store16(float *y, int64_t row0, int64_t r0, int64_t r1, __m512 v) {{
    if (row0 >= r0 && row0 + 16 <= r1) {{ _mm512_storeu_ps(y + row0, v); return; }}
    uint32_t m = 0xFFFF;
    if (row0 < r0) m &= 0xFFFFu << (r0 - row0);
    if (row0 + 16 > r1) m &= (1u << (r1 > row0 ? r1 - row0 : 0)) - 1;
    _mm512_mask_storeu_ps(y + row0, (__mmask16)m, v);
}}

void kq8_gemv_packed(const void *pv, const void *xv, float *y, int64_t K, int64_t r0, int64_t r1) {{
    const packed_t *pk = (const packed_t *)pv;
    const int64_t nb = K / QK8_0;
    const block_q8_0 *x = (const block_q8_0 *)xv;
    int32_t xw[8 * 1024], ncs[1024];
    float xd[1024];
    for (int64_t b = 0; b < nb; b++) {{
        int32_t s = 0;
        for (int l = 0; l < 32; l++) s += x[b].qs[l];
        memcpy(xw + 8 * b, x[b].qs, 32);
        ncs[b] = -128 * s;
        xd[b] = f16f(x[b].d);
    }}
    const int64_t g0 = r0 / 16, g1 = (r1 + 15) / 16;
    int64_t g = g0;
    for (; g + {G} <= g1; g += {G}) {{
        {decl}
        for (int64_t b = 0; b < nb; b++) {{
            const __m512i nc = _mm512_set1_epi32(ncs[b]); const __m512 dx = _mm512_set1_ps(xd[b]);
{blks}
{pf}
{seed}
{chr(10).join(kk_lines)}
{fin}
        }}
{store}
    }}
    for (; g < g1; g++) {{
        __m512 a = _mm512_setzero_ps();
        for (int64_t b = 0; b < nb; b++) {{
            const vblk *blk = pk->blk + g * nb + b;
            __m512i e = _mm512_set1_epi32(ncs[b]), o = _mm512_setzero_si512();
            for (int kk = 0; kk < 8; kk += 2) {{
                e = _mm512_dpbusd_epi32(e, _mm512_loadu_si512(blk->q + 64 * kk), _mm512_set1_epi32(xw[b * 8 + kk]));
                o = _mm512_dpbusd_epi32(o, _mm512_loadu_si512(blk->q + 64 * kk + 64), _mm512_set1_epi32(xw[b * 8 + kk + 1]));
            }}
            a = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_add_epi32(e, o)), _mm512_mul_ps(_mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)blk->d)), _mm512_set1_ps(xd[b])), a);
        }}
        store16(y, g * 16, r0, r1, a);
    }}
}}
"""
    )


def q8_0_gemv(target, s):
    if s.get("layout") == "vnni16":
        return q8_0_gemv_vnni16(s)
    R, act, P = s["rows"], s["act"], s["prefetch"]
    if target == "scalar":
        return (
            prelude(target)
            + """
void kq8_gemv(const void *W, const void *xv, float *y, int64_t K, int64_t r0, int64_t r1) {
    const int64_t nb = K / QK8_0;
    const block_q8_0 *x = (const block_q8_0 *)xv;
    for (int64_t r = r0; r < r1; r++) {
        const block_q8_0 *w = (const block_q8_0 *)W + r * nb;
        float acc = 0;
        for (int64_t b = 0; b < nb; b++) {
            int32_t s = 0;
            for (int l = 0; l < QK8_0; l++) s += (int32_t)w[b].qs[l] * x[b].qs[l];
            acc += f16f(w[b].d) * f16f(x[b].d) * (float)s;
        }
        y[r] = acc;
    }
}
"""
        )
    pf = (
        (
            lambda i: (
                f"            _mm_prefetch((const char *)(w{i} + {('2 * (p + ' + str(P) + ')') if target == 'avx512_vnni' else '(p + ' + str(P) + ')'}), _MM_HINT_T0);"
            )
        )
        if P
        else None
    )
    if target == "avx512_vnni":
        head = """
static inline __m512i load2(const block_q8_0 *b) {
    return _mm512_inserti64x4(_mm512_castsi256_si512(_mm256_loadu_si256((const __m256i *)b[0].qs)),
                              _mm256_loadu_si256((const __m256i *)b[1].qs), 1);
}
static inline __m512 scale2(const block_q8_0 *b) {
    const __m512i idx = _mm512_set_epi32(1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0);
    return _mm512_permutexvar_ps(idx, _mm512_castps128_ps512(_mm_cvtph_ps(_mm_cvtsi32_si128((int)b[0].d | ((int)b[1].d << 16)))));
}
typedef block_q8_0 block_T;
void kq8_gemv(const void *W, const void *xv, float *y, int64_t K, int64_t r0, int64_t r1) {
    const int64_t nb = K / QK8_0, np = nb / 2;
    const block_q8_0 *w = (const block_q8_0 *)W, *x = (const block_q8_0 *)xv;
    const __m512i flip = _mm512_set1_epi8((char)0x80), zero = _mm512_setzero_si512();
    (void)flip; (void)zero;
"""
        if act == "once":
            head += """    __m512i xq[512], xb[512];
    __m512 xd[512];
    for (int64_t p = 0; p < np; p++) {
        xq[p] = load2(x + 2 * p);
        xb[p] = _mm512_sub_epi32(zero, _mm512_slli_epi32(_mm512_dpbusd_epi32(zero, _mm512_set1_epi8(1), xq[p]), 7));
        xd[p] = scale2(x + 2 * p);
    }
"""
            pre = ""
            body = lambda i: (
                f"            a{i} = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_dpbusd_epi32(xb[p], _mm512_xor_si512(load2(w{i} + 2 * p), flip), xq[p])),"
                f" _mm512_mul_ps(scale2(w{i} + 2 * p), xd[p]), a{i});"
            )
        else:  # inline: no per-call prep; abs/sign via masks per row
            pre = "const __m512i xx = load2(x + 2 * p); const __m512 dx = scale2(x + 2 * p);"
            body = lambda i: (
                f"            {{ const __m512i wv = load2(w{i} + 2 * p); const __mmask64 m = _mm512_movepi8_mask(wv);"
                f" a{i} = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_dpbusd_epi32(zero, _mm512_abs_epi8(wv), _mm512_mask_sub_epi8(xx, m, zero, xx))),"
                f" _mm512_mul_ps(scale2(w{i} + 2 * p), dx), a{i}); }}"
            )
        loop = _rows_loop(
            R,
            body,
            lambda i: f"        y[r + {i}] = _mm512_reduce_add_ps(a{i});",
            lambda i: f"        __m512 a{i} = _mm512_setzero_ps();",
            pf,
        ).replace("INNER_PRE", pre)
        return prelude(target) + head + loop + "\n}\n"
    if target in ("avx2", "avx2_vnni"):
        vnni = target == "avx2_vnni"
        dp = "_mm256_dpbusd_avx_epi32" if vnni else None
        head = """
static inline float hsum8(__m256 v) {
    __m128 s = _mm_add_ps(_mm256_castps256_ps128(v), _mm256_extractf128_ps(v, 1));
    s = _mm_add_ps(s, _mm_movehl_ps(s, s));
    return _mm_cvtss_f32(_mm_add_ss(s, _mm_movehdup_ps(s)));
}
typedef block_q8_0 block_T;
void kq8_gemv(const void *W, const void *xv, float *y, int64_t K, int64_t r0, int64_t r1) {
    const int64_t nb = K / QK8_0;
    const block_q8_0 *w = (const block_q8_0 *)W, *x = (const block_q8_0 *)xv;
    const __m256i flip = _mm256_set1_epi8((char)0x80), zero = _mm256_setzero_si256(), ones16 = _mm256_set1_epi16(1);
    (void)flip; (void)zero; (void)ones16;
"""
        if act == "once":
            head += f"""    __m256i xq[1024], xb[1024];
    float xd[1024];
    for (int64_t p = 0; p < nb; p++) {{
        xq[p] = _mm256_loadu_si256((const __m256i *)x[p].qs);
        xb[p] = _mm256_sub_epi32(zero, _mm256_slli_epi32({dp}(zero, _mm256_set1_epi8(1), xq[p]), 7));
        xd[p] = f16f(x[p].d);
    }}
"""
            pre = ""
            body = lambda i: (
                f"            a{i} = _mm256_fmadd_ps(_mm256_cvtepi32_ps({dp}(xb[p], _mm256_xor_si256(_mm256_loadu_si256((const __m256i *)w{i}[p].qs), flip), xq[p])),"
                f" _mm256_set1_ps(f16f(w{i}[p].d) * xd[p]), a{i});"
            )
        else:
            pre = "const __m256i xx = _mm256_loadu_si256((const __m256i *)x[p].qs); const float dx = f16f(x[p].d);"
            mul = (
                (lambda a, b: f"{dp}(zero, {a}, {b})")
                if vnni
                else (lambda a, b: f"_mm256_madd_epi16(_mm256_maddubs_epi16({a}, {b}), ones16)")
            )
            body = lambda i: (
                f"            {{ const __m256i wv = _mm256_loadu_si256((const __m256i *)w{i}[p].qs);"
                f" a{i} = _mm256_fmadd_ps(_mm256_cvtepi32_ps({mul('_mm256_sign_epi8(wv, wv)', '_mm256_sign_epi8(xx, wv)')}),"
                f" _mm256_set1_ps(f16f(w{i}[p].d) * dx), a{i}); }}"
            )
        loop = _rows_loop(
            R,
            body,
            lambda i: f"        y[r + {i}] = hsum8(a{i});",
            lambda i: f"        __m256 a{i} = _mm256_setzero_ps();",
            pf,
            n_inner="nb",
        ).replace("INNER_PRE", pre)
        return prelude(target) + head + loop + "\n}\n"
    if target == "neon":
        pfn = (lambda i: f"            __builtin_prefetch(w{i} + p + {P});") if P else None
        head = """
typedef block_q8_0 block_T;
void kq8_gemv(const void *W, const void *xv, float *y, int64_t K, int64_t r0, int64_t r1) {
    const int64_t nb = K / QK8_0;
    const block_q8_0 *w = (const block_q8_0 *)W, *x = (const block_q8_0 *)xv;
    float xd[1024];
    for (int64_t p = 0; p < nb; p++) xd[p] = f16f(x[p].d);
"""
        pre = "const int8x16_t x0 = vld1q_s8(x[p].qs), x1 = vld1q_s8(x[p].qs + 16);"
        body = lambda i: (
            f"            a{i} = vfmaq_n_f32(a{i}, vcvtq_f32_s32(vdotq_s32(vdotq_s32(vdupq_n_s32(0), vld1q_s8(w{i}[p].qs), x0), vld1q_s8(w{i}[p].qs + 16), x1)),"
            f" f16f(w{i}[p].d) * xd[p]);"
        )
        loop = _rows_loop(
            R,
            body,
            lambda i: f"        y[r + {i}] = vaddvq_f32(a{i});",
            lambda i: f"        float32x4_t a{i} = vdupq_n_f32(0);",
            pfn,
            n_inner="nb",
        ).replace("INNER_PRE", pre)
        return prelude(target) + head + loop + "\n}\n"
    raise ValueError(target)


# --------------------------------------------------------------------------- q4_K GEMV
Q4K_DECODE = """
static inline void q4k_decode(const uint8_t *s12, uint64_t *sc, uint64_t *mn) {
    uint32_t u[4];
    memcpy(u, s12, 12);
    u[3] = ((u[2] >> 4) & 0x0f0f0f0f) | (((u[1] >> 6) & 0x03030303) << 4);
    const uint32_t a = u[1] & 0x3f3f3f3f;
    u[1] = (u[2] & 0x0f0f0f0f) | (((u[0] >> 6) & 0x03030303) << 4);
    u[2] = a;
    u[0] &= 0x3f3f3f3f;
    *sc = (uint64_t)u[0] | ((uint64_t)u[1] << 32);
    *mn = (uint64_t)u[2] | ((uint64_t)u[3] << 32);
}
static inline __m256i bsum_pairs(const block_q8_K *x) {
    __m256i a = _mm256_cvtepi16_epi32(_mm_loadu_si128((const __m128i *)x->bsums));
    __m256i b = _mm256_cvtepi16_epi32(_mm_loadu_si128((const __m128i *)(x->bsums + 8)));
    return _mm256_permutevar8x32_epi32(_mm256_hadd_epi32(a, b), _mm256_setr_epi32(0, 1, 4, 5, 2, 3, 6, 7));
}
"""


def q4_K_gemv(target, s):
    if target == "avx512_vnni":  # auto -> the v2 choices
        return q4_K_native_algo(
            dict(
                s,
                accum=s["accum"] if s["accum"] != "auto" else "float",
                scales=s["scales"] if s["scales"] != "auto" else "kmask",
                correction=s["correction"] if s["correction"] != "auto" else "act",
            )
        )
    R, P = s["rows"], s["prefetch"]
    if target == "scalar":
        return (
            prelude(target)
            + """
void kq4k_gemv(const void *W, const void *xv, float *y, int64_t K, int64_t r0, int64_t r1) {
    const int64_t nb = K / QK_K;
    const block_q8_K *x = (const block_q8_K *)xv;
    for (int64_t r = r0; r < r1; r++) {
        const block_q4_K *w = (const block_q4_K *)W + r * nb;
        float acc = 0;
        for (int64_t i = 0; i < nb; i++) {
            const uint8_t *q = w[i].scales;
            int32_t isum = 0, msum = 0;
            for (int s = 0; s < 8; s++) {
                int sc = s < 4 ? q[s] & 63 : (q[s + 4] & 0xF) | ((q[s - 4] >> 6) << 4);
                int mn = s < 4 ? q[s + 4] & 63 : (q[s + 4] >> 4) | ((q[s] >> 6) << 4);
                const uint8_t *q4 = w[i].qs + (s / 2) * 32;
                int32_t t = 0;
                for (int l = 0; l < 32; l++) t += ((q4[l] >> (4 * (s & 1))) & 0xF) * x[i].qs[32 * s + l];
                isum += sc * t;
                msum += mn * (x[i].bsums[2 * s] + x[i].bsums[2 * s + 1]);
            }
            acc += x[i].d * (f16f(w[i].d) * (float)isum - f16f(w[i].dmin) * (float)msum);
        }
        y[r] = acc;
    }
}
"""
        )
    if target == "avx512_vnni":
        sb = """
typedef struct { __m512i y[4]; __m256i bsum; float d; } xsb;
static inline __m512i cat256(const int8_t *a, const int8_t *b) {
    return _mm512_inserti64x4(_mm512_castsi256_si512(_mm256_loadu_si256((const __m256i *)a)), _mm256_loadu_si256((const __m256i *)b), 1);
}
static inline void row_sb(const block_q4_K *w, const xsb *xs, __m512 *acc, __m256 *macc) {
    const __m512i m4 = _mm512_set1_epi8(0x0F), z = _mm512_setzero_si512();
    uint64_t sc, mn;
    q4k_decode(w->scales, &sc, &mn);
    const __m512 s8 = _mm512_castps256_ps512(_mm256_mul_ps(_mm256_cvtepi32_ps(_mm256_cvtepu8_epi32(_mm_cvtsi64_si128((long long)sc))),
                                                           _mm256_set1_ps(xs->d * f16f(w->d))));
#define PAIR(a, b) _mm512_permutexvar_ps(_mm512_setr_epi32(a, a, a, a, a, a, a, a, b, b, b, b, b, b, b, b), s8)
    const __m512i q01 = _mm512_loadu_si512((const void *)w->qs), q23 = _mm512_loadu_si512((const void *)(w->qs + 64));
    *acc = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_dpbusd_epi32(z, _mm512_and_si512(q01, m4), xs->y[0])), PAIR(0, 2), *acc);
    *acc = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_dpbusd_epi32(z, _mm512_and_si512(_mm512_srli_epi16(q01, 4), m4), xs->y[1])), PAIR(1, 3), *acc);
    *acc = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_dpbusd_epi32(z, _mm512_and_si512(q23, m4), xs->y[2])), PAIR(4, 6), *acc);
    *acc = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_dpbusd_epi32(z, _mm512_and_si512(_mm512_srli_epi16(q23, 4), m4), xs->y[3])), PAIR(5, 7), *acc);
#undef PAIR
    *macc = _mm256_fmadd_ps(_mm256_cvtepi32_ps(_mm256_mullo_epi32(_mm256_cvtepu8_epi32(_mm_cvtsi64_si128((long long)mn)), xs->bsum)),
                            _mm256_set1_ps(xs->d * f16f(w->dmin)), *macc);
}
typedef block_q4_K block_T;
void kq4k_gemv(const void *W, const void *xv, float *y, int64_t K, int64_t r0, int64_t r1) {
    const int64_t nb = K / QK_K;
    const block_q4_K *w = (const block_q4_K *)W;
    const block_q8_K *x = (const block_q8_K *)xv;
    xsb xs[128];
    for (int64_t i = 0; i < nb; i++) {
        const int8_t *q = x[i].qs;
        xs[i].y[0] = cat256(q, q + 64); xs[i].y[1] = cat256(q + 32, q + 96);
        xs[i].y[2] = cat256(q + 128, q + 192); xs[i].y[3] = cat256(q + 160, q + 224);
        xs[i].bsum = bsum_pairs(x + i); xs[i].d = x[i].d;
    }
"""
        body = lambda i: f"            row_sb(w{i} + p, xs + p, &a{i}, &m{i});"
        decl = lambda i: f"        __m512 a{i} = _mm512_setzero_ps(); __m256 m{i} = _mm256_setzero_ps();"
        red = lambda i: (
            f"        y[r + {i}] = _mm512_reduce_add_ps(a{i}) - _mm512_reduce_add_ps(_mm512_insertf32x8(_mm512_setzero_ps(), m{i}, 0));"
        )
    elif target in ("avx2", "avx2_vnni"):
        dot = (
            "_mm256_dpbusd_avx_epi32(z, {a}, {b})" if target == "avx2_vnni" else "_mm256_madd_epi16(_mm256_maddubs_epi16({a}, {b}), ones16)"
        )
        lines = []
        for j in range(4):
            lines.append(f"    {{ const __m256i q = _mm256_loadu_si256((const __m256i *)(w->qs + {32 * j}));")
            lines.append(
                f"      *acc = _mm256_fmadd_ps(_mm256_cvtepi32_ps({dot.format(a='_mm256_and_si256(q, m4)', b='_mm256_loadu_si256((const __m256i *)(xs->q + ' + str(64 * j) + '))')}), _mm256_permutevar8x32_ps(s8, _mm256_set1_epi32({2 * j})), *acc);"
            )
            lines.append(
                f"      *acc = _mm256_fmadd_ps(_mm256_cvtepi32_ps({dot.format(a='_mm256_and_si256(_mm256_srli_epi16(q, 4), m4)', b='_mm256_loadu_si256((const __m256i *)(xs->q + ' + str(64 * j + 32) + '))')}), _mm256_permutevar8x32_ps(s8, _mm256_set1_epi32({2 * j + 1})), *acc); }}"
            )
        sb = (
            """
typedef struct { const int8_t *q; __m256i bsum; float d; } xsb;
static inline void row_sb(const block_q4_K *w, const xsb *xs, __m256 *acc, __m256 *macc) {
    const __m256i m4 = _mm256_set1_epi8(0x0F), z = _mm256_setzero_si256(), ones16 = _mm256_set1_epi16(1);
    (void)z; (void)ones16;
    uint64_t sc, mn;
    q4k_decode(w->scales, &sc, &mn);
    const __m256 s8 = _mm256_mul_ps(_mm256_cvtepi32_ps(_mm256_cvtepu8_epi32(_mm_cvtsi64_si128((long long)sc))), _mm256_set1_ps(xs->d * f16f(w->d)));
"""
            + "\n".join(lines)
            + """
    *macc = _mm256_fmadd_ps(_mm256_cvtepi32_ps(_mm256_mullo_epi32(_mm256_cvtepu8_epi32(_mm_cvtsi64_si128((long long)mn)), xs->bsum)),
                            _mm256_set1_ps(xs->d * f16f(w->dmin)), *macc);
}
static inline float hsum8(__m256 v) {
    __m128 s = _mm_add_ps(_mm256_castps256_ps128(v), _mm256_extractf128_ps(v, 1));
    s = _mm_add_ps(s, _mm_movehl_ps(s, s));
    return _mm_cvtss_f32(_mm_add_ss(s, _mm_movehdup_ps(s)));
}
typedef block_q4_K block_T;
void kq4k_gemv(const void *W, const void *xv, float *y, int64_t K, int64_t r0, int64_t r1) {
    const int64_t nb = K / QK_K;
    const block_q4_K *w = (const block_q4_K *)W;
    const block_q8_K *x = (const block_q8_K *)xv;
    xsb xs[128];
    for (int64_t i = 0; i < nb; i++) { xs[i].q = x[i].qs; xs[i].bsum = bsum_pairs(x + i); xs[i].d = x[i].d; }
"""
        )
        body = lambda i: f"            row_sb(w{i} + p, xs + p, &a{i}, &m{i});"
        decl = lambda i: f"        __m256 a{i} = _mm256_setzero_ps(), m{i} = _mm256_setzero_ps();"
        red = lambda i: f"        y[r + {i}] = hsum8(_mm256_sub_ps(a{i}, m{i}));"
    else:
        raise ValueError(target)
    pf = (lambda i: f"            _mm_prefetch((const char *)(w{i} + p + {P}), _MM_HINT_T0);") if P else None
    loop = _rows_loop(R, body, red, decl, pf).replace("INNER_PRE", "").replace("np;", "nb;")
    return prelude(target) + Q4K_DECODE + sb + loop + "\n}\n"


# --------------------------------------------------------------------------- q8_0 GEMM
def q8_0_gemm(target, s):
    if target == "scalar":
        return (
            prelude(target)
            + """
void kq8_gemm(const void *W, const void *Xv, float *Y, int64_t K, int64_t N, int64_t M, int64_t n0, int64_t n1) {
    const int64_t nb = K / QK8_0;
    const block_q8_0 *X = (const block_q8_0 *)Xv;
    for (int64_t n = n0; n < n1; n++) {
        const block_q8_0 *w = (const block_q8_0 *)W + n * nb;
        for (int64_t m = 0; m < M; m++) {
            const block_q8_0 *x = X + m * nb;
            float acc = 0;
            for (int64_t b = 0; b < nb; b++) {
                int32_t t = 0;
                for (int l = 0; l < QK8_0; l++) t += (int32_t)w[b].qs[l] * x[b].qs[l];
                acc += f16f(w[b].d) * f16f(x[b].d) * (float)t;
            }
            Y[m * N + n] = acc;
        }
    }
}
"""
        )
    RN, RM = s["rows"], s["cols"]
    if target == "avx512_vnni":
        decl = "\n".join(f"            __m512 c{a}_{b} = _mm512_setzero_ps();" for a in range(RN) for b in range(RM))
        wload = "\n".join(
            f"                const block_q8_0 *wb{a} = w + (n + ({a} < nr ? {a} : 0)) * nb + 2 * p;\n"
            f"                const __m512i q{a} = _mm512_xor_si512(load2(wb{a}), flip); const __m512 dw{a} = scale2(wb{a});"
            for a in range(RN)
        )
        mac = []
        for b in range(RM):
            mac.append(
                f"                {{ const int64_t xi = (m + ({b} < mr ? {b} : 0)) * np + p; const __m512i xx = xq[xi], bias = xb[xi]; const __m512 dx = xd[xi];"
            )
            for a in range(RN):
                mac.append(
                    f"                  c{a}_{b} = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_dpbusd_epi32(bias, q{a}, xx)), _mm512_mul_ps(dw{a}, dx), c{a}_{b});"
                )
            mac.append("                }")
        store = "\n".join(
            f"            if ({a} < nr && {b} < mr) Y[(m + {b}) * N + n + {a}] = _mm512_reduce_add_ps(c{a}_{b});"
            for a in range(RN)
            for b in range(RM)
        )
        return (
            prelude(target)
            + f"""
static inline __m512i load2(const block_q8_0 *b) {{
    return _mm512_inserti64x4(_mm512_castsi256_si512(_mm256_loadu_si256((const __m256i *)b[0].qs)),
                              _mm256_loadu_si256((const __m256i *)b[1].qs), 1);
}}
static inline __m512 scale2(const block_q8_0 *b) {{
    const __m512i idx = _mm512_set_epi32(1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0);
    return _mm512_permutexvar_ps(idx, _mm512_castps128_ps512(_mm_cvtph_ps(_mm_cvtsi32_si128((int)b[0].d | ((int)b[1].d << 16)))));
}}
void kq8_gemm(const void *W, const void *Xv, float *Y, int64_t K, int64_t N, int64_t M, int64_t n0, int64_t n1) {{
    const int64_t nb = K / QK8_0, np = nb / 2;
    const block_q8_0 *w = (const block_q8_0 *)W, *X = (const block_q8_0 *)Xv;
    const __m512i flip = _mm512_set1_epi8((char)0x80), zero = _mm512_setzero_si512();
    __m512i *xq = aligned_alloc(64, 64 * np * M), *xb = aligned_alloc(64, 64 * np * M);
    __m512 *xd = aligned_alloc(64, 64 * np * M);
    for (int64_t i = 0; i < M * np; i++) {{
        const block_q8_0 *b = X + 2 * i;
        xq[i] = load2(b);
        xb[i] = _mm512_sub_epi32(zero, _mm512_slli_epi32(_mm512_dpbusd_epi32(zero, _mm512_set1_epi8(1), xq[i]), 7));
        xd[i] = scale2(b);
    }}
    for (int64_t n = n0; n < n1; n += {RN}) {{
        const int nr = n1 - n < {RN} ? (int)(n1 - n) : {RN};
        for (int64_t m = 0; m < M; m += {RM}) {{
            const int mr = M - m < {RM} ? (int)(M - m) : {RM};
{decl}
            for (int64_t p = 0; p < np; p++) {{
{wload}
{chr(10).join(mac)}
            }}
{store}
        }}
    }}
    free(xq); free(xb); free(xd);
}}
"""
        )
    if target == "amx":
        return prelude(target) + _amx_gemm(RN, RM)
    raise ValueError(target)


def _amx_gemm(NT, MT):
    # NT n-tiles x MT m-tiles of 16x16 int32 accumulators per pass (C tiles 0..3, A 4..5, B 6..7)
    tiles = [(mi, ni) for mi in range(MT) for ni in range(NT)]
    cfg_c = len(tiles)
    loads = []
    for ni in range(NT):
        loads.append(f"                _tile_loadd({6 + ni}, p->B + ((nt + {ni}) * nb + b) * 512, 64);")
    for mi in range(MT):
        loads.append(f"                _tile_loadd({4 + mi}, xa + ((mt + {mi}) * nb + b) * 512, 32);")
    dps = [f"                _tile_dpbssd({k}, {4 + mi}, {6 + ni});" for k, (mi, ni) in enumerate(tiles)]
    zero = " ".join(f"_tile_zero({k});" for k in range(cfg_c))
    stores = [f"                _tile_stored({k}, cbuf[{k}], 64);" for k in range(cfg_c)]
    scale = []
    for k, (mi, ni) in enumerate(tiles):
        scale.append(f"""                {{ const float *dx = xd + ((mt + {mi}) * nb + b) * 16; const __m512 dw = _mm512_load_ps(p->dw + ((nt + {ni}) * nb + b) * 16);
                  for (int r = 0; r < 16; r++)
                      _mm512_store_ps(acc[{k}][r], _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_load_si512(cbuf[{k}][r])), _mm512_mul_ps(dw, _mm512_set1_ps(dx[r])), _mm512_load_ps(acc[{k}][r]))); }}""")
    out = []
    for k, (mi, ni) in enumerate(tiles):
        out.append(f"""            for (int r = 0; r < 16; r++) {{ const int64_t m = (mt + {mi}) * 16 + r; if (m >= M) break;
                for (int c = 0; c < 16; c++) {{ const int64_t n = (nt + {ni}) * 16 + c; if (n < n1) Y[m * N + n] = acc[{k}][r][c]; }} }}""")
    return f"""#include <stdio.h>
#include <sys/syscall.h>
#include <unistd.h>
typedef struct __attribute__((packed, aligned(64))) {{ uint8_t palette_id, start_row, reserved[14]; uint16_t colsb[16]; uint8_t rows[16]; }} tilecfg;
__attribute__((constructor)) static void amx_perm(void) {{ syscall(SYS_arch_prctl, 0x1023, 18); }}
void kern_thread_init(void) {{
    tilecfg c; memset(&c, 0, sizeof c); c.palette_id = 1;
    for (int t = 0; t < 4; t++) {{ c.rows[t] = 16; c.colsb[t] = 64; }}
    for (int t = 4; t < 6; t++) {{ c.rows[t] = 16; c.colsb[t] = 32; }}
    for (int t = 6; t < 8; t++) {{ c.rows[t] = 8; c.colsb[t] = 64; }}
    _tile_loadconfig(&c);
}}
typedef struct {{ int64_t nb, ntiles; int8_t *B; float *dw; }} packed_w;
void *kq8_gemm_prepare(const void *W, int64_t K, int64_t N) {{
    const block_q8_0 *w = (const block_q8_0 *)W;
    packed_w *p = malloc(sizeof *p);
    p->nb = K / QK8_0; p->ntiles = (N + 15) / 16 + 1;
    p->B = aligned_alloc(64, (size_t)p->ntiles * p->nb * 512); p->dw = aligned_alloc(64, (size_t)p->ntiles * p->nb * 64);
    memset(p->B, 0, (size_t)p->ntiles * p->nb * 512); memset(p->dw, 0, (size_t)p->ntiles * p->nb * 64);
    for (int64_t t = 0; t * 16 < N; t++) for (int64_t b = 0; b < p->nb; b++) for (int n = 0; n < 16 && t * 16 + n < N; n++) {{
        const block_q8_0 *blk = w + (t * 16 + n) * p->nb + b;
        p->dw[(t * p->nb + b) * 16 + n] = f16f(blk->d);
        for (int kk = 0; kk < 8; kk++) for (int j = 0; j < 4; j++) p->B[(t * p->nb + b) * 512 + kk * 64 + n * 4 + j] = blk->qs[kk * 4 + j];
    }}
    return p;
}}
void kq8_gemm(const void *W, const void *X, float *Y, int64_t K, int64_t N, int64_t M, int64_t n0, int64_t n1) {{
    (void)W; (void)X; (void)Y; (void)K; (void)N; (void)M; (void)n0; (void)n1; abort();
}}
static __thread int8_t *xa; static __thread float *xd; static __thread size_t cap;
void kq8_gemm_packed(const void *pv, const void *Xv, float *Y, int64_t K, int64_t N, int64_t M, int64_t n0, int64_t n1) {{
    const packed_w *p = (const packed_w *)pv;
    const int64_t nb = K / QK8_0, mtiles = (M + 15) / 16 + 1;
    const block_q8_0 *X = (const block_q8_0 *)Xv;
    const size_t need = (size_t)mtiles * nb * 512;
    if (cap < need) {{ free(xa); free(xd); xa = aligned_alloc(64, need); xd = aligned_alloc(64, (size_t)mtiles * nb * 64); cap = need; }}
    memset(xa, 0, need); memset(xd, 0, (size_t)mtiles * nb * 64);
    for (int64_t m = 0; m < M; m++) for (int64_t b = 0; b < nb; b++) {{
        memcpy(xa + ((m / 16) * nb + b) * 512 + (m % 16) * 32, X[m * nb + b].qs, 32);
        xd[((m / 16) * nb + b) * 16 + m % 16] = f16f(X[m * nb + b].d);
    }}
    int32_t cbuf[{cfg_c}][16][16] __attribute__((aligned(64)));
    float acc[{cfg_c}][16][16] __attribute__((aligned(64)));
    for (int64_t nt = n0 / 16; nt * 16 < n1; nt += {NT}) {{
        for (int64_t mt = 0; mt * 16 < M; mt += {MT}) {{
            memset(acc, 0, sizeof acc);
            for (int64_t b = 0; b < nb; b++) {{
                {zero}
{chr(10).join(loads)}
{chr(10).join(dps)}
{chr(10).join(stores)}
{chr(10).join(scale)}
            }}
{chr(10).join(out)}
        }}
    }}
}}
"""


# File-scope helper names used by the lowerings above (entry points come from kernels.py).
# A new lowering that adds a file-scope helper or typedef must list it here.
EMBED_HELPERS = (
    "kern_thread_init", "f16f", "store16", "load2", "scale2", "hsum8", "q4k_decode", "bsum_pairs",
    "cat256", "row_sb", "xsb", "vblk", "packed_t", "packed_w", "tilecfg", "amx_perm", "block_T",
)  # fmt: skip


_HELPER_DEF = re.compile(r"^static inline\b[^(;{]*?\b(\w+)\s*\(", re.M)


def _definition_end(src, start):
    """Index just past the body of the function whose definition starts at `start`."""
    depth, i, n = 0, src.index("{", start), len(src)
    while i < n:
        ch = src[i]
        if src.startswith("//", i):
            i = src.find("\n", i)
            i = n if i < 0 else i
            continue
        if src.startswith("/*", i):
            i = src.index("*/", i) + 2
            continue
        if ch in "'\"":
            j = i + 1
            while src[j] != ch:
                j += 2 if src[j] == "\\" else 1
            i = j + 1
            continue
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                end = i + 1
                if src.startswith("\n", end):
                    end += 1
                if src.startswith("\n", end):
                    end += 1
                return end
        i += 1
    raise ValueError("unbalanced braces in generated helper")


def prune_helpers(src):
    """Drop file-scope `static inline` helpers the kernel never calls. Templates share helper
    preambles across variants; clang's -Wunused-function (unlike GCC) warns on unused static
    inline functions in the main file, which -Werror turns into build failures."""
    while True:
        for m in _HELPER_DEF.finditer(src):
            end = _definition_end(src, m.start())
            rest = src[: m.start()] + src[end:]
            if not re.search(rf"\b{m.group(1)}\b", rest):
                src = rest
                break
        else:
            return src


def embed(src, prefix, entry_points=()):
    """Make generated C pasteable into another code base (e.g. ggml-cpu.c): drop the
    kurn.h include (the host provides the block structs), prefix every symbol, and
    make the entry points static."""
    src = src.replace('#include "kurn.h"\n', "")
    for sym in (*entry_points, *EMBED_HELPERS):
        src = re.sub(rf"\b{sym}\b", prefix + sym, src)
    return re.sub(rf"^(void \*?){re.escape(prefix)}", rf"static \g<1>{prefix}", src, flags=re.M)


# --------------------------------------------------------------------------- q4_K native, algorithm keys
def q4_K_native_algo(s):
    """Native-layout Q4_K AVX-512 GEMV assembled from independent algorithm choices.
    The hand-written phase-1 kernels are two points of this space:
      v1 = act=inline, accum=int,   scales=bytewise, correction=scalar
      v2 = act=once,   accum=float, scales=kmask,    correction=act
    """
    R, P = s["rows"], s["prefetch"]
    act, accum, scales, corr = s["act"], s["accum"], s["scales"], s["correction"]
    dec = (
        "uint64_t sc64, mn64; q4k_decode(w->scales, &sc64, &mn64); uint8_t sc[8], mn[8]; memcpy(sc, &sc64, 8); memcpy(mn, &mn64, 8);"
        if scales == "kmask"
        else "uint8_t sc[8], mn[8]; const uint8_t *q6 = w->scales;\n"
        "    for (int j = 0; j < 4; j++) { sc[j] = q6[j] & 63; mn[j] = q6[j + 4] & 63; }\n"
        "    for (int j = 4; j < 8; j++) { sc[j] = (q6[j + 4] & 0xF) | ((q6[j - 4] >> 6) << 4); mn[j] = (q6[j + 4] >> 4) | ((q6[j] >> 6) << 4); }"
    )
    lines = [
        f"    {dec}",
        "    const __m512i m4 = _mm512_set1_epi8(0x0F), z = _mm512_setzero_si512();",
        "    const float dd = xs->d * f16f(w->d);",
    ]
    if accum == "float":
        lines.append("    uint64_t scp; memcpy(&scp, sc, 8);")
        lines.append(
            "    const __m512 s8 = _mm512_castps256_ps512(_mm256_mul_ps(_mm256_cvtepi32_ps(_mm256_cvtepu8_epi32(_mm_cvtsi64_si128((long long)scp))), _mm256_set1_ps(dd)));"
        )
    else:
        lines.append("    __m512i isum = z;")
    for j in (0, 2):
        if act == "once":
            ylo, yhi = f"xs->y[{j}]", f"xs->y[{j + 1}]"
        else:
            ylo = f"cat256(xs->q + {64 * j}, xs->q + {64 * (j + 1)})"
            yhi = f"cat256(xs->q + {64 * j + 32}, xs->q + {64 * (j + 1) + 32})"
        lines.append(f"    {{ const __m512i q = _mm512_loadu_si512((const void *)(w->qs + {32 * j}));")
        lines.append(f"      const __m512i dlo = _mm512_dpbusd_epi32(z, _mm512_and_si512(q, m4), {ylo});")
        lines.append(f"      const __m512i dhi = _mm512_dpbusd_epi32(z, _mm512_and_si512(_mm512_srli_epi16(q, 4), m4), {yhi});")
        if accum == "float":
            a0, a1, b0, b1 = 2 * j, 2 * j + 2, 2 * j + 1, 2 * j + 3
            lines.append(
                f"      *acc = _mm512_fmadd_ps(_mm512_cvtepi32_ps(dlo), _mm512_permutexvar_ps(_mm512_setr_epi32({a0},{a0},{a0},{a0},{a0},{a0},{a0},{a0},{a1},{a1},{a1},{a1},{a1},{a1},{a1},{a1}), s8), *acc);"
            )
            lines.append(
                f"      *acc = _mm512_fmadd_ps(_mm512_cvtepi32_ps(dhi), _mm512_permutexvar_ps(_mm512_setr_epi32({b0},{b0},{b0},{b0},{b0},{b0},{b0},{b0},{b1},{b1},{b1},{b1},{b1},{b1},{b1},{b1}), s8), *acc); }}"
            )
        else:
            lines.append(
                f"      const __m512i slo = _mm512_inserti64x4(_mm512_set1_epi32(sc[{2 * j}]), _mm256_set1_epi32(sc[{2 * j + 2}]), 1);"
            )
            lines.append(
                f"      const __m512i shi = _mm512_inserti64x4(_mm512_set1_epi32(sc[{2 * j + 1}]), _mm256_set1_epi32(sc[{2 * j + 3}]), 1);"
            )
            lines.append(
                "      isum = _mm512_add_epi32(isum, _mm512_add_epi32(_mm512_mullo_epi32(dlo, slo), _mm512_mullo_epi32(dhi, shi))); }"
            )
    if accum == "int":
        lines.append("    *acc = _mm512_fmadd_ps(_mm512_cvtepi32_ps(isum), _mm512_set1_ps(dd), *acc);")
    if corr == "act":
        bs = "xs->bsum" if act == "once" else "bsum_pairs(xs->x)"
        lines.append("    uint64_t mnp; memcpy(&mnp, mn, 8);")
        lines.append(
            f"    *macc = _mm256_fmadd_ps(_mm256_cvtepi32_ps(_mm256_mullo_epi32(_mm256_cvtepu8_epi32(_mm_cvtsi64_si128((long long)mnp)), {bs})), _mm256_set1_ps(xs->d * f16f(w->dmin)), *macc);"
        )
    else:
        lines.append("    int32_t ms = 0;")
        lines.append("    for (int t = 0; t < 8; t++) ms += mn[t] * (xs->x->bsums[2 * t] + xs->x->bsums[2 * t + 1]);")
        lines.append("    *mscal += xs->d * f16f(w->dmin) * (float)ms;")
    if act == "once":
        prep = """
    for (int64_t i = 0; i < nb; i++) {
        const int8_t *q = x[i].qs;
        xs[i].y[0] = cat256(q, q + 64); xs[i].y[1] = cat256(q + 32, q + 96);
        xs[i].y[2] = cat256(q + 128, q + 192); xs[i].y[3] = cat256(q + 160, q + 224);
        xs[i].bsum = bsum_pairs(x + i); xs[i].d = x[i].d; xs[i].q = x[i].qs; xs[i].x = x + i;
    }"""
    else:
        prep = """
    for (int64_t i = 0; i < nb; i++) { xs[i].d = x[i].d; xs[i].q = x[i].qs; xs[i].x = x + i; }"""
    sb = f"""
typedef struct {{ __m512i y[4]; __m256i bsum; float d; const int8_t *q; const block_q8_K *x; }} xsb;
static inline __m512i cat256(const int8_t *a, const int8_t *b) {{
    return _mm512_inserti64x4(_mm512_castsi256_si512(_mm256_loadu_si256((const __m256i *)a)), _mm256_loadu_si256((const __m256i *)b), 1);
}}
static inline void row_sb(const block_q4_K *w, const xsb *xs, __m512 *acc, __m256 *macc, float *mscal) {{
    (void)macc; (void)mscal;
{chr(10).join(lines)}
}}
typedef block_q4_K block_T;
void kq4k_gemv(const void *W, const void *xv, float *y, int64_t K, int64_t r0, int64_t r1) {{
    const int64_t nb = K / QK_K;
    const block_q4_K *w = (const block_q4_K *)W;
    const block_q8_K *x = (const block_q8_K *)xv;
    xsb xs[128];{prep}
"""
    body = lambda i: f"            row_sb(w{i} + p, xs + p, &a{i}, &m{i}, &s{i});"
    decl = lambda i: f"        __m512 a{i} = _mm512_setzero_ps(); __m256 m{i} = _mm256_setzero_ps(); float s{i} = 0;"
    red = lambda i: (
        f"        y[r + {i}] = _mm512_reduce_add_ps(a{i}) - _mm512_reduce_add_ps(_mm512_insertf32x8(_mm512_setzero_ps(), m{i}, 0)) - s{i};"
    )
    pf = (lambda i: f"            _mm_prefetch((const char *)(w{i} + p + {P}), _MM_HINT_T0);") if P else None
    loop = _rows_loop(R, body, red, decl, pf).replace("INNER_PRE", "").replace("np;", "nb;")
    return prelude("avx512_vnni") + Q4K_DECODE + sb + loop + "\n}\n"
