import os
import subprocess
import sys

import pytest

from kurn import __version__
from kurn.cli import main
from kurn.toolchain import run_mode

from conftest import EXAMPLES, ROOT

Q8 = str(EXAMPLES / "q8_0_gemv_vnni16.kurn")


def test_version(capsys):
    with pytest.raises(SystemExit) as e:
        main(["--version"])
    assert e.value.code == 0 and f"kurn {__version__}" in capsys.readouterr().out


def test_check(capsys):
    assert main(["check", Q8]) == 0
    out = capsys.readouterr().out
    assert '"layout": "vnni16"' in out and "tune space: 72 legal configurations" in out


def test_check_invalid_value_lists_legal_ones(capsys):
    assert main(["check", Q8, "rows=3"]) == 2
    assert "expected one of [1, 2, 4, 8]" in capsys.readouterr().err


def test_list_override_rejected_outside_tune(capsys):
    assert main(["gen", Q8, "rows=1,2"]) == 2
    assert "only valid for `kurn tune`" in capsys.readouterr().err


def test_gen_to_file_and_embed(tmp_path):
    out = tmp_path / "k.c"
    assert main(["gen", Q8, "-o", str(out)]) == 0
    assert out.read_text().startswith("// Generated by kurn.") and "kq8_gemv_packed" in out.read_text()
    assert main(["gen", Q8, "--embed", "my_", "-o", str(out)]) == 0
    src = out.read_text()
    assert "static void my_kq8_gemv_packed(" in src and '#include "kurn.h"' not in src


def test_overrides_after_options(tmp_path):
    out = tmp_path / "k.c"
    assert main(["gen", Q8, "-o", str(out), "target=avx2", "layout=native"]) == 0
    assert "_mm256_maddubs_epi16" in out.read_text()


def test_build_and_verify(capsys):
    target = "avx512_vnni" if run_mode("avx512_vnni")[0] == "native" else "avx2"
    extra = [] if target == "avx512_vnni" else ["target=avx2", "layout=native"]
    assert main(["build", Q8, *extra]) == 0
    assert capsys.readouterr().out.strip().endswith(".so")
    assert main(["verify", Q8, *extra]) == 0
    assert "1 configurations, 0 failures" in capsys.readouterr().out


def test_verify_space(capsys):
    assert main(["verify", str(EXAMPLES / "q4_K_gemv.kurn"), "--space", "threads=4"]) == 0
    out = capsys.readouterr().out
    assert "9 configurations, 0 failures" in out  # rows x prefetch; threads/wait do not change codegen


def test_targets(capsys):
    assert main(["targets"]) == 0
    assert "avx512_vnni" in capsys.readouterr().out


def test_console_entry_point_runs():
    env = {**os.environ, "PYTHONPATH": str(ROOT / "src")}
    r = subprocess.run([sys.executable, "-m", "kurn", "check", Q8], capture_output=True, text=True, env=env)
    assert r.returncode == 0, r.stderr
