"""`kurn model`: compile the whole decode step of one fixed GGUF model into one C program.

Reads the GGUF header (dimensions, hyperparameters, tensor offsets) with the `gguf`
package, writes model_config.h with everything as compile-time constants, generates
the Q8_0 GEMV kernel from a kurn spec, and compiles the engine against both.
Supported: Qwen3 (dense) and OLMoE (MoE); all matmul weights (and token_embd/output) Q8_0, or
all Q4_0 (v2 only; e.g. `llama-quantize --pure MODEL-BF16.gguf OUT.gguf Q4_0`).

Engines: `v2` (engine.c, default) is the barrier-minimal schedule (2 barriers per dense
layer, 3 per MoE layer); `v1` (engine_v1.c) is the inherited 5-barriers-per-layer
schedule, kept as the baseline.
"""

import hashlib
import os
import subprocess

from .. import spec
from ..kernels import generate
from ..toolchain import cache_dir

HERE = os.path.dirname(os.path.abspath(__file__))
SOURCES = {"v1": "engine_v1.c", "v2": "engine.c"}


def _field(r, key):
    f = r.fields.get(key)
    if f is None:
        return None
    import gguf

    v = f.parts[f.data[0]]
    if f.types and f.types[0] == gguf.GGUFValueType.STRING:
        return bytes(v).decode()
    return v.tolist()[0]


def config_header(path):
    import gguf

    r = gguf.GGUFReader(path)
    arch = _field(r, "general.architecture")
    if arch not in ("qwen3", "olmoe"):
        raise ValueError(f"unsupported architecture {arch!r} (qwen3, olmoe)")
    g = lambda k: _field(r, f"{arch}.{k}")  # noqa: E731
    T = {t.name: t for t in r.tensors}
    mm = (
        "attn_q.weight",
        "attn_k.weight",
        "attn_v.weight",
        "attn_output.weight",
        "ffn_down.weight",
        "ffn_gate.weight",
        "ffn_up.weight",
        "_exps.weight",
        "output.weight",
        "token_embd.weight",
    )
    types = {t.name: t.tensor_type.name for t in r.tensors if t.name.endswith(mm)}
    wfmt = types["token_embd.weight"]
    for name, ty in types.items():
        if ty != wfmt or ty not in ("Q8_0", "Q4_0"):
            raise ValueError(
                f"{name} is {ty} (token_embd is {wfmt}); the engine needs all matmul weights Q8_0 or all Q4_0 (llama-quantize --pure)"
            )
    n_layer, n_embd, n_head = g("block_count"), g("embedding_length"), g("attention.head_count")
    n_kv = g("attention.head_count_kv")
    head_dim = g("attention.key_length") or n_embd // n_head
    n_expert = g("expert_count") or 0
    n_ff = g("feed_forward_length")
    if n_expert:
        n_ff = int(T["blk.0.ffn_gate_exps.weight"].shape[1])
    vocab = int(T["token_embd.weight"].shape[1])
    out = T.get("output.weight", T["token_embd.weight"])
    off = lambda name: int(T[name].data_offset)  # noqa: E731
    lines = [
        "// Generated by `kurn model`. Every dimension and tensor offset is a compile-time constant.",
        "#pragma once",
        "#include <stdint.h>",
        f"#define ARCH_{arch.upper()} 1",
        f"#define W_Q4_0 {int(wfmt == 'Q4_0')}",
        f"#define N_LAYER {n_layer}",
        f"#define N_EMBD {n_embd}",
        f"#define N_HEAD {n_head}",
        f"#define N_KV {n_kv}",
        f"#define HEAD_DIM {head_dim}",
        f"#define N_FF {n_ff}",
        f"#define N_VOCAB {vocab}",
        "#define N_QKV (N_HEAD * HEAD_DIM + 2 * N_KV * HEAD_DIM)",
        f"#define RMS_EPS {g('attention.layer_norm_rms_epsilon')}f",
        f"#define ROPE_BASE {g('rope.freq_base')}f",
        f"#define N_EXPERT {n_expert}",
        f"#define N_USED {g('expert_used_count') or 1}",
        f"#define N_USED_OR1 {g('expert_used_count') or 1}",
        f"#define EXPERT_WEIGHTS_NORM {int(bool(g('expert_weights_norm')))}",
        f"#define QK_NORM_HEAD {int(arch == 'qwen3')}",
        f"#define QK_NORM_FULL {int(arch == 'olmoe')}",
        f"static const int64_t OFF_TOK_EMBD = {off('token_embd.weight')};",
        f"static const int64_t OFF_OUT_NORM = {off('output_norm.weight')};",
        f"static const int64_t OFF_OUTPUT = {int(out.data_offset)};",
    ]

    def arr(name, suffix):
        vals = ", ".join(str(off(f"blk.{i}.{suffix}")) for i in range(n_layer))
        lines.append(f"static const int64_t {name}[N_LAYER] = {{{vals}}};")

    arr("OFF_ATTN_NORM", "attn_norm.weight")
    arr("OFF_FFN_NORM", "ffn_norm.weight")
    arr("OFF_Q", "attn_q.weight")
    arr("OFF_K", "attn_k.weight")
    arr("OFF_V", "attn_v.weight")
    arr("OFF_O", "attn_output.weight")
    arr("OFF_Q_NORM", "attn_q_norm.weight")
    arr("OFF_K_NORM", "attn_k_norm.weight")
    if n_expert:
        arr("OFF_GATE", "ffn_gate_exps.weight")
        arr("OFF_UP", "ffn_up_exps.weight")
        arr("OFF_DOWN", "ffn_down_exps.weight")
        arr("OFF_ROUTER", "ffn_gate_inp.weight")
    else:
        arr("OFF_GATE", "ffn_gate.weight")
        arr("OFF_UP", "ffn_up.weight")
        arr("OFF_DOWN", "ffn_down.weight")
    return "\n".join(lines) + "\n", arch, wfmt.lower()


def compile_model(gguf_path, out=None, kernel_keys=None, cc="gcc", engine="v2", defines=()):
    """Build the engine for one model. `defines` are extra -D flags (e.g. ("KURN_EPILOGUE=0",))."""
    hdr, arch, wfmt = config_header(gguf_path)
    if wfmt != "q8_0" and engine != "v2":
        raise ValueError(f"engine {engine} supports Q8_0 weights only (model is {wfmt})")
    keys = kernel_keys or {"layout": "vnni16", "align": "packed", "rows": 8}
    c = spec.resolve({"op": "gemv", "weights": "q8_0", "target": "avx512_vnni", **keys})
    work = os.path.join(cache_dir(), "model", os.path.basename(gguf_path).replace(".gguf", ""))
    os.makedirs(work, exist_ok=True)
    open(os.path.join(work, "model_config.h"), "w").write(hdr)
    kern = os.path.join(work, "kernel.c")
    open(kern, "w").write(generate(c))
    srcs = [os.path.join(HERE, SOURCES[engine]), kern]
    if engine == "v2":
        from ..epilogue import engine_kernels

        ep = os.path.join(work, "epilogue_kernels.c")
        open(ep, "w").write(engine_kernels(c, fmts=("q8_0",) if wfmt == "q8_0" else ("q8_0", wfmt)))
        srcs.append(ep)
    out = out or os.path.join(work, f"engine_{engine}_{_tag(engine, defines, c, hdr)}")
    from ..toolchain import data_path

    inc = os.path.dirname(data_path("kurn.h"))
    cmd = [
        cc,
        "-O3",
        "-march=native",
        "-mno-avx512fp16",
        "-fno-math-errno",
        "-I",
        work,
        "-I",
        inc,
        "-I",
        HERE,
        *(f"-D{d}" for d in defines),
        *srcs,
        "-o",
        out,
        "-lm",
        "-lpthread",
    ]
    subprocess.run(cmd, check=True)
    return out, arch, c


def _tag(engine, defines, c, hdr):
    srcs = [os.path.join(HERE, SOURCES[engine]), os.path.join(HERE, "kq8e.h"), os.path.join(HERE, "..", "epilogue.py")]
    h = hashlib.sha1(repr((engine, sorted(defines), sorted(c.items()), hdr)).encode())
    for p in srcs:
        h.update(open(p, "rb").read())
    return h.hexdigest()[:8]


def engine_binary(gguf_path, engine="v2", defines=()):
    """Path of the engine for this model/config/source, compiled only if it is not in the cache yet."""
    c = spec.resolve({"op": "gemv", "weights": "q8_0", "target": "avx512_vnni", "layout": "vnni16", "align": "packed", "rows": 8})
    work = os.path.join(cache_dir(), "model", os.path.basename(gguf_path).replace(".gguf", ""))
    out = os.path.join(work, f"engine_{engine}_{_tag(engine, defines, c, config_header(gguf_path)[0])}")
    return out if os.path.exists(out) else compile_model(gguf_path, engine=engine, defines=defines)[0]
