// Fused-epilogue vnni16 Q8_0 GEMV entry points, generated by kurn.epilogue (engine_kernels).
//
// A packed matrix is ceil(N/16) groups of 16 rows; group g holds nb vblks (one per 32-column
// block). Every GEMV multiplies blocks [b0, b1) of groups [g0, g1) by an activation prepared
// with kq8e_prep for exactly those b1 - b0 blocks, and writes rows 16*g0 .. 16*g1 - 1 of y
// (indexed absolutely: y[16 * g + lane]).
#pragma once
#include "kurn.h"
#include <stddef.h>
#include <stdint.h>

#ifndef KQ8E_MAXNB
#define KQ8E_MAXNB 1024
typedef struct { int32_t xw[8 * KQ8E_MAXNB]; int32_t ncs[KQ8E_MAXNB]; float xd[KQ8E_MAXNB]; } kq8e_act;
#endif

size_t kq8e_blk_bytes(void);                                       // bytes per (group, block)
void kq8e_pack(void *dst, const void *w, int64_t nb, int64_t N);   // N contiguous Q8_0 rows of nb blocks
void kq8e_prep(const void *x_q8, int64_t nb, kq8e_act *a);
void kq8e_quantize(const float *x, void *y_q8, int64_t k);         // == ggml quantize_row_q8_0 (x86)
void kq8e_swiglu(const float *g, const float *u, float *y, int64_t n);  // == ggml_vec_swiglu_f32 (AVX-512)

void kq8e_store(const void *W, int64_t nb, const kq8e_act *a, int64_t b0, int64_t b1, int64_t g0, int64_t g1, float *y);
float kq8e_store_sumsq(const void *W, int64_t nb, const kq8e_act *a, int64_t b0, int64_t b1, int64_t g0, int64_t g1, float *y);
void kq8e_axpy(const void *W, int64_t nb, const kq8e_act *a, int64_t b0, int64_t b1, int64_t g0, int64_t g1, float *y, float s);
// gate/up interleaved per 16 rows (group 2j = gate rows 16j.., group 2j+1 = up rows 16j..);
// g0, g1 multiples of 4; writes Q8_0 block g/4 of silu(gate)*up (and the floats to yact if non-NULL).
void kq8e_swiglu_q8(const void *W, int64_t nb, const kq8e_act *a, int64_t b0, int64_t b1, int64_t g0, int64_t g1, void *yq,
                    float *yact);

// The same entry points for Q4_0 weights (engine_kernels(..., fmts=("q4_0",))); activations are the
// same Q8_0 kq8e_act. Pack from N contiguous rows of nb block_q4_0.
typedef struct { uint16_t d; uint8_t qs[16]; } kq4e_block_q4_0;
size_t kq4e_blk_bytes(void);
void kq4e_pack(void *dst, const void *w, int64_t nb, int64_t N);
void kq4e_store(const void *W, int64_t nb, const kq8e_act *a, int64_t b0, int64_t b1, int64_t g0, int64_t g1, float *y);
float kq4e_store_sumsq(const void *W, int64_t nb, const kq8e_act *a, int64_t b0, int64_t b1, int64_t g0, int64_t g1, float *y);
void kq4e_axpy(const void *W, int64_t nb, const kq8e_act *a, int64_t b0, int64_t b1, int64_t g0, int64_t g1, float *y, float s);
void kq4e_swiglu_q8(const void *W, int64_t nb, const kq8e_act *a, int64_t b0, int64_t b1, int64_t g0, int64_t g1, void *yq,
                    float *yact);
