// kurn kernel ABI. Every kernel generated by kurn implements (a subset of) it.
//
// Block layouts are byte-identical to ggml (ggml/src/ggml-common.h):
//   block_q8_0 : fp16 d; int8 qs[32]                         -> 34 bytes / 32 weights
//   block_q4_K : fp16 d; fp16 dmin; u8 scales[12]; u8 qs[128] -> 144 bytes / 256 weights
//   block_q8_K : f32 d; int8 qs[256]; int16 bsums[16]         -> 292 bytes / 256 values
//
// All kernels compute a contiguous slice of output rows, so any thread pool can
// split work by rows. Limits of the generated code: K <= 32768 (per-call
// activation buffers live on the stack); Q8_0 avx512_vnni kernels with the
// native layout need K to be a multiple of 64; int8 values must lie in
// [-127, 127] (as ggml's quantizers produce).
#pragma once
#include <stdint.h>

#define QK8_0 32
#define QK_K 256

typedef struct { uint16_t d; int8_t qs[QK8_0]; } block_q8_0;
typedef struct { uint16_t d; uint16_t dmin; uint8_t scales[12]; uint8_t qs[QK_K / 2]; } block_q4_K;
typedef struct { float d; int8_t qs[QK_K]; int16_t bsums[QK_K / 16]; } block_q8_K;

_Static_assert(sizeof(block_q8_0) == 34, "q8_0 size");
_Static_assert(sizeof(block_q4_K) == 144, "q4_K size");
_Static_assert(sizeof(block_q8_K) == 292, "q8_K size");

#ifdef __cplusplus
extern "C" {
#endif

// Decode matrix-vector: y[r] = dot(W[r, :], x) for r in [r0, r1).
// W: rows of K/32 block_q8_0; x: K/32 block_q8_0 (activation quantized by ggml).
void kq8_gemv(const void *W, const void *x, float *y, int64_t K, int64_t r0, int64_t r1);

// W: rows of K/256 block_q4_K; x: K/256 block_q8_K.
void kq4k_gemv(const void *W, const void *x, float *y, int64_t K, int64_t r0, int64_t r1);

// Prefill matrix-matrix: Y[m*N + n] = dot(W[n, :], X[m, :]) for n in [n0, n1), all m < M.
// W: N rows of K/32 block_q8_0; X: M rows of K/32 block_q8_0.
void kq8_gemm(const void *W, const void *X, float *Y, int64_t K, int64_t N, int64_t M,
              int64_t n0, int64_t n1);

// Optional one-time hook (e.g. AMX tile repacking). Called once per weight
// matrix before timing; returns an opaque handle passed back via kq8_gemm_packed.
void *kq8_gemm_prepare(const void *W, int64_t K, int64_t N);
void kq8_gemm_packed(const void *packed, const void *X, float *Y, int64_t K, int64_t N,
                     int64_t M, int64_t n0, int64_t n1);
// Optional GEMV weight repacking (layout chosen by the implementation): the
// harness calls *_prepare once per weight matrix and then *_packed instead of
// kq8_gemv / kq4k_gemv. r0 is a multiple of 16.
void *kq8_gemv_prepare(const void *W, int64_t K, int64_t N);
void kq8_gemv_packed(const void *packed, const void *x, float *y, int64_t K, int64_t r0, int64_t r1);
void *kq4k_gemv_prepare(const void *W, int64_t K, int64_t N);
void kq4k_gemv_packed(const void *packed, const void *x, float *y, int64_t K, int64_t r0, int64_t r1);
// v0.2 (generic recipe lowering). GEMV entry points: y[r] for r in [r0, r1) with
// W in the native ggml block layout (block_q4_0, block_iq4_nl, block_q2_0,
// block_tq2_0, block_q1_0) and x in Q8_0 (Q8_K for tq2_0). Interleaved layouts
// (i16 / i8) export only the _prepare / _packed pair.
#define KURN_GEMV_DECL(name)                                                                     \
    void name(const void *W, const void *x, float *y, int64_t K, int64_t r0, int64_t r1);        \
    void *name##_prepare(const void *W, int64_t K, int64_t N);                                  \
    void name##_packed(const void *packed, const void *x, float *y, int64_t K, int64_t r0, int64_t r1);
KURN_GEMV_DECL(kq40_gemv)
KURN_GEMV_DECL(kiq4nl_gemv)
KURN_GEMV_DECL(kq20_gemv)
KURN_GEMV_DECL(ktq20_gemv)
KURN_GEMV_DECL(kq10_gemv)
// Multi-token verify: Y[m*N + n] for n in [n0, n1), m < M <= cols (2..8 activation columns,
// e.g. k draft tokens of speculative decoding, or a small decode batch). Same arithmetic
// per column as the GEMV, so results do not depend on the batch size.
#define KURN_VFY_DECL(name)                                                                      \
    void name(const void *W, const void *X, float *Y, int64_t K, int64_t N, int64_t M, int64_t n0, int64_t n1); \
    void *name##_prepare(const void *W, int64_t K, int64_t N);                                  \
    void name##_packed(const void *packed, const void *X, float *Y, int64_t K, int64_t N, int64_t M, int64_t n0, int64_t n1);
KURN_VFY_DECL(kq8_vfy)
KURN_VFY_DECL(kq4k_vfy)
KURN_VFY_DECL(kq40_vfy)
KURN_VFY_DECL(kiq4nl_vfy)
KURN_VFY_DECL(kq20_vfy)
KURN_VFY_DECL(ktq20_vfy)
KURN_VFY_DECL(kq10_vfy)
/* --- lowbit --- */
// TQ1_0 (block_tq1_0, Q8_K activations) and Q2_K (block_q2_K, Q8_K activations).
KURN_GEMV_DECL(ktq10_gemv)
KURN_GEMV_DECL(kq2k_gemv)
// layout=lut kernels of the <= 2-bit GEMVs also export a split form so the per-activation
// table precompute can be shared by all threads: every thread builds units [u0, u1) of
// one table buffer (size from _lut_info), then, after a barrier, computes its rows.
#define KURN_LUT_DECL(name)                                                                       \
    void name##_lut_info(int64_t K, int64_t *bytes, int64_t *units);                              \
    void name##_lut_build(const void *x, int64_t K, void *tabs, int64_t u0, int64_t u1);          \
    void name##_lut_rows(const void *packed, const void *tabs, float *y, int64_t K, int64_t r0, int64_t r1);
KURN_LUT_DECL(kq10_gemv)
KURN_LUT_DECL(kq20_gemv)
KURN_LUT_DECL(ktq20_gemv)
KURN_LUT_DECL(ktq10_gemv)
/* --- end lowbit --- */
/* --- fourbit --- */
// MXFP4 / NVFP4 (ggml block_mxfp4 / block_nvfp4) x Q8_0. NVFP4's per-tensor scale is
// not applied: multiply y by it.
KURN_GEMV_DECL(kmxfp4_gemv)
KURN_GEMV_DECL(knvfp4_gemv)
KURN_VFY_DECL(kmxfp4_vfy)
KURN_VFY_DECL(knvfp4_vfy)
/* --- end fourbit --- */
// Optional per-thread init (AMX needs per-thread tile config).
void kern_thread_init(void);
/* --- compress --- */
// E8P lattice codebook (QuIP#-style, 2.06 bpw): fp16 d; u8 lo[32]; u8 hi[32] (8 weights per code) per
// 256 weights; activations Q8_K of the Hadamard-rotated input (see kurn.codebook).
KURN_GEMV_DECL(ke8p_gemv)
/* --- end compress --- */

#ifdef __cplusplus
}
#endif
