// Generated by kurn (layout algebra + schedule lowering, sched.py). Do not edit; edit the .kurn spec instead.
#include "kurn.h"
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <immintrin.h>
typedef struct { uint16_t d; uint16_t dmin; uint8_t scales[12]; uint8_t qs[128]; } nblock;
typedef struct { int64_t nrec_k, ngroups; uint8_t *buf; } packed_t;
/* record layout: code 1280+((16,2),(4,2,4,8)):((8,512),(2,1,128,1024))  fields d(32,1,1):(2,64,640), dmin64+(32,1,1):(2,64,640), sc128+(32,8,1):(1,32,640), mnp384+(32,(2,4),1):(2,(1,64),640)  rec 4736 B */
#define REC_BYTES 4736
#define RG_STRIDE(nrec) ((size_t)(nrec) * REC_BYTES + 0)

void *kq4k_gemv_prepare(const void *W, int64_t K, int64_t N) {
    const nblock *w = (const nblock *)W;
    const int64_t nb = K / 256;
    packed_t *pk = malloc(sizeof *pk);
    pk->nrec_k = K / 256; pk->ngroups = (N + 31) / 32 + 1;
    const size_t bytes = (size_t)pk->ngroups * RG_STRIDE(pk->nrec_k);
    pk->buf = aligned_alloc(64, (bytes + 63) & ~(size_t)63);
    memset(pk->buf, 0, bytes);
    for (int64_t gr = 0; gr < pk->ngroups; gr++)
        for (int64_t p = 0; p < pk->nrec_k; p++) {
            uint8_t *rec = pk->buf + gr * RG_STRIDE(pk->nrec_k) + p * REC_BYTES;
            for (int64_t row = 0; row < 32; row++) {
                const int64_t n = gr * 32 + row;
                if (n >= N) continue;  /* padding rows stay zero: d = 0 */
                for (int64_t q = 0; q < 1; q++) {
                    const nblock *b = w + n * nb + (p * 256 + q * 256) / 256;
                    memcpy(rec + (row) * 2, &b->d, 2);
                    memcpy(rec + 64 + (row) * 2, &b->dmin, 2);
                    const uint8_t *q6 = b->scales; int sc[8], mn[8];
                    for (int s = 0; s < 8; s++) {
                        sc[s] = s < 4 ? q6[s] & 63 : (q6[s + 4] & 0xF) | ((q6[s - 4] >> 6) << 4);
                        mn[s] = s < 4 ? q6[s + 4] & 63 : (q6[s + 4] >> 4) | ((q6[s] >> 6) << 4);
                    }
                    (void)sc; (void)mn;
                    for (int s = 0; s < 8; s++) rec[128 + row + (s) * 32] = (uint8_t)sc[s];
                    for (int s = 0; s < 8; s++) rec[384 + (row) * 2 + (s) % 2 + ((s) / 2) * 64] = (uint8_t)mn[s];
                }
                int32_t wsum = 0;
                (void)wsum;
                for (int64_t kk = 0; kk < 256; kk++) {
                    const int64_t vv = p * 256 + kk;
                    const nblock *b = w + n * nb + vv / 256;
                    const int v = (int)(vv % 256);
                    const int q = ((b->qs[(v / 64) * 32 + v % 32] >> (4 * ((v / 32) & 1))) & 15);
                    
                    const uint8_t u = q;
                    const int64_t e = 1280 + ((row) % 16) * 8 + ((row) / 16) * 512 + ((kk) % 4) * 2 + ((kk) / 4) % 2 + (((kk) / 8) % 4) * 128 + ((kk) / 32) * 1024;
                    int64_t byte = e / 2;
                    
                    rec[byte] |= (uint8_t)(u << ((e % 2) * 4));
                    
                }
            }
        }
    return pk;
}

typedef struct { float d; int8_t qs[256]; int16_t bsums[16]; } xblock;
static const uint8_t PTBL[64] __attribute__((aligned(64))) = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};

static inline void storev(float *y, int64_t row0, int64_t r0, int64_t r1, __m512 v) {
    if (row0 >= r0 && row0 + 16 <= r1) { _mm512_storeu_ps(y + row0, v); return; }
    uint32_t m = 0xFFFF;
    if (row0 < r0) m &= r0 - row0 >= 16 ? 0 : 0xFFFFu << (r0 - row0);
    if (row0 + 16 > r1) m &= (1u << (r1 > row0 ? (r1 - row0 > 16 ? 16 : r1 - row0) : 0)) - 1;
    _mm512_mask_storeu_ps(y + row0, (__mmask16)m, v);
}

__attribute__((target("avx512vbmi"))) void kq4k_gemv_packed(const void *pv, const void *X, float *Y, int64_t K, int64_t r0, int64_t r1) {
    const packed_t *pk = (const packed_t *)pv;
    const int64_t M = 1, N = 0;
    const int64_t nk = K / 32, nbx = K / 256;
    if (M > 1) abort();
    int32_t xw[1 * 1024 * 8], sx[1 * 1024], sxp[1 * 512];
    float dx[1 * 1024];
    (void)sx; (void)sxp; (void)nbx;
    for (int64_t m = 0; m < 1; m++) {
        const xblock *xb = (const xblock *)X + (m < M ? m : 0) * nbx;  /* columns beyond M repeat column 0 */
        for (int64_t k = 0; k < nk; k++) {
            const xblock *b = xb + k / 8;
            memcpy(xw + (m * nk + k) * 8, b->qs + (k % 8) * 32, 32);
            sx[m * nk + k] = b->bsums[2 * (k % 8)] + b->bsums[2 * (k % 8) + 1];
            dx[m * nk + k] = b->d;
        }
        for (int64_t k = 0; k < nk; k += 2)
            sxp[(m * nk + k) / 2] = (int32_t)(((uint32_t)(uint16_t)(int16_t)sx[m * nk + k])
                                            | ((uint32_t)(uint16_t)(int16_t)sx[m * nk + k + 1] << 16));
    }
    const __m512i m4 = _mm512_set1_epi8((char)(0x0F)), m3 = _mm512_set1_epi8((char)(0x03)), m1 = _mm512_set1_epi8((char)(0x01));
    (void)m4; (void)m3; (void)m1;
    const __m512i ptbl = _mm512_loadu_si512((const void *)PTBL);
    const size_t rgs = RG_STRIDE(pk->nrec_k);
    const int64_t gr0 = r0 / 32, gr1 = (r1 + 31) / 32;
    for (int64_t gr = gr0; gr < gr1; gr += 1) {
        __m512 a0_0 = _mm512_setzero_ps(); __m512 a1_0 = _mm512_setzero_ps();
        
        for (int64_t p = 0; p < pk->nrec_k; p++) {
                const uint8_t *rec0 = pk->buf + (size_t)(gr + 0) * rgs + p * REC_BYTES;
                const __m512 d0 = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)(rec0 + 0))), dm0 = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)(rec0 + 64)));
                const __m512 d1 = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)(rec0 + 32))), dm1 = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)(rec0 + 96)));
                __m512i ma0_0 = _mm512_setzero_si512(); __m512 af0_0 = _mm512_setzero_ps();
                __m512i ma1_0 = _mm512_setzero_si512(); __m512 af1_0 = _mm512_setzero_ps();
                for (int kg = 0; kg < 8; kg++) {
                    const int64_t k = p * 8 + 0 + kg;
                    const size_t kgo = (size_t)(0 + kg) * 512;
                    const __m512i c0_640 = _mm512_loadu_si512((const void *)(rec0 + kgo + 640));
                    const __m512i c0_704 = _mm512_loadu_si512((const void *)(rec0 + kgo + 704));
                    const __m512i c0_768 = _mm512_loadu_si512((const void *)(rec0 + kgo + 768));
                    const __m512i c0_832 = _mm512_loadu_si512((const void *)(rec0 + kgo + 832));
                    const __m512i c0_896 = _mm512_loadu_si512((const void *)(rec0 + kgo + 896));
                    const __m512i c0_960 = _mm512_loadu_si512((const void *)(rec0 + kgo + 960));
                    const __m512i c0_1024 = _mm512_loadu_si512((const void *)(rec0 + kgo + 1024));
                    const __m512i c0_1088 = _mm512_loadu_si512((const void *)(rec0 + kgo + 1088));
                    __m512i s0_0_0 = _mm512_setzero_si512(), s0_0_1 = _mm512_setzero_si512();
                    __m512i s1_0_0 = _mm512_setzero_si512(), s1_0_1 = _mm512_setzero_si512();
                    const __m512i x0_0 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 0]);
                    { const __m512i u = _mm512_permutexvar_epi8(c0_640, ptbl);
                      s0_0_0 = _mm512_dpbusd_epi32(s0_0_0, u, x0_0);
                    }
                    { const __m512i u = _mm512_permutexvar_epi8(c0_896, ptbl);
                      s1_0_0 = _mm512_dpbusd_epi32(s1_0_0, u, x0_0);
                    }
                    const __m512i x0_1 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 1]);
                    { const __m512i u = _mm512_permutexvar_epi8(_mm512_srli_epi16(c0_640, 4), ptbl);
                      s0_0_1 = _mm512_dpbusd_epi32(s0_0_1, u, x0_1);
                    }
                    { const __m512i u = _mm512_permutexvar_epi8(_mm512_srli_epi16(c0_896, 4), ptbl);
                      s1_0_1 = _mm512_dpbusd_epi32(s1_0_1, u, x0_1);
                    }
                    const __m512i x0_2 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 2]);
                    { const __m512i u = _mm512_permutexvar_epi8(c0_704, ptbl);
                      s0_0_0 = _mm512_dpbusd_epi32(s0_0_0, u, x0_2);
                    }
                    { const __m512i u = _mm512_permutexvar_epi8(c0_960, ptbl);
                      s1_0_0 = _mm512_dpbusd_epi32(s1_0_0, u, x0_2);
                    }
                    const __m512i x0_3 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 3]);
                    { const __m512i u = _mm512_permutexvar_epi8(_mm512_srli_epi16(c0_704, 4), ptbl);
                      s0_0_1 = _mm512_dpbusd_epi32(s0_0_1, u, x0_3);
                    }
                    { const __m512i u = _mm512_permutexvar_epi8(_mm512_srli_epi16(c0_960, 4), ptbl);
                      s1_0_1 = _mm512_dpbusd_epi32(s1_0_1, u, x0_3);
                    }
                    const __m512i x0_4 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 4]);
                    { const __m512i u = _mm512_permutexvar_epi8(c0_768, ptbl);
                      s0_0_0 = _mm512_dpbusd_epi32(s0_0_0, u, x0_4);
                    }
                    { const __m512i u = _mm512_permutexvar_epi8(c0_1024, ptbl);
                      s1_0_0 = _mm512_dpbusd_epi32(s1_0_0, u, x0_4);
                    }
                    const __m512i x0_5 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 5]);
                    { const __m512i u = _mm512_permutexvar_epi8(_mm512_srli_epi16(c0_768, 4), ptbl);
                      s0_0_1 = _mm512_dpbusd_epi32(s0_0_1, u, x0_5);
                    }
                    { const __m512i u = _mm512_permutexvar_epi8(_mm512_srli_epi16(c0_1024, 4), ptbl);
                      s1_0_1 = _mm512_dpbusd_epi32(s1_0_1, u, x0_5);
                    }
                    const __m512i x0_6 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 6]);
                    { const __m512i u = _mm512_permutexvar_epi8(c0_832, ptbl);
                      s0_0_0 = _mm512_dpbusd_epi32(s0_0_0, u, x0_6);
                    }
                    { const __m512i u = _mm512_permutexvar_epi8(c0_1088, ptbl);
                      s1_0_0 = _mm512_dpbusd_epi32(s1_0_0, u, x0_6);
                    }
                    const __m512i x0_7 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 7]);
                    { const __m512i u = _mm512_permutexvar_epi8(_mm512_srli_epi16(c0_832, 4), ptbl);
                      s0_0_1 = _mm512_dpbusd_epi32(s0_0_1, u, x0_7);
                    }
                    { const __m512i u = _mm512_permutexvar_epi8(_mm512_srli_epi16(c0_1088, 4), ptbl);
                      s1_0_1 = _mm512_dpbusd_epi32(s1_0_1, u, x0_7);
                    }
                    af0_0 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_add_epi32(s0_0_0, s0_0_1)), _mm512_cvtepi32_ps(_mm512_cvtepu8_epi32(_mm_loadu_si128((const __m128i *)(rec0 + 128 + (kg) * 32)))), af0_0);
                    af1_0 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_add_epi32(s1_0_0, s1_0_1)), _mm512_cvtepi32_ps(_mm512_cvtepu8_epi32(_mm_loadu_si128((const __m128i *)(rec0 + 144 + (kg) * 32)))), af1_0);
                }
                ma0_0 = _mm512_dpwssd_epi32(ma0_0, _mm512_cvtepu8_epi16(_mm256_loadu_si256((const __m256i *)(rec0 + 384))), _mm512_set1_epi32(sxp[(0 * nk + p * 8 + 0) / 2 + 0]));
                ma0_0 = _mm512_dpwssd_epi32(ma0_0, _mm512_cvtepu8_epi16(_mm256_loadu_si256((const __m256i *)(rec0 + 448))), _mm512_set1_epi32(sxp[(0 * nk + p * 8 + 0) / 2 + 1]));
                ma0_0 = _mm512_dpwssd_epi32(ma0_0, _mm512_cvtepu8_epi16(_mm256_loadu_si256((const __m256i *)(rec0 + 512))), _mm512_set1_epi32(sxp[(0 * nk + p * 8 + 0) / 2 + 2]));
                ma0_0 = _mm512_dpwssd_epi32(ma0_0, _mm512_cvtepu8_epi16(_mm256_loadu_si256((const __m256i *)(rec0 + 576))), _mm512_set1_epi32(sxp[(0 * nk + p * 8 + 0) / 2 + 3]));
                a0_0 = _mm512_fmadd_ps(af0_0, _mm512_mul_ps(d0, _mm512_set1_ps(dx[0 * nk + p * 8 + 0])), a0_0);
                a0_0 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(ma0_0), _mm512_mul_ps(dm0, _mm512_set1_ps(-dx[0 * nk + p * 8 + 0])), a0_0);
                ma1_0 = _mm512_dpwssd_epi32(ma1_0, _mm512_cvtepu8_epi16(_mm256_loadu_si256((const __m256i *)(rec0 + 416))), _mm512_set1_epi32(sxp[(0 * nk + p * 8 + 0) / 2 + 0]));
                ma1_0 = _mm512_dpwssd_epi32(ma1_0, _mm512_cvtepu8_epi16(_mm256_loadu_si256((const __m256i *)(rec0 + 480))), _mm512_set1_epi32(sxp[(0 * nk + p * 8 + 0) / 2 + 1]));
                ma1_0 = _mm512_dpwssd_epi32(ma1_0, _mm512_cvtepu8_epi16(_mm256_loadu_si256((const __m256i *)(rec0 + 544))), _mm512_set1_epi32(sxp[(0 * nk + p * 8 + 0) / 2 + 2]));
                ma1_0 = _mm512_dpwssd_epi32(ma1_0, _mm512_cvtepu8_epi16(_mm256_loadu_si256((const __m256i *)(rec0 + 608))), _mm512_set1_epi32(sxp[(0 * nk + p * 8 + 0) / 2 + 3]));
                a1_0 = _mm512_fmadd_ps(af1_0, _mm512_mul_ps(d1, _mm512_set1_ps(dx[0 * nk + p * 8 + 0])), a1_0);
                a1_0 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(ma1_0), _mm512_mul_ps(dm1, _mm512_set1_ps(-dx[0 * nk + p * 8 + 0])), a1_0);
        }
        storev(Y + 0 * N, gr * 32 + 0, r0, r1, a0_0);
        storev(Y + 0 * N, gr * 32 + 16, r0, r1, a1_0);
    }
}
