// Generated by kurn (generic recipe lowering). Do not edit; edit the .kurn spec instead.
#include "kurn.h"
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <immintrin.h>
static inline float f16f(uint16_t h) { return _cvtsh_ss(h); }

typedef struct { uint16_t d; uint8_t qs[16]; } nblock;
static const int8_t KV[16] __attribute__((unused)) = {-127, -104, -83, -65, -49, -35, -22, -10, 1, 13, 25, 38, 53, 69, 89, 113};
static const uint8_t LUT[16] = {1, 24, 45, 63, 79, 93, 106, 118, 129, 141, 153, 166, 181, 197, 217, 241};
typedef struct { int64_t nrec_k, ngroups; uint8_t *buf; } packed_t;
#define REC_BYTES 144
#define HDR_BYTES 16
#define KG_BYTES 128
#define CODE_BYTES 128

void *kiq4nl_gemv_prepare(const void *W, int64_t K, int64_t N) {
    const nblock *w = (const nblock *)W;
    const int64_t nb = K / 32;
    packed_t *pk = malloc(sizeof *pk);
    pk->nrec_k = K / 32; pk->ngroups = (N + 7) / 8 + 1;
    const size_t bytes = (size_t)REC_BYTES * pk->nrec_k * pk->ngroups;
    pk->buf = aligned_alloc(64, (bytes + 63) & ~(size_t)63);
    memset(pk->buf, 0, bytes);
    for (int64_t g = 0; g < pk->ngroups; g++)
        for (int64_t p = 0; p < pk->nrec_k; p++) {
            uint8_t *hp = pk->buf + ((size_t)g * pk->nrec_k + p) * REC_BYTES;
            for (int row = 0; row < 8; row++) {
                const int64_t n = g * 8 + row;
                if (n >= N) continue;  /* padding rows stay zero: d = 0 */
                const int64_t v0 = p * 32;
                const nblock *b = w + n * nb + v0 / 32;
                
                memcpy(hp + 2 * row, &b->d, 2);
                for (int kg = 0; kg < 1; kg++) {
                    uint8_t *rec_codes = hp + HDR_BYTES + kg * KG_BYTES;
                    int32_t wsum = 0;
                    for (int kk = 0; kk < 8; kk++)
                        for (int j = 0; j < 4; j++) {
                            const int v = (int)((v0 + kg * 32 + kk * 4 + j) % 32);
                            const int q = (v < 16 ? b->qs[v] & 15 : b->qs[v - 16] >> 4);
                            (void)wsum;
                            
                            const uint8_t u = q;
                            rec_codes[(kk / 2) * 32 + (row) * 4 + j] |= (uint8_t)(u << (4 * (kk & 1)));
                        }
                    
                }
            }
        }
    return pk;
}

typedef struct { uint16_t d; int8_t qs[32]; } xblock;

static inline void storev(float *y, int64_t row0, int64_t r0, int64_t r1, __m256 v) {
    float t[8];
    _mm256_storeu_ps(t, v);
    for (int i = 0; i < 8; i++) if (row0 + i >= r0 && row0 + i < r1) y[row0 + i] = t[i];
}
static inline __m256i bits8x4(uint32_t w) {  /* 32 bits -> 32 bytes of 0/1 */
    const __m256i sh = _mm256_setr_epi8(0,0,0,0,0,0,0,0, 1,1,1,1,1,1,1,1, 2,2,2,2,2,2,2,2, 3,3,3,3,3,3,3,3);
    const __m256i bm = _mm256_set1_epi64x((long long)0x8040201008040201ull);
    __m256i v = _mm256_shuffle_epi8(_mm256_set1_epi32((int)w), sh);
    return _mm256_and_si256(_mm256_cmpeq_epi8(_mm256_and_si256(v, bm), bm), _mm256_set1_epi8(1));
}

void kiq4nl_gemv_packed(const void *pv, const void *X, float *Y, int64_t K, int64_t r0, int64_t r1) {
    const packed_t *pk = (const packed_t *)pv;
    const int64_t M = 1, N = 0;
    const int64_t nk = K / 32, nbx = K / 32;
    if (M > 1) abort();
    int32_t xw[1 * 1024 * 8], sx[1 * 1024];
    float dx[1 * 1024];
    (void)sx; (void)nbx;
    for (int64_t m = 0; m < 1; m++) {
    const xblock *xb = (const xblock *)X + (m < M ? m : 0) * nbx;  /* columns beyond M repeat column 0 */
    for (int64_t k = 0; k < nk; k++) {
        int32_t s = 0;
        for (int l = 0; l < 32; l++) s += xb[k].qs[l];
        memcpy(xw + (m * nk + k) * 8, xb[k].qs, 32);
        sx[m * nk + k] = s;
        dx[m * nk + k] = f16f(xb[k].d);
    }
    }
    const __m256i m4 = _mm256_set1_epi8((char)(0x0F)), m3 = _mm256_set1_epi8((char)(0x03));
    (void)m4; (void)m3;
    const __m256i lut = _mm256_broadcastsi128_si256(_mm_loadu_si128((const __m128i *)LUT));
    const int64_t g0 = r0 / 8, g1 = (r1 + 7) / 8;
    int64_t g = g0;
    for (; g < g1; g += 2) {
        __m256 a0_0 = _mm256_setzero_ps(); __m256 a1_0 = _mm256_setzero_ps();
        for (int64_t p = 0; p < pk->nrec_k; p++) {
                const uint8_t *rec0 = pk->buf + ((size_t)(g + 0) * pk->nrec_k + p) * REC_BYTES;
                const uint8_t *rec1 = pk->buf + ((size_t)(g + 1) * pk->nrec_k + p) * REC_BYTES;
                const __m256 d0 = _mm256_cvtph_ps(_mm_loadu_si128((const __m128i *)(rec0)));
                const __m256 d1 = _mm256_cvtph_ps(_mm_loadu_si128((const __m128i *)(rec1)));
                for (int kg = 0; kg < 1; kg++) {
                    const int64_t k = p * 1 + kg;
                    const __m256i c0_0 = _mm256_loadu_si256((const __m256i *)(rec0 + HDR_BYTES + kg * KG_BYTES + 0));
                    const __m256i c0_1 = _mm256_loadu_si256((const __m256i *)(rec0 + HDR_BYTES + kg * KG_BYTES + 32));
                    const __m256i c0_2 = _mm256_loadu_si256((const __m256i *)(rec0 + HDR_BYTES + kg * KG_BYTES + 64));
                    const __m256i c0_3 = _mm256_loadu_si256((const __m256i *)(rec0 + HDR_BYTES + kg * KG_BYTES + 96));
                    const __m256i c1_0 = _mm256_loadu_si256((const __m256i *)(rec1 + HDR_BYTES + kg * KG_BYTES + 0));
                    const __m256i c1_1 = _mm256_loadu_si256((const __m256i *)(rec1 + HDR_BYTES + kg * KG_BYTES + 32));
                    const __m256i c1_2 = _mm256_loadu_si256((const __m256i *)(rec1 + HDR_BYTES + kg * KG_BYTES + 64));
                    const __m256i c1_3 = _mm256_loadu_si256((const __m256i *)(rec1 + HDR_BYTES + kg * KG_BYTES + 96));
                    __m256i e0_0 = _mm256_set1_epi32(-128 * sx[0 * nk + k]), o0_0 = _mm256_setzero_si256();
                    __m256i e1_0 = _mm256_set1_epi32(-128 * sx[0 * nk + k]), o1_0 = _mm256_setzero_si256();
                    const __m256i x0_0 = _mm256_set1_epi32(xw[(0 * nk + k) * 8 + 0]);
                    { const __m256i u = _mm256_shuffle_epi8(lut, _mm256_and_si256(c0_0, m4));
                      e0_0 = _mm256_dpbusd_avx_epi32(e0_0, u, x0_0);
                    }
                    { const __m256i u = _mm256_shuffle_epi8(lut, _mm256_and_si256(c1_0, m4));
                      e1_0 = _mm256_dpbusd_avx_epi32(e1_0, u, x0_0);
                    }
                    const __m256i x0_1 = _mm256_set1_epi32(xw[(0 * nk + k) * 8 + 1]);
                    { const __m256i u = _mm256_shuffle_epi8(lut, _mm256_and_si256(_mm256_srli_epi16(c0_0, 4), m4));
                      o0_0 = _mm256_dpbusd_avx_epi32(o0_0, u, x0_1);
                    }
                    { const __m256i u = _mm256_shuffle_epi8(lut, _mm256_and_si256(_mm256_srli_epi16(c1_0, 4), m4));
                      o1_0 = _mm256_dpbusd_avx_epi32(o1_0, u, x0_1);
                    }
                    const __m256i x0_2 = _mm256_set1_epi32(xw[(0 * nk + k) * 8 + 2]);
                    { const __m256i u = _mm256_shuffle_epi8(lut, _mm256_and_si256(c0_1, m4));
                      e0_0 = _mm256_dpbusd_avx_epi32(e0_0, u, x0_2);
                    }
                    { const __m256i u = _mm256_shuffle_epi8(lut, _mm256_and_si256(c1_1, m4));
                      e1_0 = _mm256_dpbusd_avx_epi32(e1_0, u, x0_2);
                    }
                    const __m256i x0_3 = _mm256_set1_epi32(xw[(0 * nk + k) * 8 + 3]);
                    { const __m256i u = _mm256_shuffle_epi8(lut, _mm256_and_si256(_mm256_srli_epi16(c0_1, 4), m4));
                      o0_0 = _mm256_dpbusd_avx_epi32(o0_0, u, x0_3);
                    }
                    { const __m256i u = _mm256_shuffle_epi8(lut, _mm256_and_si256(_mm256_srli_epi16(c1_1, 4), m4));
                      o1_0 = _mm256_dpbusd_avx_epi32(o1_0, u, x0_3);
                    }
                    const __m256i x0_4 = _mm256_set1_epi32(xw[(0 * nk + k) * 8 + 4]);
                    { const __m256i u = _mm256_shuffle_epi8(lut, _mm256_and_si256(c0_2, m4));
                      e0_0 = _mm256_dpbusd_avx_epi32(e0_0, u, x0_4);
                    }
                    { const __m256i u = _mm256_shuffle_epi8(lut, _mm256_and_si256(c1_2, m4));
                      e1_0 = _mm256_dpbusd_avx_epi32(e1_0, u, x0_4);
                    }
                    const __m256i x0_5 = _mm256_set1_epi32(xw[(0 * nk + k) * 8 + 5]);
                    { const __m256i u = _mm256_shuffle_epi8(lut, _mm256_and_si256(_mm256_srli_epi16(c0_2, 4), m4));
                      o0_0 = _mm256_dpbusd_avx_epi32(o0_0, u, x0_5);
                    }
                    { const __m256i u = _mm256_shuffle_epi8(lut, _mm256_and_si256(_mm256_srli_epi16(c1_2, 4), m4));
                      o1_0 = _mm256_dpbusd_avx_epi32(o1_0, u, x0_5);
                    }
                    const __m256i x0_6 = _mm256_set1_epi32(xw[(0 * nk + k) * 8 + 6]);
                    { const __m256i u = _mm256_shuffle_epi8(lut, _mm256_and_si256(c0_3, m4));
                      e0_0 = _mm256_dpbusd_avx_epi32(e0_0, u, x0_6);
                    }
                    { const __m256i u = _mm256_shuffle_epi8(lut, _mm256_and_si256(c1_3, m4));
                      e1_0 = _mm256_dpbusd_avx_epi32(e1_0, u, x0_6);
                    }
                    const __m256i x0_7 = _mm256_set1_epi32(xw[(0 * nk + k) * 8 + 7]);
                    { const __m256i u = _mm256_shuffle_epi8(lut, _mm256_and_si256(_mm256_srli_epi16(c0_3, 4), m4));
                      o0_0 = _mm256_dpbusd_avx_epi32(o0_0, u, x0_7);
                    }
                    { const __m256i u = _mm256_shuffle_epi8(lut, _mm256_and_si256(_mm256_srli_epi16(c1_3, 4), m4));
                      o1_0 = _mm256_dpbusd_avx_epi32(o1_0, u, x0_7);
                    }
                    a0_0 = _mm256_fmadd_ps(_mm256_cvtepi32_ps(_mm256_add_epi32(e0_0, o0_0)), _mm256_mul_ps(d0, _mm256_set1_ps(dx[0 * nk + k])), a0_0);
                    a1_0 = _mm256_fmadd_ps(_mm256_cvtepi32_ps(_mm256_add_epi32(e1_0, o1_0)), _mm256_mul_ps(d1, _mm256_set1_ps(dx[0 * nk + k])), a1_0);
                }
        }
        storev(Y + 0 * N, (g + 0) * 8, r0, r1, a0_0);
        storev(Y + 0 * N, (g + 1) * 8, r0, r1, a1_0);
    }
}
