// Generated by kurn (generic recipe lowering). Do not edit; edit the .kurn spec instead.
#include "kurn.h"
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <immintrin.h>
static inline float f16f(uint16_t h) { return _cvtsh_ss(h); }

typedef struct { uint16_t d; uint8_t qs[16]; } nblock;
static const int8_t KV[16] __attribute__((unused)) = {-127, -104, -83, -65, -49, -35, -22, -10, 1, 13, 25, 38, 53, 69, 89, 113};
static const uint8_t LUT[16] = {1, 24, 45, 63, 79, 93, 106, 118, 129, 141, 153, 166, 181, 197, 217, 241};
typedef struct { int64_t nrec_k, ngroups; uint8_t *buf; } packed_t;
#define REC_BYTES 288
#define HDR_BYTES 32
#define KG_BYTES 256
#define CODE_BYTES 256

void *kiq4nl_vfy_prepare(const void *W, int64_t K, int64_t N) {
    const nblock *w = (const nblock *)W;
    const int64_t nb = K / 32;
    packed_t *pk = malloc(sizeof *pk);
    pk->nrec_k = K / 32; pk->ngroups = (N + 15) / 16 + 0;
    const size_t bytes = (size_t)REC_BYTES * pk->nrec_k * pk->ngroups;
    pk->buf = aligned_alloc(64, (bytes + 63) & ~(size_t)63);
    memset(pk->buf, 0, bytes);
    for (int64_t g = 0; g < pk->ngroups; g++)
        for (int64_t p = 0; p < pk->nrec_k; p++) {
            uint8_t *hp = pk->buf + ((size_t)g * pk->nrec_k + p) * REC_BYTES;
            for (int row = 0; row < 16; row++) {
                const int64_t n = g * 16 + row;
                if (n >= N) continue;  /* padding rows stay zero: d = 0 */
                const int64_t v0 = p * 32;
                const nblock *b = w + n * nb + v0 / 32;
                
                memcpy(hp + 2 * row, &b->d, 2);
                for (int kg = 0; kg < 1; kg++) {
                    uint8_t *rec_codes = hp + HDR_BYTES + kg * KG_BYTES;
                    int32_t wsum = 0;
                    for (int kk = 0; kk < 8; kk++)
                        for (int j = 0; j < 4; j++) {
                            const int v = (int)((v0 + kg * 32 + kk * 4 + j) % 32);
                            const int q = (v < 16 ? b->qs[v] & 15 : b->qs[v - 16] >> 4);
                            (void)wsum;
                            
                            const uint8_t u = q;
                            rec_codes[(kk / 2) * 64 + (row) * 4 + j] |= (uint8_t)(u << (4 * (kk & 1)));
                        }
                    
                }
            }
        }
    return pk;
}

typedef struct { uint16_t d; int8_t qs[32]; } xblock;

static inline void storev(float *y, int64_t row0, int64_t r0, int64_t r1, __m512 v) {
    if (row0 >= r0 && row0 + 16 <= r1) { _mm512_storeu_ps(y + row0, v); return; }
    uint32_t m = 0xFFFF;
    if (row0 < r0) m &= 0xFFFFu << (r0 - row0);
    if (row0 + 16 > r1) m &= (1u << (r1 > row0 ? r1 - row0 : 0)) - 1;
    _mm512_mask_storeu_ps(y + row0, (__mmask16)m, v);
}

void kiq4nl_vfy_packed(const void *pv, const void *X, float *Y, int64_t K, int64_t N, int64_t M, int64_t r0, int64_t r1) {
    const packed_t *pk = (const packed_t *)pv;
    const int64_t nk = K / 32, nbx = K / 32;
    if (M > 8) abort();
    int32_t xw[8 * 1024 * 8], sx[8 * 1024];
    float dx[8 * 1024];
    (void)sx; (void)nbx;
    for (int64_t m = 0; m < 8; m++) {
    const xblock *xb = (const xblock *)X + (m < M ? m : 0) * nbx;  /* columns beyond M repeat column 0 */
    for (int64_t k = 0; k < nk; k++) {
        int32_t s = 0;
        for (int l = 0; l < 32; l++) s += xb[k].qs[l];
        memcpy(xw + (m * nk + k) * 8, xb[k].qs, 32);
        sx[m * nk + k] = s;
        dx[m * nk + k] = f16f(xb[k].d);
    }
    }
    const __m512i m4 = _mm512_set1_epi8((char)(0x0F)), m3 = _mm512_set1_epi8((char)(0x03));
    (void)m4; (void)m3;
    const __m512i lut = _mm512_broadcast_i32x4(_mm_loadu_si128((const __m128i *)LUT));
    const int64_t g0 = r0 / 16, g1 = (r1 + 15) / 16;
    int64_t g = g0;
    for (; g < g1; g += 1) {
        __m512 a0_0 = _mm512_setzero_ps(); __m512 a0_1 = _mm512_setzero_ps(); __m512 a0_2 = _mm512_setzero_ps(); __m512 a0_3 = _mm512_setzero_ps(); __m512 a0_4 = _mm512_setzero_ps(); __m512 a0_5 = _mm512_setzero_ps(); __m512 a0_6 = _mm512_setzero_ps(); __m512 a0_7 = _mm512_setzero_ps();
        for (int64_t p = 0; p < pk->nrec_k; p++) {
                const uint8_t *rec0 = pk->buf + ((size_t)(g + 0) * pk->nrec_k + p) * REC_BYTES;
                const __m512 d0 = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)(rec0)));
                for (int kg = 0; kg < 1; kg++) {
                    const int64_t k = p * 1 + kg;
                    const __m512i c0_0 = _mm512_loadu_si512((const void *)(rec0 + HDR_BYTES + kg * KG_BYTES + 0));
                    const __m512i c0_1 = _mm512_loadu_si512((const void *)(rec0 + HDR_BYTES + kg * KG_BYTES + 64));
                    const __m512i c0_2 = _mm512_loadu_si512((const void *)(rec0 + HDR_BYTES + kg * KG_BYTES + 128));
                    const __m512i c0_3 = _mm512_loadu_si512((const void *)(rec0 + HDR_BYTES + kg * KG_BYTES + 192));
                    __m512i e0_0 = _mm512_set1_epi32(-128 * sx[0 * nk + k]), o0_0 = _mm512_setzero_si512();
                    __m512i e0_1 = _mm512_set1_epi32(-128 * sx[1 * nk + k]), o0_1 = _mm512_setzero_si512();
                    __m512i e0_2 = _mm512_set1_epi32(-128 * sx[2 * nk + k]), o0_2 = _mm512_setzero_si512();
                    __m512i e0_3 = _mm512_set1_epi32(-128 * sx[3 * nk + k]), o0_3 = _mm512_setzero_si512();
                    __m512i e0_4 = _mm512_set1_epi32(-128 * sx[4 * nk + k]), o0_4 = _mm512_setzero_si512();
                    __m512i e0_5 = _mm512_set1_epi32(-128 * sx[5 * nk + k]), o0_5 = _mm512_setzero_si512();
                    __m512i e0_6 = _mm512_set1_epi32(-128 * sx[6 * nk + k]), o0_6 = _mm512_setzero_si512();
                    __m512i e0_7 = _mm512_set1_epi32(-128 * sx[7 * nk + k]), o0_7 = _mm512_setzero_si512();
                    const __m512i x0_0 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 0]);
                    const __m512i x1_0 = _mm512_set1_epi32(xw[(1 * nk + k) * 8 + 0]);
                    const __m512i x2_0 = _mm512_set1_epi32(xw[(2 * nk + k) * 8 + 0]);
                    const __m512i x3_0 = _mm512_set1_epi32(xw[(3 * nk + k) * 8 + 0]);
                    const __m512i x4_0 = _mm512_set1_epi32(xw[(4 * nk + k) * 8 + 0]);
                    const __m512i x5_0 = _mm512_set1_epi32(xw[(5 * nk + k) * 8 + 0]);
                    const __m512i x6_0 = _mm512_set1_epi32(xw[(6 * nk + k) * 8 + 0]);
                    const __m512i x7_0 = _mm512_set1_epi32(xw[(7 * nk + k) * 8 + 0]);
                    { const __m512i u = _mm512_shuffle_epi8(lut, _mm512_and_si512(c0_0, m4));
                      e0_0 = _mm512_dpbusd_epi32(e0_0, u, x0_0);
                      e0_1 = _mm512_dpbusd_epi32(e0_1, u, x1_0);
                      e0_2 = _mm512_dpbusd_epi32(e0_2, u, x2_0);
                      e0_3 = _mm512_dpbusd_epi32(e0_3, u, x3_0);
                      e0_4 = _mm512_dpbusd_epi32(e0_4, u, x4_0);
                      e0_5 = _mm512_dpbusd_epi32(e0_5, u, x5_0);
                      e0_6 = _mm512_dpbusd_epi32(e0_6, u, x6_0);
                      e0_7 = _mm512_dpbusd_epi32(e0_7, u, x7_0);
                    }
                    const __m512i x0_1 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 1]);
                    const __m512i x1_1 = _mm512_set1_epi32(xw[(1 * nk + k) * 8 + 1]);
                    const __m512i x2_1 = _mm512_set1_epi32(xw[(2 * nk + k) * 8 + 1]);
                    const __m512i x3_1 = _mm512_set1_epi32(xw[(3 * nk + k) * 8 + 1]);
                    const __m512i x4_1 = _mm512_set1_epi32(xw[(4 * nk + k) * 8 + 1]);
                    const __m512i x5_1 = _mm512_set1_epi32(xw[(5 * nk + k) * 8 + 1]);
                    const __m512i x6_1 = _mm512_set1_epi32(xw[(6 * nk + k) * 8 + 1]);
                    const __m512i x7_1 = _mm512_set1_epi32(xw[(7 * nk + k) * 8 + 1]);
                    { const __m512i u = _mm512_shuffle_epi8(lut, _mm512_and_si512(_mm512_srli_epi16(c0_0, 4), m4));
                      o0_0 = _mm512_dpbusd_epi32(o0_0, u, x0_1);
                      o0_1 = _mm512_dpbusd_epi32(o0_1, u, x1_1);
                      o0_2 = _mm512_dpbusd_epi32(o0_2, u, x2_1);
                      o0_3 = _mm512_dpbusd_epi32(o0_3, u, x3_1);
                      o0_4 = _mm512_dpbusd_epi32(o0_4, u, x4_1);
                      o0_5 = _mm512_dpbusd_epi32(o0_5, u, x5_1);
                      o0_6 = _mm512_dpbusd_epi32(o0_6, u, x6_1);
                      o0_7 = _mm512_dpbusd_epi32(o0_7, u, x7_1);
                    }
                    const __m512i x0_2 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 2]);
                    const __m512i x1_2 = _mm512_set1_epi32(xw[(1 * nk + k) * 8 + 2]);
                    const __m512i x2_2 = _mm512_set1_epi32(xw[(2 * nk + k) * 8 + 2]);
                    const __m512i x3_2 = _mm512_set1_epi32(xw[(3 * nk + k) * 8 + 2]);
                    const __m512i x4_2 = _mm512_set1_epi32(xw[(4 * nk + k) * 8 + 2]);
                    const __m512i x5_2 = _mm512_set1_epi32(xw[(5 * nk + k) * 8 + 2]);
                    const __m512i x6_2 = _mm512_set1_epi32(xw[(6 * nk + k) * 8 + 2]);
                    const __m512i x7_2 = _mm512_set1_epi32(xw[(7 * nk + k) * 8 + 2]);
                    { const __m512i u = _mm512_shuffle_epi8(lut, _mm512_and_si512(c0_1, m4));
                      e0_0 = _mm512_dpbusd_epi32(e0_0, u, x0_2);
                      e0_1 = _mm512_dpbusd_epi32(e0_1, u, x1_2);
                      e0_2 = _mm512_dpbusd_epi32(e0_2, u, x2_2);
                      e0_3 = _mm512_dpbusd_epi32(e0_3, u, x3_2);
                      e0_4 = _mm512_dpbusd_epi32(e0_4, u, x4_2);
                      e0_5 = _mm512_dpbusd_epi32(e0_5, u, x5_2);
                      e0_6 = _mm512_dpbusd_epi32(e0_6, u, x6_2);
                      e0_7 = _mm512_dpbusd_epi32(e0_7, u, x7_2);
                    }
                    const __m512i x0_3 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 3]);
                    const __m512i x1_3 = _mm512_set1_epi32(xw[(1 * nk + k) * 8 + 3]);
                    const __m512i x2_3 = _mm512_set1_epi32(xw[(2 * nk + k) * 8 + 3]);
                    const __m512i x3_3 = _mm512_set1_epi32(xw[(3 * nk + k) * 8 + 3]);
                    const __m512i x4_3 = _mm512_set1_epi32(xw[(4 * nk + k) * 8 + 3]);
                    const __m512i x5_3 = _mm512_set1_epi32(xw[(5 * nk + k) * 8 + 3]);
                    const __m512i x6_3 = _mm512_set1_epi32(xw[(6 * nk + k) * 8 + 3]);
                    const __m512i x7_3 = _mm512_set1_epi32(xw[(7 * nk + k) * 8 + 3]);
                    { const __m512i u = _mm512_shuffle_epi8(lut, _mm512_and_si512(_mm512_srli_epi16(c0_1, 4), m4));
                      o0_0 = _mm512_dpbusd_epi32(o0_0, u, x0_3);
                      o0_1 = _mm512_dpbusd_epi32(o0_1, u, x1_3);
                      o0_2 = _mm512_dpbusd_epi32(o0_2, u, x2_3);
                      o0_3 = _mm512_dpbusd_epi32(o0_3, u, x3_3);
                      o0_4 = _mm512_dpbusd_epi32(o0_4, u, x4_3);
                      o0_5 = _mm512_dpbusd_epi32(o0_5, u, x5_3);
                      o0_6 = _mm512_dpbusd_epi32(o0_6, u, x6_3);
                      o0_7 = _mm512_dpbusd_epi32(o0_7, u, x7_3);
                    }
                    const __m512i x0_4 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 4]);
                    const __m512i x1_4 = _mm512_set1_epi32(xw[(1 * nk + k) * 8 + 4]);
                    const __m512i x2_4 = _mm512_set1_epi32(xw[(2 * nk + k) * 8 + 4]);
                    const __m512i x3_4 = _mm512_set1_epi32(xw[(3 * nk + k) * 8 + 4]);
                    const __m512i x4_4 = _mm512_set1_epi32(xw[(4 * nk + k) * 8 + 4]);
                    const __m512i x5_4 = _mm512_set1_epi32(xw[(5 * nk + k) * 8 + 4]);
                    const __m512i x6_4 = _mm512_set1_epi32(xw[(6 * nk + k) * 8 + 4]);
                    const __m512i x7_4 = _mm512_set1_epi32(xw[(7 * nk + k) * 8 + 4]);
                    { const __m512i u = _mm512_shuffle_epi8(lut, _mm512_and_si512(c0_2, m4));
                      e0_0 = _mm512_dpbusd_epi32(e0_0, u, x0_4);
                      e0_1 = _mm512_dpbusd_epi32(e0_1, u, x1_4);
                      e0_2 = _mm512_dpbusd_epi32(e0_2, u, x2_4);
                      e0_3 = _mm512_dpbusd_epi32(e0_3, u, x3_4);
                      e0_4 = _mm512_dpbusd_epi32(e0_4, u, x4_4);
                      e0_5 = _mm512_dpbusd_epi32(e0_5, u, x5_4);
                      e0_6 = _mm512_dpbusd_epi32(e0_6, u, x6_4);
                      e0_7 = _mm512_dpbusd_epi32(e0_7, u, x7_4);
                    }
                    const __m512i x0_5 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 5]);
                    const __m512i x1_5 = _mm512_set1_epi32(xw[(1 * nk + k) * 8 + 5]);
                    const __m512i x2_5 = _mm512_set1_epi32(xw[(2 * nk + k) * 8 + 5]);
                    const __m512i x3_5 = _mm512_set1_epi32(xw[(3 * nk + k) * 8 + 5]);
                    const __m512i x4_5 = _mm512_set1_epi32(xw[(4 * nk + k) * 8 + 5]);
                    const __m512i x5_5 = _mm512_set1_epi32(xw[(5 * nk + k) * 8 + 5]);
                    const __m512i x6_5 = _mm512_set1_epi32(xw[(6 * nk + k) * 8 + 5]);
                    const __m512i x7_5 = _mm512_set1_epi32(xw[(7 * nk + k) * 8 + 5]);
                    { const __m512i u = _mm512_shuffle_epi8(lut, _mm512_and_si512(_mm512_srli_epi16(c0_2, 4), m4));
                      o0_0 = _mm512_dpbusd_epi32(o0_0, u, x0_5);
                      o0_1 = _mm512_dpbusd_epi32(o0_1, u, x1_5);
                      o0_2 = _mm512_dpbusd_epi32(o0_2, u, x2_5);
                      o0_3 = _mm512_dpbusd_epi32(o0_3, u, x3_5);
                      o0_4 = _mm512_dpbusd_epi32(o0_4, u, x4_5);
                      o0_5 = _mm512_dpbusd_epi32(o0_5, u, x5_5);
                      o0_6 = _mm512_dpbusd_epi32(o0_6, u, x6_5);
                      o0_7 = _mm512_dpbusd_epi32(o0_7, u, x7_5);
                    }
                    const __m512i x0_6 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 6]);
                    const __m512i x1_6 = _mm512_set1_epi32(xw[(1 * nk + k) * 8 + 6]);
                    const __m512i x2_6 = _mm512_set1_epi32(xw[(2 * nk + k) * 8 + 6]);
                    const __m512i x3_6 = _mm512_set1_epi32(xw[(3 * nk + k) * 8 + 6]);
                    const __m512i x4_6 = _mm512_set1_epi32(xw[(4 * nk + k) * 8 + 6]);
                    const __m512i x5_6 = _mm512_set1_epi32(xw[(5 * nk + k) * 8 + 6]);
                    const __m512i x6_6 = _mm512_set1_epi32(xw[(6 * nk + k) * 8 + 6]);
                    const __m512i x7_6 = _mm512_set1_epi32(xw[(7 * nk + k) * 8 + 6]);
                    { const __m512i u = _mm512_shuffle_epi8(lut, _mm512_and_si512(c0_3, m4));
                      e0_0 = _mm512_dpbusd_epi32(e0_0, u, x0_6);
                      e0_1 = _mm512_dpbusd_epi32(e0_1, u, x1_6);
                      e0_2 = _mm512_dpbusd_epi32(e0_2, u, x2_6);
                      e0_3 = _mm512_dpbusd_epi32(e0_3, u, x3_6);
                      e0_4 = _mm512_dpbusd_epi32(e0_4, u, x4_6);
                      e0_5 = _mm512_dpbusd_epi32(e0_5, u, x5_6);
                      e0_6 = _mm512_dpbusd_epi32(e0_6, u, x6_6);
                      e0_7 = _mm512_dpbusd_epi32(e0_7, u, x7_6);
                    }
                    const __m512i x0_7 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 7]);
                    const __m512i x1_7 = _mm512_set1_epi32(xw[(1 * nk + k) * 8 + 7]);
                    const __m512i x2_7 = _mm512_set1_epi32(xw[(2 * nk + k) * 8 + 7]);
                    const __m512i x3_7 = _mm512_set1_epi32(xw[(3 * nk + k) * 8 + 7]);
                    const __m512i x4_7 = _mm512_set1_epi32(xw[(4 * nk + k) * 8 + 7]);
                    const __m512i x5_7 = _mm512_set1_epi32(xw[(5 * nk + k) * 8 + 7]);
                    const __m512i x6_7 = _mm512_set1_epi32(xw[(6 * nk + k) * 8 + 7]);
                    const __m512i x7_7 = _mm512_set1_epi32(xw[(7 * nk + k) * 8 + 7]);
                    { const __m512i u = _mm512_shuffle_epi8(lut, _mm512_and_si512(_mm512_srli_epi16(c0_3, 4), m4));
                      o0_0 = _mm512_dpbusd_epi32(o0_0, u, x0_7);
                      o0_1 = _mm512_dpbusd_epi32(o0_1, u, x1_7);
                      o0_2 = _mm512_dpbusd_epi32(o0_2, u, x2_7);
                      o0_3 = _mm512_dpbusd_epi32(o0_3, u, x3_7);
                      o0_4 = _mm512_dpbusd_epi32(o0_4, u, x4_7);
                      o0_5 = _mm512_dpbusd_epi32(o0_5, u, x5_7);
                      o0_6 = _mm512_dpbusd_epi32(o0_6, u, x6_7);
                      o0_7 = _mm512_dpbusd_epi32(o0_7, u, x7_7);
                    }
                    a0_0 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_add_epi32(e0_0, o0_0)), _mm512_mul_ps(d0, _mm512_set1_ps(dx[0 * nk + k])), a0_0);
                    a0_1 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_add_epi32(e0_1, o0_1)), _mm512_mul_ps(d0, _mm512_set1_ps(dx[1 * nk + k])), a0_1);
                    a0_2 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_add_epi32(e0_2, o0_2)), _mm512_mul_ps(d0, _mm512_set1_ps(dx[2 * nk + k])), a0_2);
                    a0_3 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_add_epi32(e0_3, o0_3)), _mm512_mul_ps(d0, _mm512_set1_ps(dx[3 * nk + k])), a0_3);
                    a0_4 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_add_epi32(e0_4, o0_4)), _mm512_mul_ps(d0, _mm512_set1_ps(dx[4 * nk + k])), a0_4);
                    a0_5 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_add_epi32(e0_5, o0_5)), _mm512_mul_ps(d0, _mm512_set1_ps(dx[5 * nk + k])), a0_5);
                    a0_6 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_add_epi32(e0_6, o0_6)), _mm512_mul_ps(d0, _mm512_set1_ps(dx[6 * nk + k])), a0_6);
                    a0_7 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_add_epi32(e0_7, o0_7)), _mm512_mul_ps(d0, _mm512_set1_ps(dx[7 * nk + k])), a0_7);
                }
        }
        storev(Y + 0 * N, (g + 0) * 16, r0, r1, a0_0);
        if (1 < M) storev(Y + 1 * N, (g + 0) * 16, r0, r1, a0_1);
        if (2 < M) storev(Y + 2 * N, (g + 0) * 16, r0, r1, a0_2);
        if (3 < M) storev(Y + 3 * N, (g + 0) * 16, r0, r1, a0_3);
        if (4 < M) storev(Y + 4 * N, (g + 0) * 16, r0, r1, a0_4);
        if (5 < M) storev(Y + 5 * N, (g + 0) * 16, r0, r1, a0_5);
        if (6 < M) storev(Y + 6 * N, (g + 0) * 16, r0, r1, a0_6);
        if (7 < M) storev(Y + 7 * N, (g + 0) * 16, r0, r1, a0_7);
    }
}
void kiq4nl_vfy(const void *W, const void *X, float *Y, int64_t K, int64_t N, int64_t M, int64_t n0, int64_t n1) {
    (void)W; (void)X; (void)Y; (void)K; (void)N; (void)M; (void)n0; (void)n1; abort();
}
