// Generated by kurn (generic recipe lowering, scalar reference). Do not edit.
#include "kurn.h"
#include <stdint.h>
#include <string.h>
static inline float f16f(uint16_t h) {
    uint32_t s = (uint32_t)(h & 0x8000) << 16, e = (h >> 10) & 0x1f, m = h & 0x3ff, bb;
    if (e == 0) { if (!m) bb = s; else { e = 113; while (!(m & 0x400)) { m <<= 1; e--; } bb = s | (e << 23) | ((m & 0x3ff) << 13); } }
    else if (e == 31) bb = s | 0x7f800000 | (m << 13);
    else bb = s | ((e + 112) << 23) | (m << 13);
    float f; memcpy(&f, &bb, 4); return f;
}
static inline float bitsf(uint32_t u) { float f; memcpy(&f, &u, 4); return f; }
static inline float e8m0h(uint8_t x) {  /* ggml_e8m0_to_fp32_half */
    return bitsf(x < 2 ? 0x00200000u << x : (uint32_t)(x - 1) << 23);
}
static inline float ue4m3h(uint8_t x) {  /* ggml_ue4m3_to_fp32: UE4M3 scale x 0.5 (the codes are E2M1 x 2) */
    if (x == 0 || x == 0x7F) return 0.0f;
    const int e = (x >> 3) & 15, m = x & 7;
    return e ? bitsf((uint32_t)(e - 8 + 127) << 23) * (1.0f + (float)m / 8.0f) : (float)m * (1.0f / 1024.0f);
}
typedef struct { uint8_t e; uint8_t qs[16]; } nblock;
typedef struct { uint16_t d; int8_t qs[32]; } xblock;
static const int8_t KV[16] = {0, 1, 2, 3, 4, 6, 8, 12, 0, -1, -2, -3, -4, -6, -8, -12};
void kmxfp4_gemv(const void *W, const void *X, float *Y, int64_t K, int64_t r0, int64_t r1) {
    const xblock *x = (const xblock *)X;
    for (int64_t n = r0; n < r1; n++) {
        const nblock *wr = (const nblock *)W + n * (K / 32);
        float acc = 0;
        for (int64_t k = 0; k < K / 32; k++)
            for (int h = 0; h < 1; h++) {
                const nblock *b = wr + (k * 32 + h * 32) / 32;
                const int v0 = (int)((k * 32 + h * 32) % 32);
                int32_t t = 0;
                for (int l = 0; l < 32; l++) {
                    const int64_t vv = k * 32 + h * 32 + l;
                    const int v = v0 + l;
                    const int q = (v < 16 ? b->qs[v] & 15 : b->qs[v - 16] >> 4);
                    t += (KV[q]) * x[vv / 32].qs[vv % 32];
                }
                { const int v __attribute__((unused)) = v0; acc += e8m0h(b->e) * f16f(x[k].d) * (float)t; }
            }
        Y[n] = acc;
    }
}
