// Generated by kurn (generic recipe lowering). Do not edit; edit the .kurn spec instead.
#include "kurn.h"
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <immintrin.h>
static inline float f16f(uint16_t h) { return _cvtsh_ss(h); }

typedef struct { uint8_t d[4]; uint8_t qs[32]; } nblock;
typedef struct { int64_t nrec_k, ngroups; uint8_t *buf; } packed_t;
#define REC_BYTES 320
#define HDR_BYTES 64
#define KG_BYTES 256
static uint16_t ue4m3_f16(uint8_t x) {  /* ggml_ue4m3_to_fp32 (incl. x0.5) as an exact fp16 */
    if (x == 0) return 0;
    const int e = (x >> 3) & 15, m = x & 7;
    if (e) return (uint16_t)(((e + 7) << 10) | (m << 7));
    return _cvtss_sh((float)m * (1.0f / 1024.0f), 0);
}

/* repack: records of 16 rows x 32 values; see lower_nibble in kurn/generic.py for the layout */
void *knvfp4_gemv_prepare(const void *W, int64_t K, int64_t N) {
    const nblock *w = (const nblock *)W;
    const int64_t nb = K / 64;
    packed_t *pk = malloc(sizeof *pk);
    pk->nrec_k = K / 32; pk->ngroups = (N + 15) / 16 + 0;
    const size_t bytes = (size_t)REC_BYTES * pk->nrec_k * pk->ngroups;
    pk->buf = aligned_alloc(64, (bytes + 63) & ~(size_t)63);
    memset(pk->buf, 0, bytes);
    for (int64_t g = 0; g < pk->ngroups; g++)
        for (int64_t p = 0; p < pk->nrec_k; p++) {
            uint8_t *hp = pk->buf + ((size_t)g * pk->nrec_k + p) * REC_BYTES;
            for (int row = 0; row < 16; row++) {
                const int64_t n = g * 16 + row;
                if (n >= N) continue;  /* padding rows stay zero: scale 0 */
                const int64_t v0 = p * 32;
                const nblock *b = w + n * nb + v0 / 64;
                for (int s = 0; s < 2; s++) {
                    uint8_t u = b->d[(v0 % 64) / 16 + s];
                    if (u == 0x7F) u = 0;  /* NaN encoding: ggml decodes it as 0 */
                    { const uint16_t h = ue4m3_f16(u); memcpy(hp + 2 * (s * 16 + row), &h, 2); }
                }
                for (int kg = 0; kg < 1; kg++) {
                    uint8_t *rec_codes = hp + HDR_BYTES + kg * KG_BYTES;
                    for (int kk = 0; kk < 8; kk++)
                        for (int j = 0; j < 4; j++) {
                            const int v = (int)((v0 + kg * 32 + kk * 4 + j) % 64);
                            const int q = ((v % 16) < 8 ? b->qs[(v / 16) * 8 + v % 16] & 15 : b->qs[(v / 16) * 8 + v % 16 - 8] >> 4);
                            rec_codes[(kk / 2) * 64 + row * 4 + j] |= (uint8_t)(q << (4 * (kk & 1)));
                        }
                }
            }
        }
    return pk;
}
static const uint8_t LUT[64] __attribute__((aligned(64))) = {128, 129, 130, 131, 132, 134, 136, 140, 128, 127, 126, 125, 124, 122, 120, 116, 128, 129, 130, 131, 132, 134, 136, 140, 128, 127, 126, 125, 124, 122, 120, 116, 128, 129, 130, 131, 132, 134, 136, 140, 128, 127, 126, 125, 124, 122, 120, 116, 128, 129, 130, 131, 132, 134, 136, 140, 128, 127, 126, 125, 124, 122, 120, 116};

static inline int32_t ld32(const uint8_t *p) { int32_t v; memcpy(&v, p, 4); return v; }
static inline int64_t ld64(const uint8_t *p) { int64_t v; memcpy(&v, p, 8); return v; }
static inline uint16_t ld16(const uint8_t *p) { uint16_t v; memcpy(&v, p, 2); return v; }
static inline float ldf(const uint8_t *p) { float v; memcpy(&v, p, 4); return v; }
static inline int32_t sum_i8(const uint8_t *q, int n) {  /* sum of n = 16 or 32 int8 */
    __m128i s;
    if (n == 32) {
        const __m256i t = _mm256_sad_epu8(_mm256_xor_si256(_mm256_loadu_si256((const __m256i *)q), _mm256_set1_epi8((char)0x80)),
                                          _mm256_setzero_si256());
        s = _mm_add_epi64(_mm256_castsi256_si128(t), _mm256_extracti128_si256(t, 1));
    } else {
        s = _mm_sad_epu8(_mm_xor_si128(_mm_loadu_si128((const __m128i *)q), _mm_set1_epi8((char)0x80)), _mm_setzero_si128());
    }
    s = _mm_add_epi64(s, _mm_unpackhi_epi64(s, s));
    return _mm_cvtsi128_si32(s) - 128 * n;
}

static inline void storev(float *y, int64_t row0, int64_t r0, int64_t r1, __m512 v) {
    if (row0 >= r0 && row0 + 16 <= r1) { _mm512_storeu_ps(y + row0, v); return; }
    uint32_t m = 0xFFFF;
    if (row0 < r0) m &= r0 - row0 >= 16 ? 0 : 0xFFFFu << (r0 - row0);
    if (row0 + 16 > r1) m &= r1 <= row0 ? 0 : (r1 - row0 >= 16 ? 0xFFFFu : (1u << (r1 - row0)) - 1);
    _mm512_mask_storeu_ps(y + row0, (__mmask16)m, v);
}

#define PERMB(i, t) _mm512_permutexvar_epi8((i), (t))
__attribute__((target("avx512vbmi"))) static void knvfp4_gemv_vbmi(const void *pv, const void *X, float *Y, int64_t K, int64_t r0, int64_t r1) {
    const packed_t *pk = (const packed_t *)pv;
    const int64_t M = 1, N = 0;
    const int64_t nk = K / 32;
    if (M > 1) abort();
    (void)N;
    float dx[1 * 1024];
    int32_t sd0[1 * 1024 * 2];
    const uint8_t *xp[1];
    for (int64_t m = 0; m < 1; m++) {
        xp[m] = (const uint8_t *)X + (m < M ? m : 0) * nk * 34;  /* columns beyond M repeat column 0 */
        for (int64_t k = 0; k < nk; k++) {
        const uint8_t *blk = xp[m] + 34 * k;
        dx[m * nk + k] = f16f(ld16(blk)) * 1.0f;
        sd0[(m * nk + k) * 2 + 0] = -128 * sum_i8(blk + 2 + 0, 16);
        sd0[(m * nk + k) * 2 + 1] = -128 * sum_i8(blk + 2 + 16, 16);
        }
    }
    const __m512i m4 = _mm512_set1_epi8((char)(0x0F)), mF0 = _mm512_set1_epi8((char)(0xF0));
    (void)m4; (void)mF0;
    const __m512i lut = _mm512_loadu_si512((const void *)LUT);
    const int64_t g0 = r0 / 16, g1 = (r1 + 15) / 16;
    for (int64_t g = g0; g < g1; g += 1) {
        __m512 a0_0_0 = _mm512_setzero_ps();
        for (int64_t p = 0; p < pk->nrec_k; p++) {
                const uint8_t *rec0 = pk->buf + ((size_t)(g + 0) * pk->nrec_k + p) * REC_BYTES;
                const __m512 ds0_0_0 = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)(rec0 + 0)));
                const __m512 ds0_0_1 = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)(rec0 + 32)));
                const int64_t k = p;
                const uint8_t *xq0 = xp[0] + 34 * k + 2;
                const __m512i c0_0 = _mm512_loadu_si512((const void *)(rec0 + HDR_BYTES + 0));
                const __m512i c0_1 = _mm512_loadu_si512((const void *)(rec0 + HDR_BYTES + 64));
                const __m512i c0_2 = _mm512_loadu_si512((const void *)(rec0 + HDR_BYTES + 128));
                const __m512i c0_3 = _mm512_loadu_si512((const void *)(rec0 + HDR_BYTES + 192));
                __m512i e0_0_0 = _mm512_set1_epi32(sd0[(0 * nk + k) * 2 + 0]), o0_0_0 = _mm512_setzero_si512();
                __m512i e0_0_1 = _mm512_set1_epi32(sd0[(0 * nk + k) * 2 + 1]), o0_0_1 = _mm512_setzero_si512();
                { const __m512i lo = PERMB(c0_0, lut), hi = PERMB(_mm512_srli_epi16(c0_0, 4), lut);
                  e0_0_0 = _mm512_dpbusd_epi32(e0_0_0, lo, _mm512_set1_epi32(ld32(xq0 + 0)));
                  o0_0_0 = _mm512_dpbusd_epi32(o0_0_0, hi, _mm512_set1_epi32(ld32(xq0 + 4)));
                }
                { const __m512i lo = PERMB(c0_1, lut), hi = PERMB(_mm512_srli_epi16(c0_1, 4), lut);
                  e0_0_0 = _mm512_dpbusd_epi32(e0_0_0, lo, _mm512_set1_epi32(ld32(xq0 + 8)));
                  o0_0_0 = _mm512_dpbusd_epi32(o0_0_0, hi, _mm512_set1_epi32(ld32(xq0 + 12)));
                }
                { const __m512i lo = PERMB(c0_2, lut), hi = PERMB(_mm512_srli_epi16(c0_2, 4), lut);
                  e0_0_1 = _mm512_dpbusd_epi32(e0_0_1, lo, _mm512_set1_epi32(ld32(xq0 + 16)));
                  o0_0_1 = _mm512_dpbusd_epi32(o0_0_1, hi, _mm512_set1_epi32(ld32(xq0 + 20)));
                }
                { const __m512i lo = PERMB(c0_3, lut), hi = PERMB(_mm512_srli_epi16(c0_3, 4), lut);
                  e0_0_1 = _mm512_dpbusd_epi32(e0_0_1, lo, _mm512_set1_epi32(ld32(xq0 + 24)));
                  o0_0_1 = _mm512_dpbusd_epi32(o0_0_1, hi, _mm512_set1_epi32(ld32(xq0 + 28)));
                }
                a0_0_0 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_add_epi32(e0_0_0, o0_0_0)), _mm512_mul_ps(ds0_0_0, _mm512_set1_ps(dx[0 * nk + k])), a0_0_0);
                a0_0_0 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_add_epi32(e0_0_1, o0_0_1)), _mm512_mul_ps(ds0_0_1, _mm512_set1_ps(dx[0 * nk + k])), a0_0_0);
        }
        storev(Y + 0 * N, (g + 0) * 16 + 0, r0, r1, a0_0_0);
    }
}
#undef PERMB
#define PERMB(i, t) _mm512_shuffle_epi8((t), _mm512_and_si512((i), m4))  /* LUT is 4 copies of the 16 entries */
static void knvfp4_gemv_novbmi(const void *pv, const void *X, float *Y, int64_t K, int64_t r0, int64_t r1) {
    const packed_t *pk = (const packed_t *)pv;
    const int64_t M = 1, N = 0;
    const int64_t nk = K / 32;
    if (M > 1) abort();
    (void)N;
    float dx[1 * 1024];
    int32_t sd0[1 * 1024 * 2];
    const uint8_t *xp[1];
    for (int64_t m = 0; m < 1; m++) {
        xp[m] = (const uint8_t *)X + (m < M ? m : 0) * nk * 34;  /* columns beyond M repeat column 0 */
        for (int64_t k = 0; k < nk; k++) {
        const uint8_t *blk = xp[m] + 34 * k;
        dx[m * nk + k] = f16f(ld16(blk)) * 1.0f;
        sd0[(m * nk + k) * 2 + 0] = -128 * sum_i8(blk + 2 + 0, 16);
        sd0[(m * nk + k) * 2 + 1] = -128 * sum_i8(blk + 2 + 16, 16);
        }
    }
    const __m512i m4 = _mm512_set1_epi8((char)(0x0F)), mF0 = _mm512_set1_epi8((char)(0xF0));
    (void)m4; (void)mF0;
    const __m512i lut = _mm512_loadu_si512((const void *)LUT);
    const int64_t g0 = r0 / 16, g1 = (r1 + 15) / 16;
    for (int64_t g = g0; g < g1; g += 1) {
        __m512 a0_0_0 = _mm512_setzero_ps();
        for (int64_t p = 0; p < pk->nrec_k; p++) {
                const uint8_t *rec0 = pk->buf + ((size_t)(g + 0) * pk->nrec_k + p) * REC_BYTES;
                const __m512 ds0_0_0 = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)(rec0 + 0)));
                const __m512 ds0_0_1 = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)(rec0 + 32)));
                const int64_t k = p;
                const uint8_t *xq0 = xp[0] + 34 * k + 2;
                const __m512i c0_0 = _mm512_loadu_si512((const void *)(rec0 + HDR_BYTES + 0));
                const __m512i c0_1 = _mm512_loadu_si512((const void *)(rec0 + HDR_BYTES + 64));
                const __m512i c0_2 = _mm512_loadu_si512((const void *)(rec0 + HDR_BYTES + 128));
                const __m512i c0_3 = _mm512_loadu_si512((const void *)(rec0 + HDR_BYTES + 192));
                __m512i e0_0_0 = _mm512_set1_epi32(sd0[(0 * nk + k) * 2 + 0]), o0_0_0 = _mm512_setzero_si512();
                __m512i e0_0_1 = _mm512_set1_epi32(sd0[(0 * nk + k) * 2 + 1]), o0_0_1 = _mm512_setzero_si512();
                { const __m512i lo = PERMB(c0_0, lut), hi = PERMB(_mm512_srli_epi16(c0_0, 4), lut);
                  e0_0_0 = _mm512_dpbusd_epi32(e0_0_0, lo, _mm512_set1_epi32(ld32(xq0 + 0)));
                  o0_0_0 = _mm512_dpbusd_epi32(o0_0_0, hi, _mm512_set1_epi32(ld32(xq0 + 4)));
                }
                { const __m512i lo = PERMB(c0_1, lut), hi = PERMB(_mm512_srli_epi16(c0_1, 4), lut);
                  e0_0_0 = _mm512_dpbusd_epi32(e0_0_0, lo, _mm512_set1_epi32(ld32(xq0 + 8)));
                  o0_0_0 = _mm512_dpbusd_epi32(o0_0_0, hi, _mm512_set1_epi32(ld32(xq0 + 12)));
                }
                { const __m512i lo = PERMB(c0_2, lut), hi = PERMB(_mm512_srli_epi16(c0_2, 4), lut);
                  e0_0_1 = _mm512_dpbusd_epi32(e0_0_1, lo, _mm512_set1_epi32(ld32(xq0 + 16)));
                  o0_0_1 = _mm512_dpbusd_epi32(o0_0_1, hi, _mm512_set1_epi32(ld32(xq0 + 20)));
                }
                { const __m512i lo = PERMB(c0_3, lut), hi = PERMB(_mm512_srli_epi16(c0_3, 4), lut);
                  e0_0_1 = _mm512_dpbusd_epi32(e0_0_1, lo, _mm512_set1_epi32(ld32(xq0 + 24)));
                  o0_0_1 = _mm512_dpbusd_epi32(o0_0_1, hi, _mm512_set1_epi32(ld32(xq0 + 28)));
                }
                a0_0_0 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_add_epi32(e0_0_0, o0_0_0)), _mm512_mul_ps(ds0_0_0, _mm512_set1_ps(dx[0 * nk + k])), a0_0_0);
                a0_0_0 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_add_epi32(e0_0_1, o0_0_1)), _mm512_mul_ps(ds0_0_1, _mm512_set1_ps(dx[0 * nk + k])), a0_0_0);
        }
        storev(Y + 0 * N, (g + 0) * 16 + 0, r0, r1, a0_0_0);
    }
}
#undef PERMB

void knvfp4_gemv_packed(const void *pv, const void *X, float *Y, int64_t K, int64_t r0, int64_t r1) {
#ifdef KURN_NO_VBMI
    const int vbmi = 0;
#else
    static int vbmi = -1;
    if (vbmi < 0) vbmi = __builtin_cpu_supports("avx512vbmi") ? 1 : 0;
#endif
    if (vbmi) knvfp4_gemv_vbmi(pv, X, Y, K, r0, r1);
    else knvfp4_gemv_novbmi(pv, X, Y, K, r0, r1);
}
