// Generated by kurn (generic recipe lowering). Do not edit; edit the .kurn spec instead.
#include "kurn.h"
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <immintrin.h>
static inline float f16f(uint16_t h) { return _cvtsh_ss(h); }

typedef struct { uint16_t d; uint8_t qs[16]; } nblock;
typedef struct { uint16_t d; int8_t qs[32]; } xblock;
typedef struct { int64_t nrec_k, ngroups; uint8_t *buf; } packed_t;
#define REC_BYTES 576
#define HDR_BYTES 64
#define IDX_BYTES 128

/* repack: per (32-row group, scale period): d[32] (fp16), then per K-group
   8 4-bit table indices per row; byte (pair * 32 + row) holds chunk 2*pair
   in the low nibble and chunk 2*pair + 1 in the high nibble */
void *kq10_gemv_prepare(const void *W, int64_t K, int64_t N) {
    const nblock *w = (const nblock *)W;
    const int64_t nb = K / 128;
    packed_t *pk = malloc(sizeof *pk);
    pk->nrec_k = K / 128; pk->ngroups = (N + 31) / 32 + 0;
    const size_t bytes = (size_t)REC_BYTES * pk->nrec_k * pk->ngroups;
    pk->buf = aligned_alloc(64, (bytes + 63) & ~(size_t)63);
    memset(pk->buf, 0, bytes);
    for (int64_t gr = 0; gr < pk->ngroups; gr++)
        for (int64_t p = 0; p < pk->nrec_k; p++) {
            uint8_t *hp = pk->buf + ((size_t)gr * pk->nrec_k + p) * REC_BYTES;
            for (int row = 0; row < 32; row++) {
                const int64_t n = gr * 32 + row;
                if (n >= N) continue;
                const int64_t v0 = p * 128;
                const nblock *b = w + n * nb + v0 / 128;
                memcpy(hp + 2 * row, &b->d, 2);
                for (int kg = 0; kg < 4; kg++)
                    for (int ch = 0; ch < 8; ch++) {
                        int idx = 0;
                        for (int j = 0; j < 4; j++) {
                            const int v = (int)((v0 + kg * 32 + ch * 4 + j) % 128);
                            const int q = ((b->qs[v / 8] >> (v % 8)) & 1);
                            idx |= q << (1 * j);
                        }
                        hp[HDR_BYTES + kg * IDX_BYTES + (ch / 2) * 32 + row] |= (uint8_t)(idx << (4 * (ch & 1)));
                    }
            }
        }
    return pk;
}

static inline void storev(float *y, int64_t row0, int64_t r0, int64_t r1, __m512 v) {
    if (row0 >= r0 && row0 + 16 <= r1) { _mm512_storeu_ps(y + row0, v); return; }
    uint32_t m = 0xFFFF;
    if (row0 < r0) m &= r0 - row0 >= 16 ? 0 : 0xFFFFu << (r0 - row0);
    if (row0 + 16 > r1) m &= (1u << (r1 > row0 ? (r1 - row0 > 16 ? 16 : r1 - row0) : 0)) - 1;
    _mm512_mask_storeu_ps(y + row0, (__mmask16)m, v);
}

void kq10_gemv_packed(const void *pv, const void *X, float *Y, int64_t K, int64_t r0, int64_t r1) {
    const packed_t *pk = (const packed_t *)pv;
    const xblock *xb = (const xblock *)X;
    const int64_t nk = K / 32, nbx = K / 32;
    (void)nbx;
    /* per-call tables: one 16-entry int16 table per 4 activations (exact partial sums) */
    static __thread __m512i *tabs;
    static __thread int64_t tcap;
    if (tcap < nk * 8) { free(tabs); tabs = aligned_alloc(64, sizeof(__m512i) * nk * 8); tcap = nk * 8; }
    float dxs[1024];
    for (int64_t k = 0; k < nk; k++) {
        dxs[k] = f16f(xb[k].d);
        for (int ch = 0; ch < 8; ch++) {
            int16_t t[32] = {0};
            for (int i = 0; i < 16; i++) {
                int s = 0;
                for (int j = 0; j < 4; j++) { const int64_t v = k * 32 + ch * 4 + j; s += ((i >> j) & 1 ? 1 : -1) * xb[(v) / 32].qs[(v) % 32]; }
                t[i] = (int16_t)s;
            }
            tabs[k * 8 + ch] = _mm512_loadu_si512((const void *)t);
        }
    }
    const __m512i m15 = _mm512_set1_epi16(15);
    const int64_t g0 = r0 / 32, g1 = (r1 + 31) / 32;
    for (int64_t g = g0; g < g1; g += 1) {
        __m512 alo0 = _mm512_setzero_ps(), ahi0 = _mm512_setzero_ps();
        for (int64_t p = 0; p < pk->nrec_k; p++) {
                const uint8_t *rec0 = pk->buf + ((size_t)(g + 0) * pk->nrec_k + p) * REC_BYTES;
                const __m512 dlo0 = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)rec0)), dhi0 = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)(rec0 + 32)));
                for (int kg = 0; kg < 4; kg++) {
                    const int64_t k = p * 4 + kg;
                    const __m512i *T = tabs + k * 8;
                    __m512i s0 = _mm512_setzero_si512();
                    { const __m512i w = _mm512_cvtepu8_epi16(_mm256_loadu_si256((const __m256i *)(rec0 + HDR_BYTES + kg * IDX_BYTES + 0)));
                      s0 = _mm512_add_epi16(s0, _mm512_add_epi16(_mm512_permutexvar_epi16(_mm512_and_si512(w, m15), T[0]),
                                                                  _mm512_permutexvar_epi16(_mm512_srli_epi16(w, 4), T[1]))); }
                    { const __m512i w = _mm512_cvtepu8_epi16(_mm256_loadu_si256((const __m256i *)(rec0 + HDR_BYTES + kg * IDX_BYTES + 32)));
                      s0 = _mm512_add_epi16(s0, _mm512_add_epi16(_mm512_permutexvar_epi16(_mm512_and_si512(w, m15), T[2]),
                                                                  _mm512_permutexvar_epi16(_mm512_srli_epi16(w, 4), T[3]))); }
                    { const __m512i w = _mm512_cvtepu8_epi16(_mm256_loadu_si256((const __m256i *)(rec0 + HDR_BYTES + kg * IDX_BYTES + 64)));
                      s0 = _mm512_add_epi16(s0, _mm512_add_epi16(_mm512_permutexvar_epi16(_mm512_and_si512(w, m15), T[4]),
                                                                  _mm512_permutexvar_epi16(_mm512_srli_epi16(w, 4), T[5]))); }
                    { const __m512i w = _mm512_cvtepu8_epi16(_mm256_loadu_si256((const __m256i *)(rec0 + HDR_BYTES + kg * IDX_BYTES + 96)));
                      s0 = _mm512_add_epi16(s0, _mm512_add_epi16(_mm512_permutexvar_epi16(_mm512_and_si512(w, m15), T[6]),
                                                                  _mm512_permutexvar_epi16(_mm512_srli_epi16(w, 4), T[7]))); }
                    { const __m512 dx = _mm512_set1_ps(dxs[k]);
                      alo0 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_cvtepi16_epi32(_mm512_castsi512_si256(s0))), _mm512_mul_ps(dlo0, dx), alo0);
                      ahi0 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_cvtepi16_epi32(_mm512_extracti64x4_epi64(s0, 1))), _mm512_mul_ps(dhi0, dx), ahi0); }
                }
        }
        storev(Y, (g + 0) * 32, r0, r1, alo0); storev(Y, (g + 0) * 32 + 16, r0, r1, ahi0);
    }
}
