// Generated by kurn (lowbit: lut direct g4 perm). Do not edit; edit the .kurn spec instead.
#include "kurn.h"
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <immintrin.h>
static inline float f16f(uint16_t h) { return _cvtsh_ss(h); }
static inline __m512i lo16(__m512i v) { return _mm512_cvtepi16_epi32(_mm512_castsi512_si256(v)); }
static inline __m512i hi16(__m512i v) { return _mm512_cvtepi16_epi32(_mm512_extracti64x4_epi64(v, 1)); }
static inline __m512 fma16(__m512i s, __m512 d, __m512 dx, __m512 acc) {
    return _mm512_fmadd_ps(_mm512_cvtepi32_ps(s), _mm512_mul_ps(d, dx), acc);
}
/* lut=direct4 (perm): 8 chunks per 32-value unit, 16-entry int16 tables, 2 index words per row per unit (1.1250 bpw incl. scales) */

typedef struct { uint16_t d; uint8_t qs[16]; } nblock;
typedef struct { int64_t nrec_k, ngroups; uint8_t *buf; } packed_t;
#define REC_BYTES 576
#define HDR_BYTES 64
#define UNIT_BYTES 128
#define WVEC(rec, kg, w) _mm512_loadu_si512((const void *)((rec) + HDR_BYTES + (kg) * UNIT_BYTES + 64 * (w)))
typedef struct { uint16_t d; int8_t qs[32]; } xblock;

static inline void storev(float *y, int64_t row0, int64_t r0, int64_t r1, __m512 v) {
    if (row0 >= r0 && row0 + 16 <= r1) { _mm512_storeu_ps(y + row0, v); return; }
    uint32_t m = 0xFFFF;
    if (row0 < r0) m &= r0 - row0 >= 16 ? 0 : 0xFFFFu << (r0 - row0);
    if (row0 + 16 > r1) m &= (1u << (r1 > row0 ? (r1 - row0 > 16 ? 16 : r1 - row0) : 0)) - 1;
    _mm512_mask_storeu_ps(y + row0, (__mmask16)m, v);
}
void *kq10_gemv_prepare(const void *W, int64_t K, int64_t N) {
    const nblock *w = (const nblock *)W;
    const int64_t nb = K / 128;
    packed_t *pk = malloc(sizeof *pk);
    pk->nrec_k = K / 128; pk->ngroups = (N + 31) / 32 + 1;
    const size_t bytes = (size_t)REC_BYTES * pk->nrec_k * pk->ngroups;
    pk->buf = aligned_alloc(64, (bytes + 63) & ~(size_t)63);
    memset(pk->buf, 0, bytes);
    for (int64_t gr = 0; gr < pk->ngroups; gr++)
        for (int64_t p = 0; p < pk->nrec_k; p++) {
            uint8_t *hp = pk->buf + ((size_t)gr * pk->nrec_k + p) * REC_BYTES;
            for (int row = 0; row < 32; row++) {
                const int64_t n = gr * 32 + row;
                if (n >= N) continue;  /* padding rows stay zero: d = 0 */
                const int64_t v0 = p * 128;
                const nblock *b = w + n * nb + v0 / 128;
                memcpy(hp + 2 * row, &b->d, 2);
                for (int kg = 0; kg < 4; kg++) {
                    uint16_t *wp = (uint16_t *)(hp + HDR_BYTES + kg * UNIT_BYTES) + row;
                    static const int CH_O[8] = {0, 4, 8, 12, 16, 20, 24, 28}, CH_L[8] = {4, 4, 4, 4, 4, 4, 4, 4};
                    for (int c = 0; c < 8; c++)
                        for (int pl = 0; pl < 1; pl++) {
                            int e = 0;
                            for (int j = 0; j < CH_L[c]; j++) {
                                const int v = (int)((v0 + kg * 32 + CH_O[c] + j) % 128);
                                const int q = ((b->qs[v / 8] >> (v % 8)) & 1);
                                e |= q << j;
                            }
                            
                            const int slot = c * 1 + pl;
                            wp[(slot / 4) * 32] |= (uint16_t)(e << ((slot % 4) * 4));
                            (void)pl;
                        }
                }
            }
        }
    return pk;
}

static const int8_t LB_CST[1][64] __attribute__((aligned(64))) = {
    {-1, -1, -1, -1, 1, -1, -1, -1, -1, 1, -1, -1, 1, 1, -1, -1, -1, -1, 1, -1, 1, -1, 1, -1, -1, 1, 1, -1, 1, 1, 1, -1, -1, -1, -1, 1, 1, -1, -1, 1, -1, 1, -1, 1, 1, 1, -1, 1, -1, -1, 1, 1, 1, -1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1}
};
static const int32_t LB_CORR[1][16] __attribute__((aligned(64))) = {
    {512, 256, 256, 0, 256, 0, 0, -256, 256, 0, 0, -256, 0, -256, -256, -512}
};
static inline int32_t ld32(const uint8_t *p) { int32_t v; memcpy(&v, p, 4); return v; }
static inline size_t lb_toff(int64_t K) { return ((size_t)8 * (K / 32) + 63) & ~(size_t)63; }

/* table buffer: float dxs[K/32] | int32 sx[K/32] | pad to 64 | 8 tables of 16 int16 per 32-value unit */
void kq10_gemv_lut_info(int64_t K, int64_t *bytes, int64_t *units) {
    *bytes = (int64_t)(lb_toff(K) + (size_t)(K / 32) * 256);
    *units = K / 32;
}

void kq10_gemv_lut_build(const void *X, int64_t K, void *tabs, int64_t u0, int64_t u1) {
    const xblock *xb = (const xblock *)X;
    float *dxs = (float *)tabs;
    int32_t *sx = (int32_t *)((uint8_t *)tabs + 4 * (K / 32));
    uint8_t *tb = (uint8_t *)tabs + lb_toff(K);
    uint8_t xu[32] __attribute__((aligned(64)));
    for (int64_t u = u0; u < u1; u++) {
        for (int64_t k = u * 1; k < (u + 1) * 1; k++) {
            int8_t *dst = (int8_t *)xu + 32 * (k - u * 1);
            { const xblock *b = xb + k;
              memcpy(dst, b->qs, 32);
              int32_t s = 0;
              for (int l = 0; l < 32; l++) s += b->qs[l];
              dxs[k] = f16f(b->d) * 1.0f; sx[k] = s; }
        }
        for (int i = 0; i < 32; i++) xu[i] ^= 0x80;  /* x + 128 as u8 (vpdpbusd's unsigned operand) */
        uint8_t *t = tb + (size_t)u * 256;
            _mm256_store_si256((__m256i *)(t + 0), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 0)), _mm512_load_si512((const void *)LB_CST[0]))));
            _mm256_store_si256((__m256i *)(t + 32), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 4)), _mm512_load_si512((const void *)LB_CST[0]))));
            _mm256_store_si256((__m256i *)(t + 64), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 8)), _mm512_load_si512((const void *)LB_CST[0]))));
            _mm256_store_si256((__m256i *)(t + 96), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 12)), _mm512_load_si512((const void *)LB_CST[0]))));
            _mm256_store_si256((__m256i *)(t + 128), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 16)), _mm512_load_si512((const void *)LB_CST[0]))));
            _mm256_store_si256((__m256i *)(t + 160), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 20)), _mm512_load_si512((const void *)LB_CST[0]))));
            _mm256_store_si256((__m256i *)(t + 192), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 24)), _mm512_load_si512((const void *)LB_CST[0]))));
            _mm256_store_si256((__m256i *)(t + 224), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 28)), _mm512_load_si512((const void *)LB_CST[0]))));
    }
}

void kq10_gemv_lut_rows(const void *pv, const void *tabs, float *Y, int64_t K, int64_t r0, int64_t r1) {
    const packed_t *pk = (const packed_t *)pv;
    const float *dxs = (const float *)tabs;
    const int32_t *sx = (const int32_t *)((const uint8_t *)tabs + 4 * (K / 32));
    const uint8_t *tb = (const uint8_t *)tabs + lb_toff(K);
    const __m512i zero = _mm512_setzero_si512(), k27 = _mm512_set1_epi16(27), k3 = _mm512_set1_epi16(3);
    (void)sx; (void)zero; (void)k27; (void)k3;
    const int64_t g0 = r0 / 32, g1 = (r1 + 31) / 32;
    for (int64_t g = g0; g < g1; g += 2) {
        __m512 alo0 = _mm512_setzero_ps(), ahi0 = _mm512_setzero_ps(); __m512 alo1 = _mm512_setzero_ps(), ahi1 = _mm512_setzero_ps();
        for (int64_t p = 0; p < pk->nrec_k; p++) {
                const uint8_t *rec0 = pk->buf + ((size_t)(g + 0) * pk->nrec_k + p) * REC_BYTES;
                const __m512 dlo0 = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)rec0)), dhi0 = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)(rec0 + 32)));
                const uint8_t *rec1 = pk->buf + ((size_t)(g + 1) * pk->nrec_k + p) * REC_BYTES;
                const __m512 dlo1 = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)rec1)), dhi1 = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)(rec1 + 32)));
                for (int kg = 0; kg < 4; kg++) {
                    const int64_t k = p * 4 + kg;  /* unit index */
                    const uint8_t *T = tb + (size_t)k * 256;
                    __m512i s0_0 = _mm512_setzero_si512();
                    __m512i s1_0 = _mm512_setzero_si512();
                    { const __m512i W = WVEC(rec0, kg, 0);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(W, _mm512_broadcast_i64x4(_mm256_load_si256((const __m256i *)(T + 0)))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_srli_epi16(W, 4), _mm512_broadcast_i64x4(_mm256_load_si256((const __m256i *)(T + 32)))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_srli_epi16(W, 8), _mm512_broadcast_i64x4(_mm256_load_si256((const __m256i *)(T + 64)))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_srli_epi16(W, 12), _mm512_broadcast_i64x4(_mm256_load_si256((const __m256i *)(T + 96)))));
                    }
                    { const __m512i W = WVEC(rec1, kg, 0);
                      s1_0 = _mm512_add_epi16(s1_0, _mm512_permutexvar_epi16(W, _mm512_broadcast_i64x4(_mm256_load_si256((const __m256i *)(T + 0)))));
                      s1_0 = _mm512_add_epi16(s1_0, _mm512_permutexvar_epi16(_mm512_srli_epi16(W, 4), _mm512_broadcast_i64x4(_mm256_load_si256((const __m256i *)(T + 32)))));
                      s1_0 = _mm512_add_epi16(s1_0, _mm512_permutexvar_epi16(_mm512_srli_epi16(W, 8), _mm512_broadcast_i64x4(_mm256_load_si256((const __m256i *)(T + 64)))));
                      s1_0 = _mm512_add_epi16(s1_0, _mm512_permutexvar_epi16(_mm512_srli_epi16(W, 12), _mm512_broadcast_i64x4(_mm256_load_si256((const __m256i *)(T + 96)))));
                    }
                    { const __m512i W = WVEC(rec0, kg, 1);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(W, _mm512_broadcast_i64x4(_mm256_load_si256((const __m256i *)(T + 128)))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_srli_epi16(W, 4), _mm512_broadcast_i64x4(_mm256_load_si256((const __m256i *)(T + 160)))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_srli_epi16(W, 8), _mm512_broadcast_i64x4(_mm256_load_si256((const __m256i *)(T + 192)))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_srli_epi16(W, 12), _mm512_broadcast_i64x4(_mm256_load_si256((const __m256i *)(T + 224)))));
                    }
                    { const __m512i W = WVEC(rec1, kg, 1);
                      s1_0 = _mm512_add_epi16(s1_0, _mm512_permutexvar_epi16(W, _mm512_broadcast_i64x4(_mm256_load_si256((const __m256i *)(T + 128)))));
                      s1_0 = _mm512_add_epi16(s1_0, _mm512_permutexvar_epi16(_mm512_srli_epi16(W, 4), _mm512_broadcast_i64x4(_mm256_load_si256((const __m256i *)(T + 160)))));
                      s1_0 = _mm512_add_epi16(s1_0, _mm512_permutexvar_epi16(_mm512_srli_epi16(W, 8), _mm512_broadcast_i64x4(_mm256_load_si256((const __m256i *)(T + 192)))));
                      s1_0 = _mm512_add_epi16(s1_0, _mm512_permutexvar_epi16(_mm512_srli_epi16(W, 12), _mm512_broadcast_i64x4(_mm256_load_si256((const __m256i *)(T + 224)))));
                    }
                    { const __m512i sv = s0_0;
                      const __m512 dx = _mm512_set1_ps(dxs[k]);
                      alo0 = fma16(lo16(sv), dlo0, dx, alo0);
                      ahi0 = fma16(hi16(sv), dhi0, dx, ahi0); }
                    { const __m512i sv = s1_0;
                      const __m512 dx = _mm512_set1_ps(dxs[k]);
                      alo1 = fma16(lo16(sv), dlo1, dx, alo1);
                      ahi1 = fma16(hi16(sv), dhi1, dx, ahi1); }
                }
        }
        storev(Y, (g + 0) * 32, r0, r1, alo0); storev(Y, (g + 0) * 32 + 16, r0, r1, ahi0);
        storev(Y, (g + 1) * 32, r0, r1, alo1); storev(Y, (g + 1) * 32 + 16, r0, r1, ahi1);
    }
}

void kq10_gemv_packed(const void *pv, const void *X, float *Y, int64_t K, int64_t r0, int64_t r1) {
    static __thread uint8_t *tabs;
    static __thread int64_t cap;
    int64_t bytes, units;
    kq10_gemv_lut_info(K, &bytes, &units);
    if (cap < bytes) { free(tabs); tabs = aligned_alloc(64, (size_t)(bytes + 63) & ~(size_t)63); cap = bytes; }
    kq10_gemv_lut_build(X, K, tabs, 0, units);
    kq10_gemv_lut_rows(pv, tabs, Y, K, r0, r1);
}
