// Generated by kurn (lowbit: addsub mask). Do not edit; edit the .kurn spec instead.
#include "kurn.h"
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <immintrin.h>
static inline float f16f(uint16_t h) { return _cvtsh_ss(h); }
static inline __m512i lo16(__m512i v) { return _mm512_cvtepi16_epi32(_mm512_castsi512_si256(v)); }
static inline __m512i hi16(__m512i v) { return _mm512_cvtepi16_epi32(_mm512_extracti64x4_epi64(v, 1)); }
static inline __m512 fma16(__m512i s, __m512 d, __m512 dx, __m512 acc) {
    return _mm512_fmadd_ps(_mm512_cvtepi32_ps(s), _mm512_mul_ps(d, dx), acc);
}
static inline __m256 fma8(__m512i s, __m256 d, __m256 dx, __m256 acc) {
    return _mm256_fmadd_ps(_mm512_cvtepi64_ps(s), _mm256_mul_ps(d, dx), acc);
}
/* addsub=mask: multiplication-free; 2 bit plane(s) per weight, 256 B per 32 rows x 32 values */

typedef struct { uint16_t d; uint8_t qs[16]; } nblock;
typedef struct { int64_t nrec_k, ngroups; uint8_t *buf; } packed_t;
#define REC_BYTES 576
#define HDR_BYTES 64
#define UNIT_BYTES 256
typedef struct { uint16_t d; int8_t qs[32]; } xblock;

static inline void storev(float *y, int64_t row0, int64_t r0, int64_t r1, __m512 v) {
    if (row0 >= r0 && row0 + 16 <= r1) { _mm512_storeu_ps(y + row0, v); return; }
    uint32_t m = 0xFFFF;
    if (row0 < r0) m &= r0 - row0 >= 16 ? 0 : 0xFFFFu << (r0 - row0);
    if (row0 + 16 > r1) m &= (1u << (r1 > row0 ? (r1 - row0 > 16 ? 16 : r1 - row0) : 0)) - 1;
    _mm512_mask_storeu_ps(y + row0, (__mmask16)m, v);
}
void *kq20_gemv_prepare(const void *W, int64_t K, int64_t N) {
    const nblock *w = (const nblock *)W;
    const int64_t nb = K / 64;
    packed_t *pk = malloc(sizeof *pk);
    pk->nrec_k = K / 64; pk->ngroups = (N + 31) / 32 + 0;
    const size_t bytes = (size_t)REC_BYTES * pk->nrec_k * pk->ngroups;
    pk->buf = aligned_alloc(64, (bytes + 63) & ~(size_t)63);
    memset(pk->buf, 0, bytes);
    for (int64_t gr = 0; gr < pk->ngroups; gr++)
        for (int64_t p = 0; p < pk->nrec_k; p++) {
            uint8_t *hp = pk->buf + ((size_t)gr * pk->nrec_k + p) * REC_BYTES;
            for (int row = 0; row < 32; row++) {
                const int64_t n = gr * 32 + row;
                if (n >= N) continue;
                const int64_t v0 = p * 64;
                const nblock *b = w + n * nb + v0 / 64;
                memcpy(hp + 2 * row, &b->d, 2);
                for (int kg = 0; kg < 2; kg++) {
                    uint8_t *up = hp + HDR_BYTES + kg * UNIT_BYTES;
                    for (int kk = 0; kk < 32; kk++) {
                        const int v = (int)((v0 + kg * 32 + kk) % 64);
                        const int q = ((b->qs[v / 4] >> (2 * (v % 4))) & 3);
                        for (int pl = 0; pl < 2; pl++)
                            if ((q >> pl) & 1) ((uint32_t *)(up + pl * 128))[kk] |= 1u << row;
                    }
                }
            }
        }
    return pk;
}

static inline int64_t ldq(const uint8_t *p) { int64_t v; memcpy(&v, p, 8); return v; }
void kq20_gemv_packed(const void *pv, const void *X, float *Y, int64_t K, int64_t r0, int64_t r1) {
    const packed_t *pk = (const packed_t *)pv;
    const xblock *xb = (const xblock *)X;
    int8_t xq[32768] __attribute__((aligned(64)));
    float dxs[1024]; int32_t sx[1024];
    for (int64_t k = 0; k < K / 32; k++) {
        int8_t *dst = xq + 32 * k;
        { const xblock *b = xb + k;
              memcpy(dst, b->qs, 32);
              int32_t s = 0;
              for (int l = 0; l < 32; l++) s += b->qs[l];
              dxs[k] = f16f(b->d) * 1.0f; sx[k] = s; }
    }
    int16_t xw[32768];
    for (int64_t i = 0; i < K; i++) xw[i] = xq[i];
    const __m512i zero = _mm512_setzero_si512();
    (void)zero;
    const int64_t g0 = r0 / 32, g1 = (r1 + 31) / 32;
    for (int64_t g = g0; g < g1; g += 1) {
        __m512 alo0 = _mm512_setzero_ps(), ahi0 = _mm512_setzero_ps();
        for (int64_t p = 0; p < pk->nrec_k; p++) {
                const uint8_t *rec0 = pk->buf + ((size_t)(g + 0) * pk->nrec_k + p) * REC_BYTES;
                const __m512 dlo0 = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)rec0)), dhi0 = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)(rec0 + 32)));
                __m512i a0_0 = _mm512_setzero_si512();
                __m512i a0_1 = _mm512_setzero_si512();
                for (int kg = 0; kg < 2; kg++) {
                    const int64_t k = p * 2 + kg;
                    const int16_t *xk = xw + k * 32;
                    for (int kk = 0; kk < 32; kk++) {
                        const __m512i xv = _mm512_set1_epi16(xk[kk]);
                        a0_0 = _mm512_mask_add_epi16(a0_0, _cvtu32_mask32(((const uint32_t *)(rec0 + HDR_BYTES + kg * UNIT_BYTES + 0))[kk]), a0_0, xv);
                        a0_1 = _mm512_mask_add_epi16(a0_1, _cvtu32_mask32(((const uint32_t *)(rec0 + HDR_BYTES + kg * UNIT_BYTES + 128))[kk]), a0_1, xv);
                    }
                    { const __m512i sv = _mm512_sub_epi16(_mm512_add_epi16(_mm512_slli_epi16(a0_1, 1), a0_0), _mm512_set1_epi16((short)sx[k]));
                      const __m512 dx = _mm512_set1_ps(dxs[k]);
                      alo0 = fma16(lo16(sv), dlo0, dx, alo0);
                      ahi0 = fma16(hi16(sv), dhi0, dx, ahi0); }
                    a0_0 = _mm512_setzero_si512();
                    a0_1 = _mm512_setzero_si512();
                }
        }
        storev(Y, (g + 0) * 32, r0, r1, alo0); storev(Y, (g + 0) * 32 + 16, r0, r1, ahi0);
    }
}
