// Generated by kurn (lowbit: q2_K k16). Do not edit; edit the .kurn spec instead.
#include "kurn.h"
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <immintrin.h>
static inline float f16f(uint16_t h) { return _cvtsh_ss(h); }
static inline __m512i lo16(__m512i v) { return _mm512_cvtepi16_epi32(_mm512_castsi512_si256(v)); }
static inline __m512i hi16(__m512i v) { return _mm512_cvtepi16_epi32(_mm512_extracti64x4_epi64(v, 1)); }
static inline __m512 fma16(__m512i s, __m512 d, __m512 dx, __m512 acc) {
    return _mm512_fmadd_ps(_mm512_cvtepi32_ps(s), _mm512_mul_ps(d, dx), acc);
}
static inline __m256 fma8(__m512i s, __m256 d, __m256 dx, __m256 acc) {
    return _mm256_fmadd_ps(_mm512_cvtepi64_ps(s), _mm256_mul_ps(d, dx), acc);
}

typedef struct { uint8_t scales[16]; uint8_t qs[64]; uint16_t d; uint16_t dmin; } nblock;
typedef struct { float d; int8_t qs[256]; int16_t bsums[16]; } xblock;
typedef struct { int64_t nrec_k, ngroups; uint8_t *buf; } packed_t;
#define REC_BYTES 1344

static inline void storev(float *y, int64_t row0, int64_t r0, int64_t r1, __m512 v) {
    if (row0 >= r0 && row0 + 16 <= r1) { _mm512_storeu_ps(y + row0, v); return; }
    uint32_t m = 0xFFFF;
    if (row0 < r0) m &= r0 - row0 >= 16 ? 0 : 0xFFFFu << (r0 - row0);
    if (row0 + 16 > r1) m &= (1u << (r1 > row0 ? (r1 - row0 > 16 ? 16 : r1 - row0) : 0)) - 1;
    _mm512_mask_storeu_ps(y + row0, (__mmask16)m, v);
}

void *kq2k_gemv_prepare(const void *W, int64_t K, int64_t N) {
    const nblock *w = (const nblock *)W;
    const int64_t nb = K / 256;
    packed_t *pk = malloc(sizeof *pk);
    pk->nrec_k = nb; pk->ngroups = (N + 15) / 16 + 1;
    const size_t bytes = (size_t)REC_BYTES * pk->nrec_k * pk->ngroups;
    pk->buf = aligned_alloc(64, (bytes + 63) & ~(size_t)63);
    memset(pk->buf, 0, bytes);
    for (int64_t gr = 0; gr < pk->ngroups; gr++)
        for (int64_t p = 0; p < nb; p++) {
            uint8_t *hp = pk->buf + ((size_t)gr * nb + p) * REC_BYTES;
            for (int row = 0; row < 16; row++) {
                const int64_t n = gr * 16 + row;
                if (n >= N) continue;
                const nblock *b = w + n * nb + p;
                memcpy(hp + 2 * row, &b->d, 2); memcpy(hp + 32 + 2 * row, &b->dmin, 2);
                for (int s = 0; s < 16; s++) hp[64 + (s / 2) * 32 + row * 2 + (s & 1)] = b->scales[s];
                for (int kg = 0; kg < 8; kg++)
                    for (int kk = 0; kk < 8; kk++)
                        for (int j = 0; j < 4; j++) {
                            const int v = kg * 32 + kk * 4 + j;
                            const int q = ((b->qs[(v / 128) * 32 + v % 32] >> (2 * ((v % 128) / 32))) & 3);
                            hp[320 + kg * 128 + (kk / 4) * 64 + row * 4 + j] |= (uint8_t)(q << (2 * (kk & 3)));
                        }
            }
        }
    return pk;
}

void kq2k_gemv_packed(const void *pv, const void *X, float *Y, int64_t K, int64_t r0, int64_t r1) {
    const packed_t *pk = (const packed_t *)pv;
    const xblock *xb = (const xblock *)X;
    const int64_t nk = K / 32;
    int32_t xw[32768 / 4], bsp[1024];
    float dxs[128];
    for (int64_t k = 0; k < nk; k++) {
        const xblock *b = xb + k / 8;
        memcpy(xw + k * 8, b->qs + (k % 8) * 32, 32);
        memcpy(bsp + k, b->bsums + 2 * (k % 8), 4);
        dxs[k / 8] = b->d;
    }
    const __m512i m3 = _mm512_set1_epi8(3), m15w = _mm512_set1_epi16(15);
    const int64_t g0 = r0 / 16, g1 = (r1 + 15) / 16;
    for (int64_t g = g0; g < g1; g += 2) {
        __m512 a0 = _mm512_setzero_ps(); __m512 a1 = _mm512_setzero_ps();
        for (int64_t p = 0; p < pk->nrec_k; p++) {
                const uint8_t *rec0 = pk->buf + ((size_t)(g + 0) * pk->nrec_k + p) * REC_BYTES;
                __m512i ia0 = _mm512_setzero_si512(), ma0 = _mm512_setzero_si512();
                const uint8_t *rec1 = pk->buf + ((size_t)(g + 1) * pk->nrec_k + p) * REC_BYTES;
                __m512i ia1 = _mm512_setzero_si512(), ma1 = _mm512_setzero_si512();
                for (int kg = 0; kg < 8; kg++) {
                    const int64_t k = p * 8 + kg;
                    const __m512i bs = _mm512_set1_epi32(bsp[k]);  /* (bsums[2kg], bsums[2kg+1]) */
                    const __m512i x0 = _mm512_set1_epi32(xw[k * 8 + 0]);
                    const __m512i x1 = _mm512_set1_epi32(xw[k * 8 + 1]);
                    const __m512i x2 = _mm512_set1_epi32(xw[k * 8 + 2]);
                    const __m512i x3 = _mm512_set1_epi32(xw[k * 8 + 3]);
                    const __m512i x4 = _mm512_set1_epi32(xw[k * 8 + 4]);
                    const __m512i x5 = _mm512_set1_epi32(xw[k * 8 + 5]);
                    const __m512i x6 = _mm512_set1_epi32(xw[k * 8 + 6]);
                    const __m512i x7 = _mm512_set1_epi32(xw[k * 8 + 7]);
                    { const uint8_t *cp = rec0 + 320 + kg * 128;
                      const __m512i c0 = _mm512_loadu_si512((const void *)cp), c1 = _mm512_loadu_si512((const void *)(cp + 64));
                      __m512i e = _mm512_setzero_si512(), o = _mm512_setzero_si512();
                      e = _mm512_dpbusd_epi32(e, _mm512_and_si512(c0, m3), x0);
                      e = _mm512_dpbusd_epi32(e, _mm512_and_si512(_mm512_srli_epi16(c0, 2), m3), x1);
                      e = _mm512_dpbusd_epi32(e, _mm512_and_si512(_mm512_srli_epi16(c0, 4), m3), x2);
                      e = _mm512_dpbusd_epi32(e, _mm512_and_si512(_mm512_srli_epi16(c0, 6), m3), x3);
                      o = _mm512_dpbusd_epi32(o, _mm512_and_si512(c1, m3), x4);
                      o = _mm512_dpbusd_epi32(o, _mm512_and_si512(_mm512_srli_epi16(c1, 2), m3), x5);
                      o = _mm512_dpbusd_epi32(o, _mm512_and_si512(_mm512_srli_epi16(c1, 4), m3), x6);
                      o = _mm512_dpbusd_epi32(o, _mm512_and_si512(_mm512_srli_epi16(c1, 6), m3), x7);
                      const __m512i sp = _mm512_cvtepu8_epi16(_mm256_loadu_si256((const __m256i *)(rec0 + 64 + kg * 32)));
                      const __m512i pair = _mm512_mask_blend_epi16(0xAAAAAAAAu, e, _mm512_slli_epi32(o, 16));
                      ia0 = _mm512_dpwssd_epi32(ia0, pair, _mm512_and_si512(sp, m15w));
                      ma0 = _mm512_dpwssd_epi32(ma0, _mm512_srli_epi16(sp, 4), bs); }
                    { const uint8_t *cp = rec1 + 320 + kg * 128;
                      const __m512i c0 = _mm512_loadu_si512((const void *)cp), c1 = _mm512_loadu_si512((const void *)(cp + 64));
                      __m512i e = _mm512_setzero_si512(), o = _mm512_setzero_si512();
                      e = _mm512_dpbusd_epi32(e, _mm512_and_si512(c0, m3), x0);
                      e = _mm512_dpbusd_epi32(e, _mm512_and_si512(_mm512_srli_epi16(c0, 2), m3), x1);
                      e = _mm512_dpbusd_epi32(e, _mm512_and_si512(_mm512_srli_epi16(c0, 4), m3), x2);
                      e = _mm512_dpbusd_epi32(e, _mm512_and_si512(_mm512_srli_epi16(c0, 6), m3), x3);
                      o = _mm512_dpbusd_epi32(o, _mm512_and_si512(c1, m3), x4);
                      o = _mm512_dpbusd_epi32(o, _mm512_and_si512(_mm512_srli_epi16(c1, 2), m3), x5);
                      o = _mm512_dpbusd_epi32(o, _mm512_and_si512(_mm512_srli_epi16(c1, 4), m3), x6);
                      o = _mm512_dpbusd_epi32(o, _mm512_and_si512(_mm512_srli_epi16(c1, 6), m3), x7);
                      const __m512i sp = _mm512_cvtepu8_epi16(_mm256_loadu_si256((const __m256i *)(rec1 + 64 + kg * 32)));
                      const __m512i pair = _mm512_mask_blend_epi16(0xAAAAAAAAu, e, _mm512_slli_epi32(o, 16));
                      ia1 = _mm512_dpwssd_epi32(ia1, pair, _mm512_and_si512(sp, m15w));
                      ma1 = _mm512_dpwssd_epi32(ma1, _mm512_srli_epi16(sp, 4), bs); }
                }
                { const __m512 dx = _mm512_set1_ps(dxs[p]);
                  const __m512 d = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)rec0)), dm = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)(rec0 + 32)));
                  a0 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(ia0), _mm512_mul_ps(d, dx), a0);
                  a0 = _mm512_fnmadd_ps(_mm512_cvtepi32_ps(ma0), _mm512_mul_ps(dm, dx), a0); }
                { const __m512 dx = _mm512_set1_ps(dxs[p]);
                  const __m512 d = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)rec1)), dm = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)(rec1 + 32)));
                  a1 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(ia1), _mm512_mul_ps(d, dx), a1);
                  a1 = _mm512_fnmadd_ps(_mm512_cvtepi32_ps(ma1), _mm512_mul_ps(dm, dx), a1); }
        }
        storev(Y, (g + 0) * 16, r0, r1, a0);
        storev(Y, (g + 1) * 16, r0, r1, a1);
    }
}
