// Generated by kurn (generic recipe lowering). Do not edit; edit the .kurn spec instead.
#include "kurn.h"
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <immintrin.h>
static inline float f16f(uint16_t h) { return _cvtsh_ss(h); }

typedef struct { uint16_t d; uint8_t qs[16]; } nblock;
typedef struct { int64_t nrec_k, ngroups; uint8_t *buf; } packed_t;
#define REC_BYTES 576
#define HDR_BYTES 64
#define KG_BYTES 512

/* repack: records of 32 rows x 32 values; see lower_nibble in kurn/generic.py for the layout */
void *kq40_gemv_prepare(const void *W, int64_t K, int64_t N) {
    const nblock *w = (const nblock *)W;
    const int64_t nb = K / 32;
    packed_t *pk = malloc(sizeof *pk);
    pk->nrec_k = K / 32; pk->ngroups = ((N + 31) / 32 + 3 + 3) / 4 * 4;
    const size_t bytes = (size_t)REC_BYTES * pk->nrec_k * pk->ngroups;
    pk->buf = aligned_alloc(64, (bytes + 63) & ~(size_t)63);
    memset(pk->buf, 0, bytes);
    for (int64_t g = 0; g < pk->ngroups; g++)
        for (int64_t p = 0; p < pk->nrec_k; p++) {
            uint8_t *hp = pk->buf + ((((size_t)(g) / 4) * pk->nrec_k + p) * 4 + (g) % 4) * REC_BYTES;
            for (int row = 0; row < 32; row++) {
                const int64_t n = g * 32 + row;
                if (n >= N) continue;  /* padding rows stay zero: scale 0 */
                const int64_t v0 = p * 32;
                const nblock *b = w + n * nb + v0 / 32;
                memcpy(hp + 2 * row, &b->d, 2);
                for (int kg = 0; kg < 1; kg++) {
                    uint8_t *rec_codes = hp + HDR_BYTES + kg * KG_BYTES;
                    for (int kk = 0; kk < 8; kk++)
                        for (int j = 0; j < 4; j++) {
                            const int v = (int)((v0 + kg * 32 + kk * 4 + j) % 32);
                            const int q = (v < 16 ? b->qs[v] & 15 : b->qs[v - 16] >> 4);
                            rec_codes[kk * 64 + (row % 16) * 4 + j] |= (uint8_t)(q << (4 * (row / 16)));
                        }
                }
            }
        }
    return pk;
}

static inline int32_t ld32(const uint8_t *p) { int32_t v; memcpy(&v, p, 4); return v; }
static inline uint16_t ld16(const uint8_t *p) { uint16_t v; memcpy(&v, p, 2); return v; }
static inline int32_t sum_i8(const uint8_t *q, int n) {  /* sum of n = 16 or 32 int8 */
    __m128i s;
    if (n == 32) {
        const __m256i t = _mm256_sad_epu8(_mm256_xor_si256(_mm256_loadu_si256((const __m256i *)q), _mm256_set1_epi8((char)0x80)),
                                          _mm256_setzero_si256());
        s = _mm_add_epi64(_mm256_castsi256_si128(t), _mm256_extracti128_si256(t, 1));
    } else {
        s = _mm_sad_epu8(_mm_xor_si128(_mm_loadu_si128((const __m128i *)q), _mm_set1_epi8((char)0x80)), _mm_setzero_si128());
    }
    s = _mm_add_epi64(s, _mm_unpackhi_epi64(s, s));
    return _mm_cvtsi128_si32(s) - 128 * n;
}

static inline void storev(float *y, int64_t row0, int64_t r0, int64_t r1, __m512 v) {
    if (row0 >= r0 && row0 + 16 <= r1) { _mm512_storeu_ps(y + row0, v); return; }
    uint32_t m = 0xFFFF;
    if (row0 < r0) m &= r0 - row0 >= 16 ? 0 : 0xFFFFu << (r0 - row0);
    if (row0 + 16 > r1) m &= r1 <= row0 ? 0 : (r1 - row0 >= 16 ? 0xFFFFu : (1u << (r1 - row0)) - 1);
    _mm512_mask_storeu_ps(y + row0, (__mmask16)m, v);
}

void kq40_gemv_packed(const void *pv, const void *X, float *Y, int64_t K, int64_t r0, int64_t r1) {
    const packed_t *pk = (const packed_t *)pv;
    const int64_t M = 1, N = 0;
    const int64_t nk = K / 32;
    if (M > 1) abort();
    (void)N;
    float dx[1 * 1024];
    int32_t sdA[1 * 1024], sdB[1 * 1024];
    const uint8_t *xp[1];
    for (int64_t m = 0; m < 1; m++) {
        xp[m] = (const uint8_t *)X + (m < M ? m : 0) * nk * 34;  /* columns beyond M repeat column 0 */
        for (int64_t k = 0; k < nk; k++) {
        const uint8_t *blk = xp[m] + 34 * k;
        dx[m * nk + k] = f16f(ld16(blk)) * 1.0f;
        { const int32_t s = sum_i8(blk + 2, 32); sdA[m * nk + k] = -136 * s; sdB[m * nk + k] = -128 * s; }
        }
    }
    const __m512i m4 = _mm512_set1_epi8((char)(0x0F)), mF0 = _mm512_set1_epi8((char)(0xF0));
    (void)m4; (void)mF0;
    const int64_t g0 = r0 / 32, g1 = (r1 + 31) / 32;
    for (int64_t g = g0; g < g1; g += 4) {
        __m512 a0_0_0 = _mm512_setzero_ps(); __m512 a0_0_1 = _mm512_setzero_ps(); __m512 a1_0_0 = _mm512_setzero_ps(); __m512 a1_0_1 = _mm512_setzero_ps(); __m512 a2_0_0 = _mm512_setzero_ps(); __m512 a2_0_1 = _mm512_setzero_ps(); __m512 a3_0_0 = _mm512_setzero_ps(); __m512 a3_0_1 = _mm512_setzero_ps();
        for (int64_t p = 0; p < pk->nrec_k; p++) {
                const uint8_t *rec0 = pk->buf + ((((size_t)(g + 0) / 4) * pk->nrec_k + p) * 4 + (g + 0) % 4) * REC_BYTES;
                const uint8_t *rec1 = pk->buf + ((((size_t)(g + 1) / 4) * pk->nrec_k + p) * 4 + (g + 1) % 4) * REC_BYTES;
                const uint8_t *rec2 = pk->buf + ((((size_t)(g + 2) / 4) * pk->nrec_k + p) * 4 + (g + 2) % 4) * REC_BYTES;
                const uint8_t *rec3 = pk->buf + ((((size_t)(g + 3) / 4) * pk->nrec_k + p) * 4 + (g + 3) % 4) * REC_BYTES;
                const __m512 ds0_0_0 = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)(rec0 + 0)));
                const __m512 ds0_1_0 = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)(rec0 + 32)));
                const __m512 ds1_0_0 = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)(rec1 + 0)));
                const __m512 ds1_1_0 = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)(rec1 + 32)));
                const __m512 ds2_0_0 = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)(rec2 + 0)));
                const __m512 ds2_1_0 = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)(rec2 + 32)));
                const __m512 ds3_0_0 = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)(rec3 + 0)));
                const __m512 ds3_1_0 = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)(rec3 + 32)));
                const int64_t k = p;
                const uint8_t *xq0 = xp[0] + 34 * k + 2;
                const __m512i c0_0 = _mm512_loadu_si512((const void *)(rec0 + HDR_BYTES + 0));
                const __m512i c0_1 = _mm512_loadu_si512((const void *)(rec0 + HDR_BYTES + 64));
                const __m512i c0_2 = _mm512_loadu_si512((const void *)(rec0 + HDR_BYTES + 128));
                const __m512i c0_3 = _mm512_loadu_si512((const void *)(rec0 + HDR_BYTES + 192));
                const __m512i c0_4 = _mm512_loadu_si512((const void *)(rec0 + HDR_BYTES + 256));
                const __m512i c0_5 = _mm512_loadu_si512((const void *)(rec0 + HDR_BYTES + 320));
                const __m512i c0_6 = _mm512_loadu_si512((const void *)(rec0 + HDR_BYTES + 384));
                const __m512i c0_7 = _mm512_loadu_si512((const void *)(rec0 + HDR_BYTES + 448));
                const __m512i c1_0 = _mm512_loadu_si512((const void *)(rec1 + HDR_BYTES + 0));
                const __m512i c1_1 = _mm512_loadu_si512((const void *)(rec1 + HDR_BYTES + 64));
                const __m512i c1_2 = _mm512_loadu_si512((const void *)(rec1 + HDR_BYTES + 128));
                const __m512i c1_3 = _mm512_loadu_si512((const void *)(rec1 + HDR_BYTES + 192));
                const __m512i c1_4 = _mm512_loadu_si512((const void *)(rec1 + HDR_BYTES + 256));
                const __m512i c1_5 = _mm512_loadu_si512((const void *)(rec1 + HDR_BYTES + 320));
                const __m512i c1_6 = _mm512_loadu_si512((const void *)(rec1 + HDR_BYTES + 384));
                const __m512i c1_7 = _mm512_loadu_si512((const void *)(rec1 + HDR_BYTES + 448));
                const __m512i c2_0 = _mm512_loadu_si512((const void *)(rec2 + HDR_BYTES + 0));
                const __m512i c2_1 = _mm512_loadu_si512((const void *)(rec2 + HDR_BYTES + 64));
                const __m512i c2_2 = _mm512_loadu_si512((const void *)(rec2 + HDR_BYTES + 128));
                const __m512i c2_3 = _mm512_loadu_si512((const void *)(rec2 + HDR_BYTES + 192));
                const __m512i c2_4 = _mm512_loadu_si512((const void *)(rec2 + HDR_BYTES + 256));
                const __m512i c2_5 = _mm512_loadu_si512((const void *)(rec2 + HDR_BYTES + 320));
                const __m512i c2_6 = _mm512_loadu_si512((const void *)(rec2 + HDR_BYTES + 384));
                const __m512i c2_7 = _mm512_loadu_si512((const void *)(rec2 + HDR_BYTES + 448));
                const __m512i c3_0 = _mm512_loadu_si512((const void *)(rec3 + HDR_BYTES + 0));
                const __m512i c3_1 = _mm512_loadu_si512((const void *)(rec3 + HDR_BYTES + 64));
                const __m512i c3_2 = _mm512_loadu_si512((const void *)(rec3 + HDR_BYTES + 128));
                const __m512i c3_3 = _mm512_loadu_si512((const void *)(rec3 + HDR_BYTES + 192));
                const __m512i c3_4 = _mm512_loadu_si512((const void *)(rec3 + HDR_BYTES + 256));
                const __m512i c3_5 = _mm512_loadu_si512((const void *)(rec3 + HDR_BYTES + 320));
                const __m512i c3_6 = _mm512_loadu_si512((const void *)(rec3 + HDR_BYTES + 384));
                const __m512i c3_7 = _mm512_loadu_si512((const void *)(rec3 + HDR_BYTES + 448));
                __m512i A0_0_0 = _mm512_set1_epi32(sdA[0 * nk + k]), A0_0_1 = _mm512_setzero_si512(), B0_0_0 = _mm512_set1_epi32(sdB[0 * nk + k]), B0_0_1 = _mm512_setzero_si512();
                __m512i A1_0_0 = _mm512_set1_epi32(sdA[0 * nk + k]), A1_0_1 = _mm512_setzero_si512(), B1_0_0 = _mm512_set1_epi32(sdB[0 * nk + k]), B1_0_1 = _mm512_setzero_si512();
                __m512i A2_0_0 = _mm512_set1_epi32(sdA[0 * nk + k]), A2_0_1 = _mm512_setzero_si512(), B2_0_0 = _mm512_set1_epi32(sdB[0 * nk + k]), B2_0_1 = _mm512_setzero_si512();
                __m512i A3_0_0 = _mm512_set1_epi32(sdA[0 * nk + k]), A3_0_1 = _mm512_setzero_si512(), B3_0_0 = _mm512_set1_epi32(sdB[0 * nk + k]), B3_0_1 = _mm512_setzero_si512();
                { const __m512i hv = _mm512_and_si512(c0_0, mF0);
                  A0_0_0 = _mm512_dpbusd_epi32(A0_0_0, c0_0, _mm512_set1_epi32(ld32(xq0 + 0)));
                  B0_0_0 = _mm512_dpbusd_epi32(B0_0_0, hv, _mm512_set1_epi32(ld32(xq0 + 0))); }
                { const __m512i hv = _mm512_and_si512(c1_0, mF0);
                  A1_0_0 = _mm512_dpbusd_epi32(A1_0_0, c1_0, _mm512_set1_epi32(ld32(xq0 + 0)));
                  B1_0_0 = _mm512_dpbusd_epi32(B1_0_0, hv, _mm512_set1_epi32(ld32(xq0 + 0))); }
                { const __m512i hv = _mm512_and_si512(c2_0, mF0);
                  A2_0_0 = _mm512_dpbusd_epi32(A2_0_0, c2_0, _mm512_set1_epi32(ld32(xq0 + 0)));
                  B2_0_0 = _mm512_dpbusd_epi32(B2_0_0, hv, _mm512_set1_epi32(ld32(xq0 + 0))); }
                { const __m512i hv = _mm512_and_si512(c3_0, mF0);
                  A3_0_0 = _mm512_dpbusd_epi32(A3_0_0, c3_0, _mm512_set1_epi32(ld32(xq0 + 0)));
                  B3_0_0 = _mm512_dpbusd_epi32(B3_0_0, hv, _mm512_set1_epi32(ld32(xq0 + 0))); }
                { const __m512i hv = _mm512_and_si512(c0_1, mF0);
                  A0_0_1 = _mm512_dpbusd_epi32(A0_0_1, c0_1, _mm512_set1_epi32(ld32(xq0 + 4)));
                  B0_0_1 = _mm512_dpbusd_epi32(B0_0_1, hv, _mm512_set1_epi32(ld32(xq0 + 4))); }
                { const __m512i hv = _mm512_and_si512(c1_1, mF0);
                  A1_0_1 = _mm512_dpbusd_epi32(A1_0_1, c1_1, _mm512_set1_epi32(ld32(xq0 + 4)));
                  B1_0_1 = _mm512_dpbusd_epi32(B1_0_1, hv, _mm512_set1_epi32(ld32(xq0 + 4))); }
                { const __m512i hv = _mm512_and_si512(c2_1, mF0);
                  A2_0_1 = _mm512_dpbusd_epi32(A2_0_1, c2_1, _mm512_set1_epi32(ld32(xq0 + 4)));
                  B2_0_1 = _mm512_dpbusd_epi32(B2_0_1, hv, _mm512_set1_epi32(ld32(xq0 + 4))); }
                { const __m512i hv = _mm512_and_si512(c3_1, mF0);
                  A3_0_1 = _mm512_dpbusd_epi32(A3_0_1, c3_1, _mm512_set1_epi32(ld32(xq0 + 4)));
                  B3_0_1 = _mm512_dpbusd_epi32(B3_0_1, hv, _mm512_set1_epi32(ld32(xq0 + 4))); }
                { const __m512i hv = _mm512_and_si512(c0_2, mF0);
                  A0_0_0 = _mm512_dpbusd_epi32(A0_0_0, c0_2, _mm512_set1_epi32(ld32(xq0 + 8)));
                  B0_0_0 = _mm512_dpbusd_epi32(B0_0_0, hv, _mm512_set1_epi32(ld32(xq0 + 8))); }
                { const __m512i hv = _mm512_and_si512(c1_2, mF0);
                  A1_0_0 = _mm512_dpbusd_epi32(A1_0_0, c1_2, _mm512_set1_epi32(ld32(xq0 + 8)));
                  B1_0_0 = _mm512_dpbusd_epi32(B1_0_0, hv, _mm512_set1_epi32(ld32(xq0 + 8))); }
                { const __m512i hv = _mm512_and_si512(c2_2, mF0);
                  A2_0_0 = _mm512_dpbusd_epi32(A2_0_0, c2_2, _mm512_set1_epi32(ld32(xq0 + 8)));
                  B2_0_0 = _mm512_dpbusd_epi32(B2_0_0, hv, _mm512_set1_epi32(ld32(xq0 + 8))); }
                { const __m512i hv = _mm512_and_si512(c3_2, mF0);
                  A3_0_0 = _mm512_dpbusd_epi32(A3_0_0, c3_2, _mm512_set1_epi32(ld32(xq0 + 8)));
                  B3_0_0 = _mm512_dpbusd_epi32(B3_0_0, hv, _mm512_set1_epi32(ld32(xq0 + 8))); }
                { const __m512i hv = _mm512_and_si512(c0_3, mF0);
                  A0_0_1 = _mm512_dpbusd_epi32(A0_0_1, c0_3, _mm512_set1_epi32(ld32(xq0 + 12)));
                  B0_0_1 = _mm512_dpbusd_epi32(B0_0_1, hv, _mm512_set1_epi32(ld32(xq0 + 12))); }
                { const __m512i hv = _mm512_and_si512(c1_3, mF0);
                  A1_0_1 = _mm512_dpbusd_epi32(A1_0_1, c1_3, _mm512_set1_epi32(ld32(xq0 + 12)));
                  B1_0_1 = _mm512_dpbusd_epi32(B1_0_1, hv, _mm512_set1_epi32(ld32(xq0 + 12))); }
                { const __m512i hv = _mm512_and_si512(c2_3, mF0);
                  A2_0_1 = _mm512_dpbusd_epi32(A2_0_1, c2_3, _mm512_set1_epi32(ld32(xq0 + 12)));
                  B2_0_1 = _mm512_dpbusd_epi32(B2_0_1, hv, _mm512_set1_epi32(ld32(xq0 + 12))); }
                { const __m512i hv = _mm512_and_si512(c3_3, mF0);
                  A3_0_1 = _mm512_dpbusd_epi32(A3_0_1, c3_3, _mm512_set1_epi32(ld32(xq0 + 12)));
                  B3_0_1 = _mm512_dpbusd_epi32(B3_0_1, hv, _mm512_set1_epi32(ld32(xq0 + 12))); }
                { const __m512i hv = _mm512_and_si512(c0_4, mF0);
                  A0_0_0 = _mm512_dpbusd_epi32(A0_0_0, c0_4, _mm512_set1_epi32(ld32(xq0 + 16)));
                  B0_0_0 = _mm512_dpbusd_epi32(B0_0_0, hv, _mm512_set1_epi32(ld32(xq0 + 16))); }
                { const __m512i hv = _mm512_and_si512(c1_4, mF0);
                  A1_0_0 = _mm512_dpbusd_epi32(A1_0_0, c1_4, _mm512_set1_epi32(ld32(xq0 + 16)));
                  B1_0_0 = _mm512_dpbusd_epi32(B1_0_0, hv, _mm512_set1_epi32(ld32(xq0 + 16))); }
                { const __m512i hv = _mm512_and_si512(c2_4, mF0);
                  A2_0_0 = _mm512_dpbusd_epi32(A2_0_0, c2_4, _mm512_set1_epi32(ld32(xq0 + 16)));
                  B2_0_0 = _mm512_dpbusd_epi32(B2_0_0, hv, _mm512_set1_epi32(ld32(xq0 + 16))); }
                { const __m512i hv = _mm512_and_si512(c3_4, mF0);
                  A3_0_0 = _mm512_dpbusd_epi32(A3_0_0, c3_4, _mm512_set1_epi32(ld32(xq0 + 16)));
                  B3_0_0 = _mm512_dpbusd_epi32(B3_0_0, hv, _mm512_set1_epi32(ld32(xq0 + 16))); }
                { const __m512i hv = _mm512_and_si512(c0_5, mF0);
                  A0_0_1 = _mm512_dpbusd_epi32(A0_0_1, c0_5, _mm512_set1_epi32(ld32(xq0 + 20)));
                  B0_0_1 = _mm512_dpbusd_epi32(B0_0_1, hv, _mm512_set1_epi32(ld32(xq0 + 20))); }
                { const __m512i hv = _mm512_and_si512(c1_5, mF0);
                  A1_0_1 = _mm512_dpbusd_epi32(A1_0_1, c1_5, _mm512_set1_epi32(ld32(xq0 + 20)));
                  B1_0_1 = _mm512_dpbusd_epi32(B1_0_1, hv, _mm512_set1_epi32(ld32(xq0 + 20))); }
                { const __m512i hv = _mm512_and_si512(c2_5, mF0);
                  A2_0_1 = _mm512_dpbusd_epi32(A2_0_1, c2_5, _mm512_set1_epi32(ld32(xq0 + 20)));
                  B2_0_1 = _mm512_dpbusd_epi32(B2_0_1, hv, _mm512_set1_epi32(ld32(xq0 + 20))); }
                { const __m512i hv = _mm512_and_si512(c3_5, mF0);
                  A3_0_1 = _mm512_dpbusd_epi32(A3_0_1, c3_5, _mm512_set1_epi32(ld32(xq0 + 20)));
                  B3_0_1 = _mm512_dpbusd_epi32(B3_0_1, hv, _mm512_set1_epi32(ld32(xq0 + 20))); }
                { const __m512i hv = _mm512_and_si512(c0_6, mF0);
                  A0_0_0 = _mm512_dpbusd_epi32(A0_0_0, c0_6, _mm512_set1_epi32(ld32(xq0 + 24)));
                  B0_0_0 = _mm512_dpbusd_epi32(B0_0_0, hv, _mm512_set1_epi32(ld32(xq0 + 24))); }
                { const __m512i hv = _mm512_and_si512(c1_6, mF0);
                  A1_0_0 = _mm512_dpbusd_epi32(A1_0_0, c1_6, _mm512_set1_epi32(ld32(xq0 + 24)));
                  B1_0_0 = _mm512_dpbusd_epi32(B1_0_0, hv, _mm512_set1_epi32(ld32(xq0 + 24))); }
                { const __m512i hv = _mm512_and_si512(c2_6, mF0);
                  A2_0_0 = _mm512_dpbusd_epi32(A2_0_0, c2_6, _mm512_set1_epi32(ld32(xq0 + 24)));
                  B2_0_0 = _mm512_dpbusd_epi32(B2_0_0, hv, _mm512_set1_epi32(ld32(xq0 + 24))); }
                { const __m512i hv = _mm512_and_si512(c3_6, mF0);
                  A3_0_0 = _mm512_dpbusd_epi32(A3_0_0, c3_6, _mm512_set1_epi32(ld32(xq0 + 24)));
                  B3_0_0 = _mm512_dpbusd_epi32(B3_0_0, hv, _mm512_set1_epi32(ld32(xq0 + 24))); }
                { const __m512i hv = _mm512_and_si512(c0_7, mF0);
                  A0_0_1 = _mm512_dpbusd_epi32(A0_0_1, c0_7, _mm512_set1_epi32(ld32(xq0 + 28)));
                  B0_0_1 = _mm512_dpbusd_epi32(B0_0_1, hv, _mm512_set1_epi32(ld32(xq0 + 28))); }
                { const __m512i hv = _mm512_and_si512(c1_7, mF0);
                  A1_0_1 = _mm512_dpbusd_epi32(A1_0_1, c1_7, _mm512_set1_epi32(ld32(xq0 + 28)));
                  B1_0_1 = _mm512_dpbusd_epi32(B1_0_1, hv, _mm512_set1_epi32(ld32(xq0 + 28))); }
                { const __m512i hv = _mm512_and_si512(c2_7, mF0);
                  A2_0_1 = _mm512_dpbusd_epi32(A2_0_1, c2_7, _mm512_set1_epi32(ld32(xq0 + 28)));
                  B2_0_1 = _mm512_dpbusd_epi32(B2_0_1, hv, _mm512_set1_epi32(ld32(xq0 + 28))); }
                { const __m512i hv = _mm512_and_si512(c3_7, mF0);
                  A3_0_1 = _mm512_dpbusd_epi32(A3_0_1, c3_7, _mm512_set1_epi32(ld32(xq0 + 28)));
                  B3_0_1 = _mm512_dpbusd_epi32(B3_0_1, hv, _mm512_set1_epi32(ld32(xq0 + 28))); }
                { const __m512i sa = _mm512_add_epi32(A0_0_0, A0_0_1), sb = _mm512_add_epi32(B0_0_0, B0_0_1);
                  a0_0_0 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_sub_epi32(sa, sb)), _mm512_mul_ps(ds0_0_0, _mm512_set1_ps(dx[0 * nk + k])), a0_0_0);
                  a0_0_1 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_srai_epi32(sb, 4)), _mm512_mul_ps(ds0_1_0, _mm512_set1_ps(dx[0 * nk + k])), a0_0_1);
                }
                { const __m512i sa = _mm512_add_epi32(A1_0_0, A1_0_1), sb = _mm512_add_epi32(B1_0_0, B1_0_1);
                  a1_0_0 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_sub_epi32(sa, sb)), _mm512_mul_ps(ds1_0_0, _mm512_set1_ps(dx[0 * nk + k])), a1_0_0);
                  a1_0_1 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_srai_epi32(sb, 4)), _mm512_mul_ps(ds1_1_0, _mm512_set1_ps(dx[0 * nk + k])), a1_0_1);
                }
                { const __m512i sa = _mm512_add_epi32(A2_0_0, A2_0_1), sb = _mm512_add_epi32(B2_0_0, B2_0_1);
                  a2_0_0 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_sub_epi32(sa, sb)), _mm512_mul_ps(ds2_0_0, _mm512_set1_ps(dx[0 * nk + k])), a2_0_0);
                  a2_0_1 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_srai_epi32(sb, 4)), _mm512_mul_ps(ds2_1_0, _mm512_set1_ps(dx[0 * nk + k])), a2_0_1);
                }
                { const __m512i sa = _mm512_add_epi32(A3_0_0, A3_0_1), sb = _mm512_add_epi32(B3_0_0, B3_0_1);
                  a3_0_0 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_sub_epi32(sa, sb)), _mm512_mul_ps(ds3_0_0, _mm512_set1_ps(dx[0 * nk + k])), a3_0_0);
                  a3_0_1 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_srai_epi32(sb, 4)), _mm512_mul_ps(ds3_1_0, _mm512_set1_ps(dx[0 * nk + k])), a3_0_1);
                }
        }
        storev(Y + 0 * N, (g + 0) * 32 + 0, r0, r1, a0_0_0);
        storev(Y + 0 * N, (g + 0) * 32 + 16, r0, r1, a0_0_1);
        storev(Y + 0 * N, (g + 1) * 32 + 0, r0, r1, a1_0_0);
        storev(Y + 0 * N, (g + 1) * 32 + 16, r0, r1, a1_0_1);
        storev(Y + 0 * N, (g + 2) * 32 + 0, r0, r1, a2_0_0);
        storev(Y + 0 * N, (g + 2) * 32 + 16, r0, r1, a2_0_1);
        storev(Y + 0 * N, (g + 3) * 32 + 0, r0, r1, a3_0_0);
        storev(Y + 0 * N, (g + 3) * 32 + 16, r0, r1, a3_0_1);
    }
}
