// Generated by kurn (generic recipe lowering). Do not edit; edit the .kurn spec instead.
#include "kurn.h"
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <immintrin.h>
static inline float f16f(uint16_t h) { return _cvtsh_ss(h); }

typedef struct { uint16_t d; uint8_t qs[16]; } nblock;
typedef struct { int64_t nrec_k, ngroups; uint8_t *buf; } packed_t;
#define REC_BYTES 144
#define HDR_BYTES 16
#define KG_BYTES 128

/* repack: records of 8 rows x 32 values; see lower_nibble in kurn/generic.py for the layout */
void *kq40_gemv_prepare(const void *W, int64_t K, int64_t N) {
    const nblock *w = (const nblock *)W;
    const int64_t nb = K / 32;
    packed_t *pk = malloc(sizeof *pk);
    pk->nrec_k = K / 32; pk->ngroups = (N + 7) / 8 + 1;
    const size_t bytes = (size_t)REC_BYTES * pk->nrec_k * pk->ngroups;
    pk->buf = aligned_alloc(64, (bytes + 63) & ~(size_t)63);
    memset(pk->buf, 0, bytes);
    for (int64_t g = 0; g < pk->ngroups; g++)
        for (int64_t p = 0; p < pk->nrec_k; p++) {
            uint8_t *hp = pk->buf + ((size_t)g * pk->nrec_k + p) * REC_BYTES;
            for (int row = 0; row < 8; row++) {
                const int64_t n = g * 8 + row;
                if (n >= N) continue;  /* padding rows stay zero: scale 0 */
                const int64_t v0 = p * 32;
                const nblock *b = w + n * nb + v0 / 32;
                memcpy(hp + 2 * row, &b->d, 2);
                for (int kg = 0; kg < 1; kg++) {
                    uint8_t *rec_codes = hp + HDR_BYTES + kg * KG_BYTES;
                    for (int kk = 0; kk < 8; kk++)
                        for (int j = 0; j < 4; j++) {
                            const int v = (int)((v0 + kg * 32 + kk * 4 + j) % 32);
                            const int q = (v < 16 ? b->qs[v] & 15 : b->qs[v - 16] >> 4);
                            rec_codes[(kk / 2) * 32 + row * 4 + j] |= (uint8_t)(q << (4 * (kk & 1)));
                        }
                }
            }
        }
    return pk;
}

static inline int32_t ld32(const uint8_t *p) { int32_t v; memcpy(&v, p, 4); return v; }
static inline uint16_t ld16(const uint8_t *p) { uint16_t v; memcpy(&v, p, 2); return v; }
static inline int32_t sum_i8(const uint8_t *q, int n) {  /* sum of n = 16 or 32 int8 */
    __m128i s;
    if (n == 32) {
        const __m256i t = _mm256_sad_epu8(_mm256_xor_si256(_mm256_loadu_si256((const __m256i *)q), _mm256_set1_epi8((char)0x80)),
                                          _mm256_setzero_si256());
        s = _mm_add_epi64(_mm256_castsi256_si128(t), _mm256_extracti128_si256(t, 1));
    } else {
        s = _mm_sad_epu8(_mm_xor_si128(_mm_loadu_si128((const __m128i *)q), _mm_set1_epi8((char)0x80)), _mm_setzero_si128());
    }
    s = _mm_add_epi64(s, _mm_unpackhi_epi64(s, s));
    return _mm_cvtsi128_si32(s) - 128 * n;
}

static inline void storev(float *y, int64_t row0, int64_t r0, int64_t r1, __m256 v) {
    float t[8];
    _mm256_storeu_ps(t, v);
    for (int i = 0; i < 8; i++) if (row0 + i >= r0 && row0 + i < r1) y[row0 + i] = t[i];
}

void kq40_gemv_packed(const void *pv, const void *X, float *Y, int64_t K, int64_t r0, int64_t r1) {
    const packed_t *pk = (const packed_t *)pv;
    const int64_t M = 1, N = 0;
    const int64_t nk = K / 32;
    if (M > 1) abort();
    (void)N;
    float dx[1 * 1024];
    int32_t sd0[1 * 1024 * 1];
    const uint8_t *xp[1];
    for (int64_t m = 0; m < 1; m++) {
        xp[m] = (const uint8_t *)X + (m < M ? m : 0) * nk * 34;  /* columns beyond M repeat column 0 */
        for (int64_t k = 0; k < nk; k++) {
        const uint8_t *blk = xp[m] + 34 * k;
        dx[m * nk + k] = f16f(ld16(blk)) * 1.0f;
        sd0[(m * nk + k) * 1 + 0] = -8 * sum_i8(blk + 2 + 0, 32);
        }
    }
    const __m256i m4 = _mm256_set1_epi8((char)(0x0F)), mF0 = _mm256_set1_epi8((char)(0xF0));
    (void)m4; (void)mF0;
    const int64_t g0 = r0 / 8, g1 = (r1 + 7) / 8;
    for (int64_t g = g0; g < g1; g += 2) {
        __m256 a0_0_0 = _mm256_setzero_ps(); __m256 a1_0_0 = _mm256_setzero_ps();
        for (int64_t p = 0; p < pk->nrec_k; p++) {
                const uint8_t *rec0 = pk->buf + ((size_t)(g + 0) * pk->nrec_k + p) * REC_BYTES;
                const uint8_t *rec1 = pk->buf + ((size_t)(g + 1) * pk->nrec_k + p) * REC_BYTES;
                const __m256 ds0_0_0 = _mm256_cvtph_ps(_mm_loadu_si128((const __m128i *)(rec0 + 0)));
                const __m256 ds1_0_0 = _mm256_cvtph_ps(_mm_loadu_si128((const __m128i *)(rec1 + 0)));
                const int64_t k = p;
                const uint8_t *xq0 = xp[0] + 34 * k + 2;
                const __m256i c0_0 = _mm256_loadu_si256((const __m256i *)(rec0 + HDR_BYTES + 0));
                const __m256i c0_1 = _mm256_loadu_si256((const __m256i *)(rec0 + HDR_BYTES + 32));
                const __m256i c0_2 = _mm256_loadu_si256((const __m256i *)(rec0 + HDR_BYTES + 64));
                const __m256i c0_3 = _mm256_loadu_si256((const __m256i *)(rec0 + HDR_BYTES + 96));
                const __m256i c1_0 = _mm256_loadu_si256((const __m256i *)(rec1 + HDR_BYTES + 0));
                const __m256i c1_1 = _mm256_loadu_si256((const __m256i *)(rec1 + HDR_BYTES + 32));
                const __m256i c1_2 = _mm256_loadu_si256((const __m256i *)(rec1 + HDR_BYTES + 64));
                const __m256i c1_3 = _mm256_loadu_si256((const __m256i *)(rec1 + HDR_BYTES + 96));
                __m256i e0_0_0 = _mm256_set1_epi32(sd0[(0 * nk + k) * 1 + 0]), o0_0_0 = _mm256_setzero_si256();
                __m256i e1_0_0 = _mm256_set1_epi32(sd0[(0 * nk + k) * 1 + 0]), o1_0_0 = _mm256_setzero_si256();
                { const __m256i lo = _mm256_and_si256(c0_0, m4), hi = _mm256_and_si256(c0_0, mF0);
                  e0_0_0 = _mm256_dpbusd_avx_epi32(e0_0_0, lo, _mm256_set1_epi32(ld32(xq0 + 0)));
                  o0_0_0 = _mm256_dpbusd_avx_epi32(o0_0_0, hi, _mm256_set1_epi32(ld32(xq0 + 4)));
                }
                { const __m256i lo = _mm256_and_si256(c1_0, m4), hi = _mm256_and_si256(c1_0, mF0);
                  e1_0_0 = _mm256_dpbusd_avx_epi32(e1_0_0, lo, _mm256_set1_epi32(ld32(xq0 + 0)));
                  o1_0_0 = _mm256_dpbusd_avx_epi32(o1_0_0, hi, _mm256_set1_epi32(ld32(xq0 + 4)));
                }
                { const __m256i lo = _mm256_and_si256(c0_1, m4), hi = _mm256_and_si256(c0_1, mF0);
                  e0_0_0 = _mm256_dpbusd_avx_epi32(e0_0_0, lo, _mm256_set1_epi32(ld32(xq0 + 8)));
                  o0_0_0 = _mm256_dpbusd_avx_epi32(o0_0_0, hi, _mm256_set1_epi32(ld32(xq0 + 12)));
                }
                { const __m256i lo = _mm256_and_si256(c1_1, m4), hi = _mm256_and_si256(c1_1, mF0);
                  e1_0_0 = _mm256_dpbusd_avx_epi32(e1_0_0, lo, _mm256_set1_epi32(ld32(xq0 + 8)));
                  o1_0_0 = _mm256_dpbusd_avx_epi32(o1_0_0, hi, _mm256_set1_epi32(ld32(xq0 + 12)));
                }
                { const __m256i lo = _mm256_and_si256(c0_2, m4), hi = _mm256_and_si256(c0_2, mF0);
                  e0_0_0 = _mm256_dpbusd_avx_epi32(e0_0_0, lo, _mm256_set1_epi32(ld32(xq0 + 16)));
                  o0_0_0 = _mm256_dpbusd_avx_epi32(o0_0_0, hi, _mm256_set1_epi32(ld32(xq0 + 20)));
                }
                { const __m256i lo = _mm256_and_si256(c1_2, m4), hi = _mm256_and_si256(c1_2, mF0);
                  e1_0_0 = _mm256_dpbusd_avx_epi32(e1_0_0, lo, _mm256_set1_epi32(ld32(xq0 + 16)));
                  o1_0_0 = _mm256_dpbusd_avx_epi32(o1_0_0, hi, _mm256_set1_epi32(ld32(xq0 + 20)));
                }
                { const __m256i lo = _mm256_and_si256(c0_3, m4), hi = _mm256_and_si256(c0_3, mF0);
                  e0_0_0 = _mm256_dpbusd_avx_epi32(e0_0_0, lo, _mm256_set1_epi32(ld32(xq0 + 24)));
                  o0_0_0 = _mm256_dpbusd_avx_epi32(o0_0_0, hi, _mm256_set1_epi32(ld32(xq0 + 28)));
                }
                { const __m256i lo = _mm256_and_si256(c1_3, m4), hi = _mm256_and_si256(c1_3, mF0);
                  e1_0_0 = _mm256_dpbusd_avx_epi32(e1_0_0, lo, _mm256_set1_epi32(ld32(xq0 + 24)));
                  o1_0_0 = _mm256_dpbusd_avx_epi32(o1_0_0, hi, _mm256_set1_epi32(ld32(xq0 + 28)));
                }
                a0_0_0 = _mm256_fmadd_ps(_mm256_cvtepi32_ps(_mm256_add_epi32(e0_0_0, _mm256_srai_epi32(o0_0_0, 4))), _mm256_mul_ps(ds0_0_0, _mm256_set1_ps(dx[0 * nk + k])), a0_0_0);
                a1_0_0 = _mm256_fmadd_ps(_mm256_cvtepi32_ps(_mm256_add_epi32(e1_0_0, _mm256_srai_epi32(o1_0_0, 4))), _mm256_mul_ps(ds1_0_0, _mm256_set1_ps(dx[0 * nk + k])), a1_0_0);
        }
        storev(Y + 0 * N, (g + 0) * 8 + 0, r0, r1, a0_0_0);
        storev(Y + 0 * N, (g + 1) * 8 + 0, r0, r1, a1_0_0);
    }
}
