// Generated by kurn (generic recipe lowering, scalar reference). Do not edit.
#include "kurn.h"
#include <stdint.h>
#include <string.h>
static inline float f16f(uint16_t h) {
    uint32_t s = (uint32_t)(h & 0x8000) << 16, e = (h >> 10) & 0x1f, m = h & 0x3ff, bb;
    if (e == 0) { if (!m) bb = s; else { e = 113; while (!(m & 0x400)) { m <<= 1; e--; } bb = s | (e << 23) | ((m & 0x3ff) << 13); } }
    else if (e == 31) bb = s | 0x7f800000 | (m << 13);
    else bb = s | ((e + 112) << 23) | (m << 13);
    float f; memcpy(&f, &bb, 4); return f;
}
typedef struct { uint16_t d; uint8_t qs[16]; } nblock;
typedef struct { uint16_t d; int8_t qs[32]; } xblock;

void kq40_gemv(const void *W, const void *X, float *Y, int64_t K, int64_t r0, int64_t r1) {
    const xblock *x = (const xblock *)X;
    for (int64_t n = r0; n < r1; n++) {
        const nblock *wr = (const nblock *)W + n * (K / 32);
        float acc = 0;
        for (int64_t k = 0; k < K / 32; k++) {
            const nblock *b = wr + (k * 32) / 32;
            int32_t t = 0;
            for (int l = 0; l < 32; l++) {
                const int64_t vv = k * 32 + l;
                const int v = (int)(vv % 32);
                const int q = (v < 16 ? b->qs[v] & 15 : b->qs[v - 16] >> 4);
                t += ((q - 8)) * x[vv / 32].qs[vv % 32];
            }
            acc += f16f(b->d) * f16f(x[k].d) * (float)t;
        }
        Y[n] = acc;
    }
}
