// Generated by kurn (generic recipe lowering). Do not edit; edit the .kurn spec instead.
#include "kurn.h"
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <immintrin.h>
static inline float f16f(uint16_t h) { return _cvtsh_ss(h); }

typedef struct { uint16_t d; uint8_t qs[16]; } nblock;
typedef struct { int64_t nrec_k, ngroups; uint8_t *buf; } packed_t;
#define REC_BYTES 288
#define HDR_BYTES 32
#define KG_BYTES 256
#define CODE_BYTES 256

void *kq40_gemv_prepare(const void *W, int64_t K, int64_t N) {
    const nblock *w = (const nblock *)W;
    const int64_t nb = K / 32;
    packed_t *pk = malloc(sizeof *pk);
    pk->nrec_k = K / 32; pk->ngroups = (N + 15) / 16 + 1;
    const size_t bytes = (size_t)REC_BYTES * pk->nrec_k * pk->ngroups;
    pk->buf = aligned_alloc(64, (bytes + 63) & ~(size_t)63);
    memset(pk->buf, 0, bytes);
    for (int64_t g = 0; g < pk->ngroups; g++)
        for (int64_t p = 0; p < pk->nrec_k; p++) {
            uint8_t *hp = pk->buf + ((size_t)g * pk->nrec_k + p) * REC_BYTES;
            for (int row = 0; row < 16; row++) {
                const int64_t n = g * 16 + row;
                if (n >= N) continue;  /* padding rows stay zero: d = 0 */
                const int64_t v0 = p * 32;
                const nblock *b = w + n * nb + v0 / 32;
                
                memcpy(hp + 2 * row, &b->d, 2);
                for (int kg = 0; kg < 1; kg++) {
                    uint8_t *rec_codes = hp + HDR_BYTES + kg * KG_BYTES;
                    int32_t wsum = 0;
                    for (int kk = 0; kk < 8; kk++)
                        for (int j = 0; j < 4; j++) {
                            const int v = (int)((v0 + kg * 32 + kk * 4 + j) % 32);
                            const int q = (v < 16 ? b->qs[v] & 15 : b->qs[v - 16] >> 4);
                            (void)wsum;
                            
                            const uint8_t u = q;
                            rec_codes[(kk / 2) * 64 + (row) * 4 + j] |= (uint8_t)(u << (4 * (kk & 1)));
                        }
                    
                }
            }
        }
    return pk;
}

typedef struct { uint16_t d; int8_t qs[32]; } xblock;

static inline void storev(float *y, int64_t row0, int64_t r0, int64_t r1, __m512 v) {
    if (row0 >= r0 && row0 + 16 <= r1) { _mm512_storeu_ps(y + row0, v); return; }
    uint32_t m = 0xFFFF;
    if (row0 < r0) m &= 0xFFFFu << (r0 - row0);
    if (row0 + 16 > r1) m &= (1u << (r1 > row0 ? r1 - row0 : 0)) - 1;
    _mm512_mask_storeu_ps(y + row0, (__mmask16)m, v);
}

void kq40_gemv_packed(const void *pv, const void *X, float *Y, int64_t K, int64_t r0, int64_t r1) {
    const packed_t *pk = (const packed_t *)pv;
    const int64_t M = 1, N = 0;
    const int64_t nk = K / 32, nbx = K / 32;
    if (M > 1) abort();
    int32_t xw[1 * 1024 * 8], sx[1 * 1024];
    float dx[1 * 1024];
    (void)sx; (void)nbx;
    for (int64_t m = 0; m < 1; m++) {
    const xblock *xb = (const xblock *)X + (m < M ? m : 0) * nbx;  /* columns beyond M repeat column 0 */
    for (int64_t k = 0; k < nk; k++) {
        int32_t s = 0;
        for (int l = 0; l < 32; l++) s += xb[k].qs[l];
        memcpy(xw + (m * nk + k) * 8, xb[k].qs, 32);
        sx[m * nk + k] = s;
        dx[m * nk + k] = f16f(xb[k].d);
    }
    }
    const __m512i m4 = _mm512_set1_epi8((char)(0x0F)), m3 = _mm512_set1_epi8((char)(0x03));
    (void)m4; (void)m3;
    
    const int64_t g0 = r0 / 16, g1 = (r1 + 15) / 16;
    int64_t g = g0;
    for (; g < g1; g += 2) {
        __m512 a0_0 = _mm512_setzero_ps(); __m512 a1_0 = _mm512_setzero_ps();
        for (int64_t p = 0; p < pk->nrec_k; p++) {
                const uint8_t *rec0 = pk->buf + ((size_t)(g + 0) * pk->nrec_k + p) * REC_BYTES;
                const uint8_t *rec1 = pk->buf + ((size_t)(g + 1) * pk->nrec_k + p) * REC_BYTES;
                _mm_prefetch((const char *)(rec0 + 8 * REC_BYTES), _MM_HINT_T0);
                _mm_prefetch((const char *)(rec1 + 8 * REC_BYTES), _MM_HINT_T0);
                const __m512 d0 = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)(rec0)));
                const __m512 d1 = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)(rec1)));
                for (int kg = 0; kg < 1; kg++) {
                    const int64_t k = p * 1 + kg;
                    const __m512i c0_0 = _mm512_loadu_si512((const void *)(rec0 + HDR_BYTES + kg * KG_BYTES + 0));
                    const __m512i c0_1 = _mm512_loadu_si512((const void *)(rec0 + HDR_BYTES + kg * KG_BYTES + 64));
                    const __m512i c0_2 = _mm512_loadu_si512((const void *)(rec0 + HDR_BYTES + kg * KG_BYTES + 128));
                    const __m512i c0_3 = _mm512_loadu_si512((const void *)(rec0 + HDR_BYTES + kg * KG_BYTES + 192));
                    const __m512i c1_0 = _mm512_loadu_si512((const void *)(rec1 + HDR_BYTES + kg * KG_BYTES + 0));
                    const __m512i c1_1 = _mm512_loadu_si512((const void *)(rec1 + HDR_BYTES + kg * KG_BYTES + 64));
                    const __m512i c1_2 = _mm512_loadu_si512((const void *)(rec1 + HDR_BYTES + kg * KG_BYTES + 128));
                    const __m512i c1_3 = _mm512_loadu_si512((const void *)(rec1 + HDR_BYTES + kg * KG_BYTES + 192));
                    __m512i e0_0 = _mm512_set1_epi32(-8 * sx[0 * nk + k]), o0_0 = _mm512_setzero_si512();
                    __m512i e1_0 = _mm512_set1_epi32(-8 * sx[0 * nk + k]), o1_0 = _mm512_setzero_si512();
                    const __m512i x0_0 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 0]);
                    { const __m512i u = _mm512_and_si512(c0_0, m4);
                      e0_0 = _mm512_dpbusd_epi32(e0_0, u, x0_0);
                    }
                    { const __m512i u = _mm512_and_si512(c1_0, m4);
                      e1_0 = _mm512_dpbusd_epi32(e1_0, u, x0_0);
                    }
                    const __m512i x0_1 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 1]);
                    { const __m512i u = _mm512_and_si512(_mm512_srli_epi16(c0_0, 4), m4);
                      o0_0 = _mm512_dpbusd_epi32(o0_0, u, x0_1);
                    }
                    { const __m512i u = _mm512_and_si512(_mm512_srli_epi16(c1_0, 4), m4);
                      o1_0 = _mm512_dpbusd_epi32(o1_0, u, x0_1);
                    }
                    const __m512i x0_2 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 2]);
                    { const __m512i u = _mm512_and_si512(c0_1, m4);
                      e0_0 = _mm512_dpbusd_epi32(e0_0, u, x0_2);
                    }
                    { const __m512i u = _mm512_and_si512(c1_1, m4);
                      e1_0 = _mm512_dpbusd_epi32(e1_0, u, x0_2);
                    }
                    const __m512i x0_3 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 3]);
                    { const __m512i u = _mm512_and_si512(_mm512_srli_epi16(c0_1, 4), m4);
                      o0_0 = _mm512_dpbusd_epi32(o0_0, u, x0_3);
                    }
                    { const __m512i u = _mm512_and_si512(_mm512_srli_epi16(c1_1, 4), m4);
                      o1_0 = _mm512_dpbusd_epi32(o1_0, u, x0_3);
                    }
                    const __m512i x0_4 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 4]);
                    { const __m512i u = _mm512_and_si512(c0_2, m4);
                      e0_0 = _mm512_dpbusd_epi32(e0_0, u, x0_4);
                    }
                    { const __m512i u = _mm512_and_si512(c1_2, m4);
                      e1_0 = _mm512_dpbusd_epi32(e1_0, u, x0_4);
                    }
                    const __m512i x0_5 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 5]);
                    { const __m512i u = _mm512_and_si512(_mm512_srli_epi16(c0_2, 4), m4);
                      o0_0 = _mm512_dpbusd_epi32(o0_0, u, x0_5);
                    }
                    { const __m512i u = _mm512_and_si512(_mm512_srli_epi16(c1_2, 4), m4);
                      o1_0 = _mm512_dpbusd_epi32(o1_0, u, x0_5);
                    }
                    const __m512i x0_6 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 6]);
                    { const __m512i u = _mm512_and_si512(c0_3, m4);
                      e0_0 = _mm512_dpbusd_epi32(e0_0, u, x0_6);
                    }
                    { const __m512i u = _mm512_and_si512(c1_3, m4);
                      e1_0 = _mm512_dpbusd_epi32(e1_0, u, x0_6);
                    }
                    const __m512i x0_7 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 7]);
                    { const __m512i u = _mm512_and_si512(_mm512_srli_epi16(c0_3, 4), m4);
                      o0_0 = _mm512_dpbusd_epi32(o0_0, u, x0_7);
                    }
                    { const __m512i u = _mm512_and_si512(_mm512_srli_epi16(c1_3, 4), m4);
                      o1_0 = _mm512_dpbusd_epi32(o1_0, u, x0_7);
                    }
                    a0_0 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_add_epi32(e0_0, o0_0)), _mm512_mul_ps(d0, _mm512_set1_ps(dx[0 * nk + k])), a0_0);
                    a1_0 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_add_epi32(e1_0, o1_0)), _mm512_mul_ps(d1, _mm512_set1_ps(dx[0 * nk + k])), a1_0);
                }
        }
        storev(Y + 0 * N, (g + 0) * 16, r0, r1, a0_0);
        storev(Y + 0 * N, (g + 1) * 16, r0, r1, a1_0);
    }
}
