// Generated by kurn. Do not edit; edit the .kurn spec instead.
#include "kurn.h"
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <immintrin.h>
static inline float f16f(uint16_t h) { return _cvtsh_ss(h); }

static inline void q4k_decode(const uint8_t *s12, uint64_t *sc, uint64_t *mn) {
    uint32_t u[4];
    memcpy(u, s12, 12);
    u[3] = ((u[2] >> 4) & 0x0f0f0f0f) | (((u[1] >> 6) & 0x03030303) << 4);
    const uint32_t a = u[1] & 0x3f3f3f3f;
    u[1] = (u[2] & 0x0f0f0f0f) | (((u[0] >> 6) & 0x03030303) << 4);
    u[2] = a;
    u[0] &= 0x3f3f3f3f;
    *sc = (uint64_t)u[0] | ((uint64_t)u[1] << 32);
    *mn = (uint64_t)u[2] | ((uint64_t)u[3] << 32);
}
static inline __m256i bsum_pairs(const block_q8_K *x) {
    __m256i a = _mm256_cvtepi16_epi32(_mm_loadu_si128((const __m128i *)x->bsums));
    __m256i b = _mm256_cvtepi16_epi32(_mm_loadu_si128((const __m128i *)(x->bsums + 8)));
    return _mm256_permutevar8x32_epi32(_mm256_hadd_epi32(a, b), _mm256_setr_epi32(0, 1, 4, 5, 2, 3, 6, 7));
}

typedef struct { const int8_t *q; __m256i bsum; float d; } xsb;
static inline void row_sb(const block_q4_K *w, const xsb *xs, __m256 *acc, __m256 *macc) {
    const __m256i m4 = _mm256_set1_epi8(0x0F), z = _mm256_setzero_si256(), ones16 = _mm256_set1_epi16(1);
    (void)z; (void)ones16;
    uint64_t sc, mn;
    q4k_decode(w->scales, &sc, &mn);
    const __m256 s8 = _mm256_mul_ps(_mm256_cvtepi32_ps(_mm256_cvtepu8_epi32(_mm_cvtsi64_si128((long long)sc))), _mm256_set1_ps(xs->d * f16f(w->d)));
    { const __m256i q = _mm256_loadu_si256((const __m256i *)(w->qs + 0));
      *acc = _mm256_fmadd_ps(_mm256_cvtepi32_ps(_mm256_dpbusd_avx_epi32(z, _mm256_and_si256(q, m4), _mm256_loadu_si256((const __m256i *)(xs->q + 0)))), _mm256_permutevar8x32_ps(s8, _mm256_set1_epi32(0)), *acc);
      *acc = _mm256_fmadd_ps(_mm256_cvtepi32_ps(_mm256_dpbusd_avx_epi32(z, _mm256_and_si256(_mm256_srli_epi16(q, 4), m4), _mm256_loadu_si256((const __m256i *)(xs->q + 32)))), _mm256_permutevar8x32_ps(s8, _mm256_set1_epi32(1)), *acc); }
    { const __m256i q = _mm256_loadu_si256((const __m256i *)(w->qs + 32));
      *acc = _mm256_fmadd_ps(_mm256_cvtepi32_ps(_mm256_dpbusd_avx_epi32(z, _mm256_and_si256(q, m4), _mm256_loadu_si256((const __m256i *)(xs->q + 64)))), _mm256_permutevar8x32_ps(s8, _mm256_set1_epi32(2)), *acc);
      *acc = _mm256_fmadd_ps(_mm256_cvtepi32_ps(_mm256_dpbusd_avx_epi32(z, _mm256_and_si256(_mm256_srli_epi16(q, 4), m4), _mm256_loadu_si256((const __m256i *)(xs->q + 96)))), _mm256_permutevar8x32_ps(s8, _mm256_set1_epi32(3)), *acc); }
    { const __m256i q = _mm256_loadu_si256((const __m256i *)(w->qs + 64));
      *acc = _mm256_fmadd_ps(_mm256_cvtepi32_ps(_mm256_dpbusd_avx_epi32(z, _mm256_and_si256(q, m4), _mm256_loadu_si256((const __m256i *)(xs->q + 128)))), _mm256_permutevar8x32_ps(s8, _mm256_set1_epi32(4)), *acc);
      *acc = _mm256_fmadd_ps(_mm256_cvtepi32_ps(_mm256_dpbusd_avx_epi32(z, _mm256_and_si256(_mm256_srli_epi16(q, 4), m4), _mm256_loadu_si256((const __m256i *)(xs->q + 160)))), _mm256_permutevar8x32_ps(s8, _mm256_set1_epi32(5)), *acc); }
    { const __m256i q = _mm256_loadu_si256((const __m256i *)(w->qs + 96));
      *acc = _mm256_fmadd_ps(_mm256_cvtepi32_ps(_mm256_dpbusd_avx_epi32(z, _mm256_and_si256(q, m4), _mm256_loadu_si256((const __m256i *)(xs->q + 192)))), _mm256_permutevar8x32_ps(s8, _mm256_set1_epi32(6)), *acc);
      *acc = _mm256_fmadd_ps(_mm256_cvtepi32_ps(_mm256_dpbusd_avx_epi32(z, _mm256_and_si256(_mm256_srli_epi16(q, 4), m4), _mm256_loadu_si256((const __m256i *)(xs->q + 224)))), _mm256_permutevar8x32_ps(s8, _mm256_set1_epi32(7)), *acc); }
    *macc = _mm256_fmadd_ps(_mm256_cvtepi32_ps(_mm256_mullo_epi32(_mm256_cvtepu8_epi32(_mm_cvtsi64_si128((long long)mn)), xs->bsum)),
                            _mm256_set1_ps(xs->d * f16f(w->dmin)), *macc);
}
static inline float hsum8(__m256 v) {
    __m128 s = _mm_add_ps(_mm256_castps256_ps128(v), _mm256_extractf128_ps(v, 1));
    s = _mm_add_ps(s, _mm_movehl_ps(s, s));
    return _mm_cvtss_f32(_mm_add_ss(s, _mm_movehdup_ps(s)));
}
typedef block_q4_K block_T;
void kq4k_gemv(const void *W, const void *xv, float *y, int64_t K, int64_t r0, int64_t r1) {
    const int64_t nb = K / QK_K;
    const block_q4_K *w = (const block_q4_K *)W;
    const block_q8_K *x = (const block_q8_K *)xv;
    xsb xs[128];
    for (int64_t i = 0; i < nb; i++) { xs[i].q = x[i].qs; xs[i].bsum = bsum_pairs(x + i); xs[i].d = x[i].d; }
    int64_t r = r0;
    for (; r + 2 <= r1; r += 2) {
        const block_T *w0 = w + (r + 0) * nb;
        const block_T *w1 = w + (r + 1) * nb;
        __m256 a0 = _mm256_setzero_ps(), m0 = _mm256_setzero_ps();
        __m256 a1 = _mm256_setzero_ps(), m1 = _mm256_setzero_ps();
        for (int64_t p = 0; p < nb; p++) {
            
            row_sb(w0 + p, xs + p, &a0, &m0);
            row_sb(w1 + p, xs + p, &a1, &m1);
        }
        y[r + 0] = hsum8(_mm256_sub_ps(a0, m0));
        y[r + 1] = hsum8(_mm256_sub_ps(a1, m1));
    }
    for (; r < r1; r++) {
        const block_T *w0 = w + (r + 0) * nb;
        __m256 a0 = _mm256_setzero_ps(), m0 = _mm256_setzero_ps();
        for (int64_t p = 0; p < nb; p++) {
            
            row_sb(w0 + p, xs + p, &a0, &m0);
        }
        y[r + 0] = hsum8(_mm256_sub_ps(a0, m0));
    }
}
