// Generated by kurn. Do not edit; edit the .kurn spec instead.
#include "kurn.h"
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <immintrin.h>
static inline float f16f(uint16_t h) { return _cvtsh_ss(h); }

static inline void q4k_decode(const uint8_t *s12, uint64_t *sc, uint64_t *mn) {
    uint32_t u[4];
    memcpy(u, s12, 12);
    u[3] = ((u[2] >> 4) & 0x0f0f0f0f) | (((u[1] >> 6) & 0x03030303) << 4);
    const uint32_t a = u[1] & 0x3f3f3f3f;
    u[1] = (u[2] & 0x0f0f0f0f) | (((u[0] >> 6) & 0x03030303) << 4);
    u[2] = a;
    u[0] &= 0x3f3f3f3f;
    *sc = (uint64_t)u[0] | ((uint64_t)u[1] << 32);
    *mn = (uint64_t)u[2] | ((uint64_t)u[3] << 32);
}
static inline __m256i bsum_pairs(const block_q8_K *x) {
    __m256i a = _mm256_cvtepi16_epi32(_mm_loadu_si128((const __m128i *)x->bsums));
    __m256i b = _mm256_cvtepi16_epi32(_mm_loadu_si128((const __m128i *)(x->bsums + 8)));
    return _mm256_permutevar8x32_epi32(_mm256_hadd_epi32(a, b), _mm256_setr_epi32(0, 1, 4, 5, 2, 3, 6, 7));
}

typedef struct { __m512i y[4]; __m256i bsum; float d; const int8_t *q; const block_q8_K *x; } xsb;
static inline __m512i cat256(const int8_t *a, const int8_t *b) {
    return _mm512_inserti64x4(_mm512_castsi256_si512(_mm256_loadu_si256((const __m256i *)a)), _mm256_loadu_si256((const __m256i *)b), 1);
}
static inline void row_sb(const block_q4_K *w, const xsb *xs, __m512 *acc, __m256 *macc, float *mscal) {
    (void)macc; (void)mscal;
    uint64_t sc64, mn64; q4k_decode(w->scales, &sc64, &mn64); uint8_t sc[8], mn[8]; memcpy(sc, &sc64, 8); memcpy(mn, &mn64, 8);
    const __m512i m4 = _mm512_set1_epi8(0x0F), z = _mm512_setzero_si512();
    const float dd = xs->d * f16f(w->d);
    uint64_t scp; memcpy(&scp, sc, 8);
    const __m512 s8 = _mm512_castps256_ps512(_mm256_mul_ps(_mm256_cvtepi32_ps(_mm256_cvtepu8_epi32(_mm_cvtsi64_si128((long long)scp))), _mm256_set1_ps(dd)));
    { const __m512i q = _mm512_loadu_si512((const void *)(w->qs + 0));
      const __m512i dlo = _mm512_dpbusd_epi32(z, _mm512_and_si512(q, m4), xs->y[0]);
      const __m512i dhi = _mm512_dpbusd_epi32(z, _mm512_and_si512(_mm512_srli_epi16(q, 4), m4), xs->y[1]);
      *acc = _mm512_fmadd_ps(_mm512_cvtepi32_ps(dlo), _mm512_permutexvar_ps(_mm512_setr_epi32(0,0,0,0,0,0,0,0,2,2,2,2,2,2,2,2), s8), *acc);
      *acc = _mm512_fmadd_ps(_mm512_cvtepi32_ps(dhi), _mm512_permutexvar_ps(_mm512_setr_epi32(1,1,1,1,1,1,1,1,3,3,3,3,3,3,3,3), s8), *acc); }
    { const __m512i q = _mm512_loadu_si512((const void *)(w->qs + 64));
      const __m512i dlo = _mm512_dpbusd_epi32(z, _mm512_and_si512(q, m4), xs->y[2]);
      const __m512i dhi = _mm512_dpbusd_epi32(z, _mm512_and_si512(_mm512_srli_epi16(q, 4), m4), xs->y[3]);
      *acc = _mm512_fmadd_ps(_mm512_cvtepi32_ps(dlo), _mm512_permutexvar_ps(_mm512_setr_epi32(4,4,4,4,4,4,4,4,6,6,6,6,6,6,6,6), s8), *acc);
      *acc = _mm512_fmadd_ps(_mm512_cvtepi32_ps(dhi), _mm512_permutexvar_ps(_mm512_setr_epi32(5,5,5,5,5,5,5,5,7,7,7,7,7,7,7,7), s8), *acc); }
    uint64_t mnp; memcpy(&mnp, mn, 8);
    *macc = _mm256_fmadd_ps(_mm256_cvtepi32_ps(_mm256_mullo_epi32(_mm256_cvtepu8_epi32(_mm_cvtsi64_si128((long long)mnp)), xs->bsum)), _mm256_set1_ps(xs->d * f16f(w->dmin)), *macc);
}
typedef block_q4_K block_T;
void kq4k_gemv(const void *W, const void *xv, float *y, int64_t K, int64_t r0, int64_t r1) {
    const int64_t nb = K / QK_K;
    const block_q4_K *w = (const block_q4_K *)W;
    const block_q8_K *x = (const block_q8_K *)xv;
    xsb xs[128];
    for (int64_t i = 0; i < nb; i++) {
        const int8_t *q = x[i].qs;
        xs[i].y[0] = cat256(q, q + 64); xs[i].y[1] = cat256(q + 32, q + 96);
        xs[i].y[2] = cat256(q + 128, q + 192); xs[i].y[3] = cat256(q + 160, q + 224);
        xs[i].bsum = bsum_pairs(x + i); xs[i].d = x[i].d; xs[i].q = x[i].qs; xs[i].x = x + i;
    }
    int64_t r = r0;
    for (; r + 4 <= r1; r += 4) {
        const block_T *w0 = w + (r + 0) * nb;
        const block_T *w1 = w + (r + 1) * nb;
        const block_T *w2 = w + (r + 2) * nb;
        const block_T *w3 = w + (r + 3) * nb;
        __m512 a0 = _mm512_setzero_ps(); __m256 m0 = _mm256_setzero_ps(); float s0 = 0;
        __m512 a1 = _mm512_setzero_ps(); __m256 m1 = _mm256_setzero_ps(); float s1 = 0;
        __m512 a2 = _mm512_setzero_ps(); __m256 m2 = _mm256_setzero_ps(); float s2 = 0;
        __m512 a3 = _mm512_setzero_ps(); __m256 m3 = _mm256_setzero_ps(); float s3 = 0;
        for (int64_t p = 0; p < nb; p++) {
            
            _mm_prefetch((const char *)(w0 + p + 4), _MM_HINT_T0);
            _mm_prefetch((const char *)(w1 + p + 4), _MM_HINT_T0);
            _mm_prefetch((const char *)(w2 + p + 4), _MM_HINT_T0);
            _mm_prefetch((const char *)(w3 + p + 4), _MM_HINT_T0);
            row_sb(w0 + p, xs + p, &a0, &m0, &s0);
            row_sb(w1 + p, xs + p, &a1, &m1, &s1);
            row_sb(w2 + p, xs + p, &a2, &m2, &s2);
            row_sb(w3 + p, xs + p, &a3, &m3, &s3);
        }
        y[r + 0] = _mm512_reduce_add_ps(a0) - _mm512_reduce_add_ps(_mm512_insertf32x8(_mm512_setzero_ps(), m0, 0)) - s0;
        y[r + 1] = _mm512_reduce_add_ps(a1) - _mm512_reduce_add_ps(_mm512_insertf32x8(_mm512_setzero_ps(), m1, 0)) - s1;
        y[r + 2] = _mm512_reduce_add_ps(a2) - _mm512_reduce_add_ps(_mm512_insertf32x8(_mm512_setzero_ps(), m2, 0)) - s2;
        y[r + 3] = _mm512_reduce_add_ps(a3) - _mm512_reduce_add_ps(_mm512_insertf32x8(_mm512_setzero_ps(), m3, 0)) - s3;
    }
    for (; r < r1; r++) {
        const block_T *w0 = w + (r + 0) * nb;
        __m512 a0 = _mm512_setzero_ps(); __m256 m0 = _mm256_setzero_ps(); float s0 = 0;
        for (int64_t p = 0; p < nb; p++) {
            
            _mm_prefetch((const char *)(w0 + p + 4), _MM_HINT_T0);
            row_sb(w0 + p, xs + p, &a0, &m0, &s0);
        }
        y[r + 0] = _mm512_reduce_add_ps(a0) - _mm512_reduce_add_ps(_mm512_insertf32x8(_mm512_setzero_ps(), m0, 0)) - s0;
    }
}
