// Generated by kurn (generic recipe lowering). Do not edit; edit the .kurn spec instead.
#include "kurn.h"
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <immintrin.h>
typedef struct { uint16_t d; uint16_t dmin; uint8_t scales[12]; uint8_t qs[128]; } nblock;
typedef struct { int64_t nrec_k, ngroups; uint8_t *buf; } packed_t;
#define REC_BYTES 2368
#define HDR_BYTES 320
#define KG_BYTES 256
#define CODE_BYTES 256

void *kq4k_vfy_prepare(const void *W, int64_t K, int64_t N) {
    const nblock *w = (const nblock *)W;
    const int64_t nb = K / 256;
    packed_t *pk = malloc(sizeof *pk);
    pk->nrec_k = K / 256; pk->ngroups = (N + 15) / 16 + 0;
    const size_t bytes = (size_t)REC_BYTES * pk->nrec_k * pk->ngroups;
    pk->buf = aligned_alloc(64, (bytes + 63) & ~(size_t)63);
    memset(pk->buf, 0, bytes);
    for (int64_t g = 0; g < pk->ngroups; g++)
        for (int64_t p = 0; p < pk->nrec_k; p++) {
            uint8_t *hp = pk->buf + ((size_t)g * pk->nrec_k + p) * REC_BYTES;
            for (int row = 0; row < 16; row++) {
                const int64_t n = g * 16 + row;
                if (n >= N) continue;  /* padding rows stay zero: d = 0 */
                const int64_t v0 = p * 256;
                const nblock *b = w + n * nb + v0 / 256;
                
                memcpy(hp + 2 * row, &b->d, 2); memcpy(hp + 2 * 16 + 2 * row, &b->dmin, 2);
                { const uint8_t *q = b->scales;
                  for (int s = 0; s < 8; s++) {
                      hp[4 * 16 + s * 16 + row] = s < 4 ? q[s] & 63 : (q[s + 4] & 0xF) | ((q[s - 4] >> 6) << 4);
                      hp[12 * 16 + s * 16 + row] = s < 4 ? q[s + 4] & 63 : (q[s + 4] >> 4) | ((q[s] >> 6) << 4);
                  } }
                for (int kg = 0; kg < 8; kg++) {
                    uint8_t *rec_codes = hp + HDR_BYTES + kg * KG_BYTES;
                    int32_t wsum = 0;
                    for (int kk = 0; kk < 8; kk++)
                        for (int j = 0; j < 4; j++) {
                            const int v = (int)((v0 + kg * 32 + kk * 4 + j) % 256);
                            const int q = ((b->qs[(v / 64) * 32 + v % 32] >> (4 * ((v / 32) & 1))) & 15);
                            (void)wsum;
                            
                            const uint8_t u = q;
                            rec_codes[(kk / 2) * 64 + (row) * 4 + j] |= (uint8_t)(u << (4 * (kk & 1)));
                        }
                    
                }
            }
        }
    return pk;
}

typedef struct { float d; int8_t qs[256]; int16_t bsums[16]; } xblock;

static inline void storev(float *y, int64_t row0, int64_t r0, int64_t r1, __m512 v) {
    if (row0 >= r0 && row0 + 16 <= r1) { _mm512_storeu_ps(y + row0, v); return; }
    uint32_t m = 0xFFFF;
    if (row0 < r0) m &= 0xFFFFu << (r0 - row0);
    if (row0 + 16 > r1) m &= (1u << (r1 > row0 ? r1 - row0 : 0)) - 1;
    _mm512_mask_storeu_ps(y + row0, (__mmask16)m, v);
}

void kq4k_vfy_packed(const void *pv, const void *X, float *Y, int64_t K, int64_t N, int64_t M, int64_t r0, int64_t r1) {
    const packed_t *pk = (const packed_t *)pv;
    const int64_t nk = K / 32, nbx = K / 256;
    if (M > 2) abort();
    int32_t xw[2 * 1024 * 8], sx[2 * 1024];
    float dx[2 * 1024];
    (void)sx; (void)nbx;
    for (int64_t m = 0; m < 2; m++) {
    const xblock *xb = (const xblock *)X + (m < M ? m : 0) * nbx;  /* columns beyond M repeat column 0 */
    for (int64_t k = 0; k < nk; k++) {
        const xblock *b = xb + k / 8;
        memcpy(xw + (m * nk + k) * 8, b->qs + (k % 8) * 32, 32);
        sx[m * nk + k] = b->bsums[2 * (k % 8)] + b->bsums[2 * (k % 8) + 1];
        dx[m * nk + k] = b->d;
    }
    }
    const __m512i m4 = _mm512_set1_epi8((char)(0x0F)), m3 = _mm512_set1_epi8((char)(0x03));
    (void)m4; (void)m3;
    
    const int64_t g0 = r0 / 16, g1 = (r1 + 15) / 16;
    int64_t g = g0;
    for (; g < g1; g += 1) {
        __m512 a0_0 = _mm512_setzero_ps(); __m512 a0_1 = _mm512_setzero_ps();
        for (int64_t p = 0; p < pk->nrec_k; p++) {
                const uint8_t *rec0 = pk->buf + ((size_t)(g + 0) * pk->nrec_k + p) * REC_BYTES;
                const __m512 d0 = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)(rec0))), dm0 = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)(rec0 + 32)));
                __m512i ia0_0 = _mm512_setzero_si512(); __m512i ma0_0 = _mm512_setzero_si512();
                __m512i ia0_1 = _mm512_setzero_si512(); __m512i ma0_1 = _mm512_setzero_si512();
                for (int kg = 0; kg < 8; kg++) {
                    const int64_t k = p * 8 + kg;
                    const __m512i c0_0 = _mm512_loadu_si512((const void *)(rec0 + HDR_BYTES + kg * KG_BYTES + 0));
                    const __m512i c0_1 = _mm512_loadu_si512((const void *)(rec0 + HDR_BYTES + kg * KG_BYTES + 64));
                    const __m512i c0_2 = _mm512_loadu_si512((const void *)(rec0 + HDR_BYTES + kg * KG_BYTES + 128));
                    const __m512i c0_3 = _mm512_loadu_si512((const void *)(rec0 + HDR_BYTES + kg * KG_BYTES + 192));
                    __m512i e0_0 = _mm512_setzero_si512(), o0_0 = _mm512_setzero_si512();
                    __m512i e0_1 = _mm512_setzero_si512(), o0_1 = _mm512_setzero_si512();
                    const __m512i x0_0 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 0]);
                    const __m512i x1_0 = _mm512_set1_epi32(xw[(1 * nk + k) * 8 + 0]);
                    { const __m512i u = _mm512_and_si512(c0_0, m4);
                      e0_0 = _mm512_dpbusd_epi32(e0_0, u, x0_0);
                      e0_1 = _mm512_dpbusd_epi32(e0_1, u, x1_0);
                    }
                    const __m512i x0_1 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 1]);
                    const __m512i x1_1 = _mm512_set1_epi32(xw[(1 * nk + k) * 8 + 1]);
                    { const __m512i u = _mm512_and_si512(_mm512_srli_epi16(c0_0, 4), m4);
                      o0_0 = _mm512_dpbusd_epi32(o0_0, u, x0_1);
                      o0_1 = _mm512_dpbusd_epi32(o0_1, u, x1_1);
                    }
                    const __m512i x0_2 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 2]);
                    const __m512i x1_2 = _mm512_set1_epi32(xw[(1 * nk + k) * 8 + 2]);
                    { const __m512i u = _mm512_and_si512(c0_1, m4);
                      e0_0 = _mm512_dpbusd_epi32(e0_0, u, x0_2);
                      e0_1 = _mm512_dpbusd_epi32(e0_1, u, x1_2);
                    }
                    const __m512i x0_3 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 3]);
                    const __m512i x1_3 = _mm512_set1_epi32(xw[(1 * nk + k) * 8 + 3]);
                    { const __m512i u = _mm512_and_si512(_mm512_srli_epi16(c0_1, 4), m4);
                      o0_0 = _mm512_dpbusd_epi32(o0_0, u, x0_3);
                      o0_1 = _mm512_dpbusd_epi32(o0_1, u, x1_3);
                    }
                    const __m512i x0_4 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 4]);
                    const __m512i x1_4 = _mm512_set1_epi32(xw[(1 * nk + k) * 8 + 4]);
                    { const __m512i u = _mm512_and_si512(c0_2, m4);
                      e0_0 = _mm512_dpbusd_epi32(e0_0, u, x0_4);
                      e0_1 = _mm512_dpbusd_epi32(e0_1, u, x1_4);
                    }
                    const __m512i x0_5 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 5]);
                    const __m512i x1_5 = _mm512_set1_epi32(xw[(1 * nk + k) * 8 + 5]);
                    { const __m512i u = _mm512_and_si512(_mm512_srli_epi16(c0_2, 4), m4);
                      o0_0 = _mm512_dpbusd_epi32(o0_0, u, x0_5);
                      o0_1 = _mm512_dpbusd_epi32(o0_1, u, x1_5);
                    }
                    const __m512i x0_6 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 6]);
                    const __m512i x1_6 = _mm512_set1_epi32(xw[(1 * nk + k) * 8 + 6]);
                    { const __m512i u = _mm512_and_si512(c0_3, m4);
                      e0_0 = _mm512_dpbusd_epi32(e0_0, u, x0_6);
                      e0_1 = _mm512_dpbusd_epi32(e0_1, u, x1_6);
                    }
                    const __m512i x0_7 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 7]);
                    const __m512i x1_7 = _mm512_set1_epi32(xw[(1 * nk + k) * 8 + 7]);
                    { const __m512i u = _mm512_and_si512(_mm512_srli_epi16(c0_3, 4), m4);
                      o0_0 = _mm512_dpbusd_epi32(o0_0, u, x0_7);
                      o0_1 = _mm512_dpbusd_epi32(o0_1, u, x1_7);
                    }
                    ia0_0 = _mm512_add_epi32(ia0_0, _mm512_mullo_epi32(_mm512_add_epi32(e0_0, o0_0), _mm512_cvtepu8_epi32(_mm_loadu_si128((const __m128i *)(rec0 + 64 + kg * 16)))));
                    ma0_0 = _mm512_add_epi32(ma0_0, _mm512_mullo_epi32(_mm512_cvtepu8_epi32(_mm_loadu_si128((const __m128i *)(rec0 + 192 + kg * 16))), _mm512_set1_epi32(sx[0 * nk + k])));
                    ia0_1 = _mm512_add_epi32(ia0_1, _mm512_mullo_epi32(_mm512_add_epi32(e0_1, o0_1), _mm512_cvtepu8_epi32(_mm_loadu_si128((const __m128i *)(rec0 + 64 + kg * 16)))));
                    ma0_1 = _mm512_add_epi32(ma0_1, _mm512_mullo_epi32(_mm512_cvtepu8_epi32(_mm_loadu_si128((const __m128i *)(rec0 + 192 + kg * 16))), _mm512_set1_epi32(sx[1 * nk + k])));
                }
                a0_0 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(ia0_0), _mm512_mul_ps(d0, _mm512_set1_ps(dx[0 * nk + p * 8])), a0_0);
                a0_0 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(ma0_0), _mm512_mul_ps(dm0, _mm512_set1_ps(-dx[0 * nk + p * 8])), a0_0);
                a0_1 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(ia0_1), _mm512_mul_ps(d0, _mm512_set1_ps(dx[1 * nk + p * 8])), a0_1);
                a0_1 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(ma0_1), _mm512_mul_ps(dm0, _mm512_set1_ps(-dx[1 * nk + p * 8])), a0_1);
        }
        storev(Y + 0 * N, (g + 0) * 16, r0, r1, a0_0);
        if (1 < M) storev(Y + 1 * N, (g + 0) * 16, r0, r1, a0_1);
    }
}
void kq4k_vfy(const void *W, const void *X, float *Y, int64_t K, int64_t N, int64_t M, int64_t n0, int64_t n1) {
    (void)W; (void)X; (void)Y; (void)K; (void)N; (void)M; (void)n0; (void)n1; abort();
}
