// Generated by kurn. Do not edit; edit the .kurn spec instead.
#include "kurn.h"
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <immintrin.h>
static inline __m512i load2(const block_q8_0 *b) {
    return _mm512_inserti64x4(_mm512_castsi256_si512(_mm256_loadu_si256((const __m256i *)b[0].qs)),
                              _mm256_loadu_si256((const __m256i *)b[1].qs), 1);
}
static inline __m512 scale2(const block_q8_0 *b) {
    const __m512i idx = _mm512_set_epi32(1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0);
    return _mm512_permutexvar_ps(idx, _mm512_castps128_ps512(_mm_cvtph_ps(_mm_cvtsi32_si128((int)b[0].d | ((int)b[1].d << 16)))));
}
typedef block_q8_0 block_T;
void kq8_gemv(const void *W, const void *xv, float *y, int64_t K, int64_t r0, int64_t r1) {
    const int64_t nb = K / QK8_0, np = nb / 2;
    const block_q8_0 *w = (const block_q8_0 *)W, *x = (const block_q8_0 *)xv;
    const __m512i flip = _mm512_set1_epi8((char)0x80), zero = _mm512_setzero_si512();
    (void)flip; (void)zero;
    __m512i xq[512], xb[512];
    __m512 xd[512];
    for (int64_t p = 0; p < np; p++) {
        xq[p] = load2(x + 2 * p);
        xb[p] = _mm512_sub_epi32(zero, _mm512_slli_epi32(_mm512_dpbusd_epi32(zero, _mm512_set1_epi8(1), xq[p]), 7));
        xd[p] = scale2(x + 2 * p);
    }
    int64_t r = r0;
    for (; r + 4 <= r1; r += 4) {
        const block_T *w0 = w + (r + 0) * nb;
        const block_T *w1 = w + (r + 1) * nb;
        const block_T *w2 = w + (r + 2) * nb;
        const block_T *w3 = w + (r + 3) * nb;
        __m512 a0 = _mm512_setzero_ps();
        __m512 a1 = _mm512_setzero_ps();
        __m512 a2 = _mm512_setzero_ps();
        __m512 a3 = _mm512_setzero_ps();
        for (int64_t p = 0; p < np; p++) {
            
            _mm_prefetch((const char *)(w0 + 2 * (p + 8)), _MM_HINT_T0);
            _mm_prefetch((const char *)(w1 + 2 * (p + 8)), _MM_HINT_T0);
            _mm_prefetch((const char *)(w2 + 2 * (p + 8)), _MM_HINT_T0);
            _mm_prefetch((const char *)(w3 + 2 * (p + 8)), _MM_HINT_T0);
            a0 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_dpbusd_epi32(xb[p], _mm512_xor_si512(load2(w0 + 2 * p), flip), xq[p])), _mm512_mul_ps(scale2(w0 + 2 * p), xd[p]), a0);
            a1 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_dpbusd_epi32(xb[p], _mm512_xor_si512(load2(w1 + 2 * p), flip), xq[p])), _mm512_mul_ps(scale2(w1 + 2 * p), xd[p]), a1);
            a2 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_dpbusd_epi32(xb[p], _mm512_xor_si512(load2(w2 + 2 * p), flip), xq[p])), _mm512_mul_ps(scale2(w2 + 2 * p), xd[p]), a2);
            a3 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_dpbusd_epi32(xb[p], _mm512_xor_si512(load2(w3 + 2 * p), flip), xq[p])), _mm512_mul_ps(scale2(w3 + 2 * p), xd[p]), a3);
        }
        y[r + 0] = _mm512_reduce_add_ps(a0);
        y[r + 1] = _mm512_reduce_add_ps(a1);
        y[r + 2] = _mm512_reduce_add_ps(a2);
        y[r + 3] = _mm512_reduce_add_ps(a3);
    }
    for (; r < r1; r++) {
        const block_T *w0 = w + (r + 0) * nb;
        __m512 a0 = _mm512_setzero_ps();
        for (int64_t p = 0; p < np; p++) {
            
            _mm_prefetch((const char *)(w0 + 2 * (p + 8)), _MM_HINT_T0);
            a0 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_dpbusd_epi32(xb[p], _mm512_xor_si512(load2(w0 + 2 * p), flip), xq[p])), _mm512_mul_ps(scale2(w0 + 2 * p), xd[p]), a0);
        }
        y[r + 0] = _mm512_reduce_add_ps(a0);
    }
}
