// Generated by kurn. Do not edit; edit the .kurn spec instead.
#include "kurn.h"
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

static inline float f16f(uint16_t h) {
    uint32_t s = (uint32_t)(h & 0x8000) << 16, e = (h >> 10) & 0x1f, m = h & 0x3ff, b;
    if (e == 0) { if (!m) b = s; else { e = 113; while (!(m & 0x400)) { m <<= 1; e--; } b = s | (e << 23) | ((m & 0x3ff) << 13); } }
    else if (e == 31) b = s | 0x7f800000 | (m << 13);
    else b = s | ((e + 112) << 23) | (m << 13);
    float f; memcpy(&f, &b, 4); return f;
}

void kq8_gemv(const void *W, const void *xv, float *y, int64_t K, int64_t r0, int64_t r1) {
    const int64_t nb = K / QK8_0;
    const block_q8_0 *x = (const block_q8_0 *)xv;
    for (int64_t r = r0; r < r1; r++) {
        const block_q8_0 *w = (const block_q8_0 *)W + r * nb;
        float acc = 0;
        for (int64_t b = 0; b < nb; b++) {
            int32_t s = 0;
            for (int l = 0; l < QK8_0; l++) s += (int32_t)w[b].qs[l] * x[b].qs[l];
            acc += f16f(w[b].d) * f16f(x[b].d) * (float)s;
        }
        y[r] = acc;
    }
}
