// Generated by kurn. Do not edit; edit the .kurn spec instead.
#include "kurn.h"
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <arm_neon.h>
static inline float f16f(uint16_t h) { __fp16 v; memcpy(&v, &h, 2); return (float)v; }

typedef block_q8_0 block_T;
void kq8_gemv(const void *W, const void *xv, float *y, int64_t K, int64_t r0, int64_t r1) {
    const int64_t nb = K / QK8_0;
    const block_q8_0 *w = (const block_q8_0 *)W, *x = (const block_q8_0 *)xv;
    float xd[1024];
    for (int64_t p = 0; p < nb; p++) xd[p] = f16f(x[p].d);
    int64_t r = r0;
    for (; r + 4 <= r1; r += 4) {
        const block_T *w0 = w + (r + 0) * nb;
        const block_T *w1 = w + (r + 1) * nb;
        const block_T *w2 = w + (r + 2) * nb;
        const block_T *w3 = w + (r + 3) * nb;
        float32x4_t a0 = vdupq_n_f32(0);
        float32x4_t a1 = vdupq_n_f32(0);
        float32x4_t a2 = vdupq_n_f32(0);
        float32x4_t a3 = vdupq_n_f32(0);
        for (int64_t p = 0; p < nb; p++) {
            const int8x16_t x0 = vld1q_s8(x[p].qs), x1 = vld1q_s8(x[p].qs + 16);
            __builtin_prefetch(w0 + p + 8);
            __builtin_prefetch(w1 + p + 8);
            __builtin_prefetch(w2 + p + 8);
            __builtin_prefetch(w3 + p + 8);
            a0 = vfmaq_n_f32(a0, vcvtq_f32_s32(vdotq_s32(vdotq_s32(vdupq_n_s32(0), vld1q_s8(w0[p].qs), x0), vld1q_s8(w0[p].qs + 16), x1)), f16f(w0[p].d) * xd[p]);
            a1 = vfmaq_n_f32(a1, vcvtq_f32_s32(vdotq_s32(vdotq_s32(vdupq_n_s32(0), vld1q_s8(w1[p].qs), x0), vld1q_s8(w1[p].qs + 16), x1)), f16f(w1[p].d) * xd[p]);
            a2 = vfmaq_n_f32(a2, vcvtq_f32_s32(vdotq_s32(vdotq_s32(vdupq_n_s32(0), vld1q_s8(w2[p].qs), x0), vld1q_s8(w2[p].qs + 16), x1)), f16f(w2[p].d) * xd[p]);
            a3 = vfmaq_n_f32(a3, vcvtq_f32_s32(vdotq_s32(vdotq_s32(vdupq_n_s32(0), vld1q_s8(w3[p].qs), x0), vld1q_s8(w3[p].qs + 16), x1)), f16f(w3[p].d) * xd[p]);
        }
        y[r + 0] = vaddvq_f32(a0);
        y[r + 1] = vaddvq_f32(a1);
        y[r + 2] = vaddvq_f32(a2);
        y[r + 3] = vaddvq_f32(a3);
    }
    for (; r < r1; r++) {
        const block_T *w0 = w + (r + 0) * nb;
        float32x4_t a0 = vdupq_n_f32(0);
        for (int64_t p = 0; p < nb; p++) {
            const int8x16_t x0 = vld1q_s8(x[p].qs), x1 = vld1q_s8(x[p].qs + 16);
            __builtin_prefetch(w0 + p + 8);
            a0 = vfmaq_n_f32(a0, vcvtq_f32_s32(vdotq_s32(vdotq_s32(vdupq_n_s32(0), vld1q_s8(w0[p].qs), x0), vld1q_s8(w0[p].qs + 16), x1)), f16f(w0[p].d) * xd[p]);
        }
        y[r + 0] = vaddvq_f32(a0);
    }
}
