// Generated by kurn. Do not edit; edit the .kurn spec instead.
#include "kurn.h"
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <immintrin.h>
static inline float f16f(uint16_t h) { return _cvtsh_ss(h); }

static inline float hsum8(__m256 v) {
    __m128 s = _mm_add_ps(_mm256_castps256_ps128(v), _mm256_extractf128_ps(v, 1));
    s = _mm_add_ps(s, _mm_movehl_ps(s, s));
    return _mm_cvtss_f32(_mm_add_ss(s, _mm_movehdup_ps(s)));
}
typedef block_q8_0 block_T;
void kq8_gemv(const void *W, const void *xv, float *y, int64_t K, int64_t r0, int64_t r1) {
    const int64_t nb = K / QK8_0;
    const block_q8_0 *w = (const block_q8_0 *)W, *x = (const block_q8_0 *)xv;
    const __m256i flip = _mm256_set1_epi8((char)0x80), zero = _mm256_setzero_si256(), ones16 = _mm256_set1_epi16(1);
    (void)flip; (void)zero; (void)ones16;
    int64_t r = r0;
    for (; r + 4 <= r1; r += 4) {
        const block_T *w0 = w + (r + 0) * nb;
        const block_T *w1 = w + (r + 1) * nb;
        const block_T *w2 = w + (r + 2) * nb;
        const block_T *w3 = w + (r + 3) * nb;
        __m256 a0 = _mm256_setzero_ps();
        __m256 a1 = _mm256_setzero_ps();
        __m256 a2 = _mm256_setzero_ps();
        __m256 a3 = _mm256_setzero_ps();
        for (int64_t p = 0; p < nb; p++) {
            const __m256i xx = _mm256_loadu_si256((const __m256i *)x[p].qs); const float dx = f16f(x[p].d);
            { const __m256i wv = _mm256_loadu_si256((const __m256i *)w0[p].qs); a0 = _mm256_fmadd_ps(_mm256_cvtepi32_ps(_mm256_madd_epi16(_mm256_maddubs_epi16(_mm256_sign_epi8(wv, wv), _mm256_sign_epi8(xx, wv)), ones16)), _mm256_set1_ps(f16f(w0[p].d) * dx), a0); }
            { const __m256i wv = _mm256_loadu_si256((const __m256i *)w1[p].qs); a1 = _mm256_fmadd_ps(_mm256_cvtepi32_ps(_mm256_madd_epi16(_mm256_maddubs_epi16(_mm256_sign_epi8(wv, wv), _mm256_sign_epi8(xx, wv)), ones16)), _mm256_set1_ps(f16f(w1[p].d) * dx), a1); }
            { const __m256i wv = _mm256_loadu_si256((const __m256i *)w2[p].qs); a2 = _mm256_fmadd_ps(_mm256_cvtepi32_ps(_mm256_madd_epi16(_mm256_maddubs_epi16(_mm256_sign_epi8(wv, wv), _mm256_sign_epi8(xx, wv)), ones16)), _mm256_set1_ps(f16f(w2[p].d) * dx), a2); }
            { const __m256i wv = _mm256_loadu_si256((const __m256i *)w3[p].qs); a3 = _mm256_fmadd_ps(_mm256_cvtepi32_ps(_mm256_madd_epi16(_mm256_maddubs_epi16(_mm256_sign_epi8(wv, wv), _mm256_sign_epi8(xx, wv)), ones16)), _mm256_set1_ps(f16f(w3[p].d) * dx), a3); }
        }
        y[r + 0] = hsum8(a0);
        y[r + 1] = hsum8(a1);
        y[r + 2] = hsum8(a2);
        y[r + 3] = hsum8(a3);
    }
    for (; r < r1; r++) {
        const block_T *w0 = w + (r + 0) * nb;
        __m256 a0 = _mm256_setzero_ps();
        for (int64_t p = 0; p < nb; p++) {
            const __m256i xx = _mm256_loadu_si256((const __m256i *)x[p].qs); const float dx = f16f(x[p].d);
            { const __m256i wv = _mm256_loadu_si256((const __m256i *)w0[p].qs); a0 = _mm256_fmadd_ps(_mm256_cvtepi32_ps(_mm256_madd_epi16(_mm256_maddubs_epi16(_mm256_sign_epi8(wv, wv), _mm256_sign_epi8(xx, wv)), ones16)), _mm256_set1_ps(f16f(w0[p].d) * dx), a0); }
        }
        y[r + 0] = hsum8(a0);
    }
}
