// Generated by kurn. Do not edit; edit the .kurn spec instead.
#include "kurn.h"
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <immintrin.h>
static inline __m512i load2(const block_q8_0 *b) {
    return _mm512_inserti64x4(_mm512_castsi256_si512(_mm256_loadu_si256((const __m256i *)b[0].qs)),
                              _mm256_loadu_si256((const __m256i *)b[1].qs), 1);
}
static inline __m512 scale2(const block_q8_0 *b) {
    const __m512i idx = _mm512_set_epi32(1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0);
    return _mm512_permutexvar_ps(idx, _mm512_castps128_ps512(_mm_cvtph_ps(_mm_cvtsi32_si128((int)b[0].d | ((int)b[1].d << 16)))));
}
typedef block_q8_0 block_T;
void kq8_gemv(const void *W, const void *xv, float *y, int64_t K, int64_t r0, int64_t r1) {
    const int64_t nb = K / QK8_0, np = nb / 2;
    const block_q8_0 *w = (const block_q8_0 *)W, *x = (const block_q8_0 *)xv;
    const __m512i flip = _mm512_set1_epi8((char)0x80), zero = _mm512_setzero_si512();
    (void)flip; (void)zero;
    int64_t r = r0;
    for (; r + 2 <= r1; r += 2) {
        const block_T *w0 = w + (r + 0) * nb;
        const block_T *w1 = w + (r + 1) * nb;
        __m512 a0 = _mm512_setzero_ps();
        __m512 a1 = _mm512_setzero_ps();
        for (int64_t p = 0; p < np; p++) {
            const __m512i xx = load2(x + 2 * p); const __m512 dx = scale2(x + 2 * p);
            { const __m512i wv = load2(w0 + 2 * p); const __mmask64 m = _mm512_movepi8_mask(wv); a0 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_dpbusd_epi32(zero, _mm512_abs_epi8(wv), _mm512_mask_sub_epi8(xx, m, zero, xx))), _mm512_mul_ps(scale2(w0 + 2 * p), dx), a0); }
            { const __m512i wv = load2(w1 + 2 * p); const __mmask64 m = _mm512_movepi8_mask(wv); a1 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_dpbusd_epi32(zero, _mm512_abs_epi8(wv), _mm512_mask_sub_epi8(xx, m, zero, xx))), _mm512_mul_ps(scale2(w1 + 2 * p), dx), a1); }
        }
        y[r + 0] = _mm512_reduce_add_ps(a0);
        y[r + 1] = _mm512_reduce_add_ps(a1);
    }
    for (; r < r1; r++) {
        const block_T *w0 = w + (r + 0) * nb;
        __m512 a0 = _mm512_setzero_ps();
        for (int64_t p = 0; p < np; p++) {
            const __m512i xx = load2(x + 2 * p); const __m512 dx = scale2(x + 2 * p);
            { const __m512i wv = load2(w0 + 2 * p); const __mmask64 m = _mm512_movepi8_mask(wv); a0 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_dpbusd_epi32(zero, _mm512_abs_epi8(wv), _mm512_mask_sub_epi8(xx, m, zero, xx))), _mm512_mul_ps(scale2(w0 + 2 * p), dx), a0); }
        }
        y[r + 0] = _mm512_reduce_add_ps(a0);
    }
}
