// Generated by kurn (generic recipe lowering, scalar reference). Do not edit.
#include "kurn.h"
#include <stdint.h>
#include <string.h>
static inline float f16f(uint16_t h) {
    uint32_t s = (uint32_t)(h & 0x8000) << 16, e = (h >> 10) & 0x1f, m = h & 0x3ff, bb;
    if (e == 0) { if (!m) bb = s; else { e = 113; while (!(m & 0x400)) { m <<= 1; e--; } bb = s | (e << 23) | ((m & 0x3ff) << 13); } }
    else if (e == 31) bb = s | 0x7f800000 | (m << 13);
    else bb = s | ((e + 112) << 23) | (m << 13);
    float f; memcpy(&f, &bb, 4); return f;
}
typedef struct { uint8_t qs[48]; uint8_t qh[4]; uint16_t d; } nblock;
typedef struct { float d; int8_t qs[256]; int16_t bsums[16]; } xblock;

void ktq10_gemv(const void *W, const void *X, float *Y, int64_t K, int64_t r0, int64_t r1) {
    const xblock *x = (const xblock *)X;
    for (int64_t n = r0; n < r1; n++) {
        const nblock *wr = (const nblock *)W + n * (K / 256);
        float acc = 0;
        for (int64_t k = 0; k < K / 32; k++) {
            const nblock *b = wr + (k * 32) / 256;
            int32_t t = 0;
            for (int l = 0; l < 32; l++) {
                const int64_t vv = k * 32 + l;
                const int v = (int)(vv % 256);
                const int q = ((((unsigned)(uint8_t)((unsigned)(v < 160 ? b->qs[v % 32] : v < 240 ? b->qs[32 + (v - 160) % 16] : b->qh[(v - 240) % 4]) * (unsigned)"\001\003\011\033\121"[v < 160 ? v / 32 : v < 240 ? (v - 160) / 16 : (v - 240) / 4])) * 3u) >> 8);
                t += ((q - 1)) * x[vv / 256].qs[vv % 256];
            }
            acc += f16f(b->d) * x[k / 8].d * (float)t;
        }
        Y[n] = acc;
    }
}
