// Generated by kurn (lowbit: lut tern g3 perm). Do not edit; edit the .kurn spec instead.
#include "kurn.h"
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <immintrin.h>
static inline __m512i lo16(__m512i v) { return _mm512_cvtepi16_epi32(_mm512_castsi512_si256(v)); }
static inline __m512i hi16(__m512i v) { return _mm512_cvtepi16_epi32(_mm512_extracti64x4_epi64(v, 1)); }
static inline __m512 fma16(__m512i s, __m512 d, __m512 dx, __m512 acc) {
    return _mm512_fmadd_ps(_mm512_cvtepi32_ps(s), _mm512_mul_ps(d, dx), acc);
}
/* lut=tern3 (perm): 102 chunks per 256-value unit, 32-entry int16 tables, 26 index words per row per unit (1.6875 bpw incl. scales) */

typedef struct { uint8_t qs[48]; uint8_t qh[4]; uint16_t d; } nblock;
typedef struct { int64_t nrec_k, ngroups; uint8_t *buf; } packed_t;
#define REC_BYTES 1728
#define HDR_BYTES 64
#define UNIT_BYTES 1664
#define WVEC(rec, kg, w) _mm512_loadu_si512((const void *)((rec) + HDR_BYTES + (kg) * UNIT_BYTES + 64 * (w)))
typedef struct { float d; int8_t qs[256]; int16_t bsums[16]; } xblock;

static inline void storev(float *y, int64_t row0, int64_t r0, int64_t r1, __m512 v) {
    if (row0 >= r0 && row0 + 16 <= r1) { _mm512_storeu_ps(y + row0, v); return; }
    uint32_t m = 0xFFFF;
    if (row0 < r0) m &= r0 - row0 >= 16 ? 0 : 0xFFFFu << (r0 - row0);
    if (row0 + 16 > r1) m &= (1u << (r1 > row0 ? (r1 - row0 > 16 ? 16 : r1 - row0) : 0)) - 1;
    _mm512_mask_storeu_ps(y + row0, (__mmask16)m, v);
}
void *ktq10_gemv_prepare(const void *W, int64_t K, int64_t N) {
    const nblock *w = (const nblock *)W;
    const int64_t nb = K / 256;
    packed_t *pk = malloc(sizeof *pk);
    pk->nrec_k = K / 256; pk->ngroups = (N + 31) / 32 + 0;
    const size_t bytes = (size_t)REC_BYTES * pk->nrec_k * pk->ngroups;
    pk->buf = aligned_alloc(64, (bytes + 63) & ~(size_t)63);
    memset(pk->buf, 0, bytes);
    for (int64_t gr = 0; gr < pk->ngroups; gr++)
        for (int64_t p = 0; p < pk->nrec_k; p++) {
            uint8_t *hp = pk->buf + ((size_t)gr * pk->nrec_k + p) * REC_BYTES;
            for (int row = 0; row < 32; row++) {
                const int64_t n = gr * 32 + row;
                if (n >= N) continue;  /* padding rows stay zero: d = 0 */
                const int64_t v0 = p * 256;
                const nblock *b = w + n * nb + v0 / 256;
                memcpy(hp + 2 * row, &b->d, 2);
                for (int kg = 0; kg < 1; kg++) {
                    uint16_t *wp = (uint16_t *)(hp + HDR_BYTES + kg * UNIT_BYTES) + row;
                    for (int wd = 0; wd < 26; wd++) {
                        uint32_t t10 = 0;
                        for (int t = 0; t < 10; t++) {
                            const int vv = 10 * wd + t;
                            int q = 0;
                            if (vv < 256) { const int v = (int)((v0 + vv) % 256); q = ((((unsigned)(uint8_t)((unsigned)(v < 160 ? b->qs[v % 32] : v < 240 ? b->qs[32 + (v - 160) % 16] : b->qh[(v - 240) % 4]) * (unsigned)"\001\003\011\033\121"[v < 160 ? v / 32 : v < 240 ? (v - 160) / 16 : (v - 240) / 4])) * 3u) >> 8); }
                            t10 = t10 * 3 + (uint32_t)q;
                        }
                        wp[wd * 32] = (uint16_t)((t10 * 65536u + 59048u) / 59049u);  /* base-3 fixed point: digits by * 27 */
                    }
                }
            }
        }
    return pk;
}

static const int8_t LB_CST[14][64] __attribute__((aligned(64))) = {
    {-1, -1, -1, 0, -1, -1, 0, 0, -1, -1, 1, 0, -1, 0, -1, 0, -1, 0, 0, 0, -1, 0, 1, 0, -1, 1, -1, 0, -1, 1, 0, 0, -1, 1, 1, 0, 0, -1, -1, 0, 0, -1, 0, 0, 0, -1, 1, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, -1, 0},
    {0, 1, 0, 0, 0, 1, 1, 0, 1, -1, -1, 0, 1, -1, 0, 0, 1, -1, 1, 0, 1, 0, -1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, -1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, -1, 0, 0, 0, -1, 0, 0, 0, -1, 0, 0, 0, -1, 0, 0, 0, -1, 0, 0, 0, -1, 0, 0, 0, -1, 0, 0, 0, -1, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {-1, -1, 0, 0, -1, 0, 0, 0, -1, 1, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, -1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, -1, -1, 0, 0, -1, 0, 0, 0, -1, 1, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, -1, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {1, 0, 0, 0, 1, 1, 0, 0, -1, -1, 0, 0, -1, 0, 0, 0, -1, 1, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, -1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, -1, -1, 0, 0, -1, -1, 0, 0, -1, -1, 0, 0, -1, 0, 0, 0, -1, 0, 0, 0, -1, 0, 0, 0, -1, 1, 0, 0, -1, 1, 0, 0, -1, 1, 0, 0, 0, -1, 0, 0, 0, -1, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1},
    {-1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, -1, 0, 0, 0},
    {0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, -1, 0, 0, 1, -1, 0, 0, 1, -1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 1, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, -1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, -1, -1, -1, 0, -1, -1, 0, 0, -1, -1, 1, 0, -1, 0, -1, 0, -1, 0, 0, 0, -1, 0, 1, 0, -1, 1, -1, 0, -1, 1, 0, 0, -1, 1, 1, 0, 0, -1, -1, 0, 0, -1, 0, 0, 0, -1, 1, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, -1},
    {0, 0, 1, 0, 0, 0, 1, 1, 0, 1, -1, -1, 0, 1, -1, 0, 0, 1, -1, 1, 0, 1, 0, -1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, -1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
};
static const int32_t LB_CORR[3][16] __attribute__((aligned(64))) = {
    {384, 256, 128, 256, 128, 0, 128, 0, -128, 256, 128, 0, 128, 0, -128, 0},
    {-128, -256, 128, 0, -128, 0, -128, -256, -128, -256, -384, 0, 0, 0, 0, 0},
    {128, 0, -128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
};
static inline int32_t ld32(const uint8_t *p) { int32_t v; memcpy(&v, p, 4); return v; }
static inline size_t lb_toff(int64_t K) { return ((size_t)8 * (K / 32) + 63) & ~(size_t)63; }

/* table buffer: float dxs[K/32] | int32 sx[K/32] | pad to 64 | 102 tables of 32 int16 per 256-value unit */
void ktq10_gemv_lut_info(int64_t K, int64_t *bytes, int64_t *units) {
    *bytes = (int64_t)(lb_toff(K) + (size_t)(K / 256) * 6528);
    *units = K / 256;
}

void ktq10_gemv_lut_build(const void *X, int64_t K, void *tabs, int64_t u0, int64_t u1) {
    const xblock *xb = (const xblock *)X;
    float *dxs = (float *)tabs;
    int32_t *sx = (int32_t *)((uint8_t *)tabs + 4 * (K / 32));
    uint8_t *tb = (uint8_t *)tabs + lb_toff(K);
    uint8_t xu[256] __attribute__((aligned(64)));
    for (int64_t u = u0; u < u1; u++) {
        for (int64_t k = u * 8; k < (u + 1) * 8; k++) {
            int8_t *dst = (int8_t *)xu + 32 * (k - u * 8);
            { const xblock *b = xb + k / 8;
              memcpy(dst, b->qs + (k % 8) * 32, 32);
              dxs[k] = b->d * 1.0f; sx[k] = b->bsums[2 * (k % 8)] + b->bsums[2 * (k % 8) + 1]; }
        }
        for (int i = 0; i < 256; i++) xu[i] ^= 0x80;  /* x + 128 as u8 (vpdpbusd's unsigned operand) */
        uint8_t *t = tb + (size_t)u * 6528;
            _mm256_store_si256((__m256i *)(t + 0), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 0)), _mm512_load_si512((const void *)LB_CST[0]))));
            _mm256_store_si256((__m256i *)(t + 32), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 0)), _mm512_load_si512((const void *)LB_CST[1]))));
            _mm256_store_si256((__m256i *)(t + 64), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 0)), _mm512_load_si512((const void *)LB_CST[2])), _mm512_set1_epi32(ld32(xu + 4)), _mm512_load_si512((const void *)LB_CST[3]))));
            _mm256_store_si256((__m256i *)(t + 96), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 0)), _mm512_load_si512((const void *)LB_CST[4])), _mm512_set1_epi32(ld32(xu + 4)), _mm512_load_si512((const void *)LB_CST[5]))));
            _mm256_store_si256((__m256i *)(t + 128), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 4)), _mm512_load_si512((const void *)LB_CST[6])), _mm512_set1_epi32(ld32(xu + 8)), _mm512_load_si512((const void *)LB_CST[7]))));
            _mm256_store_si256((__m256i *)(t + 160), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 4)), _mm512_load_si512((const void *)LB_CST[8])), _mm512_set1_epi32(ld32(xu + 8)), _mm512_load_si512((const void *)LB_CST[9]))));
            _mm256_store_si256((__m256i *)(t + 192), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[2]), _mm512_set1_epi32(ld32(xu + 8)), _mm512_load_si512((const void *)LB_CST[10]))));
            _mm256_store_si256((__m256i *)(t + 256), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 8)), _mm512_load_si512((const void *)LB_CST[6])), _mm512_set1_epi32(ld32(xu + 12)), _mm512_load_si512((const void *)LB_CST[7]))));
            _mm256_store_si256((__m256i *)(t + 288), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 8)), _mm512_load_si512((const void *)LB_CST[8])), _mm512_set1_epi32(ld32(xu + 12)), _mm512_load_si512((const void *)LB_CST[9]))));
            _mm256_store_si256((__m256i *)(t + 320), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 12)), _mm512_load_si512((const void *)LB_CST[11]))));
            _mm256_store_si256((__m256i *)(t + 352), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 12)), _mm512_load_si512((const void *)LB_CST[12]))));
            _mm256_store_si256((__m256i *)(t + 384), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 16)), _mm512_load_si512((const void *)LB_CST[0]))));
            _mm256_store_si256((__m256i *)(t + 416), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 16)), _mm512_load_si512((const void *)LB_CST[1]))));
            _mm256_store_si256((__m256i *)(t + 448), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[2]), _mm512_set1_epi32(ld32(xu + 16)), _mm512_load_si512((const void *)LB_CST[13]))));
            _mm256_store_si256((__m256i *)(t + 512), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 20)), _mm512_load_si512((const void *)LB_CST[0]))));
            _mm256_store_si256((__m256i *)(t + 544), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 20)), _mm512_load_si512((const void *)LB_CST[1]))));
            _mm256_store_si256((__m256i *)(t + 576), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 20)), _mm512_load_si512((const void *)LB_CST[2])), _mm512_set1_epi32(ld32(xu + 24)), _mm512_load_si512((const void *)LB_CST[3]))));
            _mm256_store_si256((__m256i *)(t + 608), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 20)), _mm512_load_si512((const void *)LB_CST[4])), _mm512_set1_epi32(ld32(xu + 24)), _mm512_load_si512((const void *)LB_CST[5]))));
            _mm256_store_si256((__m256i *)(t + 640), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 24)), _mm512_load_si512((const void *)LB_CST[6])), _mm512_set1_epi32(ld32(xu + 28)), _mm512_load_si512((const void *)LB_CST[7]))));
            _mm256_store_si256((__m256i *)(t + 672), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 24)), _mm512_load_si512((const void *)LB_CST[8])), _mm512_set1_epi32(ld32(xu + 28)), _mm512_load_si512((const void *)LB_CST[9]))));
            _mm256_store_si256((__m256i *)(t + 704), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[2]), _mm512_set1_epi32(ld32(xu + 28)), _mm512_load_si512((const void *)LB_CST[10]))));
            _mm256_store_si256((__m256i *)(t + 768), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 28)), _mm512_load_si512((const void *)LB_CST[6])), _mm512_set1_epi32(ld32(xu + 32)), _mm512_load_si512((const void *)LB_CST[7]))));
            _mm256_store_si256((__m256i *)(t + 800), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 28)), _mm512_load_si512((const void *)LB_CST[8])), _mm512_set1_epi32(ld32(xu + 32)), _mm512_load_si512((const void *)LB_CST[9]))));
            _mm256_store_si256((__m256i *)(t + 832), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 32)), _mm512_load_si512((const void *)LB_CST[11]))));
            _mm256_store_si256((__m256i *)(t + 864), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 32)), _mm512_load_si512((const void *)LB_CST[12]))));
            _mm256_store_si256((__m256i *)(t + 896), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 36)), _mm512_load_si512((const void *)LB_CST[0]))));
            _mm256_store_si256((__m256i *)(t + 928), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 36)), _mm512_load_si512((const void *)LB_CST[1]))));
            _mm256_store_si256((__m256i *)(t + 960), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[2]), _mm512_set1_epi32(ld32(xu + 36)), _mm512_load_si512((const void *)LB_CST[13]))));
            _mm256_store_si256((__m256i *)(t + 1024), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 40)), _mm512_load_si512((const void *)LB_CST[0]))));
            _mm256_store_si256((__m256i *)(t + 1056), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 40)), _mm512_load_si512((const void *)LB_CST[1]))));
            _mm256_store_si256((__m256i *)(t + 1088), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 40)), _mm512_load_si512((const void *)LB_CST[2])), _mm512_set1_epi32(ld32(xu + 44)), _mm512_load_si512((const void *)LB_CST[3]))));
            _mm256_store_si256((__m256i *)(t + 1120), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 40)), _mm512_load_si512((const void *)LB_CST[4])), _mm512_set1_epi32(ld32(xu + 44)), _mm512_load_si512((const void *)LB_CST[5]))));
            _mm256_store_si256((__m256i *)(t + 1152), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 44)), _mm512_load_si512((const void *)LB_CST[6])), _mm512_set1_epi32(ld32(xu + 48)), _mm512_load_si512((const void *)LB_CST[7]))));
            _mm256_store_si256((__m256i *)(t + 1184), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 44)), _mm512_load_si512((const void *)LB_CST[8])), _mm512_set1_epi32(ld32(xu + 48)), _mm512_load_si512((const void *)LB_CST[9]))));
            _mm256_store_si256((__m256i *)(t + 1216), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[2]), _mm512_set1_epi32(ld32(xu + 48)), _mm512_load_si512((const void *)LB_CST[10]))));
            _mm256_store_si256((__m256i *)(t + 1280), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 48)), _mm512_load_si512((const void *)LB_CST[6])), _mm512_set1_epi32(ld32(xu + 52)), _mm512_load_si512((const void *)LB_CST[7]))));
            _mm256_store_si256((__m256i *)(t + 1312), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 48)), _mm512_load_si512((const void *)LB_CST[8])), _mm512_set1_epi32(ld32(xu + 52)), _mm512_load_si512((const void *)LB_CST[9]))));
            _mm256_store_si256((__m256i *)(t + 1344), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 52)), _mm512_load_si512((const void *)LB_CST[11]))));
            _mm256_store_si256((__m256i *)(t + 1376), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 52)), _mm512_load_si512((const void *)LB_CST[12]))));
            _mm256_store_si256((__m256i *)(t + 1408), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 56)), _mm512_load_si512((const void *)LB_CST[0]))));
            _mm256_store_si256((__m256i *)(t + 1440), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 56)), _mm512_load_si512((const void *)LB_CST[1]))));
            _mm256_store_si256((__m256i *)(t + 1472), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[2]), _mm512_set1_epi32(ld32(xu + 56)), _mm512_load_si512((const void *)LB_CST[13]))));
            _mm256_store_si256((__m256i *)(t + 1536), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 60)), _mm512_load_si512((const void *)LB_CST[0]))));
            _mm256_store_si256((__m256i *)(t + 1568), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 60)), _mm512_load_si512((const void *)LB_CST[1]))));
            _mm256_store_si256((__m256i *)(t + 1600), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 60)), _mm512_load_si512((const void *)LB_CST[2])), _mm512_set1_epi32(ld32(xu + 64)), _mm512_load_si512((const void *)LB_CST[3]))));
            _mm256_store_si256((__m256i *)(t + 1632), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 60)), _mm512_load_si512((const void *)LB_CST[4])), _mm512_set1_epi32(ld32(xu + 64)), _mm512_load_si512((const void *)LB_CST[5]))));
            _mm256_store_si256((__m256i *)(t + 1664), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 64)), _mm512_load_si512((const void *)LB_CST[6])), _mm512_set1_epi32(ld32(xu + 68)), _mm512_load_si512((const void *)LB_CST[7]))));
            _mm256_store_si256((__m256i *)(t + 1696), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 64)), _mm512_load_si512((const void *)LB_CST[8])), _mm512_set1_epi32(ld32(xu + 68)), _mm512_load_si512((const void *)LB_CST[9]))));
            _mm256_store_si256((__m256i *)(t + 1728), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[2]), _mm512_set1_epi32(ld32(xu + 68)), _mm512_load_si512((const void *)LB_CST[10]))));
            _mm256_store_si256((__m256i *)(t + 1792), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 68)), _mm512_load_si512((const void *)LB_CST[6])), _mm512_set1_epi32(ld32(xu + 72)), _mm512_load_si512((const void *)LB_CST[7]))));
            _mm256_store_si256((__m256i *)(t + 1824), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 68)), _mm512_load_si512((const void *)LB_CST[8])), _mm512_set1_epi32(ld32(xu + 72)), _mm512_load_si512((const void *)LB_CST[9]))));
            _mm256_store_si256((__m256i *)(t + 1856), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 72)), _mm512_load_si512((const void *)LB_CST[11]))));
            _mm256_store_si256((__m256i *)(t + 1888), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 72)), _mm512_load_si512((const void *)LB_CST[12]))));
            _mm256_store_si256((__m256i *)(t + 1920), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 76)), _mm512_load_si512((const void *)LB_CST[0]))));
            _mm256_store_si256((__m256i *)(t + 1952), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 76)), _mm512_load_si512((const void *)LB_CST[1]))));
            _mm256_store_si256((__m256i *)(t + 1984), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[2]), _mm512_set1_epi32(ld32(xu + 76)), _mm512_load_si512((const void *)LB_CST[13]))));
            _mm256_store_si256((__m256i *)(t + 2048), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 80)), _mm512_load_si512((const void *)LB_CST[0]))));
            _mm256_store_si256((__m256i *)(t + 2080), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 80)), _mm512_load_si512((const void *)LB_CST[1]))));
            _mm256_store_si256((__m256i *)(t + 2112), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 80)), _mm512_load_si512((const void *)LB_CST[2])), _mm512_set1_epi32(ld32(xu + 84)), _mm512_load_si512((const void *)LB_CST[3]))));
            _mm256_store_si256((__m256i *)(t + 2144), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 80)), _mm512_load_si512((const void *)LB_CST[4])), _mm512_set1_epi32(ld32(xu + 84)), _mm512_load_si512((const void *)LB_CST[5]))));
            _mm256_store_si256((__m256i *)(t + 2176), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 84)), _mm512_load_si512((const void *)LB_CST[6])), _mm512_set1_epi32(ld32(xu + 88)), _mm512_load_si512((const void *)LB_CST[7]))));
            _mm256_store_si256((__m256i *)(t + 2208), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 84)), _mm512_load_si512((const void *)LB_CST[8])), _mm512_set1_epi32(ld32(xu + 88)), _mm512_load_si512((const void *)LB_CST[9]))));
            _mm256_store_si256((__m256i *)(t + 2240), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[2]), _mm512_set1_epi32(ld32(xu + 88)), _mm512_load_si512((const void *)LB_CST[10]))));
            _mm256_store_si256((__m256i *)(t + 2304), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 88)), _mm512_load_si512((const void *)LB_CST[6])), _mm512_set1_epi32(ld32(xu + 92)), _mm512_load_si512((const void *)LB_CST[7]))));
            _mm256_store_si256((__m256i *)(t + 2336), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 88)), _mm512_load_si512((const void *)LB_CST[8])), _mm512_set1_epi32(ld32(xu + 92)), _mm512_load_si512((const void *)LB_CST[9]))));
            _mm256_store_si256((__m256i *)(t + 2368), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 92)), _mm512_load_si512((const void *)LB_CST[11]))));
            _mm256_store_si256((__m256i *)(t + 2400), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 92)), _mm512_load_si512((const void *)LB_CST[12]))));
            _mm256_store_si256((__m256i *)(t + 2432), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 96)), _mm512_load_si512((const void *)LB_CST[0]))));
            _mm256_store_si256((__m256i *)(t + 2464), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 96)), _mm512_load_si512((const void *)LB_CST[1]))));
            _mm256_store_si256((__m256i *)(t + 2496), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[2]), _mm512_set1_epi32(ld32(xu + 96)), _mm512_load_si512((const void *)LB_CST[13]))));
            _mm256_store_si256((__m256i *)(t + 2560), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 100)), _mm512_load_si512((const void *)LB_CST[0]))));
            _mm256_store_si256((__m256i *)(t + 2592), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 100)), _mm512_load_si512((const void *)LB_CST[1]))));
            _mm256_store_si256((__m256i *)(t + 2624), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 100)), _mm512_load_si512((const void *)LB_CST[2])), _mm512_set1_epi32(ld32(xu + 104)), _mm512_load_si512((const void *)LB_CST[3]))));
            _mm256_store_si256((__m256i *)(t + 2656), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 100)), _mm512_load_si512((const void *)LB_CST[4])), _mm512_set1_epi32(ld32(xu + 104)), _mm512_load_si512((const void *)LB_CST[5]))));
            _mm256_store_si256((__m256i *)(t + 2688), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 104)), _mm512_load_si512((const void *)LB_CST[6])), _mm512_set1_epi32(ld32(xu + 108)), _mm512_load_si512((const void *)LB_CST[7]))));
            _mm256_store_si256((__m256i *)(t + 2720), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 104)), _mm512_load_si512((const void *)LB_CST[8])), _mm512_set1_epi32(ld32(xu + 108)), _mm512_load_si512((const void *)LB_CST[9]))));
            _mm256_store_si256((__m256i *)(t + 2752), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[2]), _mm512_set1_epi32(ld32(xu + 108)), _mm512_load_si512((const void *)LB_CST[10]))));
            _mm256_store_si256((__m256i *)(t + 2816), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 108)), _mm512_load_si512((const void *)LB_CST[6])), _mm512_set1_epi32(ld32(xu + 112)), _mm512_load_si512((const void *)LB_CST[7]))));
            _mm256_store_si256((__m256i *)(t + 2848), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 108)), _mm512_load_si512((const void *)LB_CST[8])), _mm512_set1_epi32(ld32(xu + 112)), _mm512_load_si512((const void *)LB_CST[9]))));
            _mm256_store_si256((__m256i *)(t + 2880), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 112)), _mm512_load_si512((const void *)LB_CST[11]))));
            _mm256_store_si256((__m256i *)(t + 2912), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 112)), _mm512_load_si512((const void *)LB_CST[12]))));
            _mm256_store_si256((__m256i *)(t + 2944), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 116)), _mm512_load_si512((const void *)LB_CST[0]))));
            _mm256_store_si256((__m256i *)(t + 2976), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 116)), _mm512_load_si512((const void *)LB_CST[1]))));
            _mm256_store_si256((__m256i *)(t + 3008), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[2]), _mm512_set1_epi32(ld32(xu + 116)), _mm512_load_si512((const void *)LB_CST[13]))));
            _mm256_store_si256((__m256i *)(t + 3072), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 120)), _mm512_load_si512((const void *)LB_CST[0]))));
            _mm256_store_si256((__m256i *)(t + 3104), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 120)), _mm512_load_si512((const void *)LB_CST[1]))));
            _mm256_store_si256((__m256i *)(t + 3136), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 120)), _mm512_load_si512((const void *)LB_CST[2])), _mm512_set1_epi32(ld32(xu + 124)), _mm512_load_si512((const void *)LB_CST[3]))));
            _mm256_store_si256((__m256i *)(t + 3168), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 120)), _mm512_load_si512((const void *)LB_CST[4])), _mm512_set1_epi32(ld32(xu + 124)), _mm512_load_si512((const void *)LB_CST[5]))));
            _mm256_store_si256((__m256i *)(t + 3200), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 124)), _mm512_load_si512((const void *)LB_CST[6])), _mm512_set1_epi32(ld32(xu + 128)), _mm512_load_si512((const void *)LB_CST[7]))));
            _mm256_store_si256((__m256i *)(t + 3232), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 124)), _mm512_load_si512((const void *)LB_CST[8])), _mm512_set1_epi32(ld32(xu + 128)), _mm512_load_si512((const void *)LB_CST[9]))));
            _mm256_store_si256((__m256i *)(t + 3264), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[2]), _mm512_set1_epi32(ld32(xu + 128)), _mm512_load_si512((const void *)LB_CST[10]))));
            _mm256_store_si256((__m256i *)(t + 3328), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 128)), _mm512_load_si512((const void *)LB_CST[6])), _mm512_set1_epi32(ld32(xu + 132)), _mm512_load_si512((const void *)LB_CST[7]))));
            _mm256_store_si256((__m256i *)(t + 3360), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 128)), _mm512_load_si512((const void *)LB_CST[8])), _mm512_set1_epi32(ld32(xu + 132)), _mm512_load_si512((const void *)LB_CST[9]))));
            _mm256_store_si256((__m256i *)(t + 3392), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 132)), _mm512_load_si512((const void *)LB_CST[11]))));
            _mm256_store_si256((__m256i *)(t + 3424), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 132)), _mm512_load_si512((const void *)LB_CST[12]))));
            _mm256_store_si256((__m256i *)(t + 3456), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 136)), _mm512_load_si512((const void *)LB_CST[0]))));
            _mm256_store_si256((__m256i *)(t + 3488), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 136)), _mm512_load_si512((const void *)LB_CST[1]))));
            _mm256_store_si256((__m256i *)(t + 3520), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[2]), _mm512_set1_epi32(ld32(xu + 136)), _mm512_load_si512((const void *)LB_CST[13]))));
            _mm256_store_si256((__m256i *)(t + 3584), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 140)), _mm512_load_si512((const void *)LB_CST[0]))));
            _mm256_store_si256((__m256i *)(t + 3616), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 140)), _mm512_load_si512((const void *)LB_CST[1]))));
            _mm256_store_si256((__m256i *)(t + 3648), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 140)), _mm512_load_si512((const void *)LB_CST[2])), _mm512_set1_epi32(ld32(xu + 144)), _mm512_load_si512((const void *)LB_CST[3]))));
            _mm256_store_si256((__m256i *)(t + 3680), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 140)), _mm512_load_si512((const void *)LB_CST[4])), _mm512_set1_epi32(ld32(xu + 144)), _mm512_load_si512((const void *)LB_CST[5]))));
            _mm256_store_si256((__m256i *)(t + 3712), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 144)), _mm512_load_si512((const void *)LB_CST[6])), _mm512_set1_epi32(ld32(xu + 148)), _mm512_load_si512((const void *)LB_CST[7]))));
            _mm256_store_si256((__m256i *)(t + 3744), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 144)), _mm512_load_si512((const void *)LB_CST[8])), _mm512_set1_epi32(ld32(xu + 148)), _mm512_load_si512((const void *)LB_CST[9]))));
            _mm256_store_si256((__m256i *)(t + 3776), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[2]), _mm512_set1_epi32(ld32(xu + 148)), _mm512_load_si512((const void *)LB_CST[10]))));
            _mm256_store_si256((__m256i *)(t + 3840), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 148)), _mm512_load_si512((const void *)LB_CST[6])), _mm512_set1_epi32(ld32(xu + 152)), _mm512_load_si512((const void *)LB_CST[7]))));
            _mm256_store_si256((__m256i *)(t + 3872), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 148)), _mm512_load_si512((const void *)LB_CST[8])), _mm512_set1_epi32(ld32(xu + 152)), _mm512_load_si512((const void *)LB_CST[9]))));
            _mm256_store_si256((__m256i *)(t + 3904), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 152)), _mm512_load_si512((const void *)LB_CST[11]))));
            _mm256_store_si256((__m256i *)(t + 3936), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 152)), _mm512_load_si512((const void *)LB_CST[12]))));
            _mm256_store_si256((__m256i *)(t + 3968), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 156)), _mm512_load_si512((const void *)LB_CST[0]))));
            _mm256_store_si256((__m256i *)(t + 4000), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 156)), _mm512_load_si512((const void *)LB_CST[1]))));
            _mm256_store_si256((__m256i *)(t + 4032), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[2]), _mm512_set1_epi32(ld32(xu + 156)), _mm512_load_si512((const void *)LB_CST[13]))));
            _mm256_store_si256((__m256i *)(t + 4096), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 160)), _mm512_load_si512((const void *)LB_CST[0]))));
            _mm256_store_si256((__m256i *)(t + 4128), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 160)), _mm512_load_si512((const void *)LB_CST[1]))));
            _mm256_store_si256((__m256i *)(t + 4160), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 160)), _mm512_load_si512((const void *)LB_CST[2])), _mm512_set1_epi32(ld32(xu + 164)), _mm512_load_si512((const void *)LB_CST[3]))));
            _mm256_store_si256((__m256i *)(t + 4192), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 160)), _mm512_load_si512((const void *)LB_CST[4])), _mm512_set1_epi32(ld32(xu + 164)), _mm512_load_si512((const void *)LB_CST[5]))));
            _mm256_store_si256((__m256i *)(t + 4224), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 164)), _mm512_load_si512((const void *)LB_CST[6])), _mm512_set1_epi32(ld32(xu + 168)), _mm512_load_si512((const void *)LB_CST[7]))));
            _mm256_store_si256((__m256i *)(t + 4256), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 164)), _mm512_load_si512((const void *)LB_CST[8])), _mm512_set1_epi32(ld32(xu + 168)), _mm512_load_si512((const void *)LB_CST[9]))));
            _mm256_store_si256((__m256i *)(t + 4288), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[2]), _mm512_set1_epi32(ld32(xu + 168)), _mm512_load_si512((const void *)LB_CST[10]))));
            _mm256_store_si256((__m256i *)(t + 4352), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 168)), _mm512_load_si512((const void *)LB_CST[6])), _mm512_set1_epi32(ld32(xu + 172)), _mm512_load_si512((const void *)LB_CST[7]))));
            _mm256_store_si256((__m256i *)(t + 4384), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 168)), _mm512_load_si512((const void *)LB_CST[8])), _mm512_set1_epi32(ld32(xu + 172)), _mm512_load_si512((const void *)LB_CST[9]))));
            _mm256_store_si256((__m256i *)(t + 4416), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 172)), _mm512_load_si512((const void *)LB_CST[11]))));
            _mm256_store_si256((__m256i *)(t + 4448), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 172)), _mm512_load_si512((const void *)LB_CST[12]))));
            _mm256_store_si256((__m256i *)(t + 4480), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 176)), _mm512_load_si512((const void *)LB_CST[0]))));
            _mm256_store_si256((__m256i *)(t + 4512), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 176)), _mm512_load_si512((const void *)LB_CST[1]))));
            _mm256_store_si256((__m256i *)(t + 4544), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[2]), _mm512_set1_epi32(ld32(xu + 176)), _mm512_load_si512((const void *)LB_CST[13]))));
            _mm256_store_si256((__m256i *)(t + 4608), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 180)), _mm512_load_si512((const void *)LB_CST[0]))));
            _mm256_store_si256((__m256i *)(t + 4640), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 180)), _mm512_load_si512((const void *)LB_CST[1]))));
            _mm256_store_si256((__m256i *)(t + 4672), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 180)), _mm512_load_si512((const void *)LB_CST[2])), _mm512_set1_epi32(ld32(xu + 184)), _mm512_load_si512((const void *)LB_CST[3]))));
            _mm256_store_si256((__m256i *)(t + 4704), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 180)), _mm512_load_si512((const void *)LB_CST[4])), _mm512_set1_epi32(ld32(xu + 184)), _mm512_load_si512((const void *)LB_CST[5]))));
            _mm256_store_si256((__m256i *)(t + 4736), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 184)), _mm512_load_si512((const void *)LB_CST[6])), _mm512_set1_epi32(ld32(xu + 188)), _mm512_load_si512((const void *)LB_CST[7]))));
            _mm256_store_si256((__m256i *)(t + 4768), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 184)), _mm512_load_si512((const void *)LB_CST[8])), _mm512_set1_epi32(ld32(xu + 188)), _mm512_load_si512((const void *)LB_CST[9]))));
            _mm256_store_si256((__m256i *)(t + 4800), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[2]), _mm512_set1_epi32(ld32(xu + 188)), _mm512_load_si512((const void *)LB_CST[10]))));
            _mm256_store_si256((__m256i *)(t + 4864), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 188)), _mm512_load_si512((const void *)LB_CST[6])), _mm512_set1_epi32(ld32(xu + 192)), _mm512_load_si512((const void *)LB_CST[7]))));
            _mm256_store_si256((__m256i *)(t + 4896), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 188)), _mm512_load_si512((const void *)LB_CST[8])), _mm512_set1_epi32(ld32(xu + 192)), _mm512_load_si512((const void *)LB_CST[9]))));
            _mm256_store_si256((__m256i *)(t + 4928), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 192)), _mm512_load_si512((const void *)LB_CST[11]))));
            _mm256_store_si256((__m256i *)(t + 4960), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 192)), _mm512_load_si512((const void *)LB_CST[12]))));
            _mm256_store_si256((__m256i *)(t + 4992), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 196)), _mm512_load_si512((const void *)LB_CST[0]))));
            _mm256_store_si256((__m256i *)(t + 5024), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 196)), _mm512_load_si512((const void *)LB_CST[1]))));
            _mm256_store_si256((__m256i *)(t + 5056), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[2]), _mm512_set1_epi32(ld32(xu + 196)), _mm512_load_si512((const void *)LB_CST[13]))));
            _mm256_store_si256((__m256i *)(t + 5120), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 200)), _mm512_load_si512((const void *)LB_CST[0]))));
            _mm256_store_si256((__m256i *)(t + 5152), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 200)), _mm512_load_si512((const void *)LB_CST[1]))));
            _mm256_store_si256((__m256i *)(t + 5184), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 200)), _mm512_load_si512((const void *)LB_CST[2])), _mm512_set1_epi32(ld32(xu + 204)), _mm512_load_si512((const void *)LB_CST[3]))));
            _mm256_store_si256((__m256i *)(t + 5216), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 200)), _mm512_load_si512((const void *)LB_CST[4])), _mm512_set1_epi32(ld32(xu + 204)), _mm512_load_si512((const void *)LB_CST[5]))));
            _mm256_store_si256((__m256i *)(t + 5248), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 204)), _mm512_load_si512((const void *)LB_CST[6])), _mm512_set1_epi32(ld32(xu + 208)), _mm512_load_si512((const void *)LB_CST[7]))));
            _mm256_store_si256((__m256i *)(t + 5280), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 204)), _mm512_load_si512((const void *)LB_CST[8])), _mm512_set1_epi32(ld32(xu + 208)), _mm512_load_si512((const void *)LB_CST[9]))));
            _mm256_store_si256((__m256i *)(t + 5312), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[2]), _mm512_set1_epi32(ld32(xu + 208)), _mm512_load_si512((const void *)LB_CST[10]))));
            _mm256_store_si256((__m256i *)(t + 5376), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 208)), _mm512_load_si512((const void *)LB_CST[6])), _mm512_set1_epi32(ld32(xu + 212)), _mm512_load_si512((const void *)LB_CST[7]))));
            _mm256_store_si256((__m256i *)(t + 5408), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 208)), _mm512_load_si512((const void *)LB_CST[8])), _mm512_set1_epi32(ld32(xu + 212)), _mm512_load_si512((const void *)LB_CST[9]))));
            _mm256_store_si256((__m256i *)(t + 5440), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 212)), _mm512_load_si512((const void *)LB_CST[11]))));
            _mm256_store_si256((__m256i *)(t + 5472), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 212)), _mm512_load_si512((const void *)LB_CST[12]))));
            _mm256_store_si256((__m256i *)(t + 5504), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 216)), _mm512_load_si512((const void *)LB_CST[0]))));
            _mm256_store_si256((__m256i *)(t + 5536), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 216)), _mm512_load_si512((const void *)LB_CST[1]))));
            _mm256_store_si256((__m256i *)(t + 5568), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[2]), _mm512_set1_epi32(ld32(xu + 216)), _mm512_load_si512((const void *)LB_CST[13]))));
            _mm256_store_si256((__m256i *)(t + 5632), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 220)), _mm512_load_si512((const void *)LB_CST[0]))));
            _mm256_store_si256((__m256i *)(t + 5664), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 220)), _mm512_load_si512((const void *)LB_CST[1]))));
            _mm256_store_si256((__m256i *)(t + 5696), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 220)), _mm512_load_si512((const void *)LB_CST[2])), _mm512_set1_epi32(ld32(xu + 224)), _mm512_load_si512((const void *)LB_CST[3]))));
            _mm256_store_si256((__m256i *)(t + 5728), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 220)), _mm512_load_si512((const void *)LB_CST[4])), _mm512_set1_epi32(ld32(xu + 224)), _mm512_load_si512((const void *)LB_CST[5]))));
            _mm256_store_si256((__m256i *)(t + 5760), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 224)), _mm512_load_si512((const void *)LB_CST[6])), _mm512_set1_epi32(ld32(xu + 228)), _mm512_load_si512((const void *)LB_CST[7]))));
            _mm256_store_si256((__m256i *)(t + 5792), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 224)), _mm512_load_si512((const void *)LB_CST[8])), _mm512_set1_epi32(ld32(xu + 228)), _mm512_load_si512((const void *)LB_CST[9]))));
            _mm256_store_si256((__m256i *)(t + 5824), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[2]), _mm512_set1_epi32(ld32(xu + 228)), _mm512_load_si512((const void *)LB_CST[10]))));
            _mm256_store_si256((__m256i *)(t + 5888), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 228)), _mm512_load_si512((const void *)LB_CST[6])), _mm512_set1_epi32(ld32(xu + 232)), _mm512_load_si512((const void *)LB_CST[7]))));
            _mm256_store_si256((__m256i *)(t + 5920), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 228)), _mm512_load_si512((const void *)LB_CST[8])), _mm512_set1_epi32(ld32(xu + 232)), _mm512_load_si512((const void *)LB_CST[9]))));
            _mm256_store_si256((__m256i *)(t + 5952), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 232)), _mm512_load_si512((const void *)LB_CST[11]))));
            _mm256_store_si256((__m256i *)(t + 5984), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 232)), _mm512_load_si512((const void *)LB_CST[12]))));
            _mm256_store_si256((__m256i *)(t + 6016), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 236)), _mm512_load_si512((const void *)LB_CST[0]))));
            _mm256_store_si256((__m256i *)(t + 6048), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 236)), _mm512_load_si512((const void *)LB_CST[1]))));
            _mm256_store_si256((__m256i *)(t + 6080), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[2]), _mm512_set1_epi32(ld32(xu + 236)), _mm512_load_si512((const void *)LB_CST[13]))));
            _mm256_store_si256((__m256i *)(t + 6144), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 240)), _mm512_load_si512((const void *)LB_CST[0]))));
            _mm256_store_si256((__m256i *)(t + 6176), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 240)), _mm512_load_si512((const void *)LB_CST[1]))));
            _mm256_store_si256((__m256i *)(t + 6208), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 240)), _mm512_load_si512((const void *)LB_CST[2])), _mm512_set1_epi32(ld32(xu + 244)), _mm512_load_si512((const void *)LB_CST[3]))));
            _mm256_store_si256((__m256i *)(t + 6240), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 240)), _mm512_load_si512((const void *)LB_CST[4])), _mm512_set1_epi32(ld32(xu + 244)), _mm512_load_si512((const void *)LB_CST[5]))));
            _mm256_store_si256((__m256i *)(t + 6272), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 244)), _mm512_load_si512((const void *)LB_CST[6])), _mm512_set1_epi32(ld32(xu + 248)), _mm512_load_si512((const void *)LB_CST[7]))));
            _mm256_store_si256((__m256i *)(t + 6304), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 244)), _mm512_load_si512((const void *)LB_CST[8])), _mm512_set1_epi32(ld32(xu + 248)), _mm512_load_si512((const void *)LB_CST[9]))));
            _mm256_store_si256((__m256i *)(t + 6336), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[2]), _mm512_set1_epi32(ld32(xu + 248)), _mm512_load_si512((const void *)LB_CST[10]))));
            _mm256_store_si256((__m256i *)(t + 6400), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 248)), _mm512_load_si512((const void *)LB_CST[6])), _mm512_set1_epi32(ld32(xu + 252)), _mm512_load_si512((const void *)LB_CST[7]))));
            _mm256_store_si256((__m256i *)(t + 6432), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 248)), _mm512_load_si512((const void *)LB_CST[8])), _mm512_set1_epi32(ld32(xu + 252)), _mm512_load_si512((const void *)LB_CST[9]))));
            _mm256_store_si256((__m256i *)(t + 6464), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 252)), _mm512_load_si512((const void *)LB_CST[11]))));
            _mm256_store_si256((__m256i *)(t + 6496), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 252)), _mm512_load_si512((const void *)LB_CST[12]))));
    }
}

void ktq10_gemv_lut_rows(const void *pv, const void *tabs, float *Y, int64_t K, int64_t r0, int64_t r1) {
    const packed_t *pk = (const packed_t *)pv;
    const float *dxs = (const float *)tabs;
    const int32_t *sx = (const int32_t *)((const uint8_t *)tabs + 4 * (K / 32));
    const uint8_t *tb = (const uint8_t *)tabs + lb_toff(K);
    const __m512i zero = _mm512_setzero_si512(), k27 = _mm512_set1_epi16(27), k3 = _mm512_set1_epi16(3);
    (void)sx; (void)zero; (void)k27; (void)k3;
    const int64_t g0 = r0 / 32, g1 = (r1 + 31) / 32;
    for (int64_t g = g0; g < g1; g += 1) {
        __m512 alo0 = _mm512_setzero_ps(), ahi0 = _mm512_setzero_ps();
        for (int64_t p = 0; p < pk->nrec_k; p++) {
                const uint8_t *rec0 = pk->buf + ((size_t)(g + 0) * pk->nrec_k + p) * REC_BYTES;
                const __m512 dlo0 = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)rec0)), dhi0 = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)(rec0 + 32)));
                __m512i ilo0 = _mm512_setzero_si512(), ihi0 = _mm512_setzero_si512();
                __m512i s0_0 = _mm512_setzero_si512();
                for (int kg = 0; kg < 1; kg++) {
                    const int64_t k = p * 1 + kg;  /* unit index */
                    const uint8_t *T = tb + (size_t)k * 6528;
                    { const __m512i W = WVEC(rec0, kg, 0);
                      __m512i R = _mm512_mullo_epi16(W, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(W, k27), _mm512_load_si512((const void *)(T + 0))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R, k27), _mm512_load_si512((const void *)(T + 64))));
                      const __m512i R2 = _mm512_mullo_epi16(R, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R2, k27), _mm512_load_si512((const void *)(T + 128))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(_mm512_mullo_epi16(R2, k27), k3), _mm512_load_si512((const void *)(T + 192))));
                      (void)R; }
                    { const __m512i W = WVEC(rec0, kg, 1);
                      __m512i R = _mm512_mullo_epi16(W, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(W, k27), _mm512_load_si512((const void *)(T + 256))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R, k27), _mm512_load_si512((const void *)(T + 320))));
                      const __m512i R2 = _mm512_mullo_epi16(R, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R2, k27), _mm512_load_si512((const void *)(T + 384))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(_mm512_mullo_epi16(R2, k27), k3), _mm512_load_si512((const void *)(T + 448))));
                      (void)R; }
                    { const __m512i W = WVEC(rec0, kg, 2);
                      __m512i R = _mm512_mullo_epi16(W, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(W, k27), _mm512_load_si512((const void *)(T + 512))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R, k27), _mm512_load_si512((const void *)(T + 576))));
                      const __m512i R2 = _mm512_mullo_epi16(R, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R2, k27), _mm512_load_si512((const void *)(T + 640))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(_mm512_mullo_epi16(R2, k27), k3), _mm512_load_si512((const void *)(T + 704))));
                      (void)R; }
                    { const __m512i W = WVEC(rec0, kg, 3);
                      __m512i R = _mm512_mullo_epi16(W, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(W, k27), _mm512_load_si512((const void *)(T + 768))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R, k27), _mm512_load_si512((const void *)(T + 832))));
                      const __m512i R2 = _mm512_mullo_epi16(R, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R2, k27), _mm512_load_si512((const void *)(T + 896))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(_mm512_mullo_epi16(R2, k27), k3), _mm512_load_si512((const void *)(T + 960))));
                      (void)R; }
                    { const __m512i W = WVEC(rec0, kg, 4);
                      __m512i R = _mm512_mullo_epi16(W, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(W, k27), _mm512_load_si512((const void *)(T + 1024))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R, k27), _mm512_load_si512((const void *)(T + 1088))));
                      const __m512i R2 = _mm512_mullo_epi16(R, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R2, k27), _mm512_load_si512((const void *)(T + 1152))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(_mm512_mullo_epi16(R2, k27), k3), _mm512_load_si512((const void *)(T + 1216))));
                      (void)R; }
                    { const __m512i W = WVEC(rec0, kg, 5);
                      __m512i R = _mm512_mullo_epi16(W, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(W, k27), _mm512_load_si512((const void *)(T + 1280))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R, k27), _mm512_load_si512((const void *)(T + 1344))));
                      const __m512i R2 = _mm512_mullo_epi16(R, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R2, k27), _mm512_load_si512((const void *)(T + 1408))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(_mm512_mullo_epi16(R2, k27), k3), _mm512_load_si512((const void *)(T + 1472))));
                      (void)R; }
                    { const __m512i W = WVEC(rec0, kg, 6);
                      __m512i R = _mm512_mullo_epi16(W, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(W, k27), _mm512_load_si512((const void *)(T + 1536))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R, k27), _mm512_load_si512((const void *)(T + 1600))));
                      const __m512i R2 = _mm512_mullo_epi16(R, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R2, k27), _mm512_load_si512((const void *)(T + 1664))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(_mm512_mullo_epi16(R2, k27), k3), _mm512_load_si512((const void *)(T + 1728))));
                      (void)R; }
                    { const __m512i W = WVEC(rec0, kg, 7);
                      __m512i R = _mm512_mullo_epi16(W, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(W, k27), _mm512_load_si512((const void *)(T + 1792))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R, k27), _mm512_load_si512((const void *)(T + 1856))));
                      const __m512i R2 = _mm512_mullo_epi16(R, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R2, k27), _mm512_load_si512((const void *)(T + 1920))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(_mm512_mullo_epi16(R2, k27), k3), _mm512_load_si512((const void *)(T + 1984))));
                      (void)R; }
                    { const __m512i W = WVEC(rec0, kg, 8);
                      __m512i R = _mm512_mullo_epi16(W, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(W, k27), _mm512_load_si512((const void *)(T + 2048))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R, k27), _mm512_load_si512((const void *)(T + 2112))));
                      const __m512i R2 = _mm512_mullo_epi16(R, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R2, k27), _mm512_load_si512((const void *)(T + 2176))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(_mm512_mullo_epi16(R2, k27), k3), _mm512_load_si512((const void *)(T + 2240))));
                      (void)R; }
                    { const __m512i W = WVEC(rec0, kg, 9);
                      __m512i R = _mm512_mullo_epi16(W, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(W, k27), _mm512_load_si512((const void *)(T + 2304))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R, k27), _mm512_load_si512((const void *)(T + 2368))));
                      const __m512i R2 = _mm512_mullo_epi16(R, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R2, k27), _mm512_load_si512((const void *)(T + 2432))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(_mm512_mullo_epi16(R2, k27), k3), _mm512_load_si512((const void *)(T + 2496))));
                      (void)R; }
                    { const __m512i W = WVEC(rec0, kg, 10);
                      __m512i R = _mm512_mullo_epi16(W, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(W, k27), _mm512_load_si512((const void *)(T + 2560))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R, k27), _mm512_load_si512((const void *)(T + 2624))));
                      const __m512i R2 = _mm512_mullo_epi16(R, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R2, k27), _mm512_load_si512((const void *)(T + 2688))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(_mm512_mullo_epi16(R2, k27), k3), _mm512_load_si512((const void *)(T + 2752))));
                      (void)R; }
                    { const __m512i W = WVEC(rec0, kg, 11);
                      __m512i R = _mm512_mullo_epi16(W, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(W, k27), _mm512_load_si512((const void *)(T + 2816))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R, k27), _mm512_load_si512((const void *)(T + 2880))));
                      const __m512i R2 = _mm512_mullo_epi16(R, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R2, k27), _mm512_load_si512((const void *)(T + 2944))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(_mm512_mullo_epi16(R2, k27), k3), _mm512_load_si512((const void *)(T + 3008))));
                      (void)R; }
                    { const __m512i W = WVEC(rec0, kg, 12);
                      __m512i R = _mm512_mullo_epi16(W, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(W, k27), _mm512_load_si512((const void *)(T + 3072))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R, k27), _mm512_load_si512((const void *)(T + 3136))));
                      const __m512i R2 = _mm512_mullo_epi16(R, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R2, k27), _mm512_load_si512((const void *)(T + 3200))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(_mm512_mullo_epi16(R2, k27), k3), _mm512_load_si512((const void *)(T + 3264))));
                      (void)R; }
                    { const __m512i W = WVEC(rec0, kg, 13);
                      __m512i R = _mm512_mullo_epi16(W, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(W, k27), _mm512_load_si512((const void *)(T + 3328))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R, k27), _mm512_load_si512((const void *)(T + 3392))));
                      const __m512i R2 = _mm512_mullo_epi16(R, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R2, k27), _mm512_load_si512((const void *)(T + 3456))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(_mm512_mullo_epi16(R2, k27), k3), _mm512_load_si512((const void *)(T + 3520))));
                      (void)R; }
                    { const __m512i W = WVEC(rec0, kg, 14);
                      __m512i R = _mm512_mullo_epi16(W, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(W, k27), _mm512_load_si512((const void *)(T + 3584))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R, k27), _mm512_load_si512((const void *)(T + 3648))));
                      const __m512i R2 = _mm512_mullo_epi16(R, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R2, k27), _mm512_load_si512((const void *)(T + 3712))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(_mm512_mullo_epi16(R2, k27), k3), _mm512_load_si512((const void *)(T + 3776))));
                      (void)R; }
                    { const __m512i W = WVEC(rec0, kg, 15);
                      __m512i R = _mm512_mullo_epi16(W, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(W, k27), _mm512_load_si512((const void *)(T + 3840))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R, k27), _mm512_load_si512((const void *)(T + 3904))));
                      const __m512i R2 = _mm512_mullo_epi16(R, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R2, k27), _mm512_load_si512((const void *)(T + 3968))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(_mm512_mullo_epi16(R2, k27), k3), _mm512_load_si512((const void *)(T + 4032))));
                      (void)R; }
                    { const __m512i W = WVEC(rec0, kg, 16);
                      __m512i R = _mm512_mullo_epi16(W, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(W, k27), _mm512_load_si512((const void *)(T + 4096))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R, k27), _mm512_load_si512((const void *)(T + 4160))));
                      const __m512i R2 = _mm512_mullo_epi16(R, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R2, k27), _mm512_load_si512((const void *)(T + 4224))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(_mm512_mullo_epi16(R2, k27), k3), _mm512_load_si512((const void *)(T + 4288))));
                      (void)R; }
                    { const __m512i W = WVEC(rec0, kg, 17);
                      __m512i R = _mm512_mullo_epi16(W, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(W, k27), _mm512_load_si512((const void *)(T + 4352))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R, k27), _mm512_load_si512((const void *)(T + 4416))));
                      const __m512i R2 = _mm512_mullo_epi16(R, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R2, k27), _mm512_load_si512((const void *)(T + 4480))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(_mm512_mullo_epi16(R2, k27), k3), _mm512_load_si512((const void *)(T + 4544))));
                      (void)R; }
                    { const __m512i W = WVEC(rec0, kg, 18);
                      __m512i R = _mm512_mullo_epi16(W, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(W, k27), _mm512_load_si512((const void *)(T + 4608))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R, k27), _mm512_load_si512((const void *)(T + 4672))));
                      const __m512i R2 = _mm512_mullo_epi16(R, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R2, k27), _mm512_load_si512((const void *)(T + 4736))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(_mm512_mullo_epi16(R2, k27), k3), _mm512_load_si512((const void *)(T + 4800))));
                      (void)R; }
                    { const __m512i W = WVEC(rec0, kg, 19);
                      __m512i R = _mm512_mullo_epi16(W, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(W, k27), _mm512_load_si512((const void *)(T + 4864))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R, k27), _mm512_load_si512((const void *)(T + 4928))));
                      const __m512i R2 = _mm512_mullo_epi16(R, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R2, k27), _mm512_load_si512((const void *)(T + 4992))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(_mm512_mullo_epi16(R2, k27), k3), _mm512_load_si512((const void *)(T + 5056))));
                      (void)R; }
                    { const __m512i W = WVEC(rec0, kg, 20);
                      __m512i R = _mm512_mullo_epi16(W, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(W, k27), _mm512_load_si512((const void *)(T + 5120))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R, k27), _mm512_load_si512((const void *)(T + 5184))));
                      const __m512i R2 = _mm512_mullo_epi16(R, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R2, k27), _mm512_load_si512((const void *)(T + 5248))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(_mm512_mullo_epi16(R2, k27), k3), _mm512_load_si512((const void *)(T + 5312))));
                      (void)R; }
                    { const __m512i W = WVEC(rec0, kg, 21);
                      __m512i R = _mm512_mullo_epi16(W, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(W, k27), _mm512_load_si512((const void *)(T + 5376))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R, k27), _mm512_load_si512((const void *)(T + 5440))));
                      const __m512i R2 = _mm512_mullo_epi16(R, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R2, k27), _mm512_load_si512((const void *)(T + 5504))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(_mm512_mullo_epi16(R2, k27), k3), _mm512_load_si512((const void *)(T + 5568))));
                      (void)R; }
                    { const __m512i W = WVEC(rec0, kg, 22);
                      __m512i R = _mm512_mullo_epi16(W, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(W, k27), _mm512_load_si512((const void *)(T + 5632))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R, k27), _mm512_load_si512((const void *)(T + 5696))));
                      const __m512i R2 = _mm512_mullo_epi16(R, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R2, k27), _mm512_load_si512((const void *)(T + 5760))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(_mm512_mullo_epi16(R2, k27), k3), _mm512_load_si512((const void *)(T + 5824))));
                      (void)R; }
                    { const __m512i W = WVEC(rec0, kg, 23);
                      __m512i R = _mm512_mullo_epi16(W, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(W, k27), _mm512_load_si512((const void *)(T + 5888))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R, k27), _mm512_load_si512((const void *)(T + 5952))));
                      const __m512i R2 = _mm512_mullo_epi16(R, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R2, k27), _mm512_load_si512((const void *)(T + 6016))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(_mm512_mullo_epi16(R2, k27), k3), _mm512_load_si512((const void *)(T + 6080))));
                      (void)R; }
                    { const __m512i W = WVEC(rec0, kg, 24);
                      __m512i R = _mm512_mullo_epi16(W, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(W, k27), _mm512_load_si512((const void *)(T + 6144))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R, k27), _mm512_load_si512((const void *)(T + 6208))));
                      const __m512i R2 = _mm512_mullo_epi16(R, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R2, k27), _mm512_load_si512((const void *)(T + 6272))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(_mm512_mullo_epi16(R2, k27), k3), _mm512_load_si512((const void *)(T + 6336))));
                      (void)R; }
                    { const __m512i W = WVEC(rec0, kg, 25);
                      __m512i R = _mm512_mullo_epi16(W, k27);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(W, k27), _mm512_load_si512((const void *)(T + 6400))));
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(_mm512_mulhi_epu16(R, k27), _mm512_load_si512((const void *)(T + 6464))));
                      (void)R; }
                    {
                      ilo0 = _mm512_add_epi32(ilo0, lo16(s0_0));
                      ihi0 = _mm512_add_epi32(ihi0, hi16(s0_0));
                      s0_0 = _mm512_setzero_si512();
                    }
                }
                { const __m512 dx = _mm512_set1_ps(dxs[p * 8]);
                  alo0 = fma16(ilo0, dlo0, dx, alo0); ahi0 = fma16(ihi0, dhi0, dx, ahi0); }
        }
        storev(Y, (g + 0) * 32, r0, r1, alo0); storev(Y, (g + 0) * 32 + 16, r0, r1, ahi0);
    }
}

void ktq10_gemv_packed(const void *pv, const void *X, float *Y, int64_t K, int64_t r0, int64_t r1) {
    static __thread uint8_t *tabs;
    static __thread int64_t cap;
    int64_t bytes, units;
    ktq10_gemv_lut_info(K, &bytes, &units);
    if (cap < bytes) { free(tabs); tabs = aligned_alloc(64, (size_t)(bytes + 63) & ~(size_t)63); cap = bytes; }
    ktq10_gemv_lut_build(X, K, tabs, 0, units);
    ktq10_gemv_lut_rows(pv, tabs, Y, K, r0, r1);
}
