// Generated by kurn (lowbit: lut serial g6 perm). Do not edit; edit the .kurn spec instead.
#include "kurn.h"
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <immintrin.h>
static inline float f16f(uint16_t h) { return _cvtsh_ss(h); }
static inline __m512i lo16(__m512i v) { return _mm512_cvtepi16_epi32(_mm512_castsi512_si256(v)); }
static inline __m512i hi16(__m512i v) { return _mm512_cvtepi16_epi32(_mm512_extracti64x4_epi64(v, 1)); }
static inline __m512 fma16(__m512i s, __m512 d, __m512 dx, __m512 acc) {
    return _mm512_fmadd_ps(_mm512_cvtepi32_ps(s), _mm512_mul_ps(d, dx), acc);
}
static inline __m256 fma8(__m512i s, __m256 d, __m256 dx, __m256 acc) {
    return _mm256_fmadd_ps(_mm512_cvtepi64_ps(s), _mm256_mul_ps(d, dx), acc);
}
/* lut=serial6m (perm): 6 chunks per 32-value unit, 32-entry int16 tables, 6 index words per row per unit (3.0625 bpw incl. scales) */

typedef struct { uint8_t qs[64]; uint16_t d; } nblock;
typedef struct { int64_t nrec_k, ngroups; uint8_t *buf; } packed_t;
#define REC_BYTES 3136
#define HDR_BYTES 64
#define UNIT_BYTES 384
#define WVEC(rec, kg, w) _mm512_loadu_si512((const void *)((rec) + HDR_BYTES + (kg) * UNIT_BYTES + 64 * (w)))
typedef struct { float d; int8_t qs[256]; int16_t bsums[16]; } xblock;

static inline void storev(float *y, int64_t row0, int64_t r0, int64_t r1, __m512 v) {
    if (row0 >= r0 && row0 + 16 <= r1) { _mm512_storeu_ps(y + row0, v); return; }
    uint32_t m = 0xFFFF;
    if (row0 < r0) m &= r0 - row0 >= 16 ? 0 : 0xFFFFu << (r0 - row0);
    if (row0 + 16 > r1) m &= (1u << (r1 > row0 ? (r1 - row0 > 16 ? 16 : r1 - row0) : 0)) - 1;
    _mm512_mask_storeu_ps(y + row0, (__mmask16)m, v);
}
void *ktq20_gemv_prepare(const void *W, int64_t K, int64_t N) {
    const nblock *w = (const nblock *)W;
    const int64_t nb = K / 256;
    packed_t *pk = malloc(sizeof *pk);
    pk->nrec_k = K / 256; pk->ngroups = (N + 31) / 32 + 0;
    const size_t bytes = (size_t)REC_BYTES * pk->nrec_k * pk->ngroups;
    pk->buf = aligned_alloc(64, (bytes + 63) & ~(size_t)63);
    memset(pk->buf, 0, bytes);
    for (int64_t gr = 0; gr < pk->ngroups; gr++)
        for (int64_t p = 0; p < pk->nrec_k; p++) {
            uint8_t *hp = pk->buf + ((size_t)gr * pk->nrec_k + p) * REC_BYTES;
            for (int row = 0; row < 32; row++) {
                const int64_t n = gr * 32 + row;
                if (n >= N) continue;  /* padding rows stay zero: d = 0 */
                const int64_t v0 = p * 256;
                const nblock *b = w + n * nb + v0 / 256;
                memcpy(hp + 2 * row, &b->d, 2);
                for (int kg = 0; kg < 8; kg++) {
                    uint16_t *wp = (uint16_t *)(hp + HDR_BYTES + kg * UNIT_BYTES) + row;
                    static const int CH_O[6] = {0, 6, 12, 18, 24, 30}, CH_L[6] = {6, 6, 6, 6, 6, 2};
                    for (int c = 0; c < 6; c++)
                        for (int pl = 0; pl < 2; pl++) {
                            int e = 0;
                            for (int j = 0; j < CH_L[c]; j++) {
                                const int v = (int)((v0 + kg * 32 + CH_O[c] + j) % 256);
                                const int q = ((b->qs[(v / 128) * 32 + v % 32] >> (2 * ((v % 128) / 32))) & 3);
                                e |= ((q >> pl) & 1) << j;
                            }
                            if (CH_L[c] == 6 && ((e >> 5) & 1)) e = (~e & 31) | 32;
                            const int slot = c * 2 + pl;
                            wp[(slot / 2) * 32] |= (uint16_t)(e << ((slot % 2) * 6));
                            (void)pl;
                        }
                }
            }
        }
    return pk;
}

static const int8_t LB_CST[6][64] __attribute__((aligned(64))) = {
    {-1, -1, -1, -1, 1, -1, -1, -1, -1, 1, -1, -1, 1, 1, -1, -1, -1, -1, 1, -1, 1, -1, 1, -1, -1, 1, 1, -1, 1, 1, 1, -1, -1, -1, -1, 1, 1, -1, -1, 1, -1, 1, -1, 1, 1, 1, -1, 1, -1, -1, 1, 1, 1, -1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1},
    {-1, -1, 0, 0, -1, -1, 0, 0, -1, -1, 0, 0, -1, -1, 0, 0, -1, -1, 0, 0, -1, -1, 0, 0, -1, -1, 0, 0, -1, -1, 0, 0, -1, -1, 0, 0, -1, -1, 0, 0, -1, -1, 0, 0, -1, -1, 0, 0, -1, -1, 0, 0, -1, -1, 0, 0, -1, -1, 0, 0, -1, -1, 0, 0},
    {1, -1, 0, 0, 1, -1, 0, 0, 1, -1, 0, 0, 1, -1, 0, 0, 1, -1, 0, 0, 1, -1, 0, 0, 1, -1, 0, 0, 1, -1, 0, 0, 1, -1, 0, 0, 1, -1, 0, 0, 1, -1, 0, 0, 1, -1, 0, 0, 1, -1, 0, 0, 1, -1, 0, 0, 1, -1, 0, 0, 1, -1, 0, 0},
    {0, 0, -1, -1, 0, 0, 1, -1, 0, 0, -1, 1, 0, 0, 1, 1, 0, 0, -1, -1, 0, 0, 1, -1, 0, 0, -1, 1, 0, 0, 1, 1, 0, 0, -1, -1, 0, 0, 1, -1, 0, 0, -1, 1, 0, 0, 1, 1, 0, 0, -1, -1, 0, 0, 1, -1, 0, 0, -1, 1, 0, 0, 1, 1},
    {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, 1, -1, -1, -1, 1, -1, -1, -1, 1, -1, -1, -1, -1, 1, -1, -1, -1, 1, -1, -1, -1, 1, -1, -1, -1, 1, -1, -1, 1, 1, -1, -1, 1, 1, -1, -1, 1, 1, -1, -1, 1, 1, -1, -1},
    {-1, -1, 1, -1, -1, -1, 1, -1, -1, -1, 1, -1, -1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, -1, 1, 1, -1, -1, 1, 1, -1, -1, 1, 1, -1, -1, 1, 1, -1, 1, 1, 1, -1, 1, 1, 1, -1, 1, 1, 1, -1, 1, 1, 1, -1}
};
static const int32_t LB_CORR[3][16] __attribute__((aligned(64))) = {
    {768, 512, 512, 256, 512, 256, 256, 0, 512, 256, 256, 0, 256, 0, 0, -256},
    {512, 256, 256, 0, 256, 0, 0, -256, 256, 0, 0, -256, 0, -256, -256, -512},
    {256, 0, 0, -256, 256, 0, 0, -256, 256, 0, 0, -256, 256, 0, 0, -256}
};
static inline int32_t ld32(const uint8_t *p) { int32_t v; memcpy(&v, p, 4); return v; }
static inline size_t lb_toff(int64_t K) { return ((size_t)8 * (K / 32) + 63) & ~(size_t)63; }

/* table buffer: float dxs[K/32] | int32 sx[K/32] | pad to 64 | 6 tables of 32 int16 per 32-value unit */
void ktq20_gemv_lut_info(int64_t K, int64_t *bytes, int64_t *units) {
    *bytes = (int64_t)(lb_toff(K) + (size_t)(K / 32) * 384);
    *units = K / 32;
}

void ktq20_gemv_lut_build(const void *X, int64_t K, void *tabs, int64_t u0, int64_t u1) {
    const xblock *xb = (const xblock *)X;
    float *dxs = (float *)tabs;
    int32_t *sx = (int32_t *)((uint8_t *)tabs + 4 * (K / 32));
    uint8_t *tb = (uint8_t *)tabs + lb_toff(K);
    uint8_t xu[32] __attribute__((aligned(64)));
    for (int64_t u = u0; u < u1; u++) {
        for (int64_t k = u * 1; k < (u + 1) * 1; k++) {
            int8_t *dst = (int8_t *)xu + 32 * (k - u * 1);
            { const xblock *b = xb + k / 8;
              memcpy(dst, b->qs + (k % 8) * 32, 32);
              dxs[k] = b->d * 0.5f; sx[k] = b->bsums[2 * (k % 8)] + b->bsums[2 * (k % 8) + 1]; }
        }
        for (int i = 0; i < 32; i++) xu[i] ^= 0x80;  /* x + 128 as u8 (vpdpbusd's unsigned operand) */
        uint8_t *t = tb + (size_t)u * 384;
            _mm256_store_si256((__m256i *)(t + 0), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 0)), _mm512_load_si512((const void *)LB_CST[0])), _mm512_set1_epi32(ld32(xu + 4)), _mm512_load_si512((const void *)LB_CST[1]))));
            _mm256_store_si256((__m256i *)(t + 32), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 0)), _mm512_load_si512((const void *)LB_CST[0])), _mm512_set1_epi32(ld32(xu + 4)), _mm512_load_si512((const void *)LB_CST[2]))));
            _mm256_store_si256((__m256i *)(t + 64), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 4)), _mm512_load_si512((const void *)LB_CST[3])), _mm512_set1_epi32(ld32(xu + 8)), _mm512_load_si512((const void *)LB_CST[4]))));
            _mm256_store_si256((__m256i *)(t + 96), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 4)), _mm512_load_si512((const void *)LB_CST[3])), _mm512_set1_epi32(ld32(xu + 8)), _mm512_load_si512((const void *)LB_CST[5]))));
            _mm256_store_si256((__m256i *)(t + 128), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 12)), _mm512_load_si512((const void *)LB_CST[0])), _mm512_set1_epi32(ld32(xu + 16)), _mm512_load_si512((const void *)LB_CST[1]))));
            _mm256_store_si256((__m256i *)(t + 160), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 12)), _mm512_load_si512((const void *)LB_CST[0])), _mm512_set1_epi32(ld32(xu + 16)), _mm512_load_si512((const void *)LB_CST[2]))));
            _mm256_store_si256((__m256i *)(t + 192), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 16)), _mm512_load_si512((const void *)LB_CST[3])), _mm512_set1_epi32(ld32(xu + 20)), _mm512_load_si512((const void *)LB_CST[4]))));
            _mm256_store_si256((__m256i *)(t + 224), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 16)), _mm512_load_si512((const void *)LB_CST[3])), _mm512_set1_epi32(ld32(xu + 20)), _mm512_load_si512((const void *)LB_CST[5]))));
            _mm256_store_si256((__m256i *)(t + 256), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[0]), _mm512_set1_epi32(ld32(xu + 24)), _mm512_load_si512((const void *)LB_CST[0])), _mm512_set1_epi32(ld32(xu + 28)), _mm512_load_si512((const void *)LB_CST[1]))));
            _mm256_store_si256((__m256i *)(t + 288), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[1]), _mm512_set1_epi32(ld32(xu + 24)), _mm512_load_si512((const void *)LB_CST[0])), _mm512_set1_epi32(ld32(xu + 28)), _mm512_load_si512((const void *)LB_CST[2]))));
            _mm256_store_si256((__m256i *)(t + 320), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[2]), _mm512_set1_epi32(ld32(xu + 28)), _mm512_load_si512((const void *)LB_CST[3]))));
            _mm256_store_si256((__m256i *)(t + 352), _mm512_cvtepi32_epi16(_mm512_dpbusd_epi32(_mm512_load_si512((const void *)LB_CORR[2]), _mm512_set1_epi32(ld32(xu + 28)), _mm512_load_si512((const void *)LB_CST[3]))));
    }
}

void ktq20_gemv_lut_rows(const void *pv, const void *tabs, float *Y, int64_t K, int64_t r0, int64_t r1) {
    const packed_t *pk = (const packed_t *)pv;
    const float *dxs = (const float *)tabs;
    const int32_t *sx = (const int32_t *)((const uint8_t *)tabs + 4 * (K / 32));
    const uint8_t *tb = (const uint8_t *)tabs + lb_toff(K);
    const __m512i zero = _mm512_setzero_si512(), k27 = _mm512_set1_epi16(27), k3 = _mm512_set1_epi16(3);
    (void)sx; (void)zero; (void)k27; (void)k3;
    const int64_t g0 = r0 / 32, g1 = (r1 + 31) / 32;
    for (int64_t g = g0; g < g1; g += 1) {
        __m512 alo0 = _mm512_setzero_ps(), ahi0 = _mm512_setzero_ps();
        for (int64_t p = 0; p < pk->nrec_k; p++) {
                const uint8_t *rec0 = pk->buf + ((size_t)(g + 0) * pk->nrec_k + p) * REC_BYTES;
                const __m512 dlo0 = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)rec0)), dhi0 = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)(rec0 + 32)));
                __m512i ilo0 = _mm512_setzero_si512(), ihi0 = _mm512_setzero_si512();
                __m512i s0_0 = _mm512_setzero_si512();
                __m512i s0_1 = _mm512_setzero_si512();
                for (int kg = 0; kg < 8; kg++) {
                    const int64_t k = p * 8 + kg;  /* unit index */
                    const uint8_t *T = tb + (size_t)k * 384;
                    { const __m512i W = WVEC(rec0, kg, 0);
                      { const __m512i v = _mm512_permutexvar_epi16(W, _mm512_load_si512((const void *)(T + 0)));
                        const __mmask32 neg = _mm512_test_epi16_mask(W, _mm512_set1_epi16(32));
                        s0_0 = _mm512_add_epi16(s0_0, _mm512_mask_sub_epi16(v, neg, zero, v)); }
                      { const __m512i v = _mm512_permutexvar_epi16(_mm512_srli_epi16(W, 6), _mm512_load_si512((const void *)(T + 0)));
                        const __mmask32 neg = _mm512_test_epi16_mask(W, _mm512_set1_epi16(2048));
                        s0_1 = _mm512_add_epi16(s0_1, _mm512_mask_sub_epi16(v, neg, zero, v)); }
                    }
                    { const __m512i W = WVEC(rec0, kg, 1);
                      { const __m512i v = _mm512_permutexvar_epi16(W, _mm512_load_si512((const void *)(T + 64)));
                        const __mmask32 neg = _mm512_test_epi16_mask(W, _mm512_set1_epi16(32));
                        s0_0 = _mm512_add_epi16(s0_0, _mm512_mask_sub_epi16(v, neg, zero, v)); }
                      { const __m512i v = _mm512_permutexvar_epi16(_mm512_srli_epi16(W, 6), _mm512_load_si512((const void *)(T + 64)));
                        const __mmask32 neg = _mm512_test_epi16_mask(W, _mm512_set1_epi16(2048));
                        s0_1 = _mm512_add_epi16(s0_1, _mm512_mask_sub_epi16(v, neg, zero, v)); }
                    }
                    { const __m512i W = WVEC(rec0, kg, 2);
                      { const __m512i v = _mm512_permutexvar_epi16(W, _mm512_load_si512((const void *)(T + 128)));
                        const __mmask32 neg = _mm512_test_epi16_mask(W, _mm512_set1_epi16(32));
                        s0_0 = _mm512_add_epi16(s0_0, _mm512_mask_sub_epi16(v, neg, zero, v)); }
                      { const __m512i v = _mm512_permutexvar_epi16(_mm512_srli_epi16(W, 6), _mm512_load_si512((const void *)(T + 128)));
                        const __mmask32 neg = _mm512_test_epi16_mask(W, _mm512_set1_epi16(2048));
                        s0_1 = _mm512_add_epi16(s0_1, _mm512_mask_sub_epi16(v, neg, zero, v)); }
                    }
                    { const __m512i W = WVEC(rec0, kg, 3);
                      { const __m512i v = _mm512_permutexvar_epi16(W, _mm512_load_si512((const void *)(T + 192)));
                        const __mmask32 neg = _mm512_test_epi16_mask(W, _mm512_set1_epi16(32));
                        s0_0 = _mm512_add_epi16(s0_0, _mm512_mask_sub_epi16(v, neg, zero, v)); }
                      { const __m512i v = _mm512_permutexvar_epi16(_mm512_srli_epi16(W, 6), _mm512_load_si512((const void *)(T + 192)));
                        const __mmask32 neg = _mm512_test_epi16_mask(W, _mm512_set1_epi16(2048));
                        s0_1 = _mm512_add_epi16(s0_1, _mm512_mask_sub_epi16(v, neg, zero, v)); }
                    }
                    { const __m512i W = WVEC(rec0, kg, 4);
                      { const __m512i v = _mm512_permutexvar_epi16(W, _mm512_load_si512((const void *)(T + 256)));
                        const __mmask32 neg = _mm512_test_epi16_mask(W, _mm512_set1_epi16(32));
                        s0_0 = _mm512_add_epi16(s0_0, _mm512_mask_sub_epi16(v, neg, zero, v)); }
                      { const __m512i v = _mm512_permutexvar_epi16(_mm512_srli_epi16(W, 6), _mm512_load_si512((const void *)(T + 256)));
                        const __mmask32 neg = _mm512_test_epi16_mask(W, _mm512_set1_epi16(2048));
                        s0_1 = _mm512_add_epi16(s0_1, _mm512_mask_sub_epi16(v, neg, zero, v)); }
                    }
                    { const __m512i W = WVEC(rec0, kg, 5);
                      s0_0 = _mm512_add_epi16(s0_0, _mm512_permutexvar_epi16(W, _mm512_load_si512((const void *)(T + 320))));
                      s0_1 = _mm512_add_epi16(s0_1, _mm512_permutexvar_epi16(_mm512_srli_epi16(W, 6), _mm512_load_si512((const void *)(T + 320))));
                    }
                    if (kg == 7) {
                      ilo0 = _mm512_add_epi32(ilo0, _mm512_add_epi32(_mm512_slli_epi32(lo16(s0_1), 1), lo16(s0_0)));
                      ihi0 = _mm512_add_epi32(ihi0, _mm512_add_epi32(_mm512_slli_epi32(hi16(s0_1), 1), hi16(s0_0)));
                      s0_0 = _mm512_setzero_si512();
                      s0_1 = _mm512_setzero_si512();
                    }
                }
                { int32_t st = 0; for (int kk = 0; kk < 8; kk++) st += sx[p * 8 + kk];
                  const __m512i sv = _mm512_set1_epi32(st);
                  ilo0 = _mm512_add_epi32(ilo0, sv); ihi0 = _mm512_add_epi32(ihi0, sv); }
                { const __m512 dx = _mm512_set1_ps(dxs[p * 8]);
                  alo0 = fma16(ilo0, dlo0, dx, alo0); ahi0 = fma16(ihi0, dhi0, dx, ahi0); }
        }
        storev(Y, (g + 0) * 32, r0, r1, alo0); storev(Y, (g + 0) * 32 + 16, r0, r1, ahi0);
    }
}

void ktq20_gemv_packed(const void *pv, const void *X, float *Y, int64_t K, int64_t r0, int64_t r1) {
    static __thread uint8_t *tabs;
    static __thread int64_t cap;
    int64_t bytes, units;
    ktq20_gemv_lut_info(K, &bytes, &units);
    if (cap < bytes) { free(tabs); tabs = aligned_alloc(64, (size_t)(bytes + 63) & ~(size_t)63); cap = bytes; }
    ktq20_gemv_lut_build(X, K, tabs, 0, units);
    ktq20_gemv_lut_rows(pv, tabs, Y, K, r0, r1);
}
