// Generated by kurn (generic recipe lowering). Do not edit; edit the .kurn spec instead.
#include "kurn.h"
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <immintrin.h>
static inline float f16f(uint16_t h) { return _cvtsh_ss(h); }

typedef struct { uint8_t qs[64]; uint16_t d; } nblock;
typedef struct { int64_t nrec_k, ngroups; uint8_t *buf; } packed_t;
#define REC_BYTES 1056
#define HDR_BYTES 32
#define KG_BYTES 128
#define CODE_BYTES 128

void *ktq20_vfy_prepare(const void *W, int64_t K, int64_t N) {
    const nblock *w = (const nblock *)W;
    const int64_t nb = K / 256;
    packed_t *pk = malloc(sizeof *pk);
    pk->nrec_k = K / 256; pk->ngroups = (N + 15) / 16 + 0;
    const size_t bytes = (size_t)REC_BYTES * pk->nrec_k * pk->ngroups;
    pk->buf = aligned_alloc(64, (bytes + 63) & ~(size_t)63);
    memset(pk->buf, 0, bytes);
    for (int64_t g = 0; g < pk->ngroups; g++)
        for (int64_t p = 0; p < pk->nrec_k; p++) {
            uint8_t *hp = pk->buf + ((size_t)g * pk->nrec_k + p) * REC_BYTES;
            for (int row = 0; row < 16; row++) {
                const int64_t n = g * 16 + row;
                if (n >= N) continue;  /* padding rows stay zero: d = 0 */
                const int64_t v0 = p * 256;
                const nblock *b = w + n * nb + v0 / 256;
                
                memcpy(hp + 2 * row, &b->d, 2);
                for (int kg = 0; kg < 8; kg++) {
                    uint8_t *rec_codes = hp + HDR_BYTES + kg * KG_BYTES;
                    int32_t wsum = 0;
                    for (int kk = 0; kk < 8; kk++)
                        for (int j = 0; j < 4; j++) {
                            const int v = (int)((v0 + kg * 32 + kk * 4 + j) % 256);
                            const int q = ((b->qs[(v / 128) * 32 + v % 32] >> (2 * ((v % 128) / 32))) & 3);
                            (void)wsum;
                            
                            const uint8_t u = q;
                            rec_codes[(kk / 4) * 64 + (row) * 4 + j] |= (uint8_t)(u << (2 * (kk & 3)));
                        }
                    
                }
            }
        }
    return pk;
}

typedef struct { float d; int8_t qs[256]; int16_t bsums[16]; } xblock;

static inline void storev(float *y, int64_t row0, int64_t r0, int64_t r1, __m512 v) {
    if (row0 >= r0 && row0 + 16 <= r1) { _mm512_storeu_ps(y + row0, v); return; }
    uint32_t m = 0xFFFF;
    if (row0 < r0) m &= 0xFFFFu << (r0 - row0);
    if (row0 + 16 > r1) m &= (1u << (r1 > row0 ? r1 - row0 : 0)) - 1;
    _mm512_mask_storeu_ps(y + row0, (__mmask16)m, v);
}

void ktq20_vfy_packed(const void *pv, const void *X, float *Y, int64_t K, int64_t N, int64_t M, int64_t r0, int64_t r1) {
    const packed_t *pk = (const packed_t *)pv;
    const int64_t nk = K / 32, nbx = K / 256;
    if (M > 4) abort();
    int32_t xw[4 * 1024 * 8], sx[4 * 1024];
    float dx[4 * 1024];
    (void)sx; (void)nbx;
    for (int64_t m = 0; m < 4; m++) {
    const xblock *xb = (const xblock *)X + (m < M ? m : 0) * nbx;  /* columns beyond M repeat column 0 */
    for (int64_t k = 0; k < nk; k++) {
        const xblock *b = xb + k / 8;
        memcpy(xw + (m * nk + k) * 8, b->qs + (k % 8) * 32, 32);
        sx[m * nk + k] = b->bsums[2 * (k % 8)] + b->bsums[2 * (k % 8) + 1];
        dx[m * nk + k] = b->d;
    }
    }
    const __m512i m4 = _mm512_set1_epi8((char)(0x0F)), m3 = _mm512_set1_epi8((char)(0x03));
    (void)m4; (void)m3;
    
    const int64_t g0 = r0 / 16, g1 = (r1 + 15) / 16;
    int64_t g = g0;
    for (; g < g1; g += 1) {
        __m512 a0_0 = _mm512_setzero_ps(); __m512 a0_1 = _mm512_setzero_ps(); __m512 a0_2 = _mm512_setzero_ps(); __m512 a0_3 = _mm512_setzero_ps();
        for (int64_t p = 0; p < pk->nrec_k; p++) {
                const uint8_t *rec0 = pk->buf + ((size_t)(g + 0) * pk->nrec_k + p) * REC_BYTES;
                const __m512 d0 = _mm512_cvtph_ps(_mm256_loadu_si256((const __m256i *)(rec0)));
                for (int kg = 0; kg < 8; kg++) {
                    const int64_t k = p * 8 + kg;
                    const __m512i c0_0 = _mm512_loadu_si512((const void *)(rec0 + HDR_BYTES + kg * KG_BYTES + 0));
                    const __m512i c0_1 = _mm512_loadu_si512((const void *)(rec0 + HDR_BYTES + kg * KG_BYTES + 64));
                    __m512i e0_0 = _mm512_set1_epi32(-1 * sx[0 * nk + k]), o0_0 = _mm512_setzero_si512();
                    __m512i e0_1 = _mm512_set1_epi32(-1 * sx[1 * nk + k]), o0_1 = _mm512_setzero_si512();
                    __m512i e0_2 = _mm512_set1_epi32(-1 * sx[2 * nk + k]), o0_2 = _mm512_setzero_si512();
                    __m512i e0_3 = _mm512_set1_epi32(-1 * sx[3 * nk + k]), o0_3 = _mm512_setzero_si512();
                    const __m512i x0_0 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 0]);
                    const __m512i x1_0 = _mm512_set1_epi32(xw[(1 * nk + k) * 8 + 0]);
                    const __m512i x2_0 = _mm512_set1_epi32(xw[(2 * nk + k) * 8 + 0]);
                    const __m512i x3_0 = _mm512_set1_epi32(xw[(3 * nk + k) * 8 + 0]);
                    { const __m512i u = _mm512_and_si512(c0_0, m3);
                      e0_0 = _mm512_dpbusd_epi32(e0_0, u, x0_0);
                      e0_1 = _mm512_dpbusd_epi32(e0_1, u, x1_0);
                      e0_2 = _mm512_dpbusd_epi32(e0_2, u, x2_0);
                      e0_3 = _mm512_dpbusd_epi32(e0_3, u, x3_0);
                    }
                    const __m512i x0_1 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 1]);
                    const __m512i x1_1 = _mm512_set1_epi32(xw[(1 * nk + k) * 8 + 1]);
                    const __m512i x2_1 = _mm512_set1_epi32(xw[(2 * nk + k) * 8 + 1]);
                    const __m512i x3_1 = _mm512_set1_epi32(xw[(3 * nk + k) * 8 + 1]);
                    { const __m512i u = _mm512_and_si512(_mm512_srli_epi16(c0_0, 2), m3);
                      o0_0 = _mm512_dpbusd_epi32(o0_0, u, x0_1);
                      o0_1 = _mm512_dpbusd_epi32(o0_1, u, x1_1);
                      o0_2 = _mm512_dpbusd_epi32(o0_2, u, x2_1);
                      o0_3 = _mm512_dpbusd_epi32(o0_3, u, x3_1);
                    }
                    const __m512i x0_2 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 2]);
                    const __m512i x1_2 = _mm512_set1_epi32(xw[(1 * nk + k) * 8 + 2]);
                    const __m512i x2_2 = _mm512_set1_epi32(xw[(2 * nk + k) * 8 + 2]);
                    const __m512i x3_2 = _mm512_set1_epi32(xw[(3 * nk + k) * 8 + 2]);
                    { const __m512i u = _mm512_and_si512(_mm512_srli_epi16(c0_0, 4), m3);
                      e0_0 = _mm512_dpbusd_epi32(e0_0, u, x0_2);
                      e0_1 = _mm512_dpbusd_epi32(e0_1, u, x1_2);
                      e0_2 = _mm512_dpbusd_epi32(e0_2, u, x2_2);
                      e0_3 = _mm512_dpbusd_epi32(e0_3, u, x3_2);
                    }
                    const __m512i x0_3 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 3]);
                    const __m512i x1_3 = _mm512_set1_epi32(xw[(1 * nk + k) * 8 + 3]);
                    const __m512i x2_3 = _mm512_set1_epi32(xw[(2 * nk + k) * 8 + 3]);
                    const __m512i x3_3 = _mm512_set1_epi32(xw[(3 * nk + k) * 8 + 3]);
                    { const __m512i u = _mm512_and_si512(_mm512_srli_epi16(c0_0, 6), m3);
                      o0_0 = _mm512_dpbusd_epi32(o0_0, u, x0_3);
                      o0_1 = _mm512_dpbusd_epi32(o0_1, u, x1_3);
                      o0_2 = _mm512_dpbusd_epi32(o0_2, u, x2_3);
                      o0_3 = _mm512_dpbusd_epi32(o0_3, u, x3_3);
                    }
                    const __m512i x0_4 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 4]);
                    const __m512i x1_4 = _mm512_set1_epi32(xw[(1 * nk + k) * 8 + 4]);
                    const __m512i x2_4 = _mm512_set1_epi32(xw[(2 * nk + k) * 8 + 4]);
                    const __m512i x3_4 = _mm512_set1_epi32(xw[(3 * nk + k) * 8 + 4]);
                    { const __m512i u = _mm512_and_si512(c0_1, m3);
                      e0_0 = _mm512_dpbusd_epi32(e0_0, u, x0_4);
                      e0_1 = _mm512_dpbusd_epi32(e0_1, u, x1_4);
                      e0_2 = _mm512_dpbusd_epi32(e0_2, u, x2_4);
                      e0_3 = _mm512_dpbusd_epi32(e0_3, u, x3_4);
                    }
                    const __m512i x0_5 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 5]);
                    const __m512i x1_5 = _mm512_set1_epi32(xw[(1 * nk + k) * 8 + 5]);
                    const __m512i x2_5 = _mm512_set1_epi32(xw[(2 * nk + k) * 8 + 5]);
                    const __m512i x3_5 = _mm512_set1_epi32(xw[(3 * nk + k) * 8 + 5]);
                    { const __m512i u = _mm512_and_si512(_mm512_srli_epi16(c0_1, 2), m3);
                      o0_0 = _mm512_dpbusd_epi32(o0_0, u, x0_5);
                      o0_1 = _mm512_dpbusd_epi32(o0_1, u, x1_5);
                      o0_2 = _mm512_dpbusd_epi32(o0_2, u, x2_5);
                      o0_3 = _mm512_dpbusd_epi32(o0_3, u, x3_5);
                    }
                    const __m512i x0_6 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 6]);
                    const __m512i x1_6 = _mm512_set1_epi32(xw[(1 * nk + k) * 8 + 6]);
                    const __m512i x2_6 = _mm512_set1_epi32(xw[(2 * nk + k) * 8 + 6]);
                    const __m512i x3_6 = _mm512_set1_epi32(xw[(3 * nk + k) * 8 + 6]);
                    { const __m512i u = _mm512_and_si512(_mm512_srli_epi16(c0_1, 4), m3);
                      e0_0 = _mm512_dpbusd_epi32(e0_0, u, x0_6);
                      e0_1 = _mm512_dpbusd_epi32(e0_1, u, x1_6);
                      e0_2 = _mm512_dpbusd_epi32(e0_2, u, x2_6);
                      e0_3 = _mm512_dpbusd_epi32(e0_3, u, x3_6);
                    }
                    const __m512i x0_7 = _mm512_set1_epi32(xw[(0 * nk + k) * 8 + 7]);
                    const __m512i x1_7 = _mm512_set1_epi32(xw[(1 * nk + k) * 8 + 7]);
                    const __m512i x2_7 = _mm512_set1_epi32(xw[(2 * nk + k) * 8 + 7]);
                    const __m512i x3_7 = _mm512_set1_epi32(xw[(3 * nk + k) * 8 + 7]);
                    { const __m512i u = _mm512_and_si512(_mm512_srli_epi16(c0_1, 6), m3);
                      o0_0 = _mm512_dpbusd_epi32(o0_0, u, x0_7);
                      o0_1 = _mm512_dpbusd_epi32(o0_1, u, x1_7);
                      o0_2 = _mm512_dpbusd_epi32(o0_2, u, x2_7);
                      o0_3 = _mm512_dpbusd_epi32(o0_3, u, x3_7);
                    }
                    a0_0 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_add_epi32(e0_0, o0_0)), _mm512_mul_ps(d0, _mm512_set1_ps(dx[0 * nk + k])), a0_0);
                    a0_1 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_add_epi32(e0_1, o0_1)), _mm512_mul_ps(d0, _mm512_set1_ps(dx[1 * nk + k])), a0_1);
                    a0_2 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_add_epi32(e0_2, o0_2)), _mm512_mul_ps(d0, _mm512_set1_ps(dx[2 * nk + k])), a0_2);
                    a0_3 = _mm512_fmadd_ps(_mm512_cvtepi32_ps(_mm512_add_epi32(e0_3, o0_3)), _mm512_mul_ps(d0, _mm512_set1_ps(dx[3 * nk + k])), a0_3);
                }
        }
        storev(Y + 0 * N, (g + 0) * 16, r0, r1, a0_0);
        if (1 < M) storev(Y + 1 * N, (g + 0) * 16, r0, r1, a0_1);
        if (2 < M) storev(Y + 2 * N, (g + 0) * 16, r0, r1, a0_2);
        if (3 < M) storev(Y + 3 * N, (g + 0) * 16, r0, r1, a0_3);
    }
}
void ktq20_vfy(const void *W, const void *X, float *Y, int64_t K, int64_t N, int64_t M, int64_t n0, int64_t n1) {
    (void)W; (void)X; (void)Y; (void)K; (void)N; (void)M; (void)n0; (void)n1; abort();
}
