// generated by kurn: nvfp4 gemv for CUDA (NVFP4: E2M1 codes, UE4M3 scale per 16 (per-tensor scale applied by the caller))
// op=gemv weights=nvfp4 arch=sm_80 layout=split tpr=32 rpb=4 sub=2 unroll=4 cols=2 minb=0 mins=none unpack=none xlayout=split
#ifdef KURN_EMU
#include "kurn_cuemu.h"
#define KURN_H2F(h) kemu_h2f((uint16_t)(h))
#define KURN_F2H(f) kemu_f2h(f)
#define KURN_POPC(x) __builtin_popcount(x)
#else
#include <cuda_runtime.h>
#include <cuda_fp16.h>
#include <stdint.h>
#include <string.h>
#define KURN_H2F(h) __half2float(__ushort_as_half((unsigned short)(h)))
#define KURN_F2H(f) __half_as_ushort(__float2half_rn(f))
#define KURN_POPC(x) __popc(x)
#define KURN_LAUNCH(kernel, grid, block, stream, ...) kernel<<<(grid), (block), 0, (stream)>>>(__VA_ARGS__)
#define KURN_LAUNCH_SMEM(kernel, grid, block, smem, stream, ...) kernel<<<(grid), (block), (smem), (stream)>>>(__VA_ARGS__)
#endif
#define KURN_FULL 0xffffffffu
#define KURN_FN static __device__ __forceinline__ __attribute__((unused))

KURN_FN uint32_t kld_u8(const uint8_t *p) { return *p; }
KURN_FN uint32_t kld_u16(const uint8_t *p) {
#ifdef KURN_EMU
  kemu_check_align(p, 2, "16-bit load");
  uint16_t v; memcpy(&v, p, 2); return v;
#else
  return *(const uint16_t *)p;
#endif
}
KURN_FN uint32_t kld_u32(const void *p) {
#ifdef KURN_EMU
  kemu_check_align(p, 4, "32-bit load");
  uint32_t v; memcpy(&v, p, 4); return v;
#else
  return *(const uint32_t *)p;
#endif
}
KURN_FN uint32_t kld_u32_b2(const uint8_t *p) { return kld_u16(p) | (kld_u16(p + 2) << 16); }
KURN_FN uint2 kld_v2(const void *p) {
#ifdef KURN_EMU
  kemu_check_align(p, 8, "8-byte vector load");
  uint2 v; memcpy(&v, p, 8); return v;
#else
  return *(const uint2 *)p;
#endif
}
KURN_FN uint4 kld_v4(const void *p) {
#ifdef KURN_EMU
  kemu_check_align(p, 16, "16-byte vector load");
  uint4 v; memcpy(&v, p, 16); return v;
#else
  return *(const uint4 *)p;
#endif
}
KURN_FN float kld_f32(const uint8_t *p) { return __uint_as_float(kld_u32(p)); }
KURN_FN void kst_u16(uint8_t *p, uint32_t v) {
#ifdef KURN_EMU
  kemu_check_align(p, 2, "16-bit store");
  uint16_t x = (uint16_t)v; memcpy(p, &x, 2);
#else
  *(uint16_t *)p = (uint16_t)v;
#endif
}
KURN_FN void kst_u32(void *p, uint32_t v) {
#ifdef KURN_EMU
  kemu_check_align(p, 4, "32-bit store");
  memcpy(p, &v, 4);
#else
  *(uint32_t *)p = v;
#endif
}

// f32 -> q8_0 blocks (ggml quantize_row_q8_0_ref rounding), one warp per block of 32.
// split != 0: int8 plane Q[M][K] plus float scale plane D[M][K/32] (scale = the fp16-rounded d)
static __global__ void __attribute__((unused)) kg_quant_q8_0(const float *__restrict__ X, uint8_t *__restrict__ Q, float *__restrict__ D, int K, int M, int split) {
  const int lane = threadIdx.x & 31, nb = K / 32;
  const long blk = (long)blockIdx.x * (blockDim.x / 32) + (threadIdx.x >> 5);
  const bool live = blk < (long)M * nb;
  const long bb = live ? blk : 0;
  const int m = (int)(bb / nb), c = (int)(bb % nb);
  const float v = X[(size_t)m * K + c * 32 + lane];
  float amax = fabsf(v);
#pragma unroll
  for (int o = 16; o; o >>= 1) amax = fmaxf(amax, __shfl_xor_sync(KURN_FULL, amax, o));
  const float d = amax / 127.f, id = d != 0.f ? 1.f / d : 0.f;
  const int q = (int)roundf(v * id);
  if (!live) return;
  if (!split) {
    uint8_t *b = Q + ((size_t)m * nb + c) * 34;
    if (lane == 0) kst_u16(b, KURN_F2H(d));
    b[2 + lane] = (uint8_t)(int8_t)q;
  } else {
    Q[(size_t)m * K + c * 32 + lane] = (uint8_t)(int8_t)q;
    if (lane == 0) D[(size_t)m * nb + c] = KURN_H2F(KURN_F2H(d));
  }
}
// MXFP4/NVFP4 (2 * E2M1): 4 nibble indices (one per byte) -> 4 int8 codebook values
KURN_FN uint32_t kfp4(uint32_t q) {
  const uint32_t sel = (q & 0x7) | ((q >> 4) & 0x70) | ((q >> 8) & 0x700) | ((q >> 12) & 0x7000);
  const uint32_t lo = __byte_perm(0x03020100u, 0x0c080604u, sel), hi = __byte_perm(0xfdfeff00u, 0xf4f8fafcu, sel);
  const uint32_t m = ((q >> 3) & 0x01010101u) * 0xFFu;
  return (lo & ~m) | (hi & m);
}
// E8M0 scale with ggml's 1/2 for the doubled codes: 2^(e - 128); e == 0 -> 0 (kurn.mx's documented corner)
KURN_FN float ke8m0h(uint32_t e) { return __uint_as_float(e << 23) * 0.5f; }
// UE4M3 / 2 (ggml_ue4m3_to_fp32); 0 and 0x7F (NaN) -> 0
KURN_FN float kue4m3h(uint32_t u) {
  u &= 0x7Fu;
  if (u == 0x7Fu) return 0.f;
  const uint32_t e = u >> 3, m = u & 7u;
  return e ? __uint_as_float(((e + 119u) << 23) | (m << 20)) : (float)m * 0.0009765625f;
}
KURN_FN uint32_t kld_u32_b1(const uint8_t *p) {
  return (uint32_t)p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);
}
#define XD(x, c) ((x)[c])
#define XP(x, c) ((x) + (size_t)(c) * 32)

#define COLS 2
#define SUB 2
KURN_FN void kunit(const uint8_t *__restrict__ wq, const uint8_t *__restrict__ ws, int u, int p,
                                             const uint8_t *__restrict__ xb, const int *xo, const float *__restrict__ xdb, float *acc, const uint32_t *__restrict__ tab) {
  (void)ws; (void)tab;
  uint32_t q[2];
  { const uint2 t = kld_v2(wq + (size_t)u * 16 + p * 8); q[0] = t.x; q[1] = t.y; }
  const uint32_t sc = kld_u16(ws + 2 * (size_t)u);
  const float d0 = kue4m3h(sc & 0xFFu), d1 = kue4m3h(sc >> 8);
  uint32_t lo[2], hi[2];
#pragma unroll
  for (int i = 0; i < 2; i++) { lo[i] = kfp4(q[i] & 0x0F0F0F0Fu); hi[i] = kfp4((q[i] >> 4) & 0x0F0F0F0Fu); }
#pragma unroll
  for (int j = 0; j < COLS; j++) {
    int s0 = 0, s1 = 0;
#pragma unroll
    for (int i = 0; i < 2; i++) {
      const int wi = p * 2 + i, sbk = wi >> 1, ol = 16 * sbk + 4 * (wi & 1);
      const int xl = (int)kld_u32(XP((xb + xo[j]), u) + ol), xh = (int)kld_u32(XP((xb + xo[j]), u) + ol + 8);
      const int t = __dp4a((int)lo[i], xl, __dp4a((int)hi[i], xh, 0));
      if (sbk) s1 += t; else s0 += t;
    }
    acc[j] += XD((xdb + (xo[j] >> 5)), u) * (d0 * (float)s0 + d1 * (float)s1);
  }
}

static __global__ void __launch_bounds__(128, 1)
kg_gemv(const uint8_t *__restrict__ W, const uint8_t *__restrict__ X, float *__restrict__ Y, int N, int K, int M) {
  const uint32_t *tab = nullptr; (void)tab;
  const int lr = threadIdx.x / 32, lid = threadIdx.x % 32;
  const int row = blockIdx.x * 4 + lr, wrow = row < N ? row : N - 1;
  const int col0 = blockIdx.y * COLS;
  const uint8_t *wq = W + (size_t)wrow * ((size_t)K * 16 / 32);
  const uint8_t *ws = W + (size_t)N * ((size_t)K * 16 / 32) + (size_t)wrow * ((size_t)K / 64 * 4);
  int xo[COLS];  // 32-bit column offsets (columns past M repeat the last one; their results are not stored)
  float acc[COLS];
  #pragma unroll
  for (int j = 0; j < COLS; j++) { xo[j] = min(col0 + j, M - 1) * K; acc[j] = 0.f; }
  const float *xdb = (const float *)(X + (size_t)M * K);
  const int work = K / 32 * SUB;
  int w0 = lid;
  // main loop without bounds checks, so the 4 units' loads can all be issued before their math
  for (; w0 + 96 < work; w0 += 128) {
    #pragma unroll
    for (int k = 0; k < 4; k++) {
      const int w = w0 + k * 32;
      kunit(wq, ws, w / SUB, w % SUB, X, xo, xdb, acc, tab);
    }
  }
  for (; w0 < work; w0 += 32) kunit(wq, ws, w0 / SUB, w0 % SUB, X, xo, xdb, acc, tab);
  #pragma unroll
  for (int j = 0; j < COLS; j++) {
    float v = acc[j];
    v += __shfl_xor_sync(KURN_FULL, v, 16);
    v += __shfl_xor_sync(KURN_FULL, v, 8);
    v += __shfl_xor_sync(KURN_FULL, v, 4);
    v += __shfl_xor_sync(KURN_FULL, v, 2);
    v += __shfl_xor_sync(KURN_FULL, v, 1);
    if (lid == 0 && row < N && col0 + j < M) Y[(size_t)(col0 + j) * N + row] = v;
  }
}

// native ggml blocks -> split layout: quant plane [N][((size_t)K * 16 / 32)] then scale plane [N][K/64 * 4]
static __global__ void kg_repack(const uint8_t *__restrict__ W, uint8_t *__restrict__ P, int N, int K) {
  const int nb = K / 64;
  const long i = (long)blockIdx.x * blockDim.x + threadIdx.x;
  if (i >= (long)N * nb) return;
  const int r = (int)(i / nb), bl = (int)(i % nb);
  const uint8_t *src = W + (size_t)r * ((size_t)K / 64 * 36) + (size_t)bl * 36;
  uint8_t *q = P + (size_t)r * ((size_t)K * 16 / 32) + (size_t)bl * 32;
  uint8_t *s = P + (size_t)N * ((size_t)K * 16 / 32) + (size_t)r * ((size_t)K / 64 * 4) + (size_t)bl * 4;
  for (int i = 0; i < 32; i++) q[0 + i] = src[4 + i];
  for (int i = 0; i < 4; i++) s[i] = src[i];
}

extern "C" {
const char *kg_config(void) { return "op=gemv weights=nvfp4 arch=sm_80 layout=split tpr=32 rpb=4 sub=2 unroll=4 cols=2 minb=0 mins=none unpack=none xlayout=split"; }
int kg_act(void) { return 0; }  // 0: kg_quant -> q8 activations; reference from kg_xblocks
int kg_check_shape(int N, int K, int M) { return (N > 0 && M > 0 && K > 0 && K % 64 == 0) ? 0 : -1; }
size_t kg_prep_bytes(int N, int K) { (void)N; (void)K; return (size_t)N * (((size_t)K * 16 / 32) + ((size_t)K / 64 * 4)); }
size_t kg_xbytes(int K, int M) { return (size_t)M * K + (size_t)M * (K / 32) * 4; }
int kg_prepare(const void *W, void *Wp, int N, int K, cudaStream_t s) {
  const long nblk = (long)N * (K / 64);
  KURN_LAUNCH(kg_repack, dim3((unsigned)((nblk + 127) / 128)), dim3(128), s, (const uint8_t *)W, (uint8_t *)Wp, N, K);
#ifdef KURN_EMU
  return 0;
#else
  return (int)cudaGetLastError();
#endif
}
int kg_quant(const float *X, void *Xq, int K, int M, cudaStream_t s) {
  KURN_LAUNCH(kg_quant_q8_0, dim3((unsigned)(((long)M * (K / 32) + 3) / 4)), dim3(128), s, X, (uint8_t *)Xq, (float *)((uint8_t *)Xq + (size_t)M * K), K, M, 1);
#ifdef KURN_EMU
  return 0;
#else
  return (int)cudaGetLastError();
#endif
}
size_t kg_xblock_bytes(int K, int M) { return (size_t)M * (K / 32) * 34; }
int kg_xblocks(const float *X, void *Xb, int K, int M, cudaStream_t s) {
  KURN_LAUNCH(kg_quant_q8_0, dim3((unsigned)(((long)M * (K / 32) + 3) / 4)), dim3(128), s, X, (uint8_t *)Xb, (float *)nullptr, K, M, 0);
#ifdef KURN_EMU
  return 0;
#else
  return (int)cudaGetLastError();
#endif
}
int kg_run(const void *W, const void *Xq, float *Y, int N, int K, int M, cudaStream_t s) {
  if (kg_check_shape(N, K, M)) return -1;
  KURN_LAUNCH(kg_gemv, dim3((unsigned)((N + 4 - 1) / 4), (unsigned)((M + 2 - 1) / 2)), dim3(128), s, (const uint8_t *)W, (const uint8_t *)Xq, Y, N, K, M);
#ifdef KURN_EMU
  return 0;
#else
  return (int)cudaGetLastError();
#endif
}
}
