// generated by kurn: q2_0 gemv for CUDA (2-bit / ternary Bonsai, value = d*(q-1))
// op=gemv weights=q2_0 arch=sm_80 layout=native tpr=32 rpb=4 sub=1 unroll=2 cols=1 minb=0 mins=none unpack=none
#ifdef KURN_EMU
#include "kurn_cuemu.h"
#define KURN_H2F(h) kemu_h2f((uint16_t)(h))
#define KURN_F2H(f) kemu_f2h(f)
#define KURN_POPC(x) __builtin_popcount(x)
#else
#include <cuda_runtime.h>
#include <cuda_fp16.h>
#include <stdint.h>
#include <string.h>
#define KURN_H2F(h) __half2float(__ushort_as_half((unsigned short)(h)))
#define KURN_F2H(f) __half_as_ushort(__float2half_rn(f))
#define KURN_POPC(x) __popc(x)
#define KURN_LAUNCH(kernel, grid, block, stream, ...) kernel<<<(grid), (block), 0, (stream)>>>(__VA_ARGS__)
#endif
#define KURN_FULL 0xffffffffu
#define KURN_FN static __device__ __forceinline__ __attribute__((unused))

KURN_FN uint32_t kld_u8(const uint8_t *p) { return *p; }
KURN_FN uint32_t kld_u16(const uint8_t *p) {
#ifdef KURN_EMU
  kemu_check_align(p, 2, "16-bit load");
  uint16_t v; memcpy(&v, p, 2); return v;
#else
  return *(const uint16_t *)p;
#endif
}
KURN_FN uint32_t kld_u32(const void *p) {
#ifdef KURN_EMU
  kemu_check_align(p, 4, "32-bit load");
  uint32_t v; memcpy(&v, p, 4); return v;
#else
  return *(const uint32_t *)p;
#endif
}
KURN_FN uint32_t kld_u32_b2(const uint8_t *p) { return kld_u16(p) | (kld_u16(p + 2) << 16); }
KURN_FN uint2 kld_v2(const void *p) {
#ifdef KURN_EMU
  kemu_check_align(p, 8, "8-byte vector load");
  uint2 v; memcpy(&v, p, 8); return v;
#else
  return *(const uint2 *)p;
#endif
}
KURN_FN uint4 kld_v4(const void *p) {
#ifdef KURN_EMU
  kemu_check_align(p, 16, "16-byte vector load");
  uint4 v; memcpy(&v, p, 16); return v;
#else
  return *(const uint4 *)p;
#endif
}
KURN_FN float kld_f32(const uint8_t *p) { return __uint_as_float(kld_u32(p)); }
KURN_FN void kst_u16(uint8_t *p, uint32_t v) {
#ifdef KURN_EMU
  kemu_check_align(p, 2, "16-bit store");
  uint16_t x = (uint16_t)v; memcpy(p, &x, 2);
#else
  *(uint16_t *)p = (uint16_t)v;
#endif
}
KURN_FN void kst_u32(void *p, uint32_t v) {
#ifdef KURN_EMU
  kemu_check_align(p, 4, "32-bit store");
  memcpy(p, &v, 4);
#else
  *(uint32_t *)p = v;
#endif
}

// f32 -> q8_0 blocks (ggml quantize_row_q8_0_ref rounding), one warp per block of 32.
// split != 0: int8 plane Q[M][K] plus float scale plane D[M][K/32] (scale = the fp16-rounded d)
static __global__ void __attribute__((unused)) kg_quant_q8_0(const float *__restrict__ X, uint8_t *__restrict__ Q, float *__restrict__ D, int K, int M, int split) {
  const int lane = threadIdx.x & 31, nb = K / 32;
  const long blk = (long)blockIdx.x * (blockDim.x / 32) + (threadIdx.x >> 5);
  const bool live = blk < (long)M * nb;
  const long bb = live ? blk : 0;
  const int m = (int)(bb / nb), c = (int)(bb % nb);
  const float v = X[(size_t)m * K + c * 32 + lane];
  float amax = fabsf(v);
#pragma unroll
  for (int o = 16; o; o >>= 1) amax = fmaxf(amax, __shfl_xor_sync(KURN_FULL, amax, o));
  const float d = amax / 127.f, id = d != 0.f ? 1.f / d : 0.f;
  const int q = (int)roundf(v * id);
  if (!live) return;
  if (!split) {
    uint8_t *b = Q + ((size_t)m * nb + c) * 34;
    if (lane == 0) kst_u16(b, KURN_F2H(d));
    b[2 + lane] = (uint8_t)(int8_t)q;
  } else {
    Q[(size_t)m * K + c * 32 + lane] = (uint8_t)(int8_t)q;
    if (lane == 0) D[(size_t)m * nb + c] = KURN_H2F(KURN_F2H(d));
  }
}
#define XD(x, c) KURN_H2F(kld_u16((x) + (size_t)(c) * 34))
#define XQ(x, c, off) (int)kld_u32_b2((x) + (size_t)(c) * 34 + 2 + (off))

#define COLS 1
#define SUB 1
KURN_FN void kunit(const uint8_t *__restrict__ wq, const uint8_t *__restrict__ ws, int u, int p,
                                             const uint8_t *const *xr, float *acc, const uint32_t *__restrict__ tab) {
  (void)ws; (void)tab;
  const uint8_t *b = wq + (size_t)u * 18;
  const float dw = KURN_H2F(kld_u16(b));
  uint32_t q[4];
  for (int i = 0; i < 4; i++) q[i] = kld_u32_b2(b + 2 + p * 16 + 4 * i);
  uint32_t e[16];
#pragma unroll
  for (int k = 0; k < 16; k++) {
    const uint32_t x = (q[k >> 2] >> (8 * (k & 3))) & 0xFF;
    e[k] = __vsub4((x | (x << 6) | (x << 12) | (x << 18)) & 0x03030303u, 0x01010101u);
  }
  const int v0 = p * 64;  // first value of this lane within the unit
#pragma unroll
  for (int j = 0; j < COLS; j++) {
    float a = 0.f;
#pragma unroll
    for (int ch = 0; ch < 2; ch++) {
      const int cc = u * 2 + ((v0 + ch * 32) >> 5);
      int s = 0;
#pragma unroll
      for (int w = 0; w < 8; w++) s = __dp4a((int)e[ch * 8 + w], XQ(xr[j], cc, ((v0 + ch * 32) & 31) + 4 * w), s);
      a += XD(xr[j], cc) * (float)s;
    }
    acc[j] += dw * a;
  }
}

static __global__ void __launch_bounds__(128)
kg_gemv(const uint8_t *__restrict__ W, const uint8_t *__restrict__ X, float *__restrict__ Y, int N, int K, int M) {
  const uint32_t *tab = nullptr; (void)tab;
  const int lr = threadIdx.x / 32, lid = threadIdx.x % 32;
  const int row = blockIdx.x * 4 + lr, wrow = row < N ? row : N - 1;
  const int col0 = blockIdx.y * COLS;
  const uint8_t *wq = W + (size_t)wrow * ((size_t)K / 64 * 18);
  const uint8_t *ws = wq;
  const uint8_t *xr[COLS];
  float acc[COLS];
  #pragma unroll
  for (int j = 0; j < COLS; j++) { xr[j] = X + (size_t)min(col0 + j, M - 1) * ((size_t)K / 32 * 34); acc[j] = 0.f; }
  const int work = K / 64 * SUB;
  for (int w0 = lid; w0 < work; w0 += 64) {
    #pragma unroll
    for (int k = 0; k < 2; k++) {
      const int w = w0 + k * 32;
      if (w < work) kunit(wq, ws, w / SUB, w % SUB, xr, acc, tab);
    }
  }
  #pragma unroll
  for (int j = 0; j < COLS; j++) {
    float v = acc[j];
    v += __shfl_xor_sync(KURN_FULL, v, 16);
    v += __shfl_xor_sync(KURN_FULL, v, 8);
    v += __shfl_xor_sync(KURN_FULL, v, 4);
    v += __shfl_xor_sync(KURN_FULL, v, 2);
    v += __shfl_xor_sync(KURN_FULL, v, 1);
    if (lid == 0 && row < N && col0 + j < M) Y[(size_t)(col0 + j) * N + row] = v;
  }
}

extern "C" {
const char *kg_config(void) { return "op=gemv weights=q2_0 arch=sm_80 layout=native tpr=32 rpb=4 sub=1 unroll=2 cols=1 minb=0 mins=none unpack=none"; }
int kg_check_shape(int N, int K, int M) { return (N > 0 && M > 0 && K > 0 && K % 64 == 0) ? 0 : -1; }
size_t kg_prep_bytes(int N, int K) { (void)N; (void)K; return 0; }
size_t kg_xbytes(int K, int M) { return (size_t)M * ((size_t)K / 32 * 34); }
int kg_prepare(const void *W, void *Wp, int N, int K, cudaStream_t s) {
  (void)W; (void)Wp; (void)N; (void)K; (void)s;
  return 0;
}
int kg_quant(const float *X, void *Xq, int K, int M, cudaStream_t s) {
  KURN_LAUNCH(kg_quant_q8_0, dim3((unsigned)(((long)M * (K / 32) + 3) / 4)), dim3(128), s, X, (uint8_t *)Xq, (float *)nullptr, K, M, 0);
#ifdef KURN_EMU
  return 0;
#else
  return (int)cudaGetLastError();
#endif
}
size_t kg_xblock_bytes(int K, int M) { return (size_t)M * (K / 32) * 34; }
int kg_xblocks(const float *X, void *Xb, int K, int M, cudaStream_t s) {
  KURN_LAUNCH(kg_quant_q8_0, dim3((unsigned)(((long)M * (K / 32) + 3) / 4)), dim3(128), s, X, (uint8_t *)Xb, (float *)nullptr, K, M, 0);
#ifdef KURN_EMU
  return 0;
#else
  return (int)cudaGetLastError();
#endif
}
int kg_run(const void *W, const void *Xq, float *Y, int N, int K, int M, cudaStream_t s) {
  if (kg_check_shape(N, K, M)) return -1;
  KURN_LAUNCH(kg_gemv, dim3((unsigned)((N + 4 - 1) / 4), (unsigned)((M + 1 - 1) / 1)), dim3(128), s, (const uint8_t *)W, (const uint8_t *)Xq, Y, N, K, M);
#ifdef KURN_EMU
  return 0;
#else
  return (int)cudaGetLastError();
#endif
}
}
