// generated by kurn: q4_0 gemm for CUDA (4-bit, value = d*(q-8))
// op=gemm weights=q4_0 arch=sm_80 layout=split bm=64 bn=64 wm=2 wn=2 bkb=2 pipe=async3 pad=16 minb=0
#ifdef KURN_EMU
#include "kurn_cuemu.h"
#define KURN_H2F(h) kemu_h2f((uint16_t)(h))
#define KURN_F2H(f) kemu_f2h(f)
#define KURN_POPC(x) __builtin_popcount(x)
#else
#include <cuda_runtime.h>
#include <cuda_fp16.h>
#include <stdint.h>
#include <string.h>
#define KURN_H2F(h) __half2float(__ushort_as_half((unsigned short)(h)))
#define KURN_F2H(f) __half_as_ushort(__float2half_rn(f))
#define KURN_POPC(x) __popc(x)
#define KURN_LAUNCH(kernel, grid, block, stream, ...) kernel<<<(grid), (block), 0, (stream)>>>(__VA_ARGS__)
#endif
#define KURN_FULL 0xffffffffu
#define KURN_FN static __device__ __forceinline__ __attribute__((unused))

KURN_FN uint32_t kld_u8(const uint8_t *p) { return *p; }
KURN_FN uint32_t kld_u16(const uint8_t *p) {
#ifdef KURN_EMU
  kemu_check_align(p, 2, "16-bit load");
  uint16_t v; memcpy(&v, p, 2); return v;
#else
  return *(const uint16_t *)p;
#endif
}
KURN_FN uint32_t kld_u32(const void *p) {
#ifdef KURN_EMU
  kemu_check_align(p, 4, "32-bit load");
  uint32_t v; memcpy(&v, p, 4); return v;
#else
  return *(const uint32_t *)p;
#endif
}
KURN_FN uint32_t kld_u32_b2(const uint8_t *p) { return kld_u16(p) | (kld_u16(p + 2) << 16); }
KURN_FN uint2 kld_v2(const void *p) {
#ifdef KURN_EMU
  kemu_check_align(p, 8, "8-byte vector load");
  uint2 v; memcpy(&v, p, 8); return v;
#else
  return *(const uint2 *)p;
#endif
}
KURN_FN uint4 kld_v4(const void *p) {
#ifdef KURN_EMU
  kemu_check_align(p, 16, "16-byte vector load");
  uint4 v; memcpy(&v, p, 16); return v;
#else
  return *(const uint4 *)p;
#endif
}
KURN_FN float kld_f32(const uint8_t *p) { return __uint_as_float(kld_u32(p)); }
KURN_FN void kst_u16(uint8_t *p, uint32_t v) {
#ifdef KURN_EMU
  kemu_check_align(p, 2, "16-bit store");
  uint16_t x = (uint16_t)v; memcpy(p, &x, 2);
#else
  *(uint16_t *)p = (uint16_t)v;
#endif
}
KURN_FN void kst_u32(void *p, uint32_t v) {
#ifdef KURN_EMU
  kemu_check_align(p, 4, "32-bit store");
  memcpy(p, &v, 4);
#else
  *(uint32_t *)p = v;
#endif
}

// f32 -> q8_0 blocks (ggml quantize_row_q8_0_ref rounding), one warp per block of 32.
// split != 0: int8 plane Q[M][K] plus float scale plane D[M][K/32] (scale = the fp16-rounded d)
static __global__ void __attribute__((unused)) kg_quant_q8_0(const float *__restrict__ X, uint8_t *__restrict__ Q, float *__restrict__ D, int K, int M, int split) {
  const int lane = threadIdx.x & 31, nb = K / 32;
  const long blk = (long)blockIdx.x * (blockDim.x / 32) + (threadIdx.x >> 5);
  const bool live = blk < (long)M * nb;
  const long bb = live ? blk : 0;
  const int m = (int)(bb / nb), c = (int)(bb % nb);
  const float v = X[(size_t)m * K + c * 32 + lane];
  float amax = fabsf(v);
#pragma unroll
  for (int o = 16; o; o >>= 1) amax = fmaxf(amax, __shfl_xor_sync(KURN_FULL, amax, o));
  const float d = amax / 127.f, id = d != 0.f ? 1.f / d : 0.f;
  const int q = (int)roundf(v * id);
  if (!live) return;
  if (!split) {
    uint8_t *b = Q + ((size_t)m * nb + c) * 34;
    if (lane == 0) kst_u16(b, KURN_F2H(d));
    b[2 + lane] = (uint8_t)(int8_t)q;
  } else {
    Q[(size_t)m * K + c * 32 + lane] = (uint8_t)(int8_t)q;
    if (lane == 0) D[(size_t)m * nb + c] = KURN_H2F(KURN_F2H(d));
  }
}

// int8 tensor cores: D = A (16x32, row) * B (32x8, col), s32 accumulate (sm_80+)
KURN_FN void kmma(int d[4], const unsigned a[4], const unsigned b[2]) {
#ifdef KURN_EMU
  const int z[4] = {0, 0, 0, 0};
  kemu_mma_s8_16832(d, a, b, z);
#else
  asm volatile("mma.sync.aligned.m16n8k32.row.col.s32.s8.s8.s32 {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%10,%11,%12,%13};\n"
               : "=r"(d[0]), "=r"(d[1]), "=r"(d[2]), "=r"(d[3])
               : "r"(a[0]), "r"(a[1]), "r"(a[2]), "r"(a[3]), "r"(b[0]), "r"(b[1]), "r"(0), "r"(0), "r"(0), "r"(0));
#endif
}

// 16-byte async global->shared copy, zero-filled when bytes == 0 (sm_80+)
KURN_FN void kcp16(void *dst, const void *src, int bytes) {
#ifdef KURN_EMU
  kemu_cp_async16(dst, src, bytes);
#else
  unsigned d = (unsigned)__cvta_generic_to_shared(dst);
  asm volatile("cp.async.cg.shared.global [%0], [%1], 16, %2;\n" ::"r"(d), "l"(src), "r"(bytes));
#endif
}
KURN_FN void kcp_commit() {
#ifdef KURN_EMU
  kemu_cp_commit();
#else
  asm volatile("cp.async.commit_group;\n" ::);
#endif
}
#ifdef KURN_EMU
#define KCP_WAIT(n) kemu_cp_wait(n)
#else
#define KCP_WAIT(n) asm volatile("cp.async.wait_group %0;\n" ::"n"(n))
#endif

#define BM 64
#define BN 64
#define BKB 2
#define QB 16
#define WROW 48
#define XROW 80
#define NT 128
#define TW 512
#define TWS 128
#define TX 1024
#define TXS 128

// Y[m * N + n]: CTA tile BM weight rows x BN tokens; 2x2 warps of 32x32 (2x4 m16n8k32 tiles);
// one K step = BKB blocks of 32, so every mma result gets exactly one (weight, activation) scale pair.
static __global__ void __launch_bounds__(NT)
kg_gemm(const uint8_t *__restrict__ W, const uint8_t *__restrict__ X, float *__restrict__ Y, int N, int K, int M) {
  __shared__ __align__(16) uint8_t sW[3][BM * WROW];
  __shared__ float sWd[3][BM * BKB];
  __shared__ __align__(16) uint8_t sX[3][BN * XROW];
  __shared__ float sXd[3][BN * BKB];
  const int nkb = K / 32, nks = (nkb + BKB - 1) / BKB;
  const size_t ROWQ = ((size_t)K * 16 / 32), ROWS = (size_t)nkb * 2, ROWB = (size_t)nkb * 18;
  (void)ROWQ; (void)ROWS; (void)ROWB;
  const uint8_t *Wq = W;
  const uint8_t *Ws = W + (size_t)N * ROWQ;
  (void)Wq; (void)Ws;
  const uint8_t *Xq = X;
  const float *Xd = (const float *)(X + (size_t)M * K);
  const int n0 = blockIdx.x * BM, m0 = blockIdx.y * BN;
  const int warp = threadIdx.x >> 5, lane = threadIdx.x & 31, g = lane >> 2, t = lane & 3;
  const int wr = warp % 2, wc = warp / 2;
  float acc[2][4][4];
  #pragma unroll
  for (int i = 0; i < 2; i++)
    #pragma unroll
    for (int j = 0; j < 4; j++)
      #pragma unroll
      for (int k = 0; k < 4; k++) acc[i][j][k] = 0.f;
  auto compute = [&](int buf) {
    #pragma unroll
    for (int kb = 0; kb < BKB; kb++) {
      unsigned a[2][4];
      float dw0[2], dw1[2];
      #pragma unroll
      for (int mi = 0; mi < 2; mi++) {
        const int r0 = wr * 32 + mi * 16;
        { const uint32_t v0 = kld_u32(&sW[buf][(r0 + g) * WROW + kb * 16 + 4 * t]);
          const uint32_t v1 = kld_u32(&sW[buf][(r0 + g + 8) * WROW + kb * 16 + 4 * t]);
          a[mi][0] = __vsub4(v0 & 0x0F0F0F0Fu, 0x08080808u); a[mi][2] = __vsub4((v0 >> 4) & 0x0F0F0F0Fu, 0x08080808u);
          a[mi][1] = __vsub4(v1 & 0x0F0F0F0Fu, 0x08080808u); a[mi][3] = __vsub4((v1 >> 4) & 0x0F0F0F0Fu, 0x08080808u); }
        dw0[mi] = sWd[buf][(r0 + g) * BKB + kb];
        dw1[mi] = sWd[buf][(r0 + g + 8) * BKB + kb];
      }
      #pragma unroll
      for (int ni = 0; ni < 4; ni++) {
        const int c0 = wc * 32 + ni * 8;
        unsigned b[2];
        b[0] = kld_u32(&sX[buf][(c0 + g) * XROW + kb * 32 + 4 * t]);
        b[1] = kld_u32(&sX[buf][(c0 + g) * XROW + kb * 32 + 16 + 4 * t]);
        const float dx0 = sXd[buf][(c0 + 2 * t) * BKB + kb], dx1 = sXd[buf][(c0 + 2 * t + 1) * BKB + kb];
        #pragma unroll
        for (int mi = 0; mi < 2; mi++) {
          int d[4];
          kmma(d, a[mi], b);
          acc[mi][ni][0] += (float)d[0] * dw0[mi] * dx0;
          acc[mi][ni][1] += (float)d[1] * dw0[mi] * dx1;
          acc[mi][ni][2] += (float)d[2] * dw1[mi] * dx0;
          acc[mi][ni][3] += (float)d[3] * dw1[mi] * dx1;
        }
      }
    }
  };
  // cp.async issue of K step ks into shared buffer buf (scales through registers)
  auto issue = [&](int ks, int buf) {
    for (int e = threadIdx.x; e < 128; e += NT) {
      const int r = e / (BKB * QB / 16), kb = (e / (QB / 16)) % BKB, ci = e % (QB / 16);
      const int grow = min(n0 + r, N - 1), gkb = ks * BKB + kb;
      const bool ok = gkb < nkb;
      kcp16(&sW[buf][r * WROW + kb * QB + 16 * ci], ok ? (const void *)(Wq + (size_t)grow * ROWQ + (size_t)gkb * QB + 16 * ci) : (const void *)Wq, ok ? 16 : 0);
    }
    for (int e = threadIdx.x; e < 256; e += NT) {
      const int cc = e / (BKB * 2), kb = (e / 2) % BKB, ci = e % 2;
      const int gcol = min(m0 + cc, M - 1), gkb = ks * BKB + kb;
      const bool ok = gkb < nkb;
      kcp16(&sX[buf][cc * XROW + kb * 32 + 16 * ci], ok ? (const void *)(Xq + (size_t)gcol * K + (size_t)gkb * 32 + 16 * ci) : (const void *)Xq, ok ? 16 : 0);
    }
    for (int e = threadIdx.x; e < TWS; e += NT) {
    const int r = e / BKB, kb = e % BKB;
    const int grow = min(n0 + r, N - 1), gkb = ks * BKB + kb;
      sWd[buf][e] = gkb < nkb ? KURN_H2F(kld_u16(Ws + (size_t)grow * ROWS + 2 * (size_t)gkb)) : 0.f;
    }
    for (int e = threadIdx.x; e < TXS; e += NT) {
    const int cc = e / BKB, kb = e % BKB;
    const int gcol = min(m0 + cc, M - 1), gkb = ks * BKB + kb;
      sXd[buf][e] = gkb < nkb ? Xd[(size_t)gcol * nkb + gkb] : 0.f;
    }
  };
  #pragma unroll
  for (int s = 0; s < 2; s++) {
    if (s < nks) issue(s, s);
    kcp_commit();
  }
  for (int ks = 0; ks < nks; ks++) {
    KCP_WAIT(1);
    __syncthreads();
    const int nx = ks + 2;
    if (nx < nks) issue(nx, nx % 3);
    kcp_commit();
    compute(ks % 3);
  }
  KCP_WAIT(0);
  #pragma unroll
  for (int mi = 0; mi < 2; mi++)
    #pragma unroll
    for (int ni = 0; ni < 4; ni++)
      #pragma unroll
      for (int k = 0; k < 4; k++) {
        const int row = n0 + wr * 32 + mi * 16 + g + 8 * (k >> 1), col = m0 + wc * 32 + ni * 8 + 2 * t + (k & 1);
        if (row < N && col < M) Y[(size_t)col * N + row] = acc[mi][ni][k];
      }
}

// native ggml blocks -> split layout: quant plane [N][((size_t)K * 16 / 32)] then scale plane [N][K/32 * 2]
static __global__ void kg_repack(const uint8_t *__restrict__ W, uint8_t *__restrict__ P, int N, int K) {
  const int nb = K / 32;
  const long i = (long)blockIdx.x * blockDim.x + threadIdx.x;
  if (i >= (long)N * nb) return;
  const int r = (int)(i / nb), bl = (int)(i % nb);
  const uint8_t *src = W + (size_t)r * ((size_t)K / 32 * 18) + (size_t)bl * 18;
  uint8_t *q = P + (size_t)r * ((size_t)K * 16 / 32) + (size_t)bl * 16;
  uint8_t *s = P + (size_t)N * ((size_t)K * 16 / 32) + (size_t)r * ((size_t)K / 32 * 2) + (size_t)bl * 2;
  for (int i = 0; i < 16; i++) q[0 + i] = src[2 + i];
  s[0] = src[0]; s[1] = src[1];
}

extern "C" {
const char *kg_config(void) { return "op=gemm weights=q4_0 arch=sm_80 layout=split bm=64 bn=64 wm=2 wn=2 bkb=2 pipe=async3 pad=16 minb=0"; }
int kg_check_shape(int N, int K, int M) { return (N > 0 && M > 0 && K > 0 && K % 32 == 0) ? 0 : -1; }
size_t kg_prep_bytes(int N, int K) { (void)N; (void)K; return (size_t)N * (((size_t)K * 16 / 32) + ((size_t)K / 32 * 2)); }
size_t kg_xbytes(int K, int M) { return (size_t)M * K + (size_t)M * (K / 32) * 4; }
int kg_prepare(const void *W, void *Wp, int N, int K, cudaStream_t s) {
  const long nblk = (long)N * (K / 32);
  KURN_LAUNCH(kg_repack, dim3((unsigned)((nblk + 127) / 128)), dim3(128), s, (const uint8_t *)W, (uint8_t *)Wp, N, K);
#ifdef KURN_EMU
  return 0;
#else
  return (int)cudaGetLastError();
#endif
}
int kg_quant(const float *X, void *Xq, int K, int M, cudaStream_t s) {
  KURN_LAUNCH(kg_quant_q8_0, dim3((unsigned)(((long)M * (K / 32) + 3) / 4)), dim3(128), s, X, (uint8_t *)Xq, (float *)((uint8_t *)Xq + (size_t)M * K), K, M, 1);
#ifdef KURN_EMU
  return 0;
#else
  return (int)cudaGetLastError();
#endif
}
size_t kg_xblock_bytes(int K, int M) { return (size_t)M * (K / 32) * 34; }
int kg_xblocks(const float *X, void *Xb, int K, int M, cudaStream_t s) {
  KURN_LAUNCH(kg_quant_q8_0, dim3((unsigned)(((long)M * (K / 32) + 3) / 4)), dim3(128), s, X, (uint8_t *)Xb, (float *)nullptr, K, M, 0);
#ifdef KURN_EMU
  return 0;
#else
  return (int)cudaGetLastError();
#endif
}
int kg_run(const void *W, const void *Xq, float *Y, int N, int K, int M, cudaStream_t s) {
  if (kg_check_shape(N, K, M)) return -1;
  KURN_LAUNCH(kg_gemm, dim3((unsigned)((N + 64 - 1) / 64), (unsigned)((M + 64 - 1) / 64)), dim3(128), s, (const uint8_t *)W, (const uint8_t *)Xq, Y, N, K, M);
#ifdef KURN_EMU
  return 0;
#else
  return (int)cudaGetLastError();
#endif
}
}
