// generated by kurn: q4_K gemv for CUDA (4-bit K-quant (6-bit sub-scales and mins))
// op=gemv weights=q4_K arch=sm_80 layout=split tpr=64 rpb=2 sub=2 unroll=2 cols=1 minb=0 mins=dp4a unpack=none
#ifdef KURN_EMU
#include "kurn_cuemu.h"
#define KURN_H2F(h) kemu_h2f((uint16_t)(h))
#define KURN_F2H(f) kemu_f2h(f)
#define KURN_POPC(x) __builtin_popcount(x)
#else
#include <cuda_runtime.h>
#include <cuda_fp16.h>
#include <stdint.h>
#include <string.h>
#define KURN_H2F(h) __half2float(__ushort_as_half((unsigned short)(h)))
#define KURN_F2H(f) __half_as_ushort(__float2half_rn(f))
#define KURN_POPC(x) __popc(x)
#define KURN_LAUNCH(kernel, grid, block, stream, ...) kernel<<<(grid), (block), 0, (stream)>>>(__VA_ARGS__)
#endif
#define KURN_FULL 0xffffffffu
#define KURN_FN static __device__ __forceinline__ __attribute__((unused))

KURN_FN uint32_t kld_u8(const uint8_t *p) { return *p; }
KURN_FN uint32_t kld_u16(const uint8_t *p) {
#ifdef KURN_EMU
  kemu_check_align(p, 2, "16-bit load");
  uint16_t v; memcpy(&v, p, 2); return v;
#else
  return *(const uint16_t *)p;
#endif
}
KURN_FN uint32_t kld_u32(const void *p) {
#ifdef KURN_EMU
  kemu_check_align(p, 4, "32-bit load");
  uint32_t v; memcpy(&v, p, 4); return v;
#else
  return *(const uint32_t *)p;
#endif
}
KURN_FN uint32_t kld_u32_b2(const uint8_t *p) { return kld_u16(p) | (kld_u16(p + 2) << 16); }
KURN_FN uint2 kld_v2(const void *p) {
#ifdef KURN_EMU
  kemu_check_align(p, 8, "8-byte vector load");
  uint2 v; memcpy(&v, p, 8); return v;
#else
  return *(const uint2 *)p;
#endif
}
KURN_FN uint4 kld_v4(const void *p) {
#ifdef KURN_EMU
  kemu_check_align(p, 16, "16-byte vector load");
  uint4 v; memcpy(&v, p, 16); return v;
#else
  return *(const uint4 *)p;
#endif
}
KURN_FN float kld_f32(const uint8_t *p) { return __uint_as_float(kld_u32(p)); }
KURN_FN void kst_u16(uint8_t *p, uint32_t v) {
#ifdef KURN_EMU
  kemu_check_align(p, 2, "16-bit store");
  uint16_t x = (uint16_t)v; memcpy(p, &x, 2);
#else
  *(uint16_t *)p = (uint16_t)v;
#endif
}
KURN_FN void kst_u32(void *p, uint32_t v) {
#ifdef KURN_EMU
  kemu_check_align(p, 4, "32-bit store");
  memcpy(p, &v, 4);
#else
  *(uint32_t *)p = v;
#endif
}

// f32 -> q8_0 blocks (ggml quantize_row_q8_0_ref rounding), one warp per block of 32.
// split != 0: int8 plane Q[M][K] plus float scale plane D[M][K/32] (scale = the fp16-rounded d)
static __global__ void __attribute__((unused)) kg_quant_q8_0(const float *__restrict__ X, uint8_t *__restrict__ Q, float *__restrict__ D, int K, int M, int split) {
  const int lane = threadIdx.x & 31, nb = K / 32;
  const long blk = (long)blockIdx.x * (blockDim.x / 32) + (threadIdx.x >> 5);
  const bool live = blk < (long)M * nb;
  const long bb = live ? blk : 0;
  const int m = (int)(bb / nb), c = (int)(bb % nb);
  const float v = X[(size_t)m * K + c * 32 + lane];
  float amax = fabsf(v);
#pragma unroll
  for (int o = 16; o; o >>= 1) amax = fmaxf(amax, __shfl_xor_sync(KURN_FULL, amax, o));
  const float d = amax / 127.f, id = d != 0.f ? 1.f / d : 0.f;
  const int q = (int)roundf(v * id);
  if (!live) return;
  if (!split) {
    uint8_t *b = Q + ((size_t)m * nb + c) * 34;
    if (lane == 0) kst_u16(b, KURN_F2H(d));
    b[2 + lane] = (uint8_t)(int8_t)q;
  } else {
    Q[(size_t)m * K + c * 32 + lane] = (uint8_t)(int8_t)q;
    if (lane == 0) D[(size_t)m * nb + c] = KURN_H2F(KURN_F2H(d));
  }
}

// f32 -> q8_K blocks (ggml quantize_row_q8_K_ref), one warp per block of 256 (8 values per lane)
static __global__ void kg_quant_q8_K(const float *__restrict__ X, uint8_t *__restrict__ Q, int K, int M) {
  const int lane = threadIdx.x & 31, nb = K / 256;
  const long blk = (long)blockIdx.x * (blockDim.x / 32) + (threadIdx.x >> 5);
  const bool live = blk < (long)M * nb;
  const long bb = live ? blk : 0;
  const int m = (int)(bb / nb), c = (int)(bb % nb);
  const float *x = X + (size_t)m * K + (size_t)c * 256 + lane * 8;
  float v[8], amax = 0.f, mx = 0.f;
  int idx = 1 << 30;
#pragma unroll
  for (int i = 0; i < 8; i++) {
    v[i] = x[i];
    const float ax = fabsf(v[i]);
    if (ax > amax) { amax = ax; mx = v[i]; idx = lane * 8 + i; }
  }
#pragma unroll
  for (int o = 16; o; o >>= 1) {  // largest |x|, first index on ties (ggml scans in order)
    const float oa = __shfl_xor_sync(KURN_FULL, amax, o), om = __shfl_xor_sync(KURN_FULL, mx, o);
    const int oi = __shfl_xor_sync(KURN_FULL, idx, o);
    if (oa > amax || (oa == amax && oi < idx)) { amax = oa; mx = om; idx = oi; }
  }
  uint8_t *b = Q + ((size_t)m * nb + c) * 292;
  int q[8], s8 = 0;
  const float iscale = amax != 0.f ? -127.f / mx : 0.f;
#pragma unroll
  for (int i = 0; i < 8; i++) {
    q[i] = amax != 0.f ? min(127, __float2int_rn(iscale * v[i])) : 0;
    s8 += q[i];
  }
  const int pair = __shfl_xor_sync(KURN_FULL, s8, 1);
  if (!live) return;
  if (lane == 0) kst_u32(b, __float_as_uint(amax != 0.f ? 1.f / iscale : 0.f));
#pragma unroll
  for (int i = 0; i < 8; i++) b[4 + lane * 8 + i] = (uint8_t)(int8_t)q[i];
  if (!(lane & 1)) kst_u16(b + 260 + 2 * (lane >> 1), (uint32_t)(uint16_t)(int16_t)(s8 + pair));
}
#define XD8K(x, b) kld_f32((x) + (size_t)(b) * 292)
#define XQ(x, c, off) (int)kld_u32((x) + (size_t)((c) >> 3) * 292 + 4 + ((c) & 7) * 32 + (off))
#define XBS(x, c, h) (int)(int16_t)kld_u16((x) + (size_t)((c) >> 3) * 292 + 260 + 2 * (((c) & 7) * 2 + (h)))

#define COLS 1
#define SUB 2
KURN_FN void kunit(const uint8_t *__restrict__ wq, const uint8_t *__restrict__ ws, int u, int p,
                                             const uint8_t *const *xr, float *acc, const uint32_t *__restrict__ tab) {
  (void)ws; (void)tab;
  const int b = u >> 2, jj = u & 3;
  const uint8_t *meta = ws + (size_t)b * 16;
  uint32_t q[4];
  { const uint4 t = kld_v4(wq + (size_t)u * 32 + p * 16 + 0); q[0] = t.x; q[1] = t.y; q[2] = t.z; q[3] = t.w; }
  const float d = KURN_H2F(kld_u16(meta)), dmin = KURN_H2F(kld_u16(meta + 2));
  const uint32_t sw0 = kld_u32(meta + 4), sw1 = kld_u32(meta + 8), sw2 = kld_u32(meta + 12);
  const uint32_t sw[3] = {sw0, sw1, sw2};
#define SB(k) ((sw[(k) >> 2] >> (8 * ((k) & 3))) & 0xFF)
  int sc[2], mn[2];
#pragma unroll
  for (int h = 0; h < 2; h++) {
    const int sb = 2 * jj + h;
    if (sb < 4) { sc[h] = SB(sb) & 63; mn[h] = SB(sb + 4) & 63; }
    else { sc[h] = (SB(sb + 4) & 0xF) | ((SB(sb - 4) >> 6) << 4); mn[h] = (SB(sb + 4) >> 4) | ((SB(sb) >> 6) << 4); }
  }
#undef SB
  const int c0 = b * 8 + 2 * jj;
#pragma unroll
  for (int j = 0; j < COLS; j++) {
    int s0 = 0, s1 = 0, m0 = 0, m1 = 0;
#pragma unroll
    for (int i = 0; i < 4; i++) {
      const int x0 = XQ(xr[j], c0, p * 16 + 4 * i), x1 = XQ(xr[j], c0 + 1, p * 16 + 4 * i);
      s0 = __dp4a((int)(q[i] & 0x0F0F0F0Fu), x0, s0);
      s1 = __dp4a((int)((q[i] >> 4) & 0x0F0F0F0Fu), x1, s1);
      m0 = __dp4a(0x01010101, x0, m0);
      m1 = __dp4a(0x01010101, x1, m1);
    }
    acc[j] += XD8K(xr[j], b) * (d * (float)(sc[0] * s0 + sc[1] * s1) - dmin * (float)(mn[0] * m0 + mn[1] * m1));
  }
}

static __global__ void __launch_bounds__(128)
kg_gemv(const uint8_t *__restrict__ W, const uint8_t *__restrict__ X, float *__restrict__ Y, int N, int K, int M) {
  const uint32_t *tab = nullptr; (void)tab;
  const int lr = threadIdx.x / 64, lid = threadIdx.x % 64;
  const int row = blockIdx.x * 2 + lr, wrow = row < N ? row : N - 1;
  const int col0 = blockIdx.y * COLS;
  const uint8_t *wq = W + (size_t)wrow * ((size_t)K * 32 / 64);
  const uint8_t *ws = W + (size_t)N * ((size_t)K * 32 / 64) + (size_t)wrow * ((size_t)K / 256 * 16);
  const uint8_t *xr[COLS];
  float acc[COLS];
  #pragma unroll
  for (int j = 0; j < COLS; j++) { xr[j] = X + (size_t)min(col0 + j, M - 1) * ((size_t)K / 256 * 292); acc[j] = 0.f; }
  const int work = K / 64 * SUB;
  for (int w0 = lid; w0 < work; w0 += 128) {
    #pragma unroll
    for (int k = 0; k < 2; k++) {
      const int w = w0 + k * 64;
      if (w < work) kunit(wq, ws, w / SUB, w % SUB, xr, acc, tab);
    }
  }
  __shared__ float red[4];
  #pragma unroll
  for (int j = 0; j < COLS; j++) {
    float v = acc[j];
    v += __shfl_xor_sync(KURN_FULL, v, 16);
    v += __shfl_xor_sync(KURN_FULL, v, 8);
    v += __shfl_xor_sync(KURN_FULL, v, 4);
    v += __shfl_xor_sync(KURN_FULL, v, 2);
    v += __shfl_xor_sync(KURN_FULL, v, 1);
    if ((lid & 31) == 0) red[(lr * 2 + (lid >> 5)) * COLS + j] = v;
  }
  __syncthreads();
  if (lid == 0 && row < N) {
    for (int j = 0; j < COLS; j++) {
      float v = 0.f;
      for (int i = 0; i < 2; i++) v += red[(lr * 2 + i) * COLS + j];
      if (col0 + j < M) Y[(size_t)(col0 + j) * N + row] = v;
    }
  }
}

// native ggml blocks -> split layout: quant plane [N][((size_t)K * 32 / 64)] then scale plane [N][K/256 * 16]
static __global__ void kg_repack(const uint8_t *__restrict__ W, uint8_t *__restrict__ P, int N, int K) {
  const int nb = K / 256;
  const long i = (long)blockIdx.x * blockDim.x + threadIdx.x;
  if (i >= (long)N * nb) return;
  const int r = (int)(i / nb), bl = (int)(i % nb);
  const uint8_t *src = W + (size_t)r * ((size_t)K / 256 * 144) + (size_t)bl * 144;
  uint8_t *q = P + (size_t)r * ((size_t)K * 32 / 64) + (size_t)bl * 128;
  uint8_t *s = P + (size_t)N * ((size_t)K * 32 / 64) + (size_t)r * ((size_t)K / 256 * 16) + (size_t)bl * 16;
  for (int i = 0; i < 128; i++) q[0 + i] = src[16 + i];
  for (int i = 0; i < 16; i++) s[i] = src[i];
}

extern "C" {
const char *kg_config(void) { return "op=gemv weights=q4_K arch=sm_80 layout=split tpr=64 rpb=2 sub=2 unroll=2 cols=1 minb=0 mins=dp4a unpack=none"; }
int kg_check_shape(int N, int K, int M) { return (N > 0 && M > 0 && K > 0 && K % 256 == 0) ? 0 : -1; }
size_t kg_prep_bytes(int N, int K) { (void)N; (void)K; return (size_t)N * (((size_t)K * 32 / 64) + ((size_t)K / 256 * 16)); }
size_t kg_xbytes(int K, int M) { return (size_t)M * ((size_t)K / 256 * 292); }
int kg_prepare(const void *W, void *Wp, int N, int K, cudaStream_t s) {
  const long nblk = (long)N * (K / 256);
  KURN_LAUNCH(kg_repack, dim3((unsigned)((nblk + 127) / 128)), dim3(128), s, (const uint8_t *)W, (uint8_t *)Wp, N, K);
#ifdef KURN_EMU
  return 0;
#else
  return (int)cudaGetLastError();
#endif
}
int kg_quant(const float *X, void *Xq, int K, int M, cudaStream_t s) {
  KURN_LAUNCH(kg_quant_q8_K, dim3((unsigned)(((long)M * (K / 256) + 3) / 4)), dim3(128), s, X, (uint8_t *)Xq, K, M);
#ifdef KURN_EMU
  return 0;
#else
  return (int)cudaGetLastError();
#endif
}
size_t kg_xblock_bytes(int K, int M) { return (size_t)M * (K / 256) * 292; }
int kg_xblocks(const float *X, void *Xb, int K, int M, cudaStream_t s) {
  KURN_LAUNCH(kg_quant_q8_K, dim3((unsigned)(((long)M * (K / 256) + 3) / 4)), dim3(128), s, X, (uint8_t *)Xb, K, M);
#ifdef KURN_EMU
  return 0;
#else
  return (int)cudaGetLastError();
#endif
}
int kg_run(const void *W, const void *Xq, float *Y, int N, int K, int M, cudaStream_t s) {
  if (kg_check_shape(N, K, M)) return -1;
  KURN_LAUNCH(kg_gemv, dim3((unsigned)((N + 2 - 1) / 2), (unsigned)((M + 1 - 1) / 1)), dim3(128), s, (const uint8_t *)W, (const uint8_t *)Xq, Y, N, K, M);
#ifdef KURN_EMU
  return 0;
#else
  return (int)cudaGetLastError();
#endif
}
}
