// generated by kurn: q8_0 gemm for CUDA (8-bit, fp16 scale per 32)
// op=gemm weights=q8_0 arch=sm_80 layout=native bm=64 bn=32 wm=2 wn=2 bkb=2 pipe=reg2 pad=16 minb=0
#ifdef KURN_EMU
#include "kurn_cuemu.h"
#define KURN_H2F(h) kemu_h2f((uint16_t)(h))
#define KURN_F2H(f) kemu_f2h(f)
#define KURN_POPC(x) __builtin_popcount(x)
#else
#include <cuda_runtime.h>
#include <cuda_fp16.h>
#include <stdint.h>
#include <string.h>
#define KURN_H2F(h) __half2float(__ushort_as_half((unsigned short)(h)))
#define KURN_F2H(f) __half_as_ushort(__float2half_rn(f))
#define KURN_POPC(x) __popc(x)
#define KURN_LAUNCH(kernel, grid, block, stream, ...) kernel<<<(grid), (block), 0, (stream)>>>(__VA_ARGS__)
#endif
#define KURN_FULL 0xffffffffu
#define KURN_FN static __device__ __forceinline__ __attribute__((unused))

KURN_FN uint32_t kld_u8(const uint8_t *p) { return *p; }
KURN_FN uint32_t kld_u16(const uint8_t *p) {
#ifdef KURN_EMU
  kemu_check_align(p, 2, "16-bit load");
  uint16_t v; memcpy(&v, p, 2); return v;
#else
  return *(const uint16_t *)p;
#endif
}
KURN_FN uint32_t kld_u32(const void *p) {
#ifdef KURN_EMU
  kemu_check_align(p, 4, "32-bit load");
  uint32_t v; memcpy(&v, p, 4); return v;
#else
  return *(const uint32_t *)p;
#endif
}
KURN_FN uint32_t kld_u32_b2(const uint8_t *p) { return kld_u16(p) | (kld_u16(p + 2) << 16); }
KURN_FN uint2 kld_v2(const void *p) {
#ifdef KURN_EMU
  kemu_check_align(p, 8, "8-byte vector load");
  uint2 v; memcpy(&v, p, 8); return v;
#else
  return *(const uint2 *)p;
#endif
}
KURN_FN uint4 kld_v4(const void *p) {
#ifdef KURN_EMU
  kemu_check_align(p, 16, "16-byte vector load");
  uint4 v; memcpy(&v, p, 16); return v;
#else
  return *(const uint4 *)p;
#endif
}
KURN_FN float kld_f32(const uint8_t *p) { return __uint_as_float(kld_u32(p)); }
KURN_FN void kst_u16(uint8_t *p, uint32_t v) {
#ifdef KURN_EMU
  kemu_check_align(p, 2, "16-bit store");
  uint16_t x = (uint16_t)v; memcpy(p, &x, 2);
#else
  *(uint16_t *)p = (uint16_t)v;
#endif
}
KURN_FN void kst_u32(void *p, uint32_t v) {
#ifdef KURN_EMU
  kemu_check_align(p, 4, "32-bit store");
  memcpy(p, &v, 4);
#else
  *(uint32_t *)p = v;
#endif
}

// f32 -> q8_0 blocks (ggml quantize_row_q8_0_ref rounding), one warp per block of 32.
// split != 0: int8 plane Q[M][K] plus float scale plane D[M][K/32] (scale = the fp16-rounded d)
static __global__ void __attribute__((unused)) kg_quant_q8_0(const float *__restrict__ X, uint8_t *__restrict__ Q, float *__restrict__ D, int K, int M, int split) {
  const int lane = threadIdx.x & 31, nb = K / 32;
  const long blk = (long)blockIdx.x * (blockDim.x / 32) + (threadIdx.x >> 5);
  const bool live = blk < (long)M * nb;
  const long bb = live ? blk : 0;
  const int m = (int)(bb / nb), c = (int)(bb % nb);
  const float v = X[(size_t)m * K + c * 32 + lane];
  float amax = fabsf(v);
#pragma unroll
  for (int o = 16; o; o >>= 1) amax = fmaxf(amax, __shfl_xor_sync(KURN_FULL, amax, o));
  const float d = amax / 127.f, id = d != 0.f ? 1.f / d : 0.f;
  const int q = (int)roundf(v * id);
  if (!live) return;
  if (!split) {
    uint8_t *b = Q + ((size_t)m * nb + c) * 34;
    if (lane == 0) kst_u16(b, KURN_F2H(d));
    b[2 + lane] = (uint8_t)(int8_t)q;
  } else {
    Q[(size_t)m * K + c * 32 + lane] = (uint8_t)(int8_t)q;
    if (lane == 0) D[(size_t)m * nb + c] = KURN_H2F(KURN_F2H(d));
  }
}

// int8 tensor cores: D = A (16x32, row) * B (32x8, col), s32 accumulate (sm_80+)
KURN_FN void kmma(int d[4], const unsigned a[4], const unsigned b[2]) {
#ifdef KURN_EMU
  const int z[4] = {0, 0, 0, 0};
  kemu_mma_s8_16832(d, a, b, z);
#else
  asm volatile("mma.sync.aligned.m16n8k32.row.col.s32.s8.s8.s32 {%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%10,%11,%12,%13};\n"
               : "=r"(d[0]), "=r"(d[1]), "=r"(d[2]), "=r"(d[3])
               : "r"(a[0]), "r"(a[1]), "r"(a[2]), "r"(a[3]), "r"(b[0]), "r"(b[1]), "r"(0), "r"(0), "r"(0), "r"(0));
#endif
}

#define BM 64
#define BN 32
#define BKB 2
#define QB 32
#define WROW 80
#define XROW 80
#define NT 128
#define TW 1024
#define TWS 128
#define TX 512
#define TXS 64

// Y[m * N + n]: CTA tile BM weight rows x BN tokens; 2x2 warps of 32x16 (2x2 m16n8k32 tiles);
// one K step = BKB blocks of 32, so every mma result gets exactly one (weight, activation) scale pair.
static __global__ void __launch_bounds__(NT)
kg_gemm(const uint8_t *__restrict__ W, const uint8_t *__restrict__ X, float *__restrict__ Y, int N, int K, int M) {
  __shared__ __align__(16) uint8_t sW[1][BM * WROW];
  __shared__ float sWd[1][BM * BKB];
  __shared__ __align__(16) uint8_t sX[1][BN * XROW];
  __shared__ float sXd[1][BN * BKB];
  const int nkb = K / 32, nks = (nkb + BKB - 1) / BKB;
  const size_t ROWQ = ((size_t)K * 32 / 32), ROWS = (size_t)nkb * 2, ROWB = (size_t)nkb * 34;
  (void)ROWQ; (void)ROWS; (void)ROWB;
  const uint8_t *Wq = W;
  const uint8_t *Ws = W + (size_t)N * ROWQ;
  (void)Wq; (void)Ws;
  const uint8_t *Xq = X;
  const float *Xd = (const float *)(X + (size_t)M * K);
  const int n0 = blockIdx.x * BM, m0 = blockIdx.y * BN;
  const int warp = threadIdx.x >> 5, lane = threadIdx.x & 31, g = lane >> 2, t = lane & 3;
  const int wr = warp % 2, wc = warp / 2;
  float acc[2][2][4];
  #pragma unroll
  for (int i = 0; i < 2; i++)
    #pragma unroll
    for (int j = 0; j < 2; j++)
      #pragma unroll
      for (int k = 0; k < 4; k++) acc[i][j][k] = 0.f;
  auto compute = [&](int buf) {
    #pragma unroll
    for (int kb = 0; kb < BKB; kb++) {
      unsigned a[2][4];
      float dw0[2], dw1[2];
      #pragma unroll
      for (int mi = 0; mi < 2; mi++) {
        const int r0 = wr * 32 + mi * 16;
        a[mi][0] = kld_u32(&sW[buf][(r0 + g) * WROW + kb * 32 + 4 * t]);
        a[mi][1] = kld_u32(&sW[buf][(r0 + g + 8) * WROW + kb * 32 + 4 * t]);
        a[mi][2] = kld_u32(&sW[buf][(r0 + g) * WROW + kb * 32 + 16 + 4 * t]);
        a[mi][3] = kld_u32(&sW[buf][(r0 + g + 8) * WROW + kb * 32 + 16 + 4 * t]);
        dw0[mi] = sWd[buf][(r0 + g) * BKB + kb];
        dw1[mi] = sWd[buf][(r0 + g + 8) * BKB + kb];
      }
      #pragma unroll
      for (int ni = 0; ni < 2; ni++) {
        const int c0 = wc * 16 + ni * 8;
        unsigned b[2];
        b[0] = kld_u32(&sX[buf][(c0 + g) * XROW + kb * 32 + 4 * t]);
        b[1] = kld_u32(&sX[buf][(c0 + g) * XROW + kb * 32 + 16 + 4 * t]);
        const float dx0 = sXd[buf][(c0 + 2 * t) * BKB + kb], dx1 = sXd[buf][(c0 + 2 * t + 1) * BKB + kb];
        #pragma unroll
        for (int mi = 0; mi < 2; mi++) {
          int d[4];
          kmma(d, a[mi], b);
          acc[mi][ni][0] += (float)d[0] * dw0[mi] * dx0;
          acc[mi][ni][1] += (float)d[1] * dw0[mi] * dx1;
          acc[mi][ni][2] += (float)d[2] * dw1[mi] * dx0;
          acc[mi][ni][3] += (float)d[3] * dw1[mi] * dx1;
        }
      }
    }
  };
  // global -> registers for K step ks
  auto gload = [&](int ks, uint32_t *rw, float *rws, uint32_t *rx, float *rxs) {
    #pragma unroll
    for (int i = 0; i < 8; i++) {
      const int e = threadIdx.x + i * NT;
      if (e < TW) {
    const int r = e / (BKB * QB / 4), kb = (e / (QB / 4)) % BKB, wi = e % (QB / 4);
    const int grow = min(n0 + r, N - 1), gkb = ks * BKB + kb;
        rw[i] = gkb < nkb ? kld_u32_b2(W + (size_t)grow * ROWB + (size_t)gkb * 34 + 2 + 4 * wi) : 0u;
      }
    }
    #pragma unroll
    for (int i = 0; i < 1; i++) {
      const int e = threadIdx.x + i * NT;
      if (e < TWS) {
    const int r = e / BKB, kb = e % BKB;
    const int grow = min(n0 + r, N - 1), gkb = ks * BKB + kb;
        rws[i] = gkb < nkb ? KURN_H2F(kld_u16(W + (size_t)grow * ROWB + (size_t)gkb * 34)) : 0.f;
      }
    }
    #pragma unroll
    for (int i = 0; i < 4; i++) {
      const int e = threadIdx.x + i * NT;
      if (e < TX) {
    const int cc = e / (BKB * 8), kb = (e / 8) % BKB, wi = e % 8;
    const int gcol = min(m0 + cc, M - 1), gkb = ks * BKB + kb;
        rx[i] = gkb < nkb ? kld_u32(Xq + (size_t)gcol * K + (size_t)gkb * 32 + 4 * wi) : 0u;
      }
    }
    #pragma unroll
    for (int i = 0; i < 1; i++) {
      const int e = threadIdx.x + i * NT;
      if (e < TXS) {
    const int cc = e / BKB, kb = e % BKB;
    const int gcol = min(m0 + cc, M - 1), gkb = ks * BKB + kb;
        rxs[i] = gkb < nkb ? Xd[(size_t)gcol * nkb + gkb] : 0.f;
      }
    }
  };
  // registers -> shared buffer buf
  auto sstore = [&](int buf, const uint32_t *rw, const float *rws, const uint32_t *rx, const float *rxs) {
    #pragma unroll
    for (int i = 0; i < 8; i++) {
      const int e = threadIdx.x + i * NT;
      if (e < TW) { const int r = e / (BKB * QB / 4), kb = (e / (QB / 4)) % BKB, wi = e % (QB / 4);
        kst_u32(&sW[buf][r * WROW + kb * QB + 4 * wi], rw[i]); }
    }
    #pragma unroll
    for (int i = 0; i < 1; i++) { const int e = threadIdx.x + i * NT; if (e < TWS) sWd[buf][e] = rws[i]; }
    #pragma unroll
    for (int i = 0; i < 4; i++) {
      const int e = threadIdx.x + i * NT;
      if (e < TX) { const int cc = e / (BKB * 8), kb = (e / 8) % BKB, wi = e % 8;
        kst_u32(&sX[buf][cc * XROW + kb * 32 + 4 * wi], rx[i]); }
    }
    #pragma unroll
    for (int i = 0; i < 1; i++) { const int e = threadIdx.x + i * NT; if (e < TXS) sXd[buf][e] = rxs[i]; }
  };
  uint32_t rw[8]; float rws[1]; uint32_t rx[4]; float rxs[1];
  if (nks > 0) gload(0, rw, rws, rx, rxs);
  for (int ks = 0; ks < nks; ks++) {
    sstore(0, rw, rws, rx, rxs);
    __syncthreads();
    if (ks + 1 < nks) gload(ks + 1, rw, rws, rx, rxs);
    compute(0);
    __syncthreads();
  }
  #pragma unroll
  for (int mi = 0; mi < 2; mi++)
    #pragma unroll
    for (int ni = 0; ni < 2; ni++)
      #pragma unroll
      for (int k = 0; k < 4; k++) {
        const int row = n0 + wr * 32 + mi * 16 + g + 8 * (k >> 1), col = m0 + wc * 16 + ni * 8 + 2 * t + (k & 1);
        if (row < N && col < M) Y[(size_t)col * N + row] = acc[mi][ni][k];
      }
}

extern "C" {
const char *kg_config(void) { return "op=gemm weights=q8_0 arch=sm_80 layout=native bm=64 bn=32 wm=2 wn=2 bkb=2 pipe=reg2 pad=16 minb=0"; }
int kg_check_shape(int N, int K, int M) { return (N > 0 && M > 0 && K > 0 && K % 32 == 0) ? 0 : -1; }
size_t kg_prep_bytes(int N, int K) { (void)N; (void)K; return 0; }
size_t kg_xbytes(int K, int M) { return (size_t)M * K + (size_t)M * (K / 32) * 4; }
int kg_prepare(const void *W, void *Wp, int N, int K, cudaStream_t s) {
  (void)W; (void)Wp; (void)N; (void)K; (void)s;
  return 0;
}
int kg_quant(const float *X, void *Xq, int K, int M, cudaStream_t s) {
  KURN_LAUNCH(kg_quant_q8_0, dim3((unsigned)(((long)M * (K / 32) + 3) / 4)), dim3(128), s, X, (uint8_t *)Xq, (float *)((uint8_t *)Xq + (size_t)M * K), K, M, 1);
#ifdef KURN_EMU
  return 0;
#else
  return (int)cudaGetLastError();
#endif
}
size_t kg_xblock_bytes(int K, int M) { return (size_t)M * (K / 32) * 34; }
int kg_xblocks(const float *X, void *Xb, int K, int M, cudaStream_t s) {
  KURN_LAUNCH(kg_quant_q8_0, dim3((unsigned)(((long)M * (K / 32) + 3) / 4)), dim3(128), s, X, (uint8_t *)Xb, (float *)nullptr, K, M, 0);
#ifdef KURN_EMU
  return 0;
#else
  return (int)cudaGetLastError();
#endif
}
int kg_run(const void *W, const void *Xq, float *Y, int N, int K, int M, cudaStream_t s) {
  if (kg_check_shape(N, K, M)) return -1;
  KURN_LAUNCH(kg_gemm, dim3((unsigned)((N + 64 - 1) / 64), (unsigned)((M + 32 - 1) / 32)), dim3(128), s, (const uint8_t *)W, (const uint8_t *)Xq, Y, N, K, M);
#ifdef KURN_EMU
  return 0;
#else
  return (int)cudaGetLastError();
#endif
}
}
