// generated by kurn: tq2_0 gemv for CUDA (ternary (BitNet b1.58 TQ2_0))
// op=gemv weights=tq2_0 arch=sm_80 layout=split tpr=32 rpb=4 sub=2 unroll=2 cols=1 minb=0 mins=none unpack=none xlayout=blocks
#ifdef KURN_EMU
#include "kurn_cuemu.h"
#define KURN_H2F(h) kemu_h2f((uint16_t)(h))
#define KURN_F2H(f) kemu_f2h(f)
#define KURN_POPC(x) __builtin_popcount(x)
#else
#include <cuda_runtime.h>
#include <cuda_fp16.h>
#include <stdint.h>
#include <string.h>
#define KURN_H2F(h) __half2float(__ushort_as_half((unsigned short)(h)))
#define KURN_F2H(f) __half_as_ushort(__float2half_rn(f))
#define KURN_POPC(x) __popc(x)
#define KURN_LAUNCH(kernel, grid, block, stream, ...) kernel<<<(grid), (block), 0, (stream)>>>(__VA_ARGS__)
#define KURN_LAUNCH_SMEM(kernel, grid, block, smem, stream, ...) kernel<<<(grid), (block), (smem), (stream)>>>(__VA_ARGS__)
#endif
#define KURN_FULL 0xffffffffu
#define KURN_FN static __device__ __forceinline__ __attribute__((unused))

KURN_FN uint32_t kld_u8(const uint8_t *p) { return *p; }
KURN_FN uint32_t kld_u16(const uint8_t *p) {
#ifdef KURN_EMU
  kemu_check_align(p, 2, "16-bit load");
  uint16_t v; memcpy(&v, p, 2); return v;
#else
  return *(const uint16_t *)p;
#endif
}
KURN_FN uint32_t kld_u32(const void *p) {
#ifdef KURN_EMU
  kemu_check_align(p, 4, "32-bit load");
  uint32_t v; memcpy(&v, p, 4); return v;
#else
  return *(const uint32_t *)p;
#endif
}
KURN_FN uint32_t kld_u32_b2(const uint8_t *p) { return kld_u16(p) | (kld_u16(p + 2) << 16); }
KURN_FN uint2 kld_v2(const void *p) {
#ifdef KURN_EMU
  kemu_check_align(p, 8, "8-byte vector load");
  uint2 v; memcpy(&v, p, 8); return v;
#else
  return *(const uint2 *)p;
#endif
}
KURN_FN uint4 kld_v4(const void *p) {
#ifdef KURN_EMU
  kemu_check_align(p, 16, "16-byte vector load");
  uint4 v; memcpy(&v, p, 16); return v;
#else
  return *(const uint4 *)p;
#endif
}
KURN_FN float kld_f32(const uint8_t *p) { return __uint_as_float(kld_u32(p)); }
KURN_FN void kst_u16(uint8_t *p, uint32_t v) {
#ifdef KURN_EMU
  kemu_check_align(p, 2, "16-bit store");
  uint16_t x = (uint16_t)v; memcpy(p, &x, 2);
#else
  *(uint16_t *)p = (uint16_t)v;
#endif
}
KURN_FN void kst_u32(void *p, uint32_t v) {
#ifdef KURN_EMU
  kemu_check_align(p, 4, "32-bit store");
  memcpy(p, &v, 4);
#else
  *(uint32_t *)p = v;
#endif
}

// f32 -> q8_0 blocks (ggml quantize_row_q8_0_ref rounding), one warp per block of 32.
// split != 0: int8 plane Q[M][K] plus float scale plane D[M][K/32] (scale = the fp16-rounded d)
static __global__ void __attribute__((unused)) kg_quant_q8_0(const float *__restrict__ X, uint8_t *__restrict__ Q, float *__restrict__ D, int K, int M, int split) {
  const int lane = threadIdx.x & 31, nb = K / 32;
  const long blk = (long)blockIdx.x * (blockDim.x / 32) + (threadIdx.x >> 5);
  const bool live = blk < (long)M * nb;
  const long bb = live ? blk : 0;
  const int m = (int)(bb / nb), c = (int)(bb % nb);
  const float v = X[(size_t)m * K + c * 32 + lane];
  float amax = fabsf(v);
#pragma unroll
  for (int o = 16; o; o >>= 1) amax = fmaxf(amax, __shfl_xor_sync(KURN_FULL, amax, o));
  const float d = amax / 127.f, id = d != 0.f ? 1.f / d : 0.f;
  const int q = (int)roundf(v * id);
  if (!live) return;
  if (!split) {
    uint8_t *b = Q + ((size_t)m * nb + c) * 34;
    if (lane == 0) kst_u16(b, KURN_F2H(d));
    b[2 + lane] = (uint8_t)(int8_t)q;
  } else {
    Q[(size_t)m * K + c * 32 + lane] = (uint8_t)(int8_t)q;
    if (lane == 0) D[(size_t)m * nb + c] = KURN_H2F(KURN_F2H(d));
  }
}

// f32 -> q8_K blocks (ggml quantize_row_q8_K_ref), one warp per block of 256 (8 values per lane)
static __global__ void kg_quant_q8_K(const float *__restrict__ X, uint8_t *__restrict__ Q, int K, int M) {
  const int lane = threadIdx.x & 31, nb = K / 256;
  const long blk = (long)blockIdx.x * (blockDim.x / 32) + (threadIdx.x >> 5);
  const bool live = blk < (long)M * nb;
  const long bb = live ? blk : 0;
  const int m = (int)(bb / nb), c = (int)(bb % nb);
  const float *x = X + (size_t)m * K + (size_t)c * 256 + lane * 8;
  float v[8], amax = 0.f, mx = 0.f;
  int idx = 1 << 30;
#pragma unroll
  for (int i = 0; i < 8; i++) {
    v[i] = x[i];
    const float ax = fabsf(v[i]);
    if (ax > amax) { amax = ax; mx = v[i]; idx = lane * 8 + i; }
  }
#pragma unroll
  for (int o = 16; o; o >>= 1) {  // largest |x|, first index on ties (ggml scans in order)
    const float oa = __shfl_xor_sync(KURN_FULL, amax, o), om = __shfl_xor_sync(KURN_FULL, mx, o);
    const int oi = __shfl_xor_sync(KURN_FULL, idx, o);
    if (oa > amax || (oa == amax && oi < idx)) { amax = oa; mx = om; idx = oi; }
  }
  uint8_t *b = Q + ((size_t)m * nb + c) * 292;
  int q[8], s8 = 0;
  const float iscale = amax != 0.f ? -127.f / mx : 0.f;
#pragma unroll
  for (int i = 0; i < 8; i++) {
    q[i] = amax != 0.f ? min(127, __float2int_rn(iscale * v[i])) : 0;
    s8 += q[i];
  }
  const int pair = __shfl_xor_sync(KURN_FULL, s8, 1);
  if (!live) return;
  if (lane == 0) kst_u32(b, __float_as_uint(amax != 0.f ? 1.f / iscale : 0.f));
#pragma unroll
  for (int i = 0; i < 8; i++) b[4 + lane * 8 + i] = (uint8_t)(int8_t)q[i];
  if (!(lane & 1)) kst_u16(b + 260 + 2 * (lane >> 1), (uint32_t)(uint16_t)(int16_t)(s8 + pair));
}
#define XD8K(x, b) kld_f32((x) + (size_t)(b) * 292)
#define XQ(x, c, off) (int)kld_u32((x) + (size_t)((c) >> 3) * 292 + 4 + ((c) & 7) * 32 + (off))
#define XBS(x, c, h) (int)(int16_t)kld_u16((x) + (size_t)((c) >> 3) * 292 + 260 + 2 * (((c) & 7) * 2 + (h)))

#define COLS 1
#define SUB 2
KURN_FN void kunit(const uint8_t *__restrict__ wq, const uint8_t *__restrict__ ws, int u, int p,
                                             const uint8_t *__restrict__ xb, const int *xo, float *acc, const uint32_t *__restrict__ tab) {
  (void)ws; (void)tab;
  const int b = u >> 1, hh = u & 1;
  uint32_t q[4];
  { const uint4 t = kld_v4(wq + (size_t)u * 32 + p * 16 + 0); q[0] = t.x; q[1] = t.y; q[2] = t.z; q[3] = t.w; }
  const float dw = KURN_H2F(kld_u16(ws + 2 * (size_t)b));
#pragma unroll
  for (int j = 0; j < COLS; j++) {
    int s = 0;
#pragma unroll
    for (int i = 0; i < 4; i++) {
#pragma unroll
      for (int sh = 0; sh < 4; sh++)
        s = __dp4a((int)__vsub4((q[i] >> (2 * sh)) & 0x03030303u, 0x01010101u), XQ((xb + xo[j]), b * 8 + 4 * hh + sh, p * 16 + 4 * i), s);
    }
    acc[j] += dw * XD8K((xb + xo[j]), b) * (float)s;
  }
}

static __global__ void __launch_bounds__(128, 1)
kg_gemv(const uint8_t *__restrict__ W, const uint8_t *__restrict__ X, float *__restrict__ Y, int N, int K, int M) {
  const uint32_t *tab = nullptr; (void)tab;
  const int lr = threadIdx.x / 32, lid = threadIdx.x % 32;
  const int row = blockIdx.x * 4 + lr, wrow = row < N ? row : N - 1;
  const int col0 = blockIdx.y * COLS;
  const uint8_t *wq = W + (size_t)wrow * ((size_t)K * 32 / 128);
  const uint8_t *ws = W + (size_t)N * ((size_t)K * 32 / 128) + (size_t)wrow * ((size_t)K / 256 * 2);
  int xo[COLS];  // 32-bit column offsets (columns past M repeat the last one; their results are not stored)
  float acc[COLS];
  #pragma unroll
  for (int j = 0; j < COLS; j++) { xo[j] = min(col0 + j, M - 1) * (int)((size_t)K / 256 * 292); acc[j] = 0.f; }
  const int work = K / 128 * SUB;
  int w0 = lid;
  // main loop without bounds checks, so the 2 units' loads can all be issued before their math
  for (; w0 + 32 < work; w0 += 64) {
    #pragma unroll
    for (int k = 0; k < 2; k++) {
      const int w = w0 + k * 32;
      kunit(wq, ws, w / SUB, w % SUB, X, xo, acc, tab);
    }
  }
  for (; w0 < work; w0 += 32) kunit(wq, ws, w0 / SUB, w0 % SUB, X, xo, acc, tab);
  #pragma unroll
  for (int j = 0; j < COLS; j++) {
    float v = acc[j];
    v += __shfl_xor_sync(KURN_FULL, v, 16);
    v += __shfl_xor_sync(KURN_FULL, v, 8);
    v += __shfl_xor_sync(KURN_FULL, v, 4);
    v += __shfl_xor_sync(KURN_FULL, v, 2);
    v += __shfl_xor_sync(KURN_FULL, v, 1);
    if (lid == 0 && row < N && col0 + j < M) Y[(size_t)(col0 + j) * N + row] = v;
  }
}

// native ggml blocks -> split layout: quant plane [N][((size_t)K * 32 / 128)] then scale plane [N][K/256 * 2]
static __global__ void kg_repack(const uint8_t *__restrict__ W, uint8_t *__restrict__ P, int N, int K) {
  const int nb = K / 256;
  const long i = (long)blockIdx.x * blockDim.x + threadIdx.x;
  if (i >= (long)N * nb) return;
  const int r = (int)(i / nb), bl = (int)(i % nb);
  const uint8_t *src = W + (size_t)r * ((size_t)K / 256 * 66) + (size_t)bl * 66;
  uint8_t *q = P + (size_t)r * ((size_t)K * 32 / 128) + (size_t)bl * 64;
  uint8_t *s = P + (size_t)N * ((size_t)K * 32 / 128) + (size_t)r * ((size_t)K / 256 * 2) + (size_t)bl * 2;
  for (int i = 0; i < 64; i++) q[0 + i] = src[0 + i];
  s[0] = src[64]; s[1] = src[65];
}

extern "C" {
const char *kg_config(void) { return "op=gemv weights=tq2_0 arch=sm_80 layout=split tpr=32 rpb=4 sub=2 unroll=2 cols=1 minb=0 mins=none unpack=none xlayout=blocks"; }
int kg_act(void) { return 0; }  // 0: kg_quant -> q8 activations; reference from kg_xblocks
int kg_check_shape(int N, int K, int M) { return (N > 0 && M > 0 && K > 0 && K % 256 == 0) ? 0 : -1; }
size_t kg_prep_bytes(int N, int K) { (void)N; (void)K; return (size_t)N * (((size_t)K * 32 / 128) + ((size_t)K / 256 * 2)); }
size_t kg_xbytes(int K, int M) { return (size_t)M * ((size_t)K / 256 * 292); }
int kg_prepare(const void *W, void *Wp, int N, int K, cudaStream_t s) {
  const long nblk = (long)N * (K / 256);
  KURN_LAUNCH(kg_repack, dim3((unsigned)((nblk + 127) / 128)), dim3(128), s, (const uint8_t *)W, (uint8_t *)Wp, N, K);
#ifdef KURN_EMU
  return 0;
#else
  return (int)cudaGetLastError();
#endif
}
int kg_quant(const float *X, void *Xq, int K, int M, cudaStream_t s) {
  KURN_LAUNCH(kg_quant_q8_K, dim3((unsigned)(((long)M * (K / 256) + 3) / 4)), dim3(128), s, X, (uint8_t *)Xq, K, M);
#ifdef KURN_EMU
  return 0;
#else
  return (int)cudaGetLastError();
#endif
}
size_t kg_xblock_bytes(int K, int M) { return (size_t)M * (K / 256) * 292; }
int kg_xblocks(const float *X, void *Xb, int K, int M, cudaStream_t s) {
  KURN_LAUNCH(kg_quant_q8_K, dim3((unsigned)(((long)M * (K / 256) + 3) / 4)), dim3(128), s, X, (uint8_t *)Xb, K, M);
#ifdef KURN_EMU
  return 0;
#else
  return (int)cudaGetLastError();
#endif
}
int kg_run(const void *W, const void *Xq, float *Y, int N, int K, int M, cudaStream_t s) {
  if (kg_check_shape(N, K, M)) return -1;
  KURN_LAUNCH(kg_gemv, dim3((unsigned)((N + 4 - 1) / 4), (unsigned)((M + 1 - 1) / 1)), dim3(128), s, (const uint8_t *)W, (const uint8_t *)Xq, Y, N, K, M);
#ifdef KURN_EMU
  return 0;
#else
  return (int)cudaGetLastError();
#endif
}
}
